### ISSUE TITLE
Please don't use glib APIs where there are alternatives

### ISSUE THREAD

**Issue by rrthomas** [fontforge/fontforge#1247]
Recently, calls to glib have proliferated in Fontforge. This is a good thing in many ways: glib is required, and provides lots of useful functionality. However, it's better to use POSIX/GNU APIs where possible for a few reasons:
1. They're more likely to be familiar to other developers, hence easier to read.
2. ~~Currently, memory allocated by glib must be freed; this is no longer the case for memory allocated by `malloc` calls, as that is GC'd.~~
3. No casting is required between `gchar` and `char`.

Examples include: use `strdup` instead of `g_strdup`, and `xvasprintf` instead of `g_strdup_printf`.

The main exception to this rule is when dealing with gtk, when it's more natural to use glib types and APIs; also of course where glib provides functionality missing from POSIX.

I've added this guidance to https://github.com/fontforge/fontforge.github.com/blob/master/en-US/documentation/developers/index.md and put it here in the hope that more developers will see it!

**Comment by jtanx** [comment]
To be honest, I've started to prefer glib over gnulib. Now that we use gnulib, it's basically impossible to switch to using say CMake (or any other build system, if that were to ever happen) because gnulib is so inherently tied to autotools. glib is well documented, and generally speaking, it provides better implementations of functions that *just work* on Windows. One major aspect of that is the handling of unicode paths, which works if you use the glib API, but not if you stick with the standard/gnulib patched function calls.
