### ISSUE TITLE
Remove the Fontforge scripting language

### ISSUE THREAD

**Issue by rrthomas** [fontforge/fontforge#1248]
We shouldn't be maintaining an entire language. Fontforge script can easily be converted to Python (which will shortly be required), so it suffices to translate the existing repertoire of scripts, that is:

1. `fontlint`, `fontimage`, `sfddiff`
2. The tests.

Note that these can be done one at a time; this is a set of bite-sized tasks, not one big one!

A converter from Fontforge script → Python would be a big help, both for automating the process and to help users with their own scripts.

**Comment by rquadling** [comment]
Can anyone point me to where I can find sfdiff? Has this been converted to Python yet?

**Comment by davelab6** [comment]
Its still there in the src tree

https://github.com/fontforge/fontforge/blob/master/fontforgeexe/sfddiff.pe

On 13 May 2015 at 16:26, Richard Quadling <notifications@github.com> wrote:

> Can anyone point me to where I can find sfdiff? Has this been converted to
> Python yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/1248#issuecomment-101714761>
> .
>



-- 
Cheers
Dave

**Comment by ahyangyi** [comment]
Also, I still remember there are some actions that's difficult to do with Python but easy with native script. I had to use call system() to use the fontforge scripting support inside my python script in one occasion.

**Comment by rquadling** [comment]
As a non-Python user, I hadn't appreciated that .pe was python. .py was what I was looking for. Once I realised it was a script and not a compiled app.

**Comment by rrthomas** [comment]
@ahyangyi, it would be helpful if you could file issues about what those actions are: the Python support is supposed to be complete.

**Comment by jimmywarting** [comment]
I didn't know python or FF scripting at the time, so i just went ahead using the one there where most tutorials for - FF
If this gets removed, then i'm forced to learn python. might not be that hard. But it would have to be done anyway...

What about those people coding in other language? I suggest writing something standalone c lib and do bindings for it so we can use it for node, Go, python, php etc

**Comment by mskala** [comment]
Since the writing seems to be on the wall for FontForge native scripting and possibly also for FontForge itself, and I have a project for which Python is not acceptable, I've spun off a standalone interpreter for the native scripting language into part of one of my own projects:  http://tsukurimashou.osdn.jp/fontanvil.php.en

That should make it easier for FontForge to do whatever it has to do with fewer worries of users being left in the cold.

**Comment by JoesCat** [comment]
Hi @jimmywarting, although the title of this issue started-out with suggesting removal of native scripting, I don't see it disappearing any time since there are many users that use it.
What native-scripting (and FontForge, from my point of view) suffers from is...not exiting cleanly (by this, I mean, having multiple "exit()" points that aren't in main(), and the codebase (in general) doesn't cleanup after itself (from a valgrind point of view). This style of programming is older, and is very acceptable for the typical home user who uses a computer and shuts down often at the end of the day, or week, but I think it can be improved, particularly since we are seeing questions and issues suggesting that people are also adding FontForge onto servers which can typically run weeks, months, years at a time, and this where you begin seeing memory cleanup and the placement of exit() as a more worthwhile effort to get done (to reduce/remove memory cruft).

The codebase is large, and the number of developers relatively few, therefore, progress is slow, but continues along. If you, or others can help, take a look at what you think you can help in, ie, code, documentation, messages (and translation), manuals, etc... this is up to you.

**Comment by mskala** [comment]
I don't think "the server will run for weeks at a time" is really a relevant issue here - the server will run for weeks or more, but FontForge when used as a script interpreter certainly doesn't, and it's the lifetime of the FontForge processes that is relevant, not the uptime of the computer.  Nonetheless, I agree that the messy coding throughout FontForge is a problem for anyone using it in a server environment or (my own major use case) as a compiler inside a build system, where the user does not directly interact with FontForge.  It was partly because of messy code that I completely removed the GUI from FontAnvil; that alone cut the size of a code base and therefore the total volume of messy code that will need to be fixed.

**Comment by davelab6** [comment]
@rrthomas proposed this but @lemzwerg makes a fair point about things depending on it, and since no has made any progress on this, I suggest we abandon it :)

**Comment by JoesCat** [comment]
Some progress (#2512, #2710), plus added commands between 2012 and now, but not no progress ;-P

**Comment by davelab6** [comment]
@JoesCat that issue and PR is about improving scripting, not killing it :)
