### ISSUE TITLE
Support WOFF2

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1503]
Following https://github.com/fontforge/fontforge/pull/1501, add support for WOFF2 (related, https://github.com/fontforge/fontforge/issues/1457)

**Comment by jimmywarting** [comment]
+1

**Comment by ctrlcctrlv** [comment]
Google wrote a C implementation of WOFF2 compression / decompression:

https://github.com/google/woff2

I don't think it would be that difficult to use it in FontForge. Currently I use it for post processing.

**Comment by jimmywarting** [comment]
Now when #926 have been fixed, can we work on woff2 now?

**Comment by davelab6** [comment]
I recommend just using a Python script for fontforge to use the google
woff2 program.

**Comment by fred-wang** [comment]
I thought a bit on that while working on #926 and my conclusion was that WOFF2 is slightly more complex than just gzip compression of tables... So it makes sense to just generate the OpenType/TrueType file with fontforge's functions and then call Google's woff2 library on it (and the other way around for opening font). Also WOFF2 may invalidate font checksum and then remove DSIG table, so maybe we should warn the user about that...

The main "difficulty" is that libraries https://github.com/google/woff2 and https://github.com/google/brotli/ are not really available as standard released packages so we'll have to include the code into fontforge's build system in some way.

**Comment by jimmywarting** [comment]
Cool, wouldn't mind if you used a third party like google's woff2
It would just be nice to abstract away the need to use a external program to decompile and then open fontforge with that ttf file and the other way around

**Comment by fred-wang** [comment]
I'm not suggesting to use an external program, just the ConvertTTFToWOFF2/ConvertWOFF2ToTTF functions from the WOFF2 library.

Here was my rationale:

_WriteWOFFFont essentially works as follows (https://github.com/fontforge/fontforge/blob/master/fontforge/woff.c#L382):

1) It has an abstract SplineFont structure representing the font to generate.
2) It first writes the WOFF header (with free space for table offsets).
3) It calls _WriteTTFFont to generate the TrueType/OpenType font.
4) It reads again the font generated in 3), compress the binary content of each of the table with gzip and writes this compressed table into the WOFF file (filling the final table offsets in the space left in the WOFF header)
5) Finally, if the font has some WOFF metadata it is compressed with gzip and appended to the WOFF file.

For WOFF2, brotli is used instead of gzip. However, there are several differences. First, the compression is applied to the whole set of tables so the logic in 4) (to compress each of the table individually and to calculate the final offsets) does not apply. Second, there are some "high-level" optimizations (e.g. those on glyf and loca tables) that are better done using the abstract structure provided by SplineFont than the binary data obtained in 3). Finally, WOFF2 is also able to handle TrueType Collection and I'm not really sure how we would handle that here. So my conclusion was that it is not really relevant to reuse our existing code for WOFF compression/decompression.

My naive proposal for WOFF2 is just:

1) Start with the SplineFont structure representing the font to generate
2) Call _WriteTTFFont to generate the TrueType/OpenType
3) Call ConvertTTFToWOFF2 from the WOFF2 library on the generated output to generate the WOFF2 font.

And of course the same reasoning applies for opening WOFF2 file. So I guess that would be quite easy. As I said the main difficulty would be to properly integrate the woff2 library into the fontforge build system. Maybe that's why Dave suggested an alternative via Python.

**Comment by fred-wang** [comment]
So I tried a quick hack to clone & build the woff2 library during the fontforge build. However, I realize an additional difficulty: the woff2 headers are in C++ so they can not be used directly by fontforge's C source. Anyway for those interested and to illustrate the proposal of my previous comments, here is my first attempt:

https://github.com/fred-wang/fontforge/commit/0e4030ea1c0329eed98361dee504645a64fdc229

BTW, I also opened https://github.com/google/woff2/issues/49

**Comment by jimmywarting** [comment]
Bump?

**Comment by jimmywarting** [comment]
what is the status on this?

**Comment by frank-trampe** [comment]
I hadn't been following this. Now that the woff2 library seems to be buildable and linkable, I'll give it a try next week.

**Comment by Meteor0id** [comment]
So uhm, did it work?

**Comment by frank-trampe** [comment]
Sorry about that. I looked at it, but it wasn't trivial, and I got buried in other work. I won't be back on the case until February. This is on my list, though.

**Comment by Connum** [comment]
Hi there, any update on the WOFF2 front?

**Comment by jrchudy** [comment]
Also looking for an update for WOFF2 formatting in fontforge.

**Comment by Dmole** [comment]
```
sudo apt install fontforge woff2 
woff2_decompress a.woff2
fontforge a.tts
woff2_compress a.tts
```

seems like it's the best workaround...

**Comment by Connum** [comment]
Not for Windows, unfortunately! ;) but interesting, maybe I'll fire up a VM for that.

**Comment by vushe** [comment]
@Dmole, what is the **woff2** package? It's at least not available as such from my Ubuntu-based distro.

**Comment by Dmole** [comment]
@vushe 

```
> apt show woff2
Package: woff2
Version: 1.0.2-1
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Fonts Task Force <pkg-fonts-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 68.6 kB
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libstdc++6 (>= 5.2), libwoff1 (>= 1.0.0)
Homepage: https://github.com/google/woff2
Download-Size: 12.5 kB
APT-Manual-Installed: yes
APT-Sources: http://ca.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
Description: utilities for converting fonts to WOFF 2.0
 woff2 is a library for converting fonts from the TTF format to the WOFF 2.0
 format. The library also allows decompression from WOFF 2.0 to TTF.
 .
 The WOFF 2.0 format uses the Brotli compression algorithm to compress fonts
 suitable for use in CSS @font-face rules. WOFF 2.0 is a W3C Candidate
 Recommendation.
 .
 This package contains the woff2_compress, woff2_decompress, and woff2_info
 utilities.

```

**Comment by vushe** [comment]
Thanks! Looks like my core Ubuntu is a little bit outdated or such.

**Comment by jtanx** [comment]
I'll take a shot at integrating this.

**Comment by Connum** [comment]
This is great news! Can't wait for this to be available in the Windows builds. And you did this in just two days? Truly amazing!

**Comment by rgpublic** [comment]
What is needed to make this work? I already installed the WOFF2 package with APT. But still when I try to save as WOFF2 the option is disabled with no explanation why this is the case. In the documentation WOFF2 isn't even mentioned as a valid output format.

![grafik](https://user-images.githubusercontent.com/17726950/134331978-818fb0e4-d113-4491-b4bc-d700294c3182.png)

**Comment by Dmole** [comment]
> ...WOFF2 isn't even mentioned as a valid output format...

2nd from the bottom in your image.
What fontforge version are you using?
Best to start a new bug report.

**Comment by rgpublic** [comment]
I meant: WOFF2 isn't mentioned in the documentation here:

https://fontforge.org/docs/ui/dialogs/fontinfo.html#woff-web-open-font-format

I'm using the most recent version available with Ubuntu. But you are right: To my surprise it seems it's fairly outdated:

20190801~dfsg-5ubuntu1

This is only one month after the WOFF2 patch went it. Good catch. Will try a newer version. Thank you!

**Comment by Muratcol** [comment]
I installed version 20230101 to Ubuntu 20.04 from the source with the dependencies in the documentation:
```
sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev python3-dev ninja-build cmake build-essential gettext;
```

But I'm getting this error:
```
4e3178ef-4840-40a6-a5d7-cea029f09259.woff2 is not in a known format (or uses features of that format fontforge does not support, or is so badly corrupted as to be unreadable)\n
```

Do I need any other dependency or what am I doing wrong? Any idea?

**Comment by iorsh** [comment]
Oh, just discussed it in #5346. You also need `libwoff-dev`

**Comment by Dmole** [comment]
@Muratcol what is the output of

file 4e3178ef-4840-40a6-a5d7-cea029f09259.woff2

?
Is that file working in other apps?

**Comment by Muratcol** [comment]
> Oh, just discussed it in #5346. You also need `libwoff-dev`

It fixed the problem! Thank you! 


> @Muratcol what is the output of
> 
> file 4e3178ef-4840-40a6-a5d7-cea029f09259.woff2
> 
> ? Is that file working in other apps?

Yes, it works. Problem was missing dependency `libwoff-dev`
