### ISSUE TITLE
Fragment joining failure in stroke expander + bad instruction arguments

### ISSUE THREAD

**Issue by Pecita** [fontforge/fontforge#1747]
Dear developers, 

The font that I build with FontForge is corrupt. 
It is perfectly usable when installed but is rejected by ots when embedded in a web page. 
I do not know how to fix this problem.

The material related with this bug is here: http://pecita.eu/bugCFF/

*http://pecita.eu/bugCFF/version5.xhtml*
"downloadable font: CFF : failed to parse table (font-family: "Pecita" style:normal weight:normal stretch:normal src index:0)
source: http://pecita.eu/bugCFF/Pecita.otf police.css
downloadable font: rejected by sanitizer (font-family: "Pecita" style:normal weight:normal stretch:normal src index:0)
source: http://pecita.eu/bugCFF/Pecita.otf"

(Debian testing)
fontforge -version
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
fontforge 20120731
libfontforge 20120731-ML

Regards,
Philippe Cochy

**Comment by davelab6** [comment]
@frank-trampe did you work on those 2 issues?

**Comment by frank-trampe** [comment]
I did work on the fragment joining problem. I can't remember what happened.

**Comment by Pecita** [comment]
Steps to reproduce:
1) local copy of http://pecita.eu/bugCFF/ (compile.eu+PecitaSource.sfd)
2) chmod +x compile.eu then execute

Result:
./compile.pe
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 21:13 UTC 28-Feb-2015-ML-D.
 Based on source from git with hash: a875b4d41cc48aded120aa060ae520cc0113a7a7
Some fragments did not join in thornSome fragments did not join in afii10024[...]Validation error

TY, Frank. Please do not release as long as this bug is not fixed.

**Comment by davelab6** [comment]
@Pecita are you saying this worked okay in the last 2012 release?

**Comment by Pecita** [comment]
Yes!

2015-07-13 7:18 GMT+02:00 Dave Crossland <notifications@github.com>:

**Comment by Pecita** [comment]
Everything including the Expandstroke function work OK for me in the latest 2012 release except for the latin small letter n of the Pecita font that cause bad instruction arguments at autohint.

**Comment by Pecita** [comment]
(Excuse my bad English)
1) The bad instruction arguments can be close solved/not reproductible.
2) For the Fragment joining failure, a manual solution - heavy - exists: when the angle of the path is very acute the spline can be *splitted at the corner point* before applying expandstroke, then you must complete with a removeoverlap - Could this action be programmed?

**Comment by jtanx** [comment]
I've  just come across this bug, but running `compile.pe` with latest FF on Windows causes a crash: https://gist.github.com/jtanx/231eb458864383180f189fce21a587cc

**Comment by jtanx** [comment]
Okay, I've got it to stop crashing (there was a buffer overrun). I'm not getting the "Some fragments did not join" message any more - I think because of #2739, but it's still failing validation saying that `g_a.I_` has wrong contour direction

**Comment by jtanx** [comment]
WRT the invalid charstrings, I've somewhat narrowed down the cause. In the following case, I've investigated using the "n" glyph generated using `compile.pe`.

It appears that autohinting works as expected, but as the file is saved, [PrepareUnlinkRmOvrlp](https://github.com/fontforge/fontforge/blob/master/fontforge/savefont.c#L1219) is called. This eventually calls [SplineSetRemoveOverlap](https://github.com/fontforge/fontforge/blob/master/fontforge/savefont.c#L963) which generates a new spline set, but without any hintmask (`hintmask == NULL`). However, for that SplineChar, either `sc->hconflicts` or `sc->vconflicts` is true, due to previous autohinting.

The generated charstring for "n" is:
~~~~
135 21 -21 240 60 -30 60 hstemhm
450 60 550 30 rmoveto
-991 callsubr
endchar
~~~~

When the charstring is generated, these flags (`sc->hconflicts`/`sc->vconflicts` ) cause `hstemhm`/`vstemhm` to be dumped with the `vstemhm` command omitted ([Page 24/25](http://partners.adobe.com/public/developer/en/font/5177.Type2.pdf)) in the expectation of the following command being `hintmask`. **But** because `hintmask` is NULL, the [hintmask](https://github.com/fontforge/fontforge/blob/master/fontforge/splinesave.c#L2317) instruction is omitted, and the following instruction is a moveto command (`rmoveto` in this case). 

Thus the charstring should look more like
~~~~
135 21 -21 240 60 -30 60 hstemhm
450 60 hintmask 11010000
550 30 rmoveto
...
endchar
~~~~

Useful breakpoints:
~~~~
Num     Type           Disp Enb Address    What
23      breakpoint     keep n   0x6e80f15e in SFSCAutoHint at autohint.c:2989
        stop only if !strcmp("n", sc->name) || !strcmp("n.I", sc->name)
27      breakpoint     keep y   0x6ea19e20 in SplineChar2PS2
                                           at splinesave.c:2984
        stop only if !strcmp("n", sc->name) || !strcmp("n.I", sc->name)
33      breakpoint     keep y   0x6ea00791 in SplineSetRemoveOverlap
                                           at splineoverlap.c:3963
        stop only if !strcmp("n.I", sc->name)
~~~~

**Comment by frank-trampe** [comment]
@jtanx, is the fix as simple as linearly adding hint masks, or do we need to do it constructively/recursively?

**Comment by jtanx** [comment]
@frank-trampe, it seems that ensuring that `SCFigureHintMasks` is called for referenced chars (when needed) fixes the charstring corruption (see #2758). I've also uploaded a minimal test case (see [here](https://github.com/fontforge/debugfonts/blob/09f57273f8df932c1eba881e4d20d5c6ba4e4748/charstring-corruption-1747.sfd)) based on @Pecita's font

**Comment by jtanx** [comment]
I've also explored why validation is failing on `g_a.I_`. 
![1747](https://cloud.githubusercontent.com/assets/5137410/17174591/3193e3ae-5435-11e6-9cbf-6a3d915103cf.png)

Comparing the 2012 output with current output, there's an extra cluster of points which causes the validation to fail (in addition to being extraneous).

After some bisecting, I've found that the difference is a result of switching to double precision floating point numbers (first instance 8915ec447aedbc15afc9316e145ed6b2b7762716). Coincidentally, I think this is also the same reason as to why the infinite loop condition was occurring (#2739).

**Comment by jtanx** [comment]
This bug has effectively been fixed. The remaining part on floats vs doubles for the real type is another issue, which I've made a specific issue for (#2823).

**Comment by frank-trampe** [comment]
@jtanx, how was this fixed?

**Comment by frank-trampe** [comment]
The garbage points problem, I mean.

**Comment by jtanx** [comment]
@frank-trampe it's a separate issue - #2823. If you compile FontForge with `--enable-real=float`, the problem goes away. For this issue - the fragment joining failure was caused by  #2739, which was fixed, while the bad instructions were fixed by #2758.

**Comment by copyninja** [comment]
I just tried building Pecita font again with newly released fontforge 20161005 but it fails at validate() step. Is the issue really fixed?.. Or as @jtanx suggested we need to use `--enable-real=float` option for distribution builds?.

**Comment by frank-trampe** [comment]
@copyninja, I think that we wanted to move the discussion of float/double issues to #2823.

**Comment by Pecita** [comment]
It must be an angle upper than 7.5 ° for the ExpandStroke function do not causes the "Some fragments did not join" error: it's huge! I do not believe it's a rounding problem.

**Comment by frank-trampe** [comment]
@Pecita, does this still happen with the October release of FontForge?

**Comment by Pecita** [comment]
I just tested with the experimental package with the thorn letter.
You can work with PecitaSource.sfd and apply on a specific letter the ExpandStroke function.
With the GW version the angles must be not nul but very small. With this version you need to increase it widely.

**Comment by frank-trampe** [comment]
Okay. I'll take a look soon, probably this week.
