### ISSUE TITLE
y: command not found

### ISSUE THREAD

**Issue by DomT4** [fontforge/fontforge#1836]
I keep noticing this crop up in the ``` ./configure ``` readout, and I've been wondering if it's an actual bug that needs squashing or just a bit of nothing.

It's a fun little error that only displays for a few seconds before it gets drowned out by the rest of the ``` ./configure ``` process.

This is the error on the ``` ./configure ``` readout:

```
found python pkg_config information: /blah/blah/blah/blah/lib/etc
./configure: line 17616: y: command not found
```

That line inside the generated configure script is:

```
if test "y$HOMEBREW_BREW_FILE" != "y"; then
   echo "detected a homebrew build environment"
   PYLIBDIR=$(${HOMEBREW_PREFIX}/bin/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
   PYPKGCONFIG="$( cd "$PYLIBDIR/../../pkgconfig" && pwd )"
   export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PYPKGCONFIG"
   echo "found python pkg_config information: $PYPKGCONFIG"
   if  "y$PYTHON" = y  ; then
     export PYTHON="${HOMEBREW_PREFIX}/bin/python"
   fi
fi
```

The line is the: ``` if  "y$PYTHON" = y  ; then ``` line.

Any ideas what's going on here? My curiosity has gotten the better of me and I had to ask.

**Comment by apjanke** [comment]
I think it's a syntax bug with the autoconf script. Have a look at [configure.ac line 223](https://github.com/fontforge/fontforge/blob/30420324f194f3d4d148b8e662bd5b56865fb88f/configure.ac#L223).

```
   if [ "y$PYTHON" = y ] ; then 
     export PYTHON="${HOMEBREW_PREFIX}/bin/python"
   fi
```

Everything else is using the `if test ...` syntax instead of `if [ ... ]` syntax. Since this is an autoconf input file and not a shell script, I think those brackets are M4 syntax, and get stripped in the process of creating `configure`. Should probably convert this to use the `test` syntax like everything else.
