### ISSUE TITLE
Bring back Mac OS X Finder integration

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2042]
I recommend that instead of wasting hours with undocumented and deprecated Carbon APIs - which are sure to give us trouble again when 10.11+ is released without Carbon - we develop a simple Python Cocoa application and put that in the bundle, and have it call the FontForge in that bundle.

Thoughts?

http://blog.adamw523.com/os-x-cocoa-application-python-pyobjc/

**Comment by frank-trampe** [comment]
That is certainly an option. But it would not be as simple as putting FontForge into the bundle.

The Cocoa application needs to receive Finder events and then to transmit them in some non-Cocoa form to FontForge. I think that the interfacing would be easier if we were to write the Cocoa portion in Objective C. There are a few different possibilities in order of ascending complexity.

* In the first scenario, FontForge would link against a compiled Cocoa library and call a function that just checks for events and returns a simple struct.
* In the second, FontForge would outsource its event loop to a compiled Cocoa function, giving it a function pointer to the event processor.
* In the third, we would slim down fontforge_main (by moving things into other functions to be shared) so that we could have a parallel implementation in Objective C for use on the Macintosh.

I'm inclined to try the first approach and to proceed to the second if it fails. But first, I'm going to solicit comments from Macintosh developers.

**Comment by davelab6** [comment]
This sounds way too complex. The Mac package has never had a lot of finder
events, and the only finder event I care about is seeing sfd files in
Finder and double clicking them to open them, which is currently broken I
believe, and not seeing the dock icon bounce forever.

This doesn't require anything more than a python cocoa program that calls
fontforge from shutil (ie, the command line) and the existing cocoadialog
program might even be sufficient.

**Comment by frank-trampe** [comment]
Passing signals as arguments via Python is certainly an option, but I do not think that it is optimal, since many people open files from the Finder after the application has started and processed the arguments from the Python script. Depending upon whether one allows multiple instances in Info.plist, this would result in either spawning a new FontForge instance for each file opened or in being unable to open files from the Finder when FontForge is already open.

**Comment by davelab6** [comment]
Running two ff processes, I can't copy and paste between them, so that's
not good.

But in fact on my machine, sfd files have the ff icon and double clicking
them opens them. The dock icon bounces forever, though.

**Comment by frank-trampe** [comment]
Are you able to open additional files in the same FontForge instance?

**Comment by frank-trampe** [comment]
Oops.

**Comment by adrientetar** [comment]
> I'm inclined to try the first approach and to proceed to the second if it fails.

sounds good

**Comment by marty39** [comment]
Excuse me, what is going on here? I've been driving myself crazy trying to get fontforge to open a font file from the Mac OS X Finder (as it used to), and this is the only relevant page that turned up in a Google search. I thought it was failing because I restored the system (Mavericks) from Time Machine, but now it seems everybody has the same problem. Can you explain -- preferably on the main FontForge page -- why we can't open files the way we used to? Is it a new FontForge version, and if so can we get an old one that works? Is it Mac OS X updates? Will the latest version work properly on Snow Leopard? If not, do you have a version that will?

**Comment by frank-trampe** [comment]
Hi, @marty39.

FontForge previously depended upon a framework called Carbon in order to integrate with the Finder. Apple still ships Carbon, but it stopped maintaining to the point that it no longer works correctly with FontForge and causes user experience problems. So we disabled it temporarily in recent releases.

A fix (a transition to the Cocoa framework) is likely to arrive in late March. In the interim, our November release still has Cocoa support and ought to work properly on Macintosh versions before Yosemite.

Sorry for the inconvenience.

**Comment by marty39** [comment]
Well, Frank, I hate to carp, but I also hate to have to go to developers’ sites to find essential user information.

How about a link from the main FontForge page to the November release? I couldn’t find it by searching for “old” versions of FontForge because I didn’t know I was looking specifically for November. I found it by searching for november release instead of old version. I’m sure there are other users in the same boat.

On Feb 28, 2015, at 9:32 AM, Frank Trampe <notifications@github.com> wrote:

> Hi, @marty39.
> 
> FontForge previously depended upon a framework called Carbon in order to integrate with the Finder. Apple still ships Carbon, but it stopped maintaining to the point that it no longer works correctly with FontForge and causes user experience problems. So we disabled it temporarily in recent releases.
> 
> A fix (a transition to the Cocoa framework) is likely to arrive in late March. In the interim, our November release still has Cocoa support and ought to work properly on Macintosh versions before Yosemite.
> 
> Sorry for the inconvenience.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
								Marty
Martin B. Brilliant at home in Holmdel, NJ

**Comment by adrientetar** [comment]
https://github.com/fontforge/fontforge/releases

**Comment by frank-trampe** [comment]
@marty39, we don't want people to use the November release because of the pausing problem. Apple is very good at getting large numbers of its users to upgrade to its latest operating system, and most users would thus experience that problem. An application can maintain a respectable user base without Finder integration (like Inkscape, I believe), but it's hard to stay in business when the application pauses frequently.

**Comment by davelab6** [comment]
@marty39 the website is libre for you to edit, so if you don't like it,
step up and change it :)
