### ISSUE TITLE
UFO: Switching tabs renames and creates glyphs randomly

### ISSUE THREAD

**Issue by moyogo** [fontforge/fontforge#2148]
When editing a UFO where Unicode values are not assigned, like SourceSansPro-Master0.ufo from https://github.com/adobe-fonts/source-sans-pro, switching tabs in the outline window a certain amount of times empties and renames the glyph, creating a random one in its tab.

![capture d ecran 2015-03-16 a 07 19 40](https://cloud.githubusercontent.com/assets/1923747/6661950/db95f21a-cbac-11e4-96f1-cfcb9a3920cc.png)
becomes this after switching tabs a few times:
![capture d ecran 2015-03-16 a 07 19 48](https://cloud.githubusercontent.com/assets/1923747/6661954/ee8440c0-cbac-11e4-8abf-5a03e4a26bf7.png)
the new glyph is empty and a glyph with its previous name is added at the bottom of the font window.

Using View > Goto, gives the new random empty glyph but double-clicking on the original glyph in the font view opens an outline window with the right glyph name.

**Comment by adrientetar** [comment]
Hi Denis, I've got #2160 in the queue which I belive fixes this. Please try and see if it works for you.

**Comment by adrientetar** [comment]
More info: this only happens with glyphs that have unencoded single-letter names. The problem is that the lexer leaves e.g. `A` on the input field after processing instead of `/A` but this is wrong because the A is indeed unencoded, and unencoded glyphs should have a prefix slash, or at least that's the convention used in the wordlistparser. But there is an elision of slash going on when you have single letter
Reflecting on whether I should change the lexer convention (when decoding) or the processing (when writing the data on the input field). cc @frank-trampe
