### ISSUE TITLE
Issue in drawing in character uni00B5 - using fontforge python

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#2188]
First of all I'm using brew install on os x, my fontforge version installed is 20150320
but it seems to be happening in any version after 20120731

here is the minimal code to reproduce the issue:
```python
import fontforge
font = fontforge.font()
font.encoding = "UnicodeBmp"
caracter = 'uni00B5'
font.createMappedChar(caracter).unicode
pen = font[caracter].glyphPen() 
```

and instead of work it brings me this result: 
```
Traceback (most recent call last):
  File "test_uni00b5.py", line 10, in <module>
    pen = font[caracter].glyphPen() 
TypeError: No such glyph
```

There is a related thread here
http://fontforge.10959.n7.nabble.com/Fontforge-Python-module-issue-in-drawing-in-character-uni00B5-td13765.html

Thanks

**Comment by adrientetar** [comment]
This is because the glyph is named mu per the AGL:

~~~python
>>> import fontforge
>>> font = fontforge.font()
>>> font.encoding = "UnicodeBmp"
>>> char = 'uni00B5'
>>> font.createMappedChar(char)
<fontforge.glyph at 0x0x7ffa3cbe8ed8 U+00B5 "mu">
~~~

Looking up by uniXXXX always works in GUI FontForge but not in Python it seems. 
But you can call by codepoint instead:

~~~python
>>> import fontforge
>>> font = fontforge.font()
>>> font.encoding = "UnicodeBmp"
>>> codepoint = 0x00B5
>>> font.createChar(codepoint)
<fontforge.glyph at 0x0x7f3e308e4180 U+00B5 "mu">
>>> font[codepoint].glyphPen()
<fontforge.glyphPen object at 0x7f3e30a2a0f0>
~~~
