### ISSUE TITLE
Can't export .dfont fonts to .ttf

### ISSUE THREAD

**Issue by raphaelyancey** [fontforge/fontforge#2194]
Hi!

This is not really an issue, but I couldn't find an answer in the scripting guides, I hope you'll be able to help me.

I'm trying to extract fonts from a `.dfont` file and export each of the font variants to a separate `.ttf` file, from the command line.

First, I tried to get the fonts names inside the `.dfont` by using `FontsInFile("MyFont.dfont")` but it returns an empty array, whereas the GUI application asks me to select a font when I open the same `.dfont`.

```
#!/usr/local/bin/fontforge
fonts = FontsInFile("Kigali.dfont")
Print("Fonts: ")
Print(fonts)
```

Then, I tried to directly open a sub-font with `Open("MyFont.dfont(0)")` and to export it with `Generate("MySubFont.ttf")`, but it ends up with a `Segmentation fault`.

```
#!/usr/local/bin/fontforge
Open("Kigali.dfont(0)")
Generate("Kigali_Sub.ttf")
Print("Done.")
```

Could you light my path? Thank you in advance, and thank you for providing this wonderful tool.

(`$ fontforge -version` outputs `[...] libfontforge 20150403`, on OSX 10.6.8 — the font I'm trying to convert is [Kigali](http://www.mediafire.com/download/311uf2es7mhnu5o/Kigali.dfont))

**Comment by jtanx** [comment]
Segfault at [macbinary.c:2608](https://github.com/fontforge/fontforge/blob/92c5879c24ca8f960c05b4a4fac0e5389978e7b7/fontforge/macbinary.c#L2608) (both `test` and `find` are NULL)

It looks like you have to pass the name of the font you want in parentheses, e.g.

    Open("Kigali.dfont(Kigali ZigZag)")

In any case, the scripting engine doesn't allow you to generate `.ttf`'s from the dfont because it's a bitmap font.
