### ISSUE TITLE
Exporting TTF to multiple bitmap files

### ISSUE THREAD

**Issue by renannprado** [fontforge/fontforge#2205]
Hi. 

I'm trying to load a TTF font file and export to multiple bitmap files (one would also be ok), but I can't find a way to do it. I've researched a lot already.
Sorry if it's the wrong place to ask, but I didn't know where to do it.

Thanks!

**Comment by davelab6** [comment]
You mean, for example, export each glyph to a PNG?

**Comment by renannprado** [comment]
Exactly

**Comment by davelab6** [comment]
I recommend using the hb-view program for this :)

FontForge Python scripting has a layer.export() and glyph.export() method
for this, the file type is determined by filename extension.

http://fontforge.github.io/python.html

**Comment by renannprado** [comment]
I tried to use the File > Execute script to execute glyph.export, but after executing it, nothing happens. Can you give a more detailed step by step?

Thanks

**Comment by renannprado** [comment]
I`ve also tried to put the below code into a script.pe file

Open($1); 
SelectWorthOutputting(); 
foreach 
Export("png"); 
endloop;

and execute:

fontforge -script script.pe <FONT_FILE>

But I get the below error message:

Export: Wrong number of arguments
Called from...
 script.pe: line 4

**Comment by mskala** [comment]
That error message is clear:  you gave the wrong number of arguments to Export().

Looking at the documentation, I think the second argument is required because you chose png format. It's written as Export(format[,bitmap-size]) in the documentation, implying that the second argument is optional, but from the descriptions of the formats it's pretty clear that a size is expected whenever you choose a bitmap format.  It's only "optional" in the sense that you have the option of whether or not to use a format that requires it.

Note that the Export() function works on all selected glyphs, so you probably shouldn't put it inside a foreach loop.

**Comment by renannprado** [comment]
I did read the document and saw the error message. However when I tried to add the other parameter to export() method, I only got more errors. Regarding the foreach loop, even though it's not right, if the script was working fine it would just generate repeated glyph files.

**Comment by mskala** [comment]
What are the other errors you get?

**Comment by renannprado** [comment]
Now I tried the below script

Open($1); 
SelectWorthOutputting(); 
Export("png", $2); 

Execution:

fontforge -script script.pe "Wedding Chardonnay.ttf" 0
(zero is the other parameter to use in Export method, any number will give same error)

Export: Bad type of arguments
Called from...
 script.pe: line 3

If I try to hardcode the second parameter with any number:

Export: No bitmap font matches the specified size
Called from...
 script.pe: line 3

**Comment by davelab6** [comment]
On 22 April 2015 at 15:07, Renann Prado <notifications@github.com> wrote:

> Export("png", $2);
>
>
I thought you'd do

Export("filename.png", 600);

**Comment by renannprado** [comment]
True. It would really make more sense to use the whole file name as parameter. However I've just tried that and still get same "No bitmap font matches the specified size" error :(

**Comment by mskala** [comment]
Since this function creates many files, specifying one filename for all of them isn't going to work.  You can come close, though, by specifying a template for the filenames.  It doesn't have to be just the format name.

I think this error message also explains what's wrong, albeit cryptically.  No bitmap [in the] font matches the specified size.  You are probably trying to export bitmaps from a font that only has splines.  There are no bitmaps, so you can't export them.  Try using BitmapsAvail() to create bitmaps in the size you want, first.

**Comment by davelab6** [comment]
I still think hb-view from  http://www.freedesktop.org/wiki/Software/HarfBuzz/  would be better for this

**Comment by renannprado** [comment]
@davelab6 
How can I do that with hb-view to do that? Do you have a tutorial with step by step how to do what I need? I found the documentation is not so good and there isn't much information in the internet.

@mskala 

I tried to use the below script, but no luck.
Do you have a script to do that by any chance?
It's really my first time using fontforge and I don't have much knowledge about fonts, their bitmaps, metadata and so on. I really just want to export a single ttf to multiple PNGs.

Open($1); 
SelectWorthOutputting(); 
BitmapsAvail(50);
Export("test%.png", 50); 

Thanks

**Comment by davelab6** [comment]
Install harfbuzz and then in terminal explore the help info:
```
$ hb-view --help
Usage:
  hb-view [OPTION...] [FONT-FILE] [TEXT]

Help Options:
  -h, --help                            Show help options
  --help-all                            Show all help options
  --help-font                           Options controlling the font
  --help-text                           Options controlling the input text
  --help-shape                          Options controlling the shaping process
  --help-features                       Options controlling font features used
  --help-output                         Options controlling the output
  --help-view                           Options controlling output rendering

Application Options:
  --version                             Show version numbers
  --debug                               Free all resources before exit

$
```

**Comment by mskala** [comment]
My guess is that this code will probably work.  It works for me.  Without knowing what error you are getting, I can only guess at what your problem may be.

```
    Open($1);
    SelectWorthOutputting();
    BitmapsAvail([50]);
    Export("png", 50);
```

BitmapsAvail() requires an array, and Export() requires either a format name or a valid template.  The syntax for templates is explained in the documentation for Export(), but I suggest you get it working at all before trying to make it work more prettily.

**Comment by renannprado** [comment]
@mskala 

Excelent! Now I have something :)
I got one png file per glyph!
I see that growing the value of the BitmapsAvail() parameter will also grow the size (in pixels) of the images, however I don't know the relation between its parameters and the second parameter of export if any.
Is there an easy way to generate all the files with same size (in pixels)? I thought that would be the default behavior.

Documentation of BitmapsAvail()
> Controls what bitmap sizes are stored in the font's database. It is passed an array of sizes. If a size is specified which is not in the font database it will be generated. If a size is not specified which is in the font database it will be removed. A size which is specified and present in the font database will not be touched.
If you want to specify greymap fonts then the low-order 16 bits will be the pixel size and the high order 16 bits will specify the bits/pixel. Thus 0x8000c would be a 12 pixel font with 8 bits per pixel, while either 0xc or 0x1000c could be used to refer to a 12 pixel bitmap font.
If you want to create blank strikes (with no glyphs in them) set the optional rasterized parameter to 0.
 
Thanks!

**Comment by mskala** [comment]
Bear in mind that FontForge is intended for creating and editing fonts.  It sounds like you want to do something else - namely treat .TTF as a sort of image format with pictures in it that may or may not be pictures of letters - and FontForge is not well adapted to doing that.

The conversion of a vector font to bitmap is complicated, and especially at small sizes it cannot be perfectly automated.  This is especially an issue for fonts that include Chinese characters; it is less so, but still of some importance, for the fonts used to write English.  Making the best possible low-resolution bitmap to convey the meaning and style of a character requires human intelligence to know which details contribute and which ones can be omitted.  Commercial font foundries pay a lot of money to human beings to manually edit fixed-size bitmaps, and they wouldn't do that if it could be done automatically to a quality level they considered acceptable.

Many font formats, then, are designed to include pre-converted handmade bitmap versions of the characters, in addition to or instead of the vectors.  These pre-converted bitmap versions only exist in whatever sizes the font makers choose to create and store.  _The final typeset size is baked into the font._  Bitmap fonts are not just shapes you can typeset at whatever size.  (This is also true to some extent for vectors because of an issue called "optical size," but the limitation is much harder in the case of bitmaps.)  The point here:  changing the size of a bitmap font is a major change to the font itself, not just a trivial matter of different ways to look at the same data.

What BitmapsAvail() does is it attempts to create one or more pre-converted bitmap versions of a vector font, substituting AI for the human intelligence.  If you were using this for font design, the results of BitmapsAvail() would only be a starting point - you would then go and manually edit the low-quality automatically created bitmaps.  You specify the size or sizes you want to automatically create when you call it, and you only get those sizes.  When you later call Export() you are exporting the bitmaps that were created by BitmapsAvail().  You must give Export() one of the same numbers you gave BitmapsAvail(), because all it can do is export one of the sets of bitmaps you created.

When you set the bitmap size you are setting the size of the _font_ (what is often called the "em size") in pixels, not the size of individual letters.  All the images you get out of Export() with a given bitmap size will be scaled so that you can use them to typeset text and they will all be the _right_ size (which is not the _same_ size) compared to each other.  That means, for instance, that uppercase letters will usually be taller images than lowercase, and a letter like "W" will usually be much wider than a letter like "l" in the same size of text.  If instead you made all the letters the same height and width as each other, then text written that way would look very strange.  Since forcing all letters to the same height and width as each other is something people very seldom want to do with fonts, FontForge doesn't have built-in support for doing that easily.

I think you would probably be better served by using something other than FontForge for at least part of this task.  For instance, you could export large bitmaps (at least twice the final size you want, to reduce distortion in the scaling) and then scale them all down to a fixed size with the NetPBM "pnmscale" utility.  If you don't want to scale them, but instead have different amounts of blank space in images that are all the same width and height with letters of appropriate size within those images, you could do that pretty easily by postprocessing with NetPBM utilities as well. (pnmpaste into blank images the appropriate size, I think)

If you are planning to use these images in software you are writing, then you might want to consider using a library like Freetype (which FontForge also uses) to rasterize bitmaps with a relatively convenient API.
