### ISSUE TITLE
Layer Visibility not working

### ISSUE THREAD

**Issue by Ginkgo100** [fontforge/fontforge#2207]
I'm running FontForge v. 15:20 on Windows 7.

In the glyph edit window, the layer palette doesn't seem to work correctly.

No matter what I choose, the current layer and ONLY the current layer is visible. For example, if I toggle between Fore and Guide, here is what happens:

![image](https://cloud.githubusercontent.com/assets/12036864/7235388/7dda52e8-e753-11e4-9109-a833542ca472.png)

![image](https://cloud.githubusercontent.com/assets/12036864/7235417/ab308e74-e753-11e4-87ab-6500ce52ce95.png)

If I turn off Fore layer visibility while that layer is selected, the side bearings disappear, but not the glyph:

![image](https://cloud.githubusercontent.com/assets/12036864/7235484/1495611e-e754-11e4-89d8-6ff97ffe651d.png)

I want to be able to see the Guide layer while the Fore layer is active, which would seem to be the point of having a Guide layer in the first place.

Also, if I click the + button to add a new layer, it always adds a Background layer (even if "Fore" or "Guide") is selected, and always as the new "first" layer (i.e. appearing on the palette below even the main foreground layer). Using the right mouse button, I can change it to a Foreground layer, but not to a Guide layer. I can't seem to move the layer, although I can move the contents of another layer into it (which is at best a counter-intuitive solution).

Am I missing something?

**Comment by davelab6** [comment]
No, FontForge's layers palette is simple to the point of being brutal. :) 

The order of the layers in the palette doesn't matter to the program. 

I think its best to only have 1 Fore layer, named Fore. If you have several, they are copied together and exported in Generated binary fonts. 

In this image:

![image](https://cloud.githubusercontent.com/assets/12036864/7235388/7dda52e8-e753-11e4-9109-a833542ca472.png)

you are still active on the Fore layer (its black) but appear to have the mouse pointer over the Back layer (its blue) and perhaps the screenshot tool is hiding the pointer...

In this image:

![image](https://cloud.githubusercontent.com/assets/12036864/7235484/1495611e-e754-11e4-89d8-6ff97ffe651d.png)

you have turned off Fore layer visibility but while that layer is active it will be rendered, which is why the side bearings disappear, but not the glyph. If you click on Back then it will go black and the outline will not be seen.

And in this image:

![image](https://cloud.githubusercontent.com/assets/12036864/7235417/ab308e74-e753-11e4-87ab-6500ce52ce95.png)

Nothing appears to be drawn on the guide layer; instead you can see the hints being rendered (View, Show, V Hints - etc). You can drag a guide line from the rulers, and thats the same as drawing a line from -1000,A to 2000,A (where A is the height) on the Guide layer.

**Comment by Ginkgo100** [comment]
Thanks for your reply! As you have no doubt realized, I'm quite a beginner still. It never occurred to me that layers don't need to have a specific top-to-bottom order, but now things make a lot more sense. I also see that I was drawing guide lines the hard way; instead of dragging a horizontal line down from the ruler, I was using the add-a-point tool to draw its control points on the guide layer. (The result shows up as a green horizontal line on my second screen shot.)

Going back, I can actually see on those screen shots that the hand-drawn guidelines WERE visible on all layers—but they appear as fine, light gray dotted lines that are very hard to see. This is the same for the guide lines dragged out from the rulers. I have to tilt my screen back and view it at an angle in order to see them at all. I can not find an option to change the line style, although based on my online search of screenshots, it should be possible to make them easier to see.

I do have another problem with layer visibility, though. Currently I'm importing my sketches into the Fore layer as vector images (can't seem to import bitmaps, but that's a separate issue). I'd like to try importing my them into the Back layer and tracing them fresh. But nothing on the Back layer shows up on the Fore layer, even when Back is marked visible. For example, I drew a quick-n-dirty "sample" glyph on the Back layer for illustration purposes:

![image](https://cloud.githubusercontent.com/assets/12036864/7244519/59d66734-e7a2-11e4-8e76-f80bb370035f.png)

But it is not visible in the Fore layer:

![image](https://cloud.githubusercontent.com/assets/12036864/7244528/7f162e58-e7a2-11e4-8f39-f291ad0182a4.png)

Do you know what's going on here?

**Comment by adrientetar** [comment]
Does it show up if you turn off Fill?

**Comment by davelab6** [comment]
I recommend turning off fill anyway, I think its not a good way to work, its better to use the hotkey-fill (`\``) and a metrics window to see filled glyphs

**Comment by Ginkgo100** [comment]
It did work once I turned off fill. Thank you for the responses.

**Comment by craxal** [comment]
I'm a beginner, too, but that fix doesn't sound very intuitive at all. Why do guidelines except for the default ones turn invisible when Fill is turned on? Why was this issue closed?

**Comment by davelab6** [comment]
@craxal I suggest filing a new issue with your concern, since the issue was closed by the person who opened it that seems legitimate to me
