### ISSUE TITLE
Making FontForge prettier

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2209]
**Why**

Because a cleaner interface is also easier to use and thus making FontForge more accessible to new users with the added benefits of also being nicer to look at. It's also easier to convince newcomers that you can make gorgeous fonts using FontForge if the UI doesn't look like it does today.

**Why now**

I am currently making a theme where the goal is to make it look as clean as possible and have stumbled across some things that a theme "makeup" can't fix.

**What I can do**

I can make all the necessary graphics and have a fairly good understanding of how the theming currently works (and where is doesn't work). 

**What I can't do**

Code...

**What I'm proposing**

I can dig trough all issues and gather everything UI related and try to sort it after importance and how easy I assume it is to fix, make all the graphics needed but it's obviously pointless if it's not something any of you coding wizards will help fixing.

**Examples of what could be fixed**

* Update splash screen to be one single image
  * Currently a weird mix of code + image if I remember correctly
* Scrollbars
  * Removing superfluous ones (they are everywhere)
  * Make sure they all look identical
* Colors
  * There are some UI colors that can't currently be themed
* Switch to png graphics for the toolbox button on/off states so this:

![screen shot 2015-04-21 at 12 47 55](https://cloud.githubusercontent.com/assets/3859425/7250852/17d9eebc-e826-11e4-9138-6d300e5769e8.png)
could look more like e.g. 
![screen shot 2015-04-21 at 12 47 30](https://cloud.githubusercontent.com/assets/3859425/7250869/3419e456-e826-11e4-9af6-a3be6d77b42f.png)

* Switch to png graphics for the cursors
* Switch to png graphics for the Numeric Field Sign 
  * It's currently done for the List Mark:

![screen shot 2015-04-21 at 13 03 11](https://cloud.githubusercontent.com/assets/3859425/7250974/f594eea0-e826-11e4-8d76-40cee0dbfb3c.png)

**Recap**

Some of these examples may be easy to fix in code and some not. Something in the UI that I haven't mentioned might be more important to fix.

This is not the point of this post (yet). 

I'm just letting you coders know that I'd gladly do the other part if any of you guys are willing to look into the code side of things.

**Comment by andreaslarsen** [comment]
Screenshot of the theme I'm making that people [seem to like](http://www.reddit.com/r/typography/comments/337f6l/yosemiforge_a_fontforge_theme/)

![screen shot 2015-04-21 at 13 15 27](https://cloud.githubusercontent.com/assets/3859425/7251171/2be4d432-e829-11e4-8274-a0ddba0e243c.png)

**Comment by davelab6** [comment]
Any chance you can make out to libre graphics meeting? :)

**Comment by andreaslarsen** [comment]
Hehe...I'm afraid I don't have big enough pockets for a spontaneous trip to Toronto :smile:

**Comment by davelab6** [comment]
What if your flight and hotel was covered?

**Comment by andreaslarsen** [comment]
Then I'd be very much interested - are there any foundations/organisations one can seek funds?

**Comment by davelab6** [comment]
Email me for details :)

**Comment by andreaslarsen** [comment]
Can you add me on twitter so we can text there?

**Comment by davelab6** [comment]
Done!

**Comment by davelab6** [comment]
I chatted to @andreaslarsen about this and we propose a sprint in Copenhagen or Paris in the summer. Who would be interested to join? :)

**Comment by andreaslarsen** [comment]
Or somewhere else

**Comment by pathumego** [comment]
@davelab6 I have a draft wishlist doc I made [here](https://docs.google.com/document/d/10bOfbJvykm_CUN-nV4FgFn9R7cYWSEEfLm0JnJD3FSU/edit?usp=sharing)

**Comment by adrientetar** [comment]
robofab feat. defcon feat. fontTools feat. Qt

![defconqt](https://cloud.githubusercontent.com/assets/1250894/7334158/49dfdfc6-eb8b-11e4-9794-e25dd685f2cb.PNG)

Only a window to display glyphs from an existing ufo for now but that's mostly because I lack time.  
Also, I'm only getting started when it comes to GUI programming. This is a code example which I edited so it shows glyphs from robofab (well, defcon) objects rather than installed fonts.

**Comment by davelab6** [comment]
Wow, great! Will you publish the sources on Github with GPLv3+? :)

**Comment by davelab6** [comment]
I wonder if font matrix could be a helpful base for this if you want to
write it in qt c++

**Comment by adrientetar** [comment]
I have a basic font info and features editor working today.

**Comment by andreaslarsen** [comment]
Looks interesting indeed @adrientetar - what will you be using to make the gui - html/java or?

**Comment by adrientetar** [comment]
Using PyQt – Qt seems the best option for cross-platform GUI.

**Comment by andreaslarsen** [comment]
I can't really say anything about PyQT but e.g. brackets by adobe uses html/js with great performance, looks and at different screen sizes so it's definitely possible to use just js/html for the fronted side of things. Any who - good luck with the project!

**Comment by adrientetar** [comment]
Well, considering Qt uses the native widgets of each OS and it's easy-to-use and customize as well it was a natural choice. 
And while I'm pretty well versed into web development I rarely ever do complex things with JS and the dom like building apps/ui, and machine toolkits like Qt are imo more tailored for this job. The main motivation for Brackets was making an editor for the web with the web, kind of like robofont is made in python and so allowd fonts people who know python to modify or add functionality to the editor directly.
Thanks.

**Comment by pathumego** [comment]
@adrientetar Will this run existing RoboFont extensions ?

**Comment by davelab6** [comment]
I'm very happy to see yet another libre font editor project! :) 

A while back, I discussed liberating RoboFont itself with @typemytype, but it seems he isn't interested at any price. Glyphs is even more tightly coupled to Cocoa so liberating it makes less sense for Glyphs.

RoboFont itself seems to depend a fair bit on Cocoa, so I think the main things would be to match what is in the mojo API with Qt functions, and write a Vanilla backend to use PyQT widgets.

The core of RoboFont's libraries are published libre software, so making a libre Qt version is not so much effort. Also Fontlab 6 is being rewritten from scratch in Qt C++, another validation of the Qt choice.

Like Andreas I also think html5 is a better toolkit than Qt, because with native toolkits, their widget set is too limited. While it integrates nicely with a c++ code base, or a python codebase with PyQt, and is nicely cross platform, nothing beats the web for cross platform and the web is so so so customisable.

NovaCut and probably some other applications are written in python for the core with a html5 ui. That in a way allows the best of both worlds. However, the integration with the standard Qt development tools isn't there, and the gestalt application requires coordination of the heterogeneous parts.

All the other new libre font editors have taken a pure web approach, and today Glyphr-Studio, metapolator and prototypo are solid projects with over 12 months of team effort behind each. All are written wholly in js, which means the python libraries Adrien is leveraging are unavailable. 

But @graphicore already ported much of RoboFab to js in ufoJS, and OpenType.js has a nice convenience wrapper from Prototypo on plumin.js. @mattlag says glyphr will export binaries via OpenType.js soon, and I hope it will also support UFO via ufoJS. 

For me, I think the huge number of people who know web technologies means such projects are more likely to be participatory and emancipatory, but as I said, I'm very happy for all libre efforts :)

**Comment by adrientetar** [comment]
> Like Andreas I also think html5 is a better toolkit than Qt

I know and this is why I set out to do my own project.

**Comment by adrientetar** [comment]
> with native toolkits, their widget set is too limited

This is not true. Personally, the first thing I do when I start a project is actually learning about what I am going to do.

**Comment by pathumego** [comment]
@lpsandaruwan is making this plan. I think we can expand it to be a full documentation of the changes we make. https://docs.google.com/document/d/1_oWAitHWJadgmUGTt1M7oMBXfElK091cEmSsDaF3saA/edit#

**Comment by pathumego** [comment]
Closing This is being discussed in #2257
