### ISSUE TITLE
Could we remove icons from the menus?

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2230]
Can be done by just deleting the .pngs 

I think it looks a lot cleaner without and icons don't really makes sense in menus.

![screen shot 2015-04-28 at 11 54 44](https://cloud.githubusercontent.com/assets/3859425/7368991/1405fdac-edae-11e4-9e39-c482b7a0e49e.png)

**Comment by andreaslarsen** [comment]
To elaborate a bit: 

It only makes sense to use an icon - when it makes sense without the text. This is true for very few of the menu icons e.g. print, save, new, redo, undo etc.
An example of other apps using these icons is google docs. To me it's a bit redundant though because most users (especially users who download fontforge) knows the keyboard shortcuts for these menu items anyway.

The rest of the icons aren't immediately understood or needs the text explanation to be understood. I really can't see what value it adds having an icon next to it. New users won't recognise the icons and old users know where the menu item is and/or use keyboard shortcuts.

**Comment by pathumego** [comment]
@andreaslarsen I agree with this. Most of the icons dose not make sense.

But the I don't know how other users would feel about this.

**Comment by davelab6** [comment]
I believe that icons on every item were a good idea for applications with
toolbars with dozens of icons (like classic Windows 98 era ms office
applications) so that you could learn where a menu item was on the toolbar
by Pavlovian memorisation of the icon.

But for apps without a toolbar, as we are today, then having icons for
everything is the same as no icons:

The icons are most useful for signposting/telegraphing the most commonly
sought menu items, so that users find them faster and click them with less
errors.

However, when all items have icons, this effect is lost.

I'm happy for to say what the most common actions are :)

**Comment by andreaslarsen** [comment]
they can be used for signposting but this was also more relevant years ago - now people know that e.g. the new file is always located at the top of the file menu and/or they already know the keyboard shortcut. I don't think I have a single app installed besides FF that still uses menu icons.

**Comment by davelab6** [comment]
Well it's not part of the Mac hig, not sure about windows

**Comment by andreaslarsen** [comment]
In e.g. Inkscape (gnome/gtk) they are now also disabled by default

**Comment by jtanx** [comment]
I quite like icons in menus. The icons are present on Windows (not entirely sure how this is controlled). I just checked Inkscape 0.91 - they still have icons too.

**Comment by davelab6** [comment]
I think maintaining 2 Mac/win themes could be good to make it more familiar
to users of each

**Comment by andreaslarsen** [comment]
You're right they are back in 0.91 - I had a dev version installed where they had removed them.

I know that some people still like to have menu icons and I'm not suggesting we kill support for menu icons - they could easily be added with themes. 

I can't find anything in windows guidelines about menu icons. 

http://uxmyths.com/post/715009009/myth-icons-enhance-usability

**Comment by andreaslarsen** [comment]
And I'm not making this argument based on operation system interface guidelines. I think menu icons are a bad idea regardless of operation system.

Some quotes:

"A user’s understanding of an icon is based on previous experience. Due to the absence of a standard usage for most icons, text labels are necessary to communicate the meaning and reduce ambiguity."

"UIE conducted two experiments to test how people use icons. First they changed the pictures of icons in a toolbar but kept them in the same location. People quickly adapted to this change. Afterwards, they kept the images but shuffled their location in the toolbar. This change confused the participants and caused problems for them."

"icons contrary to intuition, do not necessarily help the user find a menu item better than a text label alone (see Wiedenbeck S 1999. The use of icons and labels in an end user application program: an empirical study of learning and retention, Behaviour & Information Technology, 18(2), p68-82). It’s not worth it."

"Peter Steen Høgenhaug conducted a test to measure how people understand icons of a CMS editor. The result: the widely used 'insert link’ icon was understood only by 35% of the participants, even the classic 'undo’ and 'redo’ icons were only recognized by half of the participants."

"As rule of thumb, icons alone should only be permitted when at least two out of the following three conditions apply:

Space is very limited (i.e., too small for text alone).

The icons are standardized (e.g., the “X” icon on a window Close button)

The icon represents an object with a strong physical analog or a visual attribute (e.g., a printer icon to access printer attributes, or a red rectangle to set a page background red)."

**Comment by davelab6** [comment]
If you just include Transparent only files in your theme, and the website
theme remains with current icons, we won't need any code for handling both
cases

**Comment by andreaslarsen** [comment]
No code is needed - I just think icons should be transparent/removed as default as it's better UX :)

We can always make a nostalgia theme for people still wanting icons.

**Comment by ctrlcctrlv** [comment]
Five years later I'll give you an answer: No.
