### ISSUE TITLE
Updating windows icon + (adding?) manifest

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2327]
I wanted to update the icon for FF on windows and easily found `fontforge-installer-icon.ico` and `ff.ico` but I couldn't find the manifest or similar xml file anywhere. 

Can someone tell me where it is? Or if we don't have one: where I should save it and if any other steps are required. 

Info about win8 manifest here: https://msdn.microsoft.com/en-us/library/windows/desktop/br211475.aspx

I'm also hoping less than the 49 png's used by e.g. spartan is enough for tile icon...this is a dump from the latest win10 build: 
![screen shot 2015-06-05 at 00 05 39](https://cloud.githubusercontent.com/assets/3859425/7995538/fa776976-0b16-11e5-9c90-74ac0ad4c40d.png)

**Comment by jtanx** [comment]
As I said in the other thread, having the SVG source would be nice, since then I can make the .ico.

Essentially, [these files](https://github.com/jtanx/fontforgebuilds/tree/master/fontforge-setup/Graphics) and [these files](https://github.com/jtanx/fontforgebuilds/tree/master/patches/artwork) need to be updated to update the installer and launcher (run_fontforge.exe) icons and the icon associated with opening an SFD.

The icons are updated by re-running the [installer script](https://github.com/jtanx/fontforgebuilds/blob/master/fontforge-setup/fontforgesetup.iss).

**Comment by larsenwork** [comment]
I've already med the .ico - was easy with GIMP. I only included 32 bit (the old also had 4 bit - but as far as I could see even XP supports 32 bit). I'll upload the svg too. What I'm more interested in right now is the manifest so I can make the solid white icon + set the tile background color.

**Comment by jtanx** [comment]
I don't know what manifest you are referring to. Can you clarify what you mean by 
>  make the solid white icon + set the tile background color.

**Comment by larsenwork** [comment]
Read my first comment and see the link

**Comment by jtanx** [comment]
Yep, well there's none of that, so...

**Comment by larsenwork** [comment]
But how do you set the tile background color and tell what white icons to use if not in the manifest?

**Comment by jtanx** [comment]
You don't; it gets automatically determined.

**Comment by larsenwork** [comment]
But the automatically determined color is dull - it should be orange. 
So for the solid white icons I can just include them and windows will detect?

**Comment by jtanx** [comment]
I guess. To be honest I never pay attention to the colour of the icon, since most of the time I just type the name and press enter to launch.

**Comment by larsenwork** [comment]
Many users still open apps by navigating to them and clicking so we still need:
* How to change the tile background color
* Which solid white png files is needed

**Comment by jtanx** [comment]
Even so, it's never been an issue before, so I don't see why it's an issue now. All that's really needed is the .ico file and we're good.

**Comment by larsenwork** [comment]
Why not make it not ugly?

**Comment by jtanx** [comment]
It wasn't ugly?

**Comment by larsenwork** [comment]
![screen shot 2015-06-05 at 08 05 04](https://cloud.githubusercontent.com/assets/3859425/8000347/9fff20e0-0b59-11e5-8f2a-8dd54ff5d181.png)

**Comment by larsenwork** [comment]
> Even so, it's never been an issue before, so I don't see why it's an issue now.

This knee jerking can be said with every improvement anyone's trying to make is anything but constructive.

**Comment by larsenwork** [comment]
I guess ugly is a matter of taste - but it is objectively bad (not following windows guidelines, low contrast + high detail icon, small icon and generic background color)

**Comment by jtanx** [comment]
Well what can I say, that colour's being automatically determined by Windows, so if they're breaking their own guidelines, what can I say :P

The icon is that small, because the person who made the .ico didn't include 64x64, 128x128 and 256x256 image sizes. That's why I was saying, post the SVG source.

~~~~~~
 C:\Users\tanjj\Pictures\ico>icobundl.exe fontforge-icon.ico -o test.ico
fontforge-icon.ico
#   0:   48 x  48, 32 bits/pixel
#   1:   48 x  48,  8 bits/pixel
#   2:   48 x  48,  4 bits/pixel
#   3:   32 x  32, 32 bits/pixel
#   4:   32 x  32,  8 bits/pixel
#   5:   32 x  32,  4 bits/pixel
#   6:   16 x  16, 32 bits/pixel
#   7:   16 x  16,  8 bits/pixel
#   8:   16 x  16,  4 bits/pixel
#   9: PNG (Vista) icon
fontforge-icon.ico
Bundled 10 icons from 1 input files.
~~~~~~

**Comment by larsenwork** [comment]
The guidelines obviously didn't refer to the color ?! but to the tile icon not being solid white...

**Comment by larsenwork** [comment]
And the icon is that small because there is no dedicated tile icon png present. 
The svg was there for the old icon all the time so nothing would have stopped you from fixing that.

**Comment by larsenwork** [comment]
Please consider your tone and attitude - I'm just trying to help and make things better.

**Comment by larsenwork** [comment]
Just because I like to back statements with objective facts here's a screenshot showing how an app with 256x256 ico file (the paint icon) still is small in the live tile since microsoft haven't added dedicated tile pngs to that application in contrast to e.g. spartan + camera icon also shown in the picture.
![win10a](https://cloud.githubusercontent.com/assets/3859425/8000588/04f923ee-0b5d-11e5-924d-d5e76b687eb7.png)

**Comment by larsenwork** [comment]
Where do I find the graphics for this:
![win101](https://cloud.githubusercontent.com/assets/3859425/8000844/c3b8105e-0b5f-11e5-90aa-fb9424ab45f4.png)

**Comment by larsenwork** [comment]
I couldn't figure out how to add proper tile support but I have the graphics needed should someone want to have a go at it. 

fwiw these are the new icons:
![screen shot 2015-06-05 at 09 51 04](https://cloud.githubusercontent.com/assets/3859425/8002263/9a319792-0b6d-11e5-972a-e729e39f052f.png)
![screen shot 2015-06-05 at 09 50 59](https://cloud.githubusercontent.com/assets/3859425/8002264/9a54172c-0b6d-11e5-8e0e-8831059b3e93.png)
![screen shot 2015-06-05 at 09 50 48](https://cloud.githubusercontent.com/assets/3859425/8002266/9a569862-0b6d-11e5-967b-dbf556df13ab.png)
![screen shot 2015-06-05 at 09 50 41](https://cloud.githubusercontent.com/assets/3859425/8002265/9a569bbe-0b6d-11e5-8d79-d3b11568aaa0.png)


I'll pr them to ff source once this get's answered https://github.com/fontforge/fontforge/issues/2328

**Comment by pathumego** [comment]
Wooo.. nice :)

**Comment by larsenwork** [comment]
@jtanx please be frank: Do you have a problem with me and my suggestions? If not and this is just your "style", then please refrain from commenting on anything I post, because I only want to join in positive and constructive discussions where I don't have to be defensive from the start and we try to understand each others opinion and I'm getting tired of knee-jerking holier-than-thou replies like 
`
Well what can I say, that colour's being automatically determined by Windows, so if they're breaking their own guidelines, what can I say :P
`
when thats not at all what I said.

**Comment by jtanx** [comment]
To me, you're exrapolating x from y from my comments. That quote in particular was made tongue-in-cheeck, plus there was some misunderstanding:
> generic background color

From that, I assumed you were talking about the tile colour, which as we were talking before, *is* automatically determined by Windows.

Since this is getting nowhere, this will be the last comment I make on this issue (which I think is a non-issue, apart from uploading the SVG source already to make the new icons).

**Comment by adrientetar** [comment]
@larsenwork Please be frank: will you do name calling on every single maintainer for expressing their opinion?

You might find this juvenile (re: #2319), but free speech is something my ancestors put up their life for up until the 3rd degree of my legacy.

> Just because I like to back statements with objective facts

Project Spartan and Camera that you’re showing here are WinRT apps, Paint and FontForge are win32 apps.  
That’s how the default styling is as far as I know.

**Comment by adrientetar** [comment]
@larsenwork Seriously though: I think you are excessively inferring negative intentions towards you. Criticism is part of open-source. Everyone has their opinion and the fact that not everyone thinks like you doesn’t mean they’re against you or what you are doing.

**Comment by larsenwork** [comment]
@adrientetar I don't want to name call anyone, I don't need history lessons (but hey: vive la revolution!) and I have nothing against criticism as long as it's constructive:)
It's clear from the above that I didn't know the difference between RT + win32 otherwise I wouldn't have asked how to get the solid white icon with special tinted background. Your post actually answered my questions and educated me - to me that's what projects like this are for:)
I'm not excessively inferring anything - I'm just asking for nice and constructive tone.

**Comment by adrientetar** [comment]
@larsenwork I say this: we’re all here to make this software better, but we all have different roles and knowledge. For instance, @jtanx is both a release-engineer for Windows and a user of this platform. He knows what it’s like to try and make FontForge work on Windows, he’s also doing his best so that everything goes smoothly. As far as I can see, what he said above:

```
Well what can I say, that colour's being automatically determined by Windows, so if they're breaking their own guidelines, what can I say :P 
```

essentially means the default is that on Windows. He’s giving out an information and if anything, his post is friendly and not "knee-jerk" (he makes humor on how Windows seems to break their own guidelines? That’s how I read it. A discussion on whether the default behavior should be changed may follow as a direct consequence of this comment which i.m.h.o clearly shows that it is not "not constructive" &ndash; as with anything this is extra work on @jtanx though so you have to listen to him and discuss with him whether he thinks changing e.g. the UI font or stuff makes sense on Windows, whether it’s hard to program and maintain etc. This is the difference between design and software maintenance, we have people who do both of these things here and we ought to have them work together. If you think that a comment made by a maintainer is nbot constructive, then maybe you have not looked at it the way it should. Comments made by maintainers are essentially either LGTM or questioning changes, either intrinsically or for the consequences they may have for maintenance or consistency w.r.t one platform or the others. I don’t think @jtanx or anyone else in the core team are here solely to make non-constructive comments. This all takes up some of our time to everyone of us and we ought to be productive, that’s what we are all striving for. Now, these are words, they don’t have a tone even though they may be written in an agressive way or otherwise. What I can say though is since we’re communicating solely by the written word there is less information about intent than when you speak with someone by the voice, so i.m.h.o some of the comments you call not constructive and/or aggressive are just how you’re looking at them. Personally, I’m not here to post non-constructive comments, just discussing how we’re going to make the software better for tomorrow. )

Now this is just my opinion, I’m not speaking for anyone else here.

**Comment by larsenwork** [comment]
@adrientetar I agree on your sentiment and can see you understand what he and I say differently than I did - and understand that my replies and interpretations in this thread are "coloured" by some of the bad replies I've gotten earlier so I've probably taken this specific example harder than I should.

All I'm asking is for people to comment and criticise nicely and this thread was just the "drop that tipped the cup" (danish saying) for me.

I understand that you coding guys do some lifting that I and other frontenders can't do - that's why I try to do as much as possible - e.g. making .ico files myself, installing windows 10 and FontForge there so I could test it. 

It wasn't until your reply about RT that I learned the difference. Reading back I can see that may be the thought behind the replies but it's not what I read and it could have been written a lot clearer (like you did).

**Comment by adrientetar** [comment]
@larsenwork

> it could have been written a lot clearer

Surely, but imo the purpose of an issue thread is to talk about what we’re going to do, not emphasize what we think of eachother. Ultimately we are here to work in the first place, and as I said this takes up some of our time, for all of us so we tend to try and keep it brief. 
But we have the same goal, even though sometimes we may not have the same view on things so someone asking for clarification/discussion does not mean he wants to reject the change above all other things, maybe he genuinely wants to be explained something even though it looks obvious to you. So, I wouldn’t take a negative stance "by default" when reading a comment.

**Comment by larsenwork** [comment]
@adrientetar agreed, not sure what your point is? The whole purpose of my initial rant was based my frustration with unnecessary negative replies leading to me taking the negative stance "by default" - or being defensive or what I called it.

If we take the time to word our disagreement then we also have the time to tell why we disagree (if it's just a matter of taste) and/or educate (in a positive manner) as to which premises are wrong (this case: only RT apps have solid white icons). And also when we disagree about something purely based on taste: come up with a better solution instead of just saying "buh, bad".

I know it takes a bit longer than short knee-jerk replies but it leads to a more positive and collaborative environment in the end and is a huge time saver.

**Comment by larsenwork** [comment]
And one last pet peeve:

If person "A" suggests idea "1a" and "B" replies with a contra argument which leads to person "A" to either make more arguments for case "1a" and/or modify it into "1b" then person "B" should reply and not just let person "A" hang there not knowing if "1b" is a good idea or not. If you start a discussion then please end it too so we can close/fix the issue.

**Comment by larsenwork** [comment]
> Surely, but imo the purpose of an issue thread is to talk about what we’re going to do, not emphasize what we think of eachother. 
I've never said what I thought of anyone - haven't met any of you guys. I just said how I think we should write to each other and how we shouldn't.
> Ultimately we are here to work in the first place, and as I said this takes up some of our time, for all of us so we tend to try and keep it brief. 
Obviously, but brief doesn't necessarily != clear
> But we have the same goal, even though sometimes we may not have the same view on things so someone asking for clarification/discussion does not mean he wants to reject the change above all other things, maybe he genuinely wants to be explained something even though it looks obvious to you. 
Not sure what this is referring to.

**Comment by larsenwork** [comment]
@jtanx sorry if I misunderstood what you've tried to communicate and I hope no bad feelings. I was just really frustrated by having my ideas/suggestions shot down all the time without reason or without me understanding the reason. I hope no bad feelings.
