### ISSUE TITLE
Renaming FontForge

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2362]
There's been some discussion in other threads so I'd figured we gather in a issue to keep things on topic :smile: 

**Problems and concerns**
* Versioning for pkg managers. We have a high version number and would like to change to a simpler X.X.X based version numbering.
* SourceForge releasing their own build versions with malware attached
* Other?

**Suggestions**
* Add a suffix
  * FontForge Neue
  * FontForge Nova
* Change to a new name
  * Fontanova
  * FontFree

Any other suggestions?

**Comment by larsenwork** [comment]
I'd vote for a complete name change since suffixes evoke tacky light versions to me (e.g. Photoshop Elements and all the crippled "free" versions of apps on e.g.  App Store.)

**Comment by jtanx** [comment]
My suggestion is not changing the name at all. 

SourceForge doesn't release builds with malware attached. The closest is if you opt to have the installer use their 'installer' for advertising revenue. Otherwise perhaps this is talking about malicious advertising that displays a false 'download' button - this should be reported to FontForge AFAIK.

**Comment by larsenwork** [comment]
@jtanx would be my preferred suggestion too but I was lead to the understanding we couldn't move to a more sane version numbering without a name change?

As for the SourceForge worries they are based on what @mskala wrote here: https://github.com/fontforge/fontforge/issues/2323#issuecomment-111679682

**Comment by jtanx** [comment]
Oh yep, I see now, that Sourceforge development is a [recent thing](http://sourceforge.net/blog/third-party-offers-will-be-presented-with-opt-in-projects-only/). Well that's crap.

**Comment by pathumego** [comment]
Reflecting upon this, I felt like I would like to stick with the old name. I mean UI tweaks and new menu structure is not worth of a name change for me.  Renaming is a whole different story than a visual overhaul ryt? And I wrote on the other thread, if we all think the new menu structure is improving things then there is no need for separate build with a new name. :) The test builds with the new menu structure will land this week :) So we could ask everybody like it or not...

**Comment by larsenwork** [comment]
The reason for potential name change is not redesign as I see/understand it but to get better version numbering and avoid any potential sourceforge problems

**Comment by khaledhosny** [comment]
You want to rename a 10+ years old project because Homebrew does not support epoch?

**Comment by mskala** [comment]
:smile:

**Comment by larsenwork** [comment]
@khaledhosny no, I just wanted a more sane version numbering and was told the only way that could way that could happen was by changing the name

**Comment by khaledhosny** [comment]
You can change the version easily, as long as you ignore primitive package managers.

**Comment by larsenwork** [comment]
@khaledhosny ok, I was just led to believe it was no go solution by others here :)

**Comment by DomT4** [comment]
> You can change the version easily, as long as you ignore primitive package managers.

This is kind of harsh. `apt` doesn't handle sudden version changes from a version that seems greater to a version that seems lesser well either. *Most* package managers handle that situation horribly, because logic dictates versions should *appear* to go up rather than down.

We can handle the version situation if it comes to it; If necessary we'll stick in an artificial version to keep the updates flowing.

**Comment by khaledhosny** [comment]
Both `deb` and `rpm` packages can handle this by increasing epoch which gets the highest priority when comparing version numbers.

**Comment by ctrlcctrlv** [comment]
I see that it was decided not to rename but I still feel compelled to add:

Ridiculous. Of all the reasons to change a project name...

FontForge used to be called pfaedit, which made sense when people actually used Printer Font ASCII. It was changed because its featureset was widely expanded and PFA fell out of fashion.

Try actually adding something new before tagging on a "Nova" or a "Neue" (and no, a new Apple installer doesn't count, not to cheapen the efforts of packagers; but seriously, it doesn't). A new GUI toolkit, a better pen drawing mode or something of that sort might count.

The other names are just cringeworthy.

**Comment by larsenwork** [comment]
@ctrlcctrlv I only proposed it based on this but would also much rather keep the name but was lead to believe these major issues couldn't be "solved" otherwise:

> Versioning for pkg managers. We have a high version number and would like to change to a simpler X.X.X based version numbering.
> SourceForge releasing their own build versions with malware attached

since first point isn't a concern and the second only a hypothetical scenario I'd also vote against changing the name.

I'm closing this issue and hoping someone more knowledgeable - e.g. @khaledhosny opens an issue regarding the version numbering so we can get a more sane numbering.
