### ISSUE TITLE
UNABLE to install version on June-18 on Windows 8.1 with latest security update

### ISSUE THREAD

**Issue by newandroid66** [fontforge/fontforge#2370]
Hi.

It is impossible to install on win 8.1 with security updates.
So, 
I suggest you that
- use certified installer
  or
- make portable version.

Check it out. 
(it is not about administrator problem, but popup that harmful application warning from Windows system to block)

**Comment by jtanx** [comment]
Can you please explain further what the issue is? What antivirus software are you running? 

I am personally using Windows 8.1 and I have no trouble installing it.

**Comment by d-mal** [comment]
I think I understand what the OP's problem is, since it happened to me with the current version as well:

When I  double-click "FontForge-2016-10-04-Windows.exe" to start the installation, a warning from Windows is shown: "publisher could not be verified -- do you want to run the software anyway?" and an explanation "this software has no valid digital signature that verifies the publisher. you should only execute software that comes from publishers you trust" (don't know the exact english wording)

This will keep some people from installing Fontforge, for a good reason. I still have Win 7, but the issue will probably show up on other Windowses.
