### ISSUE TITLE
Make all font CAPS

### ISSUE THREAD

**Issue by BLACKIRISH530** [fontforge/fontforge#2418]
I want to make ArialNarrow all CAPS for AutoCAD. How would I just open the .ttf file and edit it so that no matter how I type the letter it comes out CAPS? I have seen many other true type fonts but not this one.

**Comment by ctrlcctrlv** [comment]
Pretty easy...

Open your font, obviously Arial Narrow and not Ambrosia, but I don't have Arial Narrow.

Select all the lowercase letters, right click, Clear.

![clear](https://cloud.githubusercontent.com/assets/838783/8612513/554bcc58-2704-11e5-8e77-d9e3e938057c.png)

If this window appears, "Yes to all".

![clear2](https://cloud.githubusercontent.com/assets/838783/8612516/5a4a81fe-2704-11e5-8179-ea11e0e0a818.png)

Select all the uppercase letters, Ctrl+C Copy, select the "a", Ctrl+V paste.

![clear3](https://cloud.githubusercontent.com/assets/838783/8612518/5e34777a-2704-11e5-9347-68982e2a3d48.png)

File->Generate Fonts, save as TTF.

Please note it is probably illegal to edit Arial in your jurisdiction, since it's a copyrighted computer program; it's probably even more illegal to distribute it.

Have fun :)

**Comment by larsenwork** [comment]
Closing because it's answered
