### ISSUE TITLE
Fails to import .svg on latest Windows buld

### ISSUE THREAD

**Issue by WillAdams** [fontforge/fontforge#2421]
this one: http://www.shapeoko.com/wiki/index.php/File:Tool_calipers_locking.svg

**Comment by jtanx** [comment]
It seems this is not specific to the Windows build. Hangs but does not crash while trying to import it.

**Comment by ctrlcctrlv** [comment]
I noticed this too. FontForge seems to really struggle if an SVG is stroked; actually it's very bad with complex SVG files so I recommend simplifying them as much as possible.

For getting this one to upload all I had to do was (in Inkscape) Ctrl+A, Ctrl+Shift+F, go to "Stroke Paint", click the "X" for no stroke. The Inkscape canvas will turn all white, that's fine because the paths are still there. Once you save that, it will successfully import.

![ff](https://cloud.githubusercontent.com/assets/838783/8637958/592b76cc-28dd-11e5-89e3-4a5e96b09a0f.png)
![importe](https://cloud.githubusercontent.com/assets/838783/8637967/63bd1668-28dd-11e5-97eb-e342f8f1276f.png)

**Comment by skef** [comment]
The style for the path in this file is:

```
fill:none;stroke:#231f20;stroke-width:0.5;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:3.86360002;stroke-dasharray:none;stroke-opacity:1
```
If you remove the "stroke:#231f20" the file imports fine. The "hang" is really a delay due to the huge number of points the import process adds when that "stroke" specification is present. 

I suspect that the svg import process is attempting some sort of shading. We should probably just disable that for outline import, which is really just for contours and not other aspects of the SVG spec. 
```

**Comment by skef** [comment]
With the `stroke` parameter you wind up with (at least) an order of magnitude more points than otherwise. Cairo's trouble understandably stems from that large number. 

Frustratingly I haven't managed to isolate the code adding those points. Presumably it's some sort of cross-hatching or other shade-simulating pattern. Profiling doesn't help -- apparently creating the points doesn't take much effort. I can't imagine this is something we would want enabled in practice, at least not without flashing lights and warning bells, but to turn it off I have to find it. 

I guess I will look harder ...

(Incidentally I updated the "Notes for developers" section of the CMake wiki page with advice for profiling-enabled compilation. @jtanx might want to confirm and/or modify. Worked for me, though. (This is not a passive-aggressive request for a profiling target, just an FYI.))

**Comment by ctrlcctrlv** [comment]
Maybe it would help to try a simpler test case, so the output might have a chance of not freezing FontForge? You could confirm your theory. I might try this later, but you've probably already thought of it.

**Comment by skef** [comment]
It's a good point -- with a small enough test case one could step through the creation process.

**Comment by skef** [comment]
So I did go ahead and make a simplified version, and the problem isn't cross-hatching, it's that the contours are being traced multiple times. Confusingly one pair was traced three times and one four times. Still looking.

**Comment by ctrlcctrlv** [comment]
Perhaps it's trying to make fake-opacity that way? It would sort of work. Probably different values for &alpha; will result in different results.

**Comment by jtanx** [comment]
See also #3618 if you haven't already. I'm pretty sure turning off the outline functionality at least helps a bit.
