### ISSUE TITLE
Circles imported from SVGs don't look circles

### ISSUE THREAD

**Issue by anasram** [fontforge/fontforge#2475]
![fontforge](https://cloud.githubusercontent.com/assets/12219238/9579488/b5288402-4ffb-11e5-8094-286f10bfec89.png)

**Comment by skef** [comment]
We would need a sample file to evaluate this.

**Comment by anasram** [comment]
Check character: ⚫ `U+26AB MEDIUM BLACK CIRCLE` in [RichStyle font](https://richstyle.org/themes/richstyle/fonts/RichStyle/RichStyle.ttf).

Source files are [here](https://richstyle.org/downloads/src/fonts-richstyle_0.4.tar).

**Comment by skef** [comment]
Although there are some unusual SVGs in this collection, some of which appear to need encouragement to output as proper contours, the sun SVG is very "vanilla" -- it doesn't have any SVG strokes, just normal closed paths. 

So this problem was likely due to a problem with the FontView-level rasterizer. I'm not seeing it currently with my GDK-linux compiled version:

![sun](https://user-images.githubusercontent.com/6175836/74108140-fd165e80-4b2b-11ea-80b8-752d9ecb7431.png)

Maybe my eyes are failing me but I'm not seeing 26AB in that archive. Should be `''$'\342\232\253''.svg'` with `LC_ALL=C ls -l`?, right?

**Comment by anasram** [comment]
> Although there are some unusual SVGs in this collection, some of which appear to need encouragement to output as proper contours, the sun SVG is very "vanilla" -- it doesn't have any SVG strokes, just normal closed paths.

> So this problem was likely due to a problem with the FontView-level rasterizer. I'm not seeing it currently with my GDK-linux compiled version:

In fact I'm not expert in font technologies, and this work has originally been done with the help and support of @khaledhosny, and as I remember, I think he was the one who told me that the way circles look in the font is due to a bug in Fontconfig itself.

@khaledhosny?

> Maybe my eyes are failing me but I'm not seeing 26AB in that archive. Should be ``$'\342\232\253``.svg' with LC_ALL=C ls -l?, right?

It's the `⚫.svg` file.

**Comment by ctrlcctrlv** [comment]
> bug in Fontconfig

Presumably you meant FontForge.

> It's the `⚫.svg` file.

The archive contains no such file.

**Comment by anasram** [comment]
Ops! x2

I'm sorry. I just corrected both.

The link now refers to [fonts-richstyle_0.5.tar](https://richstyle.org/downloads/src/fonts-richstyle_0.5.tar).

**Comment by skef** [comment]
So this new version hits #3699 / #2556 when attempting to output the otf version; we should really track that problem down. However, that's not the focus of this issue. 

In the (or "a") current Cairo-based FontForge this glyph looks fine in the FontView window:

![round](https://user-images.githubusercontent.com/6175836/74428257-802a0400-4e0d-11ea-886c-6ed460827ece.png)

There may be a lingering alternate non-Cairo rasterizer lingering in the code, but it's unlikely anyone will compile against it at this point. 

It's been a number of nears since you filed this @anasram -- do you use a more recent version of FontForge now, and are you still having this problem with it?

**Comment by anasram** [comment]
No, it works fine now! 😊

![fontforge](https://user-images.githubusercontent.com/12219238/74669453-ceddf200-51af-11ea-96ea-a862d844d54f.png)
