### ISSUE TITLE
how to combine spline font database files into one

### ISSUE THREAD

**Issue by gwykwong** [fontforge/fontforge#2477]
I use text editor to combine two sdf files into one.  But after amending the "BeginChars" and using copy and paste for those "StartChar" and "EndChar" blocks from the second file to the first file, the number of fonts appeared on screen after using "open file" are restricted by the "BeginChars" initial value i.e. if the initial value is 256 255, then the number of characters displayed is 256 instead of 512.  I have lumped two files with 256 each into one.  Please advise me what is wrong with my using the text editor to perform the combination.  Your advice is highly appreciated.

**Comment by mskala** [comment]
Editing SFD files by hand is almost never a good idea.  In the case you describe, each character is marked with its encoding slot number.  The order that glyphs go into encoding slots is _not_ determined by their order in the file.  It is determined by the encoding numbers attached to the glyphs.  The glyph for slot 65 is whichever glyph has the number "65" attached to it; not the 65th glyph in the file.

If you have two different font files, they may each have a glyph numbered 65 for "A", and then if you paste part of one font file into another font file, you end up with an invalid font file containing two different definitions for glyph 65.  In order to make it work you would have to change the slot numbers on all the newly added glyphs - as well as changing the overall encoding of the font to match whatever you're trying to accomplish.  It's much more complicated than cutting and pasting lines in a text file.

I would suggest instead:

* Decide on an encoding for the finished font.  "Custom" might be a reasonable choice.  It's not clear that what you're trying to do makes any sense in the context of a more standard encoding like ASCII.
* Open both input files, and use the "new" command to create an empty font for the output file.
* If necessary, create enough new slots in the new font to contain all the glyphs you want it to have.
* Select the glyphs in the first font and choose "copy"
* Select the same number of empty glyph slots in the output font and choose "paste"
* Repeat the steps to copy and paste from the second font into the output font

You can automate these steps with a script, but I don't think it's practical to attempt to do it by editing the SFD files with a tool other than FontForge.  Editing SFD files outside of FontForge is almost always a mistake.

**Comment by gwykwong** [comment]
Dear Mr. Skala,

Thank you very much for your reply.  The reason I intend to merge two files
together instead of doing it through FontForge is that I can only create
fonts up to 256 characters in one file and the system does not allow me to
build as many characters as I like in one file.

I should be grateful if you would advise me how can solve this situation.
I do not know how many empty glyph slots I can create in one file.  If I
can create 2000, then my problem will be able to solve by your advice in
your reply.

Please enlighten me.


Best regards,
Kwong

**Comment by mskala** [comment]
First choose an appropriate encoding for your font with the "Reencode" option on the "Encoding" menu.  The choices most likely to be useful are "ISO 8859-1 (Latin1)" (256 code points, only appropriate for Western European languages such as English); "ISO 10646-1 (Unicode, BMP)" (approximately 65000 code points, appropriate for most languages but does NOT give full coverage of Chinese); or "ISO 10646-1 (Unicode, Full)" (approximately 1 million code points, appropriate for nearly any language).  There are many other choices on the menu but in general they are only appropriate if you already know what they mean.

I think that choosing one of the Unicode encodings will probably give you the slots you need with the proper encoding values, but if you need to create more, there is an "Add Encoding Slots" option on the Encoding menu as well.  There is no practical limit to how many slots you can add that way - at least a million.  However, slots added that way will have no encoding numbers and in general are unlikely to work the way you may expect.  My suggestion would be to start by choosing a Unicode encoding and see if that helps.

**Comment by gwykwong** [comment]
Dear Mr. Skala,

My heartful thanks for your most informative clues.

I will try as directed.  Thanks again.

Best regards
Kwong
2015年9月2日 下午8:45 於 "Matthew Skala" <notifications@github.com> 寫道：
