### ISSUE TITLE
FontForge 20150829 Won't Launch on OS X 10.10.5 

### ISSUE THREAD

**Issue by arandorion** [fontforge/fontforge#2506]
Here's what debug in the Terminal says:

> Process 1122 launched: '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64)
> dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
>   Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
>   Reason: image not found
> Process 1122 stopped
> * thread #1: tid = 0x6045, 0x00007fff5fc01075 dyld`dyld_fatal_error + 1, stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
>     frame #0: 0x00007fff5fc01075 dyld`dyld_fatal_error + 1
> dyld`dyld_fatal_error:
> ->  0x7fff5fc01075 <+1>: nop    
> 
> dyld`dyldbootstrap::start:
>     0x7fff5fc01076 <+0>: pushq  %rbp
>     0x7fff5fc01077 <+1>: movq   %rsp, %rbp
>     0x7fff5fc0107a <+4>: pushq  %r15

Anything I can do to get it running?

Thanks

FontForge 20150829
XQuartz 2.7.7
Mac OS X 10.10.5

**Comment by burodepeper** [comment]
Same issue here.

**Comment by glyphobet** [comment]
I am having the same problem. It appears that the August 2015 build by @jtanx expects to find FontForge 2 libraries in their MacPorts locations. `/opt/local/lib/libfontforgeexe.2.dylib` is where that lib will get installed if you are installing FontForge via MacPorts. This probably means that the August 2015 build works fine for the person who built it, because they must have FontForge installed via MacPorts in order to build it. 

This is also the reason why @jtanx notes the following in [the August 2015 release notes](https://github.com/fontforge/fontforge/releases/tag/20150824):

> the Macintosh build published here quits immediately after launching from the Finder.

To investigate further, I tried this (**don't try this at home, kids**):

    sudo ln -s /Applications/FontForge.app//Contents/Resources/opt/local/lib/libfontforgeexe.2.dylib /opt/local/lib/

That caused FontForge to find `libfontforgeexe.2.dylib` just fine, but it now fails on the next dylib it tries to load:

    $ /Applications/FontForge.app/Contents/MacOS/FontForge 
    PKGBASE: /Applications/FontForge.app
     dyld: Library not loaded: /opt/local/lib/libgdraw.5.dylib
      Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
      Reason: image not found

This likely means that the dylib loading paths in the August 2015 build are broken somehow. 

This bug is affecting lots of people, duplicates have been reported in #2481, #2479, possibly in #2470,
and [in a comment in the unrelated #2480](https://github.com/fontforge/fontforge/issues/2480#issuecomment-137649280) also.

Following on [this comment in #2481](https://github.com/fontforge/fontforge/issues/2481#issuecomment-139046291), I uncommented this line in `/Applications/FontForge.app/Contents/MacOS/FontForge`

    export DYLD_LIBRARY_PATH="$bundle_lib"

And that appears to allow FontForge to find `libfontforgeexe.2.dylib` and the other dylibs it needs, and it starts ok. 

This fix may only work for MacPorts users; since I used to have FontForge installed via MacPorts on my system, it may still be accidentally finding other libraries that FontForge depends on in `/opt/local/` that will not exist for non-MacPorts users.

I'll send a pull request with the fix soon.

**Comment by jtanx** [comment]
NB: I don't build the Mac builds, only the Windows builds. I think @frank-trampe made the Mac release this time around.

**Comment by glyphobet** [comment]
Ah! In the June 2015 release, the `export DYLD_...` line was not commented out. I wonder what changed...

**Comment by glyphobet** [comment]
@jtanx, didn't mean to point fingers, I only mentioned you because your username is on the August 2015 release.

**Comment by jtanx** [comment]
@glyphobet no worries - just clarifying that I don't know anything about the Mac side of things. IIRC anyone with modify access can edit the release notes/binaries which is not exactly made clear by GitHub.

**Comment by frank-trampe** [comment]
I am guilty as charged as pertains to building the Macintosh release, and I have a Mac Mini on my cluttered desk for that express purpose; as a non-user of the  platform, though, I would like to transfer that responsibility to somebody else. @glyphobet?

**Comment by glyphobet** [comment]
I'll try again and see if I can get the build to succeed on my system. I don't really understand the complexities of the build system & process, though.
