### ISSUE TITLE
Buffer overflow detected

### ISSUE THREAD

**Issue by krike** [fontforge/fontforge#2522]
Was this fixed? https://github.com/fontforge/fontforge/issues/1551

I'm using fontcustom (which uses fontforge) to create a font based on svg files and It throws me the 'buffer overlow detected' error

error log: https://github.com/FontCustom/fontcustom/issues/294

it only happens with complex SVG. here are 2 examples: 
- https://www.dropbox.com/s/88rg6jzo7xzql8v/beverage.svg?dl=0
- https://www.dropbox.com/s/q6104i9g85n79vp/viewtype-map.svg?dl=0

I'm using an older version of fontforge?
```
Copyright (c) 2000-2009 by George Williams.
 Executable based on sources from 22:35 GMT 22-Jun-2009.
 Library based on sources from 22:35 GMT 22-Jun-2009.
fontforge 20090622
libfontforge 20090622
```

or it was not made to process large data / complex svg? In that case what are my options?

**Comment by JoesCat** [comment]
Hi @krike,
loaded okay with current version:
```c
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 15:15 PDT 29-Aug-2015-ML-D.
```

There are well over 1000 patches between 20120731 and 20140101, and yet a lot more patches from that point until now. Some patches are fairly large and significant in size and/or effects.
It would be very safe to say:
There are no plans to go backwards and fix older versions of FontForge.

Can you check with a current copy?

**Comment by krike** [comment]
I have tried several things but it keeps showing me the same Copyright message.

I installed it on my server using yum. I also did a yum update and upgrade but still no new version is coming in.

**Comment by cicku** [comment]
What's your OS name/version? You might installed the old version from vendor repo.

**Comment by krike** [comment]
Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by JoesCat** [comment]
Hi @krike,
To support businesses, Red Hat needs to be is a fairly reserved distro to continue supporting businesses, therefore understandably, it makes sense why you are running a fairly old version.
https://access.redhat.com/articles/3078
(based on Fedora 12/13 versions, from approx 2010)
Looking at the dates of 2010, my Mageia 1 is approx 2010 as well, and the latest version I was able to load at that point was the 2014 january 01 release:
https://github.com/fontforge/fontforge/releases?after=20141013
(this version is approximately 1900 patches behind HEAD, but still holds a significant number of patches beyond version 2012, and more beyond 2009, it also is the last version built using ./autogen.sh instead of ./bootstrap).
I'll need to recheck your svg examples (above) using my other (Mageia1) machine to see if we still have the problem mentioned or if it was fixed before then (otherwise installing this later fix fixes problems, but not the problem you have now).
If you want to try building it yourself, download 20140101 into a temporary directory, and then run ./autogen.sh and take care of installing any missing files along the way, most of them will be developer versions of the same files you have now. Before you get to the make install, you will need to uninstall your existing 2009 version so there would not be any install conflicts.
If you are not familiar with the build process, I recommend you find a friend, local user group, or RedHat itself to help insure that your machine continues to run ok (I'm indicating this since you mentioned familiarity with yum, but suspect the possibility of might not have built programs from scratch).

**Comment by JoesCat** [comment]
Hi @krike,
The latest version of FontForge I have on my Mageia 1 machine is a slightly mangled pre-release of 2014-10 prerelease. This older version also loads your example svg files successfully.

Try and upgrade your FontForge if you can.

**Comment by krike** [comment]
The server I was running on is my local dev at work but the project i'm making is for both work and personal projects. So i might put it on my personal server. I quickly run `apt-get install fontforge` and got a more up to date version from the looks of it.

`Copyright (c) 2000-2011 by George Williams.
 Executable based on sources from 13:48 GMT 22-Feb-2011-ML.
 Library based on sources from 13:48 GMT 22-Feb-2011.
Could not open screen.`

It's an ubuntu server, which is easier for me. I'll test that and see if I can update to get a more recent version and I'll get back to and report the results.

thanks for the help btw.

**Comment by krike** [comment]
Yes on my other server it is working fine. Just needed to update the Ruby version. Thanks for the help

**Comment by cicku** [comment]
You could alsk ask RHEL guys to do a rebase of fontforge. RHEL isn't that kind of oldschool product, it sometimes will rebase some softwares if the new version is really neat.

Anyway, good to see a way of getting rid of this.

**Comment by krike** [comment]
Well it works now :D and I actually wanted to play around with fontcustom which required fontforge. tho I'm not sure I'm going to keep using fontcustom as there is no support or response for the developers since over 6 months ...
