### ISSUE TITLE
Trying to create Hexadecimal font.  

### ISSUE THREAD

**Issue by DavidGreenberg** [fontforge/fontforge#2531]
Hi FontForge!
Created a font with all characters from x'00' to x'FF' with character representations.  I go to generate the font and it gives me an 'ok' box and no errors, but I can not find the generated file to install into windows for use in Excel.  I'm going back through the manuals to see what I might have missed, but could use some assistance.  
Thanks!
David Greenberg
david.greenberg <at > stcharlescitymo dot gov

**Comment by JoesCat** [comment]
Try selecting "save as" and you should see where it seems to be saving the file.

Assuming the default file ending in sfd, you can go to the start menu which should have a search box available, and search for "*.sfd" (without quotes looks like *.sfd ).

Github tends to have a limited audience, particularly for answering questions. For quicker response (due to a larger pool of readers), I recommend enrolling yourself in the fontforge user mailing list on sourceforge: https://lists.sourceforge.net/lists/listinfo/fontforge-users

**Comment by DavidGreenberg** [comment]
Thanks!  I'll give that a whirl and then go to the mailing list.
