### ISSUE TITLE
Probable out-of-range in unicode_alternates array

### ISSUE THREAD

**Issue by mskala** [fontforge/fontforge#2566]
From https://github.com/fontforge/fontforge/blame/master/fontforge/splinesaveafm.c lines 1294 to 1300:

``` c
if ( isdecompositionnormative(sc->unicodeenc) && sc->unicodeenc>=65536 &&
        unicode_alternates[sc->unicodeenc>>8]!=NULL &&
        (upt = unicode_alternates[sc->unicodeenc>>8][sc->unicodeenc&0xff])!=NULL ) {
    while ( *upt!='\0' )
        unicode[u++] = *upt++;
} else
    unicode[u++] = sc->unicodeenc;
```

Note that this only ever accesses the unicode_alternates array if sc->unicodeenc>=65536 is true, and in that case, the index is necessarily 256 or greater.  This array's valid range of indices is 0 to 255, so it can't possibly be right.  The code is from a March 2006 commit by George Williams.

At first glance it looks like that test needs to be inverted; it's asking whether there is valid data in the array and so it should be sc->unicodeenc<65536.  I'm hesitant to try to change it, though, because I don't really understand how the information from this array is intended to be used anyway.

**Comment by JoesCat** [comment]
without delving too deeply, this looks like the sort of code accessing libuninameslist.
code 0..65535 is treated one way since a fair bit of it is 'built-in' into FontForge, and a lot of the array is full of characters.
This is where the first sc>=65536 decision comes in.

Next, codes 65536...to_the_end is mostly empty space, and instead of dedicating a huge array for empty space, this is treated mostly as blocks of 256 characters at a time, or maybe easier to think of these as 'pages' of 256 characters at a time. This way, you skip a whole bunch of nothing and make the FontForge exe smaller since you waste less space.
I'm not 100% sure, but I believe that right now, the FontForge exe tables are at unicode 6.x and need to be brought up to date to version 8.0
There are be a few utility programs in the unicode directory that need to run against the latest unicode.org data, which update the data used by the sort of code you show as an example above.

**Comment by mskala** [comment]
I agree with your summary of how the array contains pointers to smaller arrays in order to skip over empty space, but not with the idea that the array is designed to cover exceptional code points beyond U+FFFF with the smaller values handled in some other way.  On the contrary, this array seems to be intended *only* for code points in the range U+0000 to U+FFFF, the Basic Multilingual Plane.  This array _is_ the "built-in" handling for those code points; higher code points are meant to be skipped.

See the definition in unialt.c.  The unicode_alternates array consists of 257 pointers to smaller arrays, each of which covers a block of 256 characters.  The range of indices at the top is 0..256.  That is 257 elements; I hadn't noticed the extra one at the end when I wrote my original posting on this thread.  The 257th element (index value 256) is a NULL pointer, which the code will correctly detect in the case of code points U+10000 to U+100FF.  Any code points beyond that will cause indexing beyond the end of the array.  The >=65536 check basically means the array will only be accessed in the cases it does _not_ cover.

I think it's clear the >=65536 check is backwards, and I note that other places in the code which use the unicode_alternates array all use <65536 checks instead.  That's an easy thing to fix.  What I wonder about is what the actual purpose of accessing unicode_alternates at this point is, at all, because I think a really good fix ought to go further than just flipping the >= check.
