### ISSUE TITLE
Helping with fontforge documentation

### ISSUE THREAD

**Issue by marty39** [fontforge/fontforge#2567]
Home page says to post a new issue if you can help. There is too much fontforge documentation, of varying quality. I think I can help but I want to know where to begin and how to get into it.

I claim excellent technical writing and editing skills, fair web development and maintenance skills, obsolete programming skills, and no illustration skills.

Before I make specific suggestions about documentation I would want to know what other people are thinking about it. Hoping for a response.

Marty

**Comment by JoesCat** [comment]
Hi Marty,
My recommendations are, start with small bite-sized changes first.
If it's easy to digest by one or more approvers/maintainers, it gets more quickly accepted.
If you go hog-wild with large edits, it gets to be more work and a harder decision to say yes or no to an edit, and then to compound the problem, the modification you are requesting becomes stale, and possibly holds-up or jams other edits in the queue from happening (you only need to the current pull requests to see what I mean here).
Not everyone is a developer, and that is okay too, as there is documentation that needs to be created, modified, updated, and/or improved, so being a 'quote' developer 'unquote' is not a necessity to help, what is really necessary, is an interest in improving what exists.
Don't put yourself down in terms of obsolete programming skills, there is a lot of fairly interesting coding within FontForge that can puzzle some of today's programmers, and it may be of benefit since there are some older machines in the mix that would like to get back in the mix of things.

Suggestions I would like to make....

Use FontForge 20120731 as a sort of template to begin with. Reasons for suggesting this is Debian and a few distros still use this older version despite all the 'advances' done here in this github version. The older version still is wanted because it works with a bunch of different machines (see bottom of this list of architectures https://packages.debian.org/sid/fontforge ). If you can encompass new improvements recognizing new machines, and still try to keep some sort of backwards compatibility, that would be good.

Think before deleting - We've had some developers who's stronger talents seemed to be to delete stuff, or simply shuffle things around, and we lost a lot of backwards compatiblity from 20120731 which could (wishfull thinking), be worth putting back. As any doctor will tell you, it's 10x easier to cut something out, than to stitch something in, so if it already exists, think about....is it possibly going to be used/fixed/improved later? It's here already, won't hurt to leave it for some future developer with an interest to finish-it up later. Likewise with simply shuffling code back-n-forth...it looks busy, but doesn't really accomplish much, and you also lose some of the meaning of what some code meant to do... for example, something as simple as...
if ( ptr!=NULL )
is equivalent to
if ( ptr )
for today's processors using C99 and up, but not true for some older achitectures using older compilers, and if you look carefully, you will still see some requests for help on older equipment.

When you make changes, I suggest you start a git 'branch' vs working on the 'master' branch. This will allow you to move ahead easier if a particular branch has issues and needs to be tossed.

Start with small changes first

**Comment by marty39** [comment]
Thanks for the recommendations and suggestions. At this point I'm more interested in filling out the documentation than tweaking the code. As a very simple example, the link at http://fontforge.github.io/en-US/documentation/interface/lookups/#Basic+substitutions points to itself and not to the explanatory text below (as do others on the same page). How do I go about getting that fixed?

Looking toward the future, the main documentation page at https://fontforge.github.io/en-US/documentation/ mentions "Design with Fontforge" and "User Interface" but doesn't mention any forums or mailing lists, which are a mine (and minefield) of information and misinformation that I could make use of if I get around to adding to or updating the main documentation. Any suggestions?

BTW I'm using fontforge in Mac OS X, "Version: 23:52 PDT 26-May-2015" downloaded as a DMG. Would I do better to install a version on my Linux laptop as a basis for documentation?

**Comment by JoesCat** [comment]
Use whichever computer you prefer to use, whether it be Linux, Mac, Windows, or something else less common (example MIPs, Big Iron, ARM, etc). ...however, keep in mind that we are trying to support multiple platforms, so you may want to test on a linux distro at some point in time. If you're not into running various distro, I'd suggest having an old 'live' distro available to try it on, for example, an older Knoppix CDrom or an older Ubuntu, but if you maintain HTML 4 penmanship, you pretty-well catch the majority already. If your forte is content, then concentrate on what needs to be said, and leave the decoration for others who are better at that. Start with small pull requests until you have a good idea what goes, and what is hard to merge.

Getting the pages fixed (you mentioned above for fontforge.github.io), is best done by getting yourself involved here: https://github.com/fontforge/fontforge.github.io
This makes more sense if you look here: https://github.com/fontforge (showing various projects).
Where you generated this issue is more related to the program itself, and not the website github.io
...however, if you want to help update the documentation that goes with FontForge and installed on the computer itself (see subdirectory doc/html for documentation that you might see when you press F1 while FontForge is running) then this is the right place for issues and pull requests.

Ideally, both sets of documentation would be updated, but that's up to you.

**Comment by davelab6** [comment]
@marty39 are you still interested in improve the docs? :)

**Comment by marty39** [comment]
I don’t know where to start.

To begin with, when I search for fontforge help I get pages with text at the top that says "This is part of the old website. New website begins at fontforge.github.io / Are you a web developer? Help us migrate this page on Github” But those pages are already on Github at fontforge.github.io!

Ia all new work to be done on the “Design with Fontforge” book? Are the old pages to be migrated to the “Design with Fontforge” book and then deleted?

I noticed that the pages in “Design with Fontforge” are all marked "Edit this page <https://github.com/fontforge/designwithfontforge.com/blob/gh-pages/en-US/Spacing_Metrics_and_Kerning.md> (learn how <https://github.com/fontforge/designwithfontforge.com>).” I clicked “learn how” and found there are two ways to make a change: report an issue, or learn Github. Reporting an issue is at best slow. Take issue #121, left vs. right side bearing. It’s a simple typo, easily corrected, but it was reported over three months ago and still there is "no milestone” and “no one assigned,” let alone “resolved”!

So I guess I have to learn Github. There is allegedly enough Github help on Github. If not, I will try to follow up here.

I can think of a few different kinds of work to be done: (1) stuff in the old pages that isn’t in the book, (2) stuff in the book that should be corrected or updated, (3) stuff that isn’t in either the old pages or the book. Which of these should I try to focus on?

Subheads under these: (a) stuff I already know or can find, (b) stuff I don’t know but can find out by asking the right people (who are the right people?), (c) stuff nobody knows yet.

So what should I do? Follow the breadcrumb trail to become a Github user? Will that explain who sets “milestones” or “assigns” people and tell me what “labels” are?

> On Apr 21, 2016, at 5:41 PM, Dave Crossland <notifications@github.com> wrote:
> 
> @marty39 <https://github.com/marty39> are you still interested in improve the docs? :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/fontforge/fontforge/issues/2567#issuecomment-213123949>

-- 
							Marty
Martin B. Brilliant at home in Holmdel, NJ

**Comment by marty39** [comment]
OK, I’m lost again.

Before doing anything about the left/right side bearing issue, I looked to see if anybody had written a correction. Yes, there is a fork, a pull request, and a commit, but the page at http://designwithfontforge.com/en-US/Spacing_Metrics_and_Kerning.html is still wrong. What didn’t happen, and who can make it happen?

> On Apr 23, 2016, at 8:42 AM, Martin B. Brilliant <mbrilliant@alum.mit.edu> wrote:
> 
> I don’t know where to start.
> 
> To begin with, when I search for fontforge help I get pages with text at the top that says "This is part of the old website. New website begins at fontforge.github.io <http://fontforge.github.io/> / Are you a web developer? Help us migrate this page on Github” But those pages are already on Github at fontforge.github.io <http://fontforge.github.io/>!
> 
> Ia all new work to be done on the “Design with Fontforge” book? Are the old pages to be migrated to the “Design with Fontforge” book and then deleted?
> 
> I noticed that the pages in “Design with Fontforge” are all marked "Edit this page <https://github.com/fontforge/designwithfontforge.com/blob/gh-pages/en-US/Spacing_Metrics_and_Kerning.md> (learn how <https://github.com/fontforge/designwithfontforge.com>).” I clicked “learn how” and found there are two ways to make a change: report an issue, or learn Github. Reporting an issue is at best slow. Take issue #121, left vs. right side bearing. It’s a simple typo, easily corrected, but it was reported over three months ago and still there is "no milestone” and “no one assigned,” let alone “resolved”!
> 
> So I guess I have to learn Github. There is allegedly enough Github help on Github. If not, I will try to follow up here.
> 
> I can think of a few different kinds of work to be done: (1) stuff in the old pages that isn’t in the book, (2) stuff in the book that should be corrected or updated, (3) stuff that isn’t in either the old pages or the book. Which of these should I try to focus on?
> 
> Subheads under these: (a) stuff I already know or can find, (b) stuff I don’t know but can find out by asking the right people (who are the right people?), (c) stuff nobody knows yet.
> 
> So what should I do? Follow the breadcrumb trail to become a Github user? Will that explain who sets “milestones” or “assigns” people and tell me what “labels” are?
> 
>> On Apr 21, 2016, at 5:41 PM, Dave Crossland <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> @marty39 <https://github.com/marty39> are you still interested in improve the docs? :)
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub <https://github.com/fontforge/fontforge/issues/2567#issuecomment-213123949>
> 
> -- 
> 							Marty
> Martin B. Brilliant at home in Holmdel, NJ
> 

-- 
							Marty
Martin B. Brilliant at home in Holmdel, NJ

**Comment by skef** [comment]
This is an old "want to help" issue. As a general principle FontForge likes and appreciates help. Always feel free to get back in touch -- but closing this issue for now.
