### ISSUE TITLE
ScaleToEm() not working properly...

### ISSUE THREAD

**Issue by nycionx** [fontforge/fontforge#2580]
I have built the latest fontforge on my CentOS 6.7 x64 machine and when i try to run the following script:

Open($1,1);
ScaleToEm(1000);
Generate($1 + "_new.ttf");

for a font that isnt 1000 epm but in my example is 1100, it doesnt effect all the glyphs for some reason. the letters i and j for instance are bigger than the other letters! i dont understand what the problem is?
i tried the same script on windows (same fontforge build version) and it works as should.
now im thinking although i succeeded in building fontforge on CentOS maybe not everything went perfectly cuz clearly it is having a problem with this function, ScaleToEm().

so i posted my whole build log here if someone is willing to check it out please. 

http://pastebin.com/WrfqkXQq

i know its huge but i need to know where it went wrong.. is it some dependency im missing or is it an older dependency or god knows what..
btw, i installed it in a separate path although i dont see why that should be the problem.. (/home/nycionx/ff/)

PS> btw i tried to build it on Linux Mint 17.2 x64 bit and also same problem happens..

**Comment by mskala** [comment]
I don't know if this will solve your problem, but you might try doing a SelectAll() before the ScaleToEm().

**Comment by nycionx** [comment]
i actually tried this first JUST now:
SelectAll(); UnlinkReference();

and it worked!!!

then i said hmmm. lets open up my font and i noticed that both i and j were composites!! so that had to first be Decomposed (fontlab studio) aka UnlinkReference()  in fontforge

:)

**Comment by nycionx** [comment]
btw i wanted to know is it possible to build fontforge so that all its required libraries are contained in one big file? i would like a portable version of fontforge. so much easier to deal with! are there some commands i would have to write when doing ./configure? or do i have to fiddle with the Makefile?...both of which i have no clue, im a real linux noob :P

**Comment by mskala** [comment]
What you describe is called static linking.  I don't believe it is possible with FontForge because FontForge is designed around a deep split between "front-end" stuff (the GUI and the main program for the command line executable) and "back-end" stuff (which actually edits fonts), stored in separate dynamic libraries.  That split is built deeply into the build system and changing it would require rewriting the build system, not just changing an option.  I proposed that such changes might be made in issue #1253, but there wasn't consensus to actually go all the way on it.  A weaker form of my proposal attracted some enthusiasm, and I ended up taking my more extreme ideas into FontAnvil instead.

FontAnvil always builds in a mostly static form (no option needed or useful for adjusting this) and the binary should be able to run from any directory on the machine where it was built without looking for FontAnvil-specific installed libraries (which I think is your desired use case, never mind whether that is a good idea).  But even FontAnvil will not be 100% statically linked in a default build; it still needs compatible versions of standard things like libc to be in their standard locations, and it's not realistic to expect the binary to be "portable" to other machines that differ from the build host to the extent of using incompatible libc versions.

**Comment by nycionx** [comment]
ok i understand now, thx for clearing that up with me.
can u tell about fontavil more? how does it compare to fontforge latest version? is it better/worse? like in what case scenario would i want to use fontavil as opposed to fontforge? what benefits does it have over it? (ps. i just need the command-line version of either one, not gui)

**Comment by mskala** [comment]
FontAnvil is a standalone interpreter for the FontForge "native" scripting language.  It is part of the Tsukurimashou Project, which is my own long-term free software project mostly focused on Japanese-language fonts.  Tsukurimashou was using a lot of FontForge scripts, and there was some talk (as of Spring 2014; this seems less of an issue recently) about FontForge ending support for the native scripting language.  That would be a disaster for Tsukurimashou, and so I built my own interpreter based on FontForge's code at the time, so that my project wouldn't depend on FontForge's future strategic decisions.

FontAnvil is intended to have a smaller footprint and many fewer dependencies than FontForge, and it achieves this primarily by deleting the features I don't need for Tsukurimashou.  In particular, it has no GUI, no Python support, no networking support (thus no "collab"), no printer support, and very little UFO support.  There are also some significant behind-the-scenes changes in the way the code base is structured; for instance, the multiple shared library design I mention above has been eliminated from FontAnvil.  Most scripts written for FontAnvil or FontForge (but FontForge native scripts only) can run equally well on both interpreters.

If you want a lightweight interpreter of FontForge-style "native" scripts to use in a command-line environment (for instance, on a server), that is what FontAnvil is designed for.  It has the advantages of fewer dependencies, less disk space consumption, and probably faster execution.  The main disadvantages of FontAnvil are that it does not have all the stuff I deleted - such as a GUI, Python, and so on.  For those things, you need FontForge.

Building FontAnvil from a distribution tarball should be as easy as building most Linux software.  Building from a version control checkout (git or ideally SVN) may not be - I've been working a lot on streamlining that part recently ahead of a planned 0.4 release in the not too distant future, but it's tightly integrated with the rest of the Tsukurimashou build and so you might end up building a lot of font stuff you're not so interested in, if you try to build the latest and greatest directly from version control.

Latest (0.3) distribution tarball here:  https://osdn.jp/projects/tsukurimashou/releases/63489

**Comment by nycionx** [comment]
wow thats exactly what i need and only need! fontforge native scripting! why would they want to remove it?

ok im trying to build fontanvil now and its failing on 2 linux OS's so far!

here are my terminal logs: 

CentOS 6.7 x64
http://pastebin.com/aNut9qLs

Linux Mint 17.2 x64
http://pastebin.com/sTmSBhYC

whats going on?

**Comment by mskala** [comment]
Support for some image file formats is badly broken in that version.  Ordinarily it's not a big deal because it doesn't actually use those formats, but it looks like on CentOS, because you DO have libxml (many systems don't), it's trying to link to the image libraries in a way that doesn't work.  I suggest trying the --without-libxml2 option on configure; that will have the effect of disabling SVG support and most of the links to image libraries.  On Mint, it looks like you don't have Freetype2 installed.  That's a required dependency (used in many places throughout the package, not practical to remove), even if the 0.3 version of configure doesn't check for it.

I made a quick snapshot of my development version for you, available from http://ansuz.sooke.bc.ca/temporary/fontanvil-0.4pre.tar.gz  .  You could try that and see if it works better.  I cannot promise that it will be stable, and the documentation in that package will certainly be in disarray.  But the build system may be in better shape than 0.3, anyway.

I'm not sure it's really fair to the FontForge project to do FontAnvil support in their bug tracker.  If you have further questions about FontAnvil, please submit them through https://osdn.jp/ticket/newticket.php?group_id=5643 .

**Comment by NuttShell** [comment]
**mskala**
please, tell me - it is possible to build FontAnvil for Windows?
Thanks!

**Comment by mskala** [comment]
Probably not, but I don't really know.  My guess is that a really enthusiastic Windows programmer with a Unix-like development environment (such as Cygwin) might be able to make it work, but I think it's unlikely to work straight out of the box.  I have no Windows expertise and no ability to test Windows builds.

**Comment by NuttShell** [comment]
It's a pity...
Thank you, Matthew!

**Comment by nycionx** [comment]
ok i managed to build fontanvil for centos --without-libxml
i just checked the libraries fontanvil uses and theres quite alot, about 28. why so many? and one of them says libX11.so.6 isnt this X11? why would fontanvil use X11 if its not GUI

here is the full list:

[nycionx@localhost bin]$ ldd -r ./fontanvil 
    linux-vdso.so.1 =>  (0x00007ffcdd7f0000)
    libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x0000003d75a00000)
    libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x0000003d79200000)
    libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x0000003d74200000)
    libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x0000003d73e00000)
    librt.so.1 => /lib64/librt.so.1 (0x0000003d72600000)
    libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x0000003d78600000)
    libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x0000003d73200000)
    libpng12.so.0 => /usr/lib64/libpng12.so.0 (0x0000003d75e00000)
    libz.so.1 => /lib64/libz.so.1 (0x0000003d72e00000)
    libtiff.so.3 => /usr/lib64/libtiff.so.3 (0x0000003d83c00000)
    libspiro.so.0 => /usr/lib64/libspiro.so.0 (0x0000003d74600000)
    libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f07df85f000)
    libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x0000003d84800000)
    libgif.so.4 => /usr/lib64/libgif.so.4 (0x0000003d8d600000)
    libm.so.6 => /lib64/libm.so.6 (0x0000003d72a00000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003d72200000)
    libc.so.6 => /lib64/libc.so.6 (0x0000003d71e00000)
    libdl.so.2 => /lib64/libdl.so.2 (0x0000003d71a00000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x0000003d73a00000)
    libselinux.so.1 => /lib64/libselinux.so.1 (0x0000003d73600000)
    /lib64/ld-linux-x86-64.so.2 (0x0000003d71600000)
    libtinfo.so.5 => /lib64/libtinfo.so.5 (0x0000003d7b200000)
    libSM.so.6 => /usr/lib64/libSM.so.6 (0x0000003d79a00000)
    libICE.so.6 => /usr/lib64/libICE.so.6 (0x0000003d79600000)
    libX11.so.6 => /usr/lib64/libX11.so.6 (0x0000003d74a00000)
    libuuid.so.1 => /lib64/libuuid.so.1 (0x0000003d78e00000)
    libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f07df63c000)
    libXau.so.6 => /usr/lib64/libXau.so.6 (0x0000003d74e00000)


my config status:

Configuration status

Requirements for all builds
gzip              yes
perl              yes

Optional items
cflow             no     http://gnu.org/software/cflow/
giflib            yes
kleknev           yes
libjpeg           yes
libpng            yes
libreadline       yes
libspiro          yes
libtiff           yes
libunicodenames   no     https://bitbucket.org/sortsmill/libunicodenames/
libuninameslist   no     https://github.com/fontforge/libuninameslist/
libxml            no     http://xmlsoft.org/
TeX               no     http://tug.org/
valgrind          yes

**Comment by mskala** [comment]
Please, file issues for FontAnvil in the FontAnvil issue tracker.  I've created a ticket for this one here:  https://osdn.jp/ticket/browse.php?group_id=5643&tid=35778

**Comment by jtanx** [comment]
FYI I had a brief shot at compiling FontAnvil. Failed at trying to compile ICE because of the use of wordexp which does not exist on Windows.

**Comment by mskala** [comment]
Interesting.  That shouldn't be necessary if building from a tarball, though - only for version control checkouts.

**Comment by NuttShell** [comment]
**jtanx**
whether it is possible in principle to make build FontAvil for Windows?

**Comment by jtanx** [comment]
After a bit of fiddling around, I compiled FontAnvil 0.3 from the tarball. Binaries [here](http://sourceforge.net/projects/fontforgebuilds/files/fontanvil/).

Changes to compile on Windows are [here](https://gist.github.com/jtanx/612bd6c629a76e1aa977). Some notes about the build:

* Compiled without libunicodenames - FontAnvil fails to detect it even though it's present (and I didn't investigate further)
* Had to backport f815fe91050dc217f84e849f2e11e9a39813a381
* Make was complaining that there was no rule/target for `fontanvil/fontanvil`, hence me removing the dependency [here](https://gist.github.com/jtanx/612bd6c629a76e1aa977#file-fontanvil-0-3-win-diff-L81)
* I don't know if it affected the build or not, but my LaTeX installation is from MikTeX installed in `C:\Program Files...` - which provides pdflatex and kpsewhich. The spaces in the path were causing issues with running kpsewhich, hence the [double quotes](https://gist.github.com/jtanx/612bd6c629a76e1aa977#file-fontanvil-0-3-win-diff-L9). I tried running `make doc` and `make doc/fontanvil.pdf` (I don't know the correct target) and both failed with `make: Nothing to be done for 'doc/fontanvil.pdf'.`

**Comment by NuttShell** [comment]
Thanks alot, **Jeremy**!
working fine, I will continue testing.

**Comment by NuttShell** [comment]
**Jeremy**
please fix in FontAvil like this
https://github.com/fontforge/fontforge/commit/e6d0a5704455e63e9332ace44ae52f4bce8838bc

**Comment by jtanx** [comment]
Try r3 now (using 2e0cb4788efc6a9a391ff2f57b2031ff88fc236a)

**Comment by NuttShell** [comment]
ok. wait

**Comment by NuttShell** [comment]
Big big thanks!
It works!

**Comment by mskala** [comment]
Thanks for your efforts, @jtanx!

I still wish people would file issues in the issue tracker at https://osdn.jp/projects/tsukurimashou/ticket/ , and if there's a desire for a "forum" kind of thing separate from the issue tracker, I can easily enable that on my OSDN account too.  Among other things, the usage stats on OSDN matter to the project appearing in "recommended related projects" lists and such; having more people visit that site would cause the project to become more visible to other potential visitors.  I also really want to avoid any suggestion that I'm hijacking FontForge's users.  However, if FontAnvil builds are getting posted on a FontForge SourceForge account (even with a big "unofficial" notice in the title) by a FontForge developer other than myself, I'll take that as indication the FontForge team is interested enough in cooperating that I don't have to avoid FontAnvil talk here too carefully.

At the very least, though, might we change the title of this issue or move to a new issue?

Is that URL of Windows builds stable enough that I could put a link to it on the FontAnvil Web site?

On other technical points:  many of these look like I could add them to the main FontAnvil code base easily enough.  I still don't think I can call Windows really "supported" when I can't build on Windows myself, but at least it should be possible to make it easier for others who are attempting that.

Double quotes, okay, that should probably be done across the board for the whole Tsukurimashou Project, since it'd be relevant to Unix-like systems with spaces in paths too.

The trouble building doc/fontanvil.pdf:  this file is supposed to be in the tarball already and shouldn't need to be built.  If it's not in the tarball that's a packaging bug; if it's in the tarball but the system is trying to build it anyway and can't, that's some other kind of bug; if it's only trying to build that because of a specific user request and doesn't NEED to be built, that's lower priority.

No rule for fontanvil/fontanvil:  the Windows executable is probably called "fontanvil.exe", right?  I expect Automake's generated rules automatically adjust for that, but my handwritten ones don't.  There ought to be something I can do to make my rules adapt the same way Automake's rules do, and I'll look into that; but it should again probably be a project-wide change, not just this one target in FontAnvil (because there are other executables built too).

At least some linking and library-detection issues would be better with a more recent version of the sources instead of 0.3.  Looks like I should make pushing out a proper 0.4 tarball a priority.

The return value of <???> in the interactive interpreter when a statement has no return value is how the Unix version behaves.  If it's a bug at all, it's not a high priority for me to fix, because it seems to be only cosmetic and only visible in this specific situation; changes to this behaviour will probably happen when I get around to the general restructuring of error handling that I want to do eventually.

**Comment by jtanx** [comment]
Personally I have no issues talking about FontAnvil here. The main reason I posted here and not on OSDN was because I couldn't be stuffed making another account :wink: 

You are right about the target being `fontanvil/fontanvil.exe` and not `fontanvil/fontanvil` on Windows. For the `<???>` value, I thought it was trying to echo the assigned value, e.g. for `i=1` it would print `1`, but I guess not. 

In terms of posting binaries to that fontforgebuilds site, that's because it was the easiest way for me to distribute the binaries. This path: http://sourceforge.net/projects/fontforgebuilds/files/fontanvil/
Is likely to stay the same for the forseeable future, although I might create subdirectories for i686/x86_64 builds like I do for FontForge.

Compiling on Windows is actually quite easy because there's no X11 dependency, so practically all dependencies are resolved in MSYS2. At one point I was trying to make automated builds for FontForge using AppVeyor (see [here](https://github.com/jtanx/fontforge/blob/appveyor/.appveyor.yml)). It would probably be simpler to setup FontAnvil for something similar, although that wordexp usage would prevent compiling git at the moment.

**Comment by mskala** [comment]
You don't need an account to post issues on OSDN.  I fairly regularly forget to log in and have to go back and add my name to stuff I accidentally did anonymously.

**Comment by nycionx** [comment]
Just a quick fontanvil question. I tried to print a letter to pdf but it doesnt work. This is the script:

Open($1); 
name = $1:r + '.pdf';
Select('m');
PrintSetup(5); 
PrintFont(1, 0, '', name);

but it complains that:
PrintSetup: Printing fonts is currently unimplemented.

Can you please put this feature in? I thought all the native fontforge scripting functions were available to fontanvil? from here http://fontforge.github.io/scripting-alpha.html

Thx and sorry this last post about fontanvil here!

**Comment by mskala** [comment]
Sorry, as I said in my earlier comment, FontAnvil _has no printer support_, including "printing" to PDF (which would go through the same code as a physical printer).  The printing code from FontForge is huge and unmaintainable - many thousands of lines dedicated to generating sample text in various languages and talking to the native printer drivers on different operating systems.  It also carries a bunch of dependencies.  See #2171 .

I'm not sure the FontForge printer code is even appropriate for FontForge; it's definitely not appropriate for FontAnvil.  Printer support has been deliberately removed from the FontAnvil code base and although I hope to someday have a more lightweight PDF-generating feature in FontAnvil, that will have to be written fresh.  If you have specific ideas on what a FontAnvil PDF-generating feature should be able to do, please file a feature request; but just rolling back to the FontForge print function as it currently exists in FontForge is not a realistic plan.

FontForge built-in functions not available in FontAnvil are listed on pages 31 and 32 of the FontAnvil manual at http://tsukurimashou.osdn.jp/fontanvil.pdf .  There aren't very many, but the printer functions are among them.

If you want to generate PDF files under script control from fonts you have processed in FontAnvil, my suggestion is to use XeLaTeX.  There are probably also utilities in Ghostscript that can generate a demo page from a font file.  There are also some functions in FontAnvil that can write to image file formats, such as FontImage(), and those could be processed externally into PDF files.

**Comment by nycionx** [comment]
ok thx i didnt even know about FontImage() ill try working with that thx :)

**Comment by nycionx** [comment]
btw u said fontanvil should be faster the fontforge, wut would make it faster? does it execute the native scripts faster and why/how?

**Comment by mskala** [comment]
I have not measured this, and would want to before making any extravagant claims, but:

* In order to interface to the GUI, many parts of the FontForge script interpreter make "callbacks" to GUI code.  Even with the GUI disabled, those callbacks remain, pointing at dummy do-nothing functions.  FontAnvil eliminates them completely.  There are similar callbacks for "collab" and for saving undo information, also eliminated in FontAnvil.
* If a script runs very briefly, then the setup time for starting the interpreter may be a significant part of the time to run the script.  Because of being a much smaller program, with fewer things to load and initialize, FontAnvil should start faster.  Smaller code size may also help with general execution speed because a bigger fraction of the program will fit in cache.
* FontForge frequently writes data to temporary files and reads it back, in order to do compression and encryption operations that are needed by file formats like Postscript.  On a modern operating system these operations will not actually hit the disk, but they will still go as far as the operating system's memory buffers.  FontAnvil uses an internal abstraction layer for this purpose instead, with no operating system call, and it's reasonable expect that to be faster - though, again, I have not measured it.

It's worth saying, though, that neither FontAnvil nor FontForge is really built for speed.

**Comment by nycionx** [comment]
i actually managed to measure and compare the speeds of the two programs somewhat using php's microtime() with the programs on my server and executing ff native scripts and the speeds are like practically the same.. the scripts arent massive but nor small in size. in fact there's quite a bit going on in them i have to say. this is just my experience/test although id love to think fontanvil is faster and PROVE faster in my application and use it instead. its interesting the stuff u mentioned above.

**Comment by skef** [comment]
One could consider documentation clarification based on the original subject of this issue, but for the most part the FF aspects are resolved. Closing.
