### ISSUE TITLE
How to change window's title name from VcXsrv X ??

### ISSUE THREAD

**Issue by frankSol** [fontforge/fontforge#2590]
I want to change window's title name from VcXsrv, but I couldn't find window title function, where is it.
Could you answer Where is it??

**Comment by jtanx** [comment]
Hello, what version of FontForge are you using? What is its installation path? It should normally not be VcXsrv X.

**Comment by frankSol** [comment]
I installed latest version on my D Drive and referenced this : http://sourceforge.net/p/fontforgebuilds/wiki/Using%20the%20build%20script/

![dd](https://cloud.githubusercontent.com/assets/3583993/11808274/cd8e7f28-a362-11e5-8638-e1c3823e9159.png)

But My team-mates' font-forge also looked like this pictures

**Comment by jtanx** [comment]
I see, so it sounds like you're building it yourself? What happens if you try the pre-built version here: https://github.com/fontforge/fontforge/releases/tag/20150824?

 This sounds similar to #2361. If you run this program: http://sourceforge.net/projects/fontforgebuilds/files/build-system-extras/ShowLocale.exe (source [here](https://github.com/jtanx/fontforgebuilds/tree/master/patches/ShowLocale) if you want to compile it yourself.), what is its output?

**Comment by frankSol** [comment]
Thanks for answer my question!

ShowLocale.exe shown Korean_Korea.949, it doesn't have any blank !!

**Comment by frankSol** [comment]
I solve this problem! Thanks for answer my question!!
