### ISSUE TITLE
ImportError: No module named fontforge

### ISSUE THREAD

**Issue by tiendoxuan** [fontforge/fontforge#2597]
I followed https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md with 
<code>./configure --without-x  --enable-pyextension --enable-python-scripting</code>
All seems went out fine with <code>make</code> and <code>make install</code>.

But when I run 
python subset.py (with import fontforge directive) 
Script is attached (as txt file).
[subset.txt](https://github.com/fontforge/fontforge/files/72574/subset.txt)
I got this error report

<code>File "subset.py", line 21, in <module>
    import fontforge
ImportError: No module named fontforge</code>

So I have no ideas how to find out what's wrong either with our Centos 7 + WHM, or the installation script / steps that I took? Thanks for any guidances.

**Comment by JoesCat** [comment]
FontForge is a compiled program, not a python script or module, so it makes sense that python does not know what it is, but FontForge knows what python is, so instead of:
python .....
try
fontforge .....

See if this works:
 fontforge -lang=py -script subset.py

**Comment by tiendoxuan** [comment]
Thanks, that seems working to me at least no errors.

**Comment by jkyeung** [comment]
@JoesCat - Sure it's a compiled program, but OP said they used `--enable-pyextension`, which is *supposed* to **also** make fontforge a Python module:

<blockquote>
<h2>FontForge as a python extension</h2>

If you have configured fontforge with the --enable-pyextension argument, then when fontforge installs itself it will also set itself up as something that can be used inside of python (up until now we have been talking about using python inside of fontforge).

    $ ./configure --enable-pyextension
    $ make
    $ sudo make install

once you do that you can invoke all of the above fontforge commands from inside of python by saying:

    >>> import fontforge
</blockquote>

The above is quoted from the bottom of the Python page of the official FontForge documentation at either [here](https://fontforge.github.io/python.html), [here](https://fontforge.github.io/en-US/documentation/scripting/python/), or [here](http://dmtr.org/ff.php).

**Comment by SunHaozhe** [comment]
Is this problem solved? I encountered the same problem but did not understand what to do.

I am on MacOS Catalina version 10.15.7
I first installed FontForge via [https://fontforge.org/en-US/downloads/mac-dl/](https://fontforge.org/en-US/downloads/mac-dl/), but it seems to me that it is only a Desktop application without python binding. Then I installed `fontforge` via `brew` using the command `brew install fontforge`, the `brew` command succeeded in installing `fontforge` but it is still the same error `No module named fontforge`. 

I would like to use `fontforge` like a normal Python module 

```python
import fontforge
```
Then execute the python script using the standard python interpreter

```zsh
python main.py
```

instead of doing `fontforge main.py`

Is this possible?

When and where should I run the command `./configure --enable-python-scripting --enable-pyextension`?

**Comment by visusys** [comment]
I am having the same issue here on Win10 Pro and the latest build of FF. I can do 

`fontforge -script myscript.py {arguments}`

but not:

`ffpython myscript.py {arguments}`

The above script errors out saying `ImportError: DLL load failed while importing fontforge: The specified procedure could not be found.`

However, if I open `C:\Program Files (x86)\FontForgeBuilds\fontforge-console.bat` and then run `ffpython` from the console that opens everything works. 

So from a scripting perspective this is really frustrating. I really want to do `ffpython myscript.py`

How can I fix this? How can I configure FontForge on Win10 to enable the Python module so I can do `import fontforge`?

Any help at all would be huge.
