### ISSUE TITLE
Unable to install on CentOS 6.7

### ISSUE THREAD

**Issue by DarkStar1** [fontforge/fontforge#2616]
I have been trying to install this on CentOs 6.7 for the last 45 mins or so and I can't get past this error:
> checking for a Python interpreter with version >= 2.7... none
> configure: error: no suitable Python interpreter found

I have installed python 2.7 (can't uninstall 2.6) and ran configure with teh following flags:
> --disable-python-scripting --disable-python-extension --with-pythonbinary=/usr/local/bin/python2.7

I even went throgh the configure script at one point and set the $PYTHON variable to the python2.7 path, still no joy.

**Comment by JoesCat** [comment]
We got some bugs taken out, but python is the big white elephant in the configure.ac at the moment - I just didn't get to that yet - note issue #2533.

Check issue #1422 - Is there any strong reason holding you back from upgrading to 7?

**Comment by DarkStar1** [comment]
Yes, it's a customer's server. I will try and request an upgrade to 7 but that won't happen anytime before the need to deliver this.
Thanks for replying

**Comment by JoesCat** [comment]
problem with the configure.ac is that there are several different checks sprinkled throughout configure.ac, plus more in the m4/directory. Your version, due to age, has a problem with pkg configure not finding python when it is not in a "standard" location. Most of the fixes we've done to get past this can be seen in the m4 directory using a combination of ac_search, ac_check_lib and ac_check_header, but there is a patch in configure.ac that drops back into using pkg_config to look for python - this is the white elephant.
I'm uncertain if you can modify your pkg_config to check the extra directories where you installed python, but the solution I know/expect to work, is to do a similar search as seen (based-on) for readline in the m4 directory.
I think this is more than a quick fix and needs a sit-down and study the problem to fix it right vs throwing a bandaid on top of a bandaid.

**Comment by DarkStar1** [comment]
Thanks for your reply. I think the most sensible thing is just to upgrade to a later CentOS version that uses the right python version. It;d be much simpler that doing this.
