### ISSUE TITLE
Copyright notice goes to stderr?

### ISSUE THREAD

**Issue by YellowAfterlife** [fontforge/fontforge#2637]
As seen here,
https://github.com/fontforge/fontforge/blob/6eac581fc4d97c2ea2ff30e76d3b02e726be2eef/fontforgeexe/startnoui.c#L82
Is the copyright notice meant to go to stderr (or why does it)? The rest of the code in the same file goes to stdout, and it would look like it might make sense to generally log just the actual errors to stderr.

**Comment by mskala** [comment]
The copyright notice is shown more or less unconditionally.  If the message went to stdout, then it would be very difficult to write scripts that generate useful output to stdout for redirection elsewhere; you'd be constantly having to filter the output to remove the copyright notice.  Sending it to stderr makes it more likely that it'll go to a terminal.  GUI builds support a -quiet option which suppresses the message, but from the code it looks like non-GUI builds do not.

Whether it *ought* to be shown unconditionally is another question.  I imagine that George, the first developer of PfaEdit,  probably did that in the dim past without giving it a lot of thought and since then nobody has dared to change it because of the general taboo against removing copyright notices from things.

Also note that startnoui.c is (as described in issue #1277) only compiled in non-GUI builds, so the code you're linking to is not what actually displays the notice in most builds.  See startui.c - but they both send the message to stdout, the difference being that the GUI builds, which need such a feature less, support -quiet.

**Comment by mskala** [comment]
For reference, FontAnvil sends the equivalent message to stdout, but only sends it at all when running in interactive mode or when it's requested by the -version option.

**Comment by JoesCat** [comment]
Hi @YellowAfterlife,
Programs often start-out fairly simple, but with time, they grow in size and complexity. GW put a lot of work into FontForge. ...and sometimes, the quickest solution, is to simply bolt-on a patch, such as the hard-coded fprint(stderr,blahblahblah) instead of the more complex function(out) {fprint(out,blahblahblah)}, but after enough patches and bolt-ons, some stuff could probably use some re-writes as version+1 in some places. startui.c and startnoui.c are looking like they could use some restructure from a "void function(void){exit in various places}" to what I think as a more preferable "result function(input){exit at the bottom of this function}" method, but from my point of view, to fix startui.c and startnoui.c, is a bit of a domino-effect, where some things need fixing before other things get/are fixed. You could see some of this domino-effect fixes happen in (for example) pull request https://github.com/fontforge/fontforge/pull/2512 (partial conversion to result function(input) method), but much more has yet to get fixed before I would consider to modify startui.c and startnoui.c

As @mskala points out, stderr is a good direction to send this message so it doesn't get thrown-in with data when users run FontForge in a commandline or piped mode, and the preferable thing to do is to push it through stdout "only" if someone types --version or --help. You've probably seen this too in other programs (eg pkzip, etc...). FontAnvil has this fix done, FontForge has yet to get this done.

If you have programming ability, and motivation, please send patches (however, I'm guessing based on past looks at startui.c/startnoui.c that this might need a fair fit of restructure to make it work cleanly).

**Comment by frank-trampe** [comment]
I think that it's perfectly appropriate to send the copyright notice and other non-output-type information to stderr. It certainly can't go to stdout.
