### ISSUE TITLE
Element functions unavailable

### ISSUE THREAD

**Issue by WhatYouSee** [fontforge/fontforge#2652]
Hello,

In an attempt to create handwriting font with FF, imported .png handwriting file (Capitalized A) with intent to use **Autotrace**. With instructions (_File >Import >Select .png file_ .... _Edit >Select >Select All_ .... _Element >**Autotrace**_) the option to **Autotrace,** along with other _Element commands/functions_ are **not available**. Downloaded **Autotrace-0.31.1** online with intent to utilize Autotrace function on FF, Autotrace function still not available. Under _Element_ menu, _**Styles, Expand Stroke, Overlap, Simplify, Add Extrema,**_ and **_Autotrace_** are not accessible.

Using Mac. Your guidance in my lost adventures is appreciated. Thank you!

**Comment by jtanx** [comment]
I recommend using potrace over autotrace. In any case you must set the AUTOTRACE environment variable to the location of your potrace or autotrace executable. It may also work if you have it in your PATH environment variable but I prefer the former method.

**Comment by frank-trampe** [comment]
You have FontForge working on a Macintosh?!

**Comment by RolfNoyer** [comment]
I am having a similar problem. After update to El Capitán (10.11.6) (and also an overhaul of machine due to hardware failure) the autotrace function has completely stopped working. Potrace does run from the command line in Terminal, so it is installed and operating properly (apparently).

I am running the latest OS X release of Fontforge through XQuartz (2.7.9, latest release). I have done the following, to no avail.

— Manually set AUTOTRACE environment variable to location of potrace executable “/opt/local/bin" -- even though potrace is always in my $PATH so not sure why this would help. 

— Tried manually setting the AUTOTRACE variable within an xterm window within XQuartz and then launching Fontforge (by double-clicking application icon: I am assuming that since Fontforge always runs through XQuartz, then this counts as “starting from within XQuartz”).

— Reinstalled potrace (last time using MacPorts package). 

— Updated to latest version of XCode, in case some new libraries were needed.... (??)

The autotrace menu item remains grayed out under all circumstances. 

I have also tried to import .eps files created by potrace (when run through the terminal) into glyph windows. I always get an error message: “bad or too complex”.  These .eps files cannot be completely corrupt because they do open (at least after automatic conversion) in Preview, for example.

Autotracing worked before I updated to El Capitán, although I did notice that FontForge often had to be restarted before it would recognize imported images for autotracing. But now potrace does not work at all, regardless of whether the image in the glyph window is .png or .bmp, or color or b&w, or imported via the “Import” menu function or pasted from the clipboard. Images which I had already imported into .sfd files before updating the OS,  but had not yet autotraced (although I could have before), also cannot be autotraced now. 

Any ideas?

**Comment by jtanx** [comment]
> — Manually set AUTOTRACE environment variable to location of potrace executable “/opt/local/bin" -- even though potrace is always in my $PATH so not sure why this would help. 

try setting

    export AUTOTRACE=/opt/local/bin/autotrace

**Comment by jtanx** [comment]
> — Manually set AUTOTRACE environment variable to location of potrace executable “/opt/local/bin" -- even though potrace is always in my $PATH so not sure why this would help. 

try setting

    export AUTOTRACE=/opt/local/bin/potrace

**Comment by RolfNoyer** [comment]
I tried “export AUTOTRACE=/opt/local/bin/potrace” just now (in both Terminal and at the command line in an xterm window after launching XQuartz but before launching Fontforge.).  This did not work. 

But I have discovered a work-around: potrace can create .svg files and these can be imported into a glyph window using the Edit > Import function. It’s not as fast as using autotrace within Fontforge, but it is better than nothing. I am now using the GUI add-on “DragPotrace” to first create the .svg files for import.

**Comment by n9yty** [comment]
I modified the startup script, /Applications/FontForge.app/ContentsMacOS/FontForge so that it did an export of AUTOTRACE and it now works for me.  I also had an issue that I didn't see until I tried to run it with terminal, regarding it using the wrong version of libexpat. It was using the system version, v7, and it needed v8. I found a note in another trouble report with a few commands that fixed that up...

 cd /Applications/FontForge.app/Contents/MacOS/fc
../library-paths-opt-local-to-absolute.sh fc-cache
