### ISSUE TITLE
Debian Packaging: Sane options for configure for building a distribution package

### ISSUE THREAD

**Issue by copyninja** [fontforge/fontforge#2732]
Hi,

I'm updating the Debian package of fontforge and I'm now wondering what are the options I need to enable for configure phase. The old version from 2012 had these options.

``` make
DEB_CONFIGURE_EXTRA_FLAGS = --prefix=/usr \
              --libdir=\$${prefix}/lib \
              --mandir=\$${prefix}/share/man \
              --with-regular-link \
              --enable-devicetables \
              --enable-type3 \
          --with-freetype-src=$(CURDIR)/freetype \
          --with-freetype-bytecode
```

Some of these options might not be even present today. So can any one suggest me a default set of options I need to use, considering we are shipping a general package to all font developers.

**Comment by JoesCat** [comment]
Hi @copyninja,
Please note that going from 20120731-b1 to 20140101 (and today), FontForge has had a very large modification to the make build system. (1) The easier to recognize change is going from {./configure make} used in 20120731, to {./bootstrap, ./configure, make} used in the latest releases. (2) The less noticed, but I think also, fairly important change is having had the dynamic linking mechanism stripped-out (this isn't all too important to source built distros, but is important to binary distributed distros).

(1) In terms of the ./bootstrap system, I would like to eventually see it get reduced to autoconf -i, automake, but we would need to put more time into the make structure, and most of our time has been concentrated on bug fixing and improvements in the FontForge source code. If you can successfully get FontForge built using autoconf automake, please aim for that first. If you cannot, then do use bootstrap.

(2) In terms of building a general package for all font developers, and if you have a binary package distribution system, since dynamic linking isn't available as in the older 2012, you will need to increase the dependencies to keep font designers happy and minimize issues/complaints/false-bugs being mentioned. I would suggest to run ./configure --help and look at the --without- options and force several of them into --with- so that these extras are checked for and added on purpose.
Ones that come to mind right away are --with-giflib --with-libpng, --with-libjpeg (to allow designers to create webpage bitmaps). There have been numerous bugs and issues with libspiro, and a few with libuninameslist, so I think both of these are desired features for font developers --with-libspiro --with-libuninameslist. If you are making a graphical FontForge, a substantial amount of fixing was added for cairo, so you may want to add --with-cairo. When you are in graphical mode, and press the 'F1' key for help, you will open a web-browser help, so you may need to add an additional reference for the html help documentation directory.

I am running another distro and I know none of the above are exact suggestions, but hopefully helps you decide what to add and exclude to your list for Debian - it is an important distro where many distros watch, start from, and branch off of.

**Comment by JoesCat** [comment]
Including additional reference information, which might be helpful for comparison to what you are doing.

Archlinux was an early adopter of the newer FontForge, plus the maintainer contributed a few improvements to FontForge - you can see details for the build system here:
https://www.archlinux.org/packages/extra/i686/fontforge/

Fedora also adopted this newer FontForge. The lineage is more RedHat and RPM based (vs Debian), so it may be a little harder to compare with, but you may find some useful information you can adapt/include, since it also has matured several revisions too: https://apps.fedoraproject.org/packages/fontforge

**Comment by copyninja** [comment]
@JoesCat Thanks for the input. I've included all dependencies mentioned by you above to make sure it builds fine. Our source is at [1](http://anonscm.debian.org/cgit/pkg-fonts/fontforge.git/). 

Also note that we do not use bootstrap script, one of my friend developed a clever way to avoid bootstrap script.

I've one more question though, is nodejs/collabwebview/js/constants.js file really used?. We get a lint warning that the file is missing source because its minified. If people don't use collabview I can probably remove it from package.


[1] http://anonscm.debian.org/cgit/pkg-fonts/fontforge.git/

**Comment by JoesCat** [comment]
Hi @copyninja,
The best person to answer constants.js is @monkeyiq

I cannot answer collaboration questions since I have not tested it, plus my main computer is currently running a fairly old distro and can't compile with several of the libraries required for collaboration (...you'll probably also notice the ./configure "summary" appears incomplete/unfinished for zeromq).

Plus, I'll CC @davelab6, @frank-trampe, @jtanx in case they have any further feedback to offer in terms of 1 above - since I recognize the fact that many distros are affected by Debian's choices for a "sane options" build.

**Comment by copyninja** [comment]
@JoesCat Yes I know about zeromq but I'm not sure if I have to enable it. Is it really used by people or its just there. I will wait for others to respond. Till then most things of the package are in place except fontforge-nox used for scripting.

**Comment by JoesCat** [comment]
In terms of zeromq, that is a difficult question to answer. I see the experienced user is unlikely to need it, but I see it might have usefulness in a classroom setting (room or continental), or maybe it might be helpful in a buddy-help system for users just learning how to use FontForge (where watching for 10 seconds gets someone over a hurdle). Dave is the best to answer this due to his experience in this sort of environment.

As clever as we see ourselves, we may be the very same people complaining about cars having no future and insisting horse buggies, saddles and whips are the future of transportation. At the same time, I can't see those that need it as being able to easily build a version from source, so they would be dependant on a pre-built setup, so we are back into a chicken-egg situation whether to include it or exclude it.

If in doubt, build two FontForge (with and without), and let the users decide - watch Debian popcorn for a year and see where it goes.

**Comment by jtanx** [comment]
In my opinion, if stability is required, I would leave collab/zeromq out. It really hasn't been maintained since it was implemented, and I've found it to be quite buggy when I have tried to use it. Current Windows builds ship without it.

**Comment by davelab6** [comment]
I used collab even when working solo, because it allows me to see the font on a web page as I am developing it. If it isn't packaged for users, then no one is interested in using it and maintaining it

**Comment by copyninja** [comment]
I'm closing the issue as I've enabled most required options in the packaging. Package is already in Debian unstable and testing. If any more options are needed new bugs can be opened against fontforge package in Debian

**Comment by JoesCat** [comment]
Glad to see this issue closed, as it also affects other distros that are 
based on Debian.
