### ISSUE TITLE
Merging of ttf fonts

### ISSUE THREAD

**Issue by PoonamGoel** [fontforge/fontforge#2733]
Hi,

Please help me merge multiple ttf font files into one otf font file. I tried using fontlab, fontforge but when they merge and generate a font, some characters get random places. But I want sequential ordering within a font. How can I achieve this?
Any suggestion or code are always welcome. I'm willing to try any font editor. Please help me finding a solution asap.

**Comment by JoesCat** [comment]
Hi @PoonamGoel, please ask for user help in the sourceforge mailinglist.
You will have many more readers watching the mailing list, plus the issues area here, is mainly for problems that need fixing with the program FontForge, and not with problems on how to use the program.
Also note: There is a difference in "how" you ask a question.
If you ask people to "help me" do "my work", it implies you do not want to do it yourself, or do not want to know/learn how to do it yourself, or you want to hire someone to work for you.
If you ask "how can I do" X or "how can I do" Y, or "how can I do" Z, then it implies you tried to learn how to do something, but still do not know how to do it, therefore are now asking to learn how to do it yourself and need help knowing how to do X or Y or Z.
I hope this helps.

Closing this issue as it is not a problem with the program.

**Comment by PoonamGoel** [comment]
Hi Joe,

Thanks for your reply & thanks for your advice, I'll keep it in the
consideration.

Can you please provide me a link to where should I post my question? I need
the solution asap, I have tried allot but couldn't find any suitable one.

I'll be very much obliged for any kind of help you can provide.

Thanks
Poonam

**Comment by JoesCat** [comment]
> I'll be very much obliged for any kind of help you can provide.

For educational "how-to" steps, see if you find what you need here;
http://designwithfontforge.com/en-US/index.html
(If it needs more information and you can add to it, there is a github page 
where you can supply additional info or corrections).

You are looking for the FontForge "user mailing list" which starts here:
https://lists.sourceforge.net/lists/listinfo/fontforge-users

..you can also search through the mailing list archives as it can be 
possibe to have the question(s) answered already sometimes.

When asking questions on the mailing list, you will get a better reply if 
you are detailed on the question(s):
Asking "help me fix this", explains very little, and people will be unsure 
exactly what are you attempting to fix.
Asking, "I tried to create this contour by doing these steps A,B,C, but I 
keep getting Y instead of Z", then you will likely get a good reply.

Try to ask one question per subject because it discourages a possibly 
knowlegeable answers if someone knows how to answer 1 question, but not the 
other questions (in a group of questions in one message). Having fewer 
questions per subject is more likely to have that message answered, and 
considered complete.

When you ask a question (as you asked - above), keep in mind, that there 
are paid professionals in the list as well as experts and hobbyists, and 
when it is worded in the context above, it comes across to the reader as 
can someone do my work for me for free? ...hehehe, yes, I've also seen my 
fair share of students trying to get someone else to do their homework for 
them, as well as people trying to get work done for them for free (of which 
they then expect to make money from it). ;-P

May you have better reaction on the mailing list, as there are potentially 
many more eyes watching.
...and please reserve this github issues tracker for program related 
problems - Thanks - Joe
