### ISSUE TITLE
Add Code of Conduct to CONTRIBUTING file

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2765]
https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md seems like a good place to start

**Comment by mskala** [comment]
Everybody whose opinion is worth considering agrees that we should all be civil and inclusive.  That is a politically neutral wish.  But to codify such a wish in the specific form of a document named "Code of Conduct," on an open source project, on Github in particular, is not a politically neutral action.  Doing that in particular imports a great deal of baggage connected to what some people call the "culture war" currently going on on the Net.  It would be a shame for FontForge to take the wrong side in that, mostly because it would be a shame for FontForge to take a side at all.  I strongly urge careful reading and consideration of this article by Scott Alexander on superweapons:  http://squid314.livejournal.com/329171.html

We have an abusive user on the mailing list.  We need to do something about that.  But couldn't what we do simply consist of banning him?  That's not rocket surgery!  I think it would be unnecessary and *extremely dangerous* to do anything that looked like building a superweapon; and deploying a document named "Code of Conduct," in an open source project, on Github, no matter that it's with the best of intentions, is something that looks like building a superweapon.  Such codes are abused at least as often as they are beneficially used; that is an understatement, but the numbers don't even matter.  The fact that they *can* be abused is itself a real problem.

The stakes on this entire topic are extremely high for me personally, but that should not be a consideration for what the project chooses to do.

**Comment by JoesCat** [comment]
Initial reaction would be to agree with @mskala (since coding still has a wild-wild-west-cowboy image to maintain), but looking at the link, there is indeed some interesting/good points worth mentioning.
As it may appear to be new and uncharted territory, my 2-cents is write...park-it a few days to clear the mind, then come back and review what you've written. First draft will probably look awful, but by the nth draft, there will be very little churn....if you're asking me what value is n?...I don't know...but suppose it's where you see little churn from the last draft.

**Comment by mvz** [comment]
It seems without some list of rules it's very hard to get someone to shut up without actually banning them. If you can point to the rules first, and try banning later, the procedure becomes a lot simpler.

A code of conduct would in this case, as it is in many cases, a way to protect the people who want to make a positive contribution to the project from abuse from those who don't. This is not a superweapon, nor a general limitation of free speech.

**Comment by davelab6** [comment]
On Aug 4, 2016 8:00 PM, "Matthew Skala" <notifications@github.com> wrote:
>
> Everybody whose opinion is worth considering agrees that we should all be
civil and inclusive. That is a politically neutral wish.

No it isn't :)

Politics is about conflict. Jb wants to carry on in one way and we want to
carry on in another. That's a conflict. There's nothing neutral about it! :)

> But to codify such a wish in the specific form of a document named "Code
of Conduct," on an open source project, on Github in particular, is not a
politically neutral action. Doing that in particular imports a great deal
of baggage connected to what some people call the "culture war" currently
going on on the Net. It would be a shame for FontForge to take the wrong
side in that, mostly because it would be a shame for FontForge to take a
side at all.

You can't be neutral in politics.

I agree it would be a shame to take the wrong side - which I think is to
continue without a coc.

> I strongly urge careful reading and consideration of this article by
Scott Alexander on superweapons: http://squid314.livejournal.com/329171.html

I read it. the author says,

> "obviously I'm against discrimination but"

Sounds to me like he isn't really, then.

> We have an abusive user on the mailing list. We need to do something
about that. But couldn't what we do simply consist of banning him? That's
not rocket surgery!

Indeed not, I already did it.

But I just shot from the hip. Frank wanted to take another approach.  We
didn't coordinate, we just arbitrarily made up the rules as we went along.

That situation is fundamentally unjust.

> I think it would be unnecessary and extremely dangerous to do anything
that looked like building a superweapon; and deploying a document named
"Code of Conduct," in an open source project, on Github, no matter that
it's with the best of intentions, is something that looks like building a
superweapon. Such codes are abused at least as often as they are
beneficially used; that is an understatement, but the numbers don't even
matter. The fact that they can be abused is itself a real problem.

The fact there isn't one is a form of unjust power and thus a form of
abuse.

Recursive application of a coc is always tricky, 'who watches the
watchers,' but I'll be pleased to see links that detail such abuses you
have in mind :)

> The stakes on this entire topic are extremely high for me personally, but
that should not be a consideration for what the project chooses to do.

Are you saying you'll leave if there's any kind of coc at all?

**Comment by mskala** [comment]
> Are you saying you'll leave if there's any kind of coc at all?

No.  I wouldn't make a threat like that, and you shouldn't listen to such a threat from me or anyone else.

**Comment by davelab6** [comment]
On 5 August 2016 at 09:06, Matthew Skala <notifications@github.com> wrote:

> Are you saying you'll leave if there's any kind of coc at all?
>
> No. I wouldn't make a threat like that, and you shouldn't listen to such a
> threat from me or anyone else.
>
Okay cool :) That's good! XD Since you say its personal I'll drop you an
email privately

**Comment by ctrlcctrlv** [comment]
I originally sided with @mskala but actually I don't see the harm in adding a CoC so long as it's not abused to remove politically incorrect "infidels". I personally support Donald Trump for president, a very unpopular position among tech people. But as long as I don't refer to it outside of this comment because it has absolutely nothing to do with fonts or FontForge and am respectful in the repository, and the CoC only can be enforced against actions done in the repository or abusive comments made via third party channels to other FontForge developers/issue helpers/occasional submitters, I don't see the harm in a CoC.

Yes, most open source communities are respectful by default and CoCs do have a political stink attached to them, but for the edge cases when it truly is necessary and considering the limitations to "only interactions between community members" I don't see the harm in a CoC. :)

**Comment by davelab6** [comment]
> I personally support Donald Trump

Similar to http://blog.samaltman.com/trump ? :)

I am not a US voter, although in the process of immigrating to the US, and I personally find Trump more awful than Clinton; but I would feel annoyed if your position in US national elections was used against you in the FontForge community.

**Comment by khaledhosny** [comment]
Would you feel the same if he was a Hitler supporter? I don’t want to ever deal with such people and the idea that supporting mass murderer or racist supremacist is a “personal” thing is some liberal bullshit I don’t endorse.

**Comment by mskala** [comment]
I'm not actively involved with the project anymore, but since I was involved in this old issue in particular, I'm going to take it on myself to close it.  FontForge has plenty of better things to talk about in 2019.

**Comment by ctrlcctrlv** [comment]
I no longer support Trump and didn't vote, so there's that... Bernie 2020

**Comment by frank-trampe** [comment]
In abstract, the idea of tolerating somebody who admires a perpetrator of mass murder seems unconscionable, but we do it all the time for groups with stronger political bases than Hitler. Mao is probably the greatest mass murderer in the history of mankind, and nobody blinks about befriending or embracing his staunchest supporters. There's even a statue of two mini-Maos at the airport in Saint Louis. We would be uniquely restrictive if we were to exclude anybody who admires a mass murderer.

For what it's worth, across the various FontForge communication channels (issue tracker, mailing list, e-mail, and Facebook page), I get seriously flamed fairly regularly, and eating it bothers me a lot less than trying to press a code of conduct violation claim. Given the size of our community, I think that it's safe just to let those offended raise their specific objections each time for anything that bothers them but doesn't violate American law or the code of conduct of the medium.

**Comment by mvz** [comment]
It is not just about being able to press a claim.

I once saw a request to be polite escalate into an endless discussion how you can never be polite on the Internet because given cultural differences there is always someone who will be offended. A code of conduct stops that.

Having to explain your specific objections every time is a lot of work and many people will just not bother. At some point only the flamers and the people willing to eat it will be left. Maybe we are already at that point.

**Comment by ctrlcctrlv** [comment]
I'm not sure how a CoC would help it if people can't agree what "polite" means. For example, let's take Contributor Covenant:

What is "inclusive" language? Certainly that's cultural.
What is "trolling"? We've had several people here in the issue tracker who I've considered to be trolls, but who others didn't agree. (None are active contributors, one eventually did something so trollish that people came to accept my view.)
"Conduct which could reasonably be considered inappropriate in a professional setting" is definitely cultural, no? I've lived and worked in both the USA and Philippines, and what's appropriate in one professional setting is not allowed at all in another&mdash;in both directions. (For example, it's much more expected that you'll give employees second and third chances in the Philippines, while in the USA it's much more acceptable to just fire people.)

If people can't agree on basic definitions I don't see how a CoC can fix that. This isn't an argument against a CoC, even in 2016, I wrote "I don't see the harm in a CoC. :)", and I continue to not see the harm in one. I just don't see how it will help people understand what "polite" or other basic words mean.

**Comment by mvz** [comment]
The Contributor Covenant has this bit: "Project maintainers are responsible for clarifying the standards of acceptable behavior."

**Comment by skef** [comment]
> Conduct which could reasonably be considered inappropriate in a professional setting

I'm OK with this as applied to communication if it applies equally to project management.

**Comment by ctrlcctrlv** [comment]
I don't see how just letting project manager(s) decide what's acceptable really changes anything, that's what we already do. IMO, in order for a CoC to be worthwhile, there has to be a way to make a claim against the person or people in charge, otherwise it's just the trappings of a legal process without any binding way to actually challenge those in power.

**Comment by ctrlcctrlv** [comment]
(I don't necessarily think there's anything wrong with how we do things right now. The buck has to stop somewhere. But if we're seriously going to indulge a CoC, then we also need a committee that can vote on violations and remedies, not just &laquo;let the person in charge decide&raquo;; the Contributor Covenant includes a clause about this, but I just want to draw attention to it so we know what we're getting ourselves into here.)
