### ISSUE TITLE
Missing translation ID for "ShowFillWithSpace" in Preferences

### ISSUE THREAD

**Issue by jrbastien** [fontforge/fontforge#2769]
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
  FontForge 17:10 Ubuntu 16.04
- [x] The behavior you expect to see, and the actual behavior
  Expected to see an ID for ShowFillWithSpace in fr.po, The ID for the tooltip is also missing
- [x] Steps to reproduce the behavior
  Search fr.po for ShowFillWithSpace, nothing is found.
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
Hmm I'm not too familiar with gettext. I think you need to regenerate the .po file? @JoesCat maybe?

**Comment by JoesCat** [comment]
On August 7, 2016 11:38:57 PM Jeremy Tan wrote:
> Hmm I'm not too familiar with gettext. I think you need to regenerate
> the .po file? @JoesCat maybe?

gettext on FontForge is a thin version missing several heavy duty things 
that wouldn't work in some operating systems, but for what you are 
interested in there's two steps involved. Generate, and merge.

Some operating systems have a gettext that could use updating (as warned in 
po/Makefile.am) so your mileage may vary. If you have access to a recent 
gettext, or one that is known not to have problems with utf8 text, use 
that. If you are not certain, you may want to run gettext on a linux 
machine, or from a live distro that runs from CDrom, DVDrom, or USBstick.

If you look in po/Makefile.am, there is two generate instructions.
Take a look at the number of options thrown in, and either use the same or 
fewer. If you want to use the same number of options, then go into the po 
directory and run:
make FontForge.pot

this will generate a new po file based on the existing Fontforge file 
structure. Then, you will need to merge the existing po with this new file. 
Using fr.po as an example, I would suggest...

mv fr.po fr-old.po
msgmerge -N fr-old.po FontForge.pot > fr.po

this new fr.po is the one you update.
You can compare with the old:
diff fr-old.po fr.po
or delete the old one:
rm fr-old.po

there is also a menu po too....it's been a while since I looked at po, but 
looking at po/Makefile.am, you would go to the po directory and run:
make FontForge-MenuShortCuts.pot

I'll see about updateing po/Makefile.am to include an update command.

Even though there are tools for modifying the po files, for myself, I've 
used a plain text editor to modify text, such as kwrite. gnome has gedit. 
Windows, you'll probably need to run an enhanced Notepad since these files 
are much larger than the older Notepad was able to load, plus you also need 
to work with utf8 text.
Watch-out for messages with %something, as they expand values into them.
There are also enhanced % commands you can use to swap values (which is 
common in some languages like French - ask on user/developer mailing list).

**Comment by jrbastien** [comment]
This is very good information.  Thank you for this. I'm going on vacation for 3 weeks but if no ones has regenerated these POs then, I can give it a try when I'm back.

**Comment by jrbastien** [comment]
Thanks for this new feature.  I could not resist and wen ahead to test it.  This works perfectly,

I did a sanity check on the resulting fr.po and I have the following observations:

1.  Text that is removed in the newer version is commented out at the end of the file without any ID.  Perhaps this is normal but this is hard for me to evaluate if there was a problem in the merge or these strings are simply no longer there in the newest code.

2.  I can find the special characters from the utf8.pot in the resulting fr.po.  So that proves that the patch is working or my gettext version is supporting utf8 correctly.

3.  Would there be any benefit to build the pot files and merge them to the po files in the main makefile?  That way, the po files would always be up-to-date.

**Comment by JoesCat** [comment]
Just regenerate the position you're working with, and leave the others untouched otherwise it creates unnecessary updates and hides the fact that it may be a fairly old file needing attention and that there isn't any updates added.

**Comment by JoesCat** [comment]
On August 9, 2016 07:13:50 PM Jean-Rene Bastien wrote:
> Thanks for this new feature.  I could not resist and went ahead to test
> it.  This works perfectly,

Thanks for the confirmation.



> I did a sanity check on the resulting fr.po and I have the following
> observations:
> 
> 1.  Text that is removed in the newer version is commented out at the
> end of the file without any ID.  Perhaps this is normal but this is
> hard for me to evaluate if there was a problem in the merge or these
> strings are simply no longer there in the newest code.

It is possible the strings are no longer in the new code. FontForge has 
spelling corrections, rewording and other fixes with edits as simple as:
"the cat in the hat"
to
"the cat in the hat."
will obsolete the first string and create a new string.

If in doubt, you can check with grep by going to main dir and doing:
grep "the cat in the hat." -R *

or for the possibility of catching the obsolete string try using:
grep "the cat in the hat" -R *



> 2.  I can find the special characters from the utf8.pot in the resulting
> fr.po.  So that proves that the patch is working or my gettext version
> is supporting utf8 correctly.

Good to know, but still better to declare the warning as some operating 
systems aren't quite as smooth. The warning was found in older makefile code 
written by George, and was worth porting into these newer Makefile.am files.



> 3.  Would there be any benefit to build the pot files and merge them to
> the po files in the main makefile?  That way, the po files would always
> be up-to-date.

Understandable to say, that at first, it does look interesting to watch all 
these automated events happening, but after the Nth update, you realize it 
has created a lot of noise but produced nothing of real value. In summary, 
you get a false impression that the file is up to date due to the very 
recent posting date, but will be the reality that the file can be several 
years old and has had nothing improved since several years ago.

I think it is more important to visually see that a po is several years old 
and has not changed (and therefore very much) needing improvement.

Personally, I also hesitate to see the po file change radically if only one 
line improvement is added, and hope whomever is the last editor fix a decent 
portion...but this is all relative...for example, a 2 year old po may need 
several dozen or hundreds of edits, while a well maintained po will 
probably need one or two edits to be topped-up again. This is a judgement 
call up to the maintainer, and I think maybe a shared value (see #2700).

Another negative for automating the po update is, that FontForge is a 
multideveloper project, and can often have people working independently on 
different parts of the project. It is realistic to have a translators work 
several days and/or possibly longer on one po file (I experienced this 
myself, and you can see that the FontForge po files are very large, 
therefore requiring a lot of time), in the meantime you can have several 
developers coding and merging updates... so there is the real potential of 
seeing the github po file update several times versus the translator's local 
copy not being updated until it's time to merge, in summary this only 
complicates merging for the translator and the github person merging.

Nobody (translator nor github maintainers) want/need this extra workload.

**Comment by jrbastien** [comment]
OK, I understand your point.  Let's have your change pulled to the main code before closing this issue.  I will also provide an update PO.  The one that was committed and that now looks updated has still the strings from September 2014.  With the merge, I need now to fix a lot of things.

I will close the other issue I have submitted (issue #2768) as a duplicate of this one.

**Comment by JoesCat** [comment]
Can you also include a French translation for the file in directory desktop too?
this file is easier to edit with a basic text editor like kwrite, gedit, notepad, or something similar (but also needs to capable of reading/writing utf8 since some translations require it.
https://github.com/fontforge/fontforge/blob/master/desktop/fontforge.appdata.xml

**Comment by jrbastien** [comment]
Sure. That's no big deal.  I will restart working on this when I'm back from vacation on August 29th.

**Comment by JoesCat** [comment]
FYI - issue# https://github.com/fontforge/fontforge/issues/2624 about ll@li.org

I also found a reference mentioning the art of swapping %s and %s if you need to do such a thing.
http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/project/howto.html
I don't know if you will find it useful, but added this link for anyone following/reading....

**Comment by jrbastien** [comment]
Thanks Joe, very useful.  I'm currently working on it.  The French translation was in such a sorry state that there are still 2300 strings untranslated.

I encountered a few issues in the base language that I will report later once I commit my changes later this week.  Hopefully with less than 2000 missing strings...
