### ISSUE TITLE
Rename structures conflicting with GLib/GIO/GDK

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2841]
Since we control the libraries (and we're the only ones using it), it would be ideal to rename some of our GDraw components, like `GList`, `GTimer` and `GMenuItem` to something else, like `GDList` , `GDTimer` and `GDMenuItem` to avoid conflicts with GLib/GIO/GDK. This means that we can eliminate `ffglib.h` and avoid having to write things like `GList_Glib` when we actually want to use the glib variant of GList.

For example, right now I have to back out @gioele's changes to `startui.c` in my [GDK PR](https://github.com/fontforge/fontforge/pull/2782/commits/c34919d0044a5ff14874eb3e919316571e67a29d) because I need to include the gdk header.

**Comment by davelab6** [comment]
Good idea :) I wonder if @JoesCat might like to take this one on? :)

**Comment by JoesCat** [comment]
On February 1, 2017 07:24:45 AM Dave Crossland wrote:
> Good idea :) I wonder if @JoesCat might like to take this one on? :)

Right now, I believe @jtanx is much more knowledgeable of what needs fixing 
there due to his involvement with these files. I would recommend bumping-up 
the library version value in configure.ac, plus look at what gets dumped 
into /usr/local/includes and add to Makefile.am a line for No-install for 
files that don't need to be dumped here, then also see what got lost if you 
compare the git version versus the 'make dist' version, and add extra-dist 
in Makefile.am so that those files also get included (Unicode/makefile.am is 
fairly complete now if you want to compare). Last but not least, I think 
there is an issue floating around about fontforge's Gdraw library in conflict 
with another Gdraw library, so, maybe this is a good time to rename the 
Gdraw library to something else, like maybe ff_gdraw.
...just throwing out ideas.

...at the moment, I still want to complete the is_Ligatures_expand, fix 
combiners, investigate adding char(0) in alts[], and @pander is pointing 
out some further things that will most likely be all Unicode/library 
involved...so, I'll be in Unicode/*.* a while longer....

**Comment by jtanx** [comment]
WIP on https://github.com/fontforge/fontforge/tree/2841-rename-structs

**Comment by davelab6** [comment]
Great job @jtanx - really looking forwards to seeing the GDK version running on macOS and Windows :)
