### ISSUE TITLE
Microsoft Word Changes Characters During Typing

### ISSUE THREAD

**Issue by laurelp448** [fontforge/fontforge#2856]
I'm working on my first FontForge font, and I'm having a problem using it with Microsoft Word.  When I type certain characters in Word, the glyph in my font is replaced with one from a font already installed on my computer.  For example, I cannot type apostrophes or quotes without them being replaced.  The apostrophe in my font is replaced with one from Courier.  I can turn off autocorrect on Word, but since I want to share this font with others, I would rather them be able to use it without having to change their settings.  

Is this a common problem?  Does anyone have any suggestions for how to alter my font so that it won't do this?  Thank You!

**Comment by jtanx** [comment]
I suggest that you sign up to the FF mailing list (https://lists.sourceforge.net/lists/listinfo/fontforge-users) as you're more likely to get a response there wrt. questions. The primary focus of this issue tracker is about bugs/problems with FF itself.

Anyway - MS Word/Windows usually substitutes glyphs if they don't exist in the font being used - have you made the apostrophe/quote glyphs in your font?

**Comment by mskala** [comment]
To elaborate... when you type an apostrophe on your keyboard it is usually U+0027 '  .  Word's "smart quotes" feature may substitute some other character, such as U+2019.  Then if your font doesn't contain U+2019 it'll substitute the glyph for that character from some other font.  Interestingly, I don't think Courier has a real glyph for U+2019 (as in, a slanted closing single quote distinct from the ASCII vertical apostrophe/quote) either, but it probably has a copy of the ASCII apostrophe/quote glyph in that character slot.

The real problem is Word's stupid feature.  When I'm forced to use Word at all, I disable all "change what I typed while I'm typing it" features as a matter of course.  But as you say, you can't control what users will do.  So I think the way to deal with it in your font is to copy appropriate glyphs into both U+2019 and U+0027, as well as any other character codes Word may substitute.  Unfortunately I don't know the complete list, but it'd be smart to include at least U+0027, U+2019, U+2018 (left single quotation mark), U+0022 (ASCII double quotation mark), U+201C (left double quotation mark) and U+201D (right double quotation mark).

**Comment by laurelp448** [comment]
Thank you jtanx and mskala for all of your help.  I spent some time going over the list of glyphs, as you all suggested and realized that I did not have glyphs for the ones Word was substituting.  I copied the glyph from U+0027 to U+2018 and U+2019 and the glyph from U+0022 to U+201C and U+201D.  It works perfectly now.  Also, thank you jtanx, I will be posting future questions in the correct location.  Thanks again!
