### ISSUE TITLE
Can I increase Fontforge stack size?

### ISSUE THREAD

**Issue by frankSol** [fontforge/fontforge#2901]
Sometimes  Fontforge was crashed When I need to open two big size font files at the same time. 

Each font file size is 18,850KB and 27,536KB

I don't have any idea How to increase the stack size.

Could you give me some tips increasing stack size? 

Thank you

**Comment by mskala** [comment]
Do you have a specific reason to think stack size is the issue here?  Loaded files in general are not stored on the stack at all, so large files would not necessarily cause it to need more stack than small files.  Unless you are getting a message specifically telling you that the program is running out of stack space, insufficient stack space is pretty far down on the list of likely causes for a crash.
