### ISSUE TITLE
Problems in libfontforge-dev header files

### ISSUE THREAD

**Issue by copyninja** [fontforge/fontforge#2908]
Hi,

We again found a bug in software `mensis` when trying to build with new fontforge.  Following is the error we found in `mensis` build log

```
checking fontforge/basics.h usability... no
checking fontforge/basics.h presence... no
checking for fontforge/basics.h... no
You must install the include files for fontforge
before building mensis.
```

It failed to detect even though libfontforge-dev provides those file. Then the maintainer notes descripencies in header file as compared to 2012 version [here on Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840393#10). Then he fixed some of those headers to look like 2012 version but that gave rise to new issue of `undefined reference to grealloc` which I'm not sure on if its related to fontforge or the mensis.

I'm bit confused now on whether issue is in fonrforge or mensis, so I would highly appreciate input from fontforge developers.

**Comment by jtanx** [comment]
Mmmm mensis is oooold software, which IIRC is unmaintained.

**Comment by jtanx** [comment]
Basically, mensis hasn't been maintained in many years. FontForge has moved on, so unless someone wants to spend the time to update mensis, it won't work with the current FontForge. Things like `grealloc` (custom allocators(?) in FF) were ripped out long ago. Those should be replaced with the standard memory allocation functions like `realloc`/`malloc` etc.

**Comment by copyninja** [comment]
Thanks for confirming. @henrich please take a call on maintaining `mensis` in Debian.

**Comment by jtanx** [comment]
Oh yeah. I did some further investigation on this. The other side of the coin is that basically no other program depends on FontForge (* okay so there are a few. But no one has complained enough about it). So there's been very little in the way of actually ensuring that dependent packages compile outside of FontForge itself.

The reason for the configure fail was likely because of the use of angle brackets instead of "" e.g. `#include <fontforge-config.h>` instead of `#include "fontforge-config.h"`. So you must include the fontforge header folder explicitly, something like:

`````
CFLAGS="-I/usr/local/include -I/usr/local/include/fontforge" LDFLAGS="-L/usr/local/lib" ./configure
`````

**Comment by copyninja** [comment]
Thanks for the clarification. I don't see any issue in fontforge hence closing the issue.
