### ISSUE TITLE
NEW RELEASE 2017

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3014]
Hello 
@davelab6 , @frank-trampe 
It would be time to release new FontForge version in 2017!

**Comment by davelab6** [comment]
Yes, I'd like to see that :)

**Comment by typedesigner** [comment]
@davelab6 Thanks, It would be great if updates are released every month.

**Comment by typedesigner** [comment]
@davelab6 When will FontForge new version release?

**Comment by davelab6** [comment]
Maybe rather than a release made by the people who have made then recently,
they could closely document the release process such that it can be done by
more members of the community

**Comment by typedesigner** [comment]
@davelab6 @frank-trampe I'm surprised that no new version was released yet.

**Comment by davelab6** [comment]
I'm not surprised. TruFont 0.6.0 was just pushed to master branch, though :D

**Comment by typedesigner** [comment]
@davelab6 Where can I download TruFont 0.6.0 ?

**Comment by typedesigner** [comment]
Hello
@frank-trampe , @jtanx, @davelab6 
It would be time to release new FontForge version in 2017! 
Since the release of the last version, more than 6 months have passed.

**Comment by fitojb** [comment]
As this project has not committed to time-based releases, and taking into account its current manpower, I find it distasteful to demand a release; there is no obligation.

**Comment by typedesigner** [comment]
@fitojb Nobody to demand a release. It would be desirable, however, if new FontForge - Windows versions with eliminate bugs are published regularly.

**Comment by davelab6** [comment]
to run it from sourcesIt would be desirable, yes. You are free to make one
and propose it for use as a release :)

TruFont 0.6.0 hasn't been released yet, you have t


On May 2, 2017 9:36 AM, "typedesigner" <notifications@github.com> wrote:

@fitojb <https://github.com/fitojb> Nobody to demand a release. It would be
desirable, however, if new FontForge - Windows versions with eliminate bugs
are published regularly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fontforge/fontforge/issues/3014#issuecomment-298637347>,
or mute the thread

**Comment by jtanx** [comment]
@typedesigner if you're after the bleeding edge, you can use appveyor builds, which have been available for quite a while now: https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts

The only difference from that to normal releases is that it lacks some manual patching for unicode filename support.

**Comment by frank-trampe** [comment]
The release happened, so I'm closing the issue.

**Comment by davelab6** [comment]
Thank you Frank!!!
