### ISSUE TITLE
lots of left-over files and not exactly clean which of make *clean wll clean it.

### ISSUE THREAD

**Issue by HinTak** [fontforge/fontforge#3110]
After `make`, a lot of files appears, and `make clean` does not really clean up much. Also there are a lot of confusing *clean targets in the generated Makefile. There is a distclean target but it does not clean up either. It is not exactly clear which will clean the tree to the original state.

I did

```
rm -rf *
git reset --hard
```

a few times already. That's really barbaric and should not be a requirement to do anything with the fontforge code base.

**Comment by jtanx** [comment]
Do you mean that lots of files appear which aren't ignored by git?

```
tanjj@fuse MINGW32 ~/ffbuild/work/mingw32/fontforge
$git status
On branch master
Your branch is up-to-date with 'upstream/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        fontforge.configure-complete

nothing added to commit but untracked files present (use "git add" to track)
```

The only file listed is my own junk, so everything looks okay here.

**Comment by HinTak** [comment]
That's besides the point. One of the *clean targets should restore the source tree - e.g. expand from a release tar ball, so it does not sit on top of git, and git is irrelevant - to somewhat closer to original, instead of the 30 or 40 extra files/directories at the moment. If one wants to be really untidy, one can just add * to gitignore to ignore everything, and work in a sh*t environment by choice. Not everybody works from git, and not everybody should be required to work from git.

**Comment by jtanx** [comment]
Sorry, nope, still don't get the issue. 

After a `make clean`

```
$git check-ignore **/*
autom4te.cache/output.0
autom4te.cache/output.1
autom4te.cache/requests
autom4te.cache/traces.0
autom4te.cache/traces.1
breakpad/Makefile
breakpad/Makefile.in
collab/Makefile
collab/Makefile.in
config/ar-lib
config/compile
config/config.guess
config/config.rpath
config/config.sub
config/depcomp
config/install-sh
config/ltmain.sh
config/mdate-sh
config/missing
config/texinfo.tex
contrib/Makefile
contrib/Makefile.in
desktop/Makefile
desktop/Makefile.in
doc/Makefile
doc/Makefile.in
fontforge/Makefile
fontforge/Makefile.in
fontforgeexe/darwinsetup
fontforgeexe/Makefile
fontforgeexe/Makefile.in
gdraw/Makefile
gdraw/Makefile.in
gnulib/build-aux
gnulib/cfg.mk
gnulib/ChangeLog
gnulib/check-copyright
gnulib/check-module
gnulib/config
gnulib/COPYING
gnulib/DEPENDENCIES
gnulib/doc
gnulib/gnulib-tool
gnulib/lib
gnulib/m4
gnulib/Makefile
gnulib/modules
gnulib/MODULES.html.sh
gnulib/NEWS
gnulib/posix-modules
gnulib/README
gnulib/STATUS-libposix
gnulib/tests
gnulib/top
gnulib/users.txt
gutils/Makefile
gutils/Makefile.in
inc/fontforge-config.h
inc/Makefile
inc/Makefile.in
inc/stamp-h2
lib/_Noreturn.h
lib/alloca.in.h
lib/arg-nonnull.h
lib/arpa_inet.in.h
lib/asnprintf.c
lib/asprintf.c
lib/basename-lgpl.c
lib/c++defs.h
lib/c-strtod.c
lib/c-strtod.h
lib/dirname.h
lib/dirname-lgpl.c
lib/dosname.h
lib/errno.in.h
lib/error.c
lib/error.h
lib/exitfail.c
lib/exitfail.h
lib/fcntl.in.h
lib/fd-hook.c
lib/fd-hook.h
lib/filename.h
lib/float.c
lib/float.in.h
lib/float+.h
lib/getdelim.c
lib/gethostname.c
lib/getline.c
lib/getprogname.c
lib/getprogname.h
lib/gettext.h
lib/gettimeofday.c
lib/inet_ntop.c
lib/intprops.h
lib/itold.c
lib/limits.in.h
lib/locale.in.h
lib/localeconv.c
lib/localtime-buffer.c
lib/localtime-buffer.h
lib/lstat.c
lib/Makefile
lib/Makefile.am
lib/Makefile.in
lib/malloc.c
lib/malloca.c
lib/malloca.h
lib/malloca.valgrind
lib/memchr.c
lib/memchr.valgrind
lib/msvc-inval.c
lib/msvc-inval.h
lib/msvc-nothrow.c
lib/msvc-nothrow.h
lib/netinet_in.in.h
lib/pathmax.h
lib/printf-args.c
lib/printf-args.h
lib/printf-parse.c
lib/printf-parse.h
lib/progname.c
lib/progname.h
lib/secure_getenv.c
lib/size_max.h
lib/sockets.c
lib/sockets.h
lib/stat.c
lib/stat-w32.c
lib/stat-w32.h
lib/stdalign.in.h
lib/stdarg.in.h
lib/stdbool.in.h
lib/stddef.in.h
lib/stdint.in.h
lib/stdio.in.h
lib/stdlib.in.h
lib/strcasecmp.c
lib/strdup.c
lib/strerror.c
lib/strerror-override.c
lib/strerror-override.h
lib/string.in.h
lib/strings.in.h
lib/stripslash.c
lib/strncasecmp.c
lib/strndup.c
lib/strnlen.c
lib/strtok_r.c
lib/sys_socket.c
lib/sys_socket.in.h
lib/sys_stat.in.h
lib/sys_time.in.h
lib/sys_types.in.h
lib/sys_uio.in.h
lib/tempname.c
lib/tempname.h
lib/time.in.h
lib/tmpdir.c
lib/tmpdir.h
lib/tmpfile.c
lib/unistd.c
lib/unistd.in.h
lib/vasnprintf.c
lib/vasnprintf.h
lib/vasprintf.c
lib/verify.h
lib/w32sock.h
lib/warn-on-use.h
lib/wchar.in.h
lib/xalloc.h
lib/xalloc-die.c
lib/xalloc-oversized.h
lib/xasprintf.c
lib/xmalloc.c
lib/xsize.c
lib/xsize.h
lib/xvasprintf.c
lib/xvasprintf.h
libltdl/COPYING.LIB
libltdl/libltdl
libltdl/loaders
libltdl/lt__alloc.c
libltdl/lt__argz.c
libltdl/lt__dirent.c
libltdl/lt__strl.c
libltdl/lt_dlloader.c
libltdl/lt_error.c
libltdl/ltdl.c
libltdl/ltdl.h
libltdl/Makefile
libltdl/Makefile.am
libltdl/Makefile.in
libltdl/README
libltdl/slist.c
m4/00gnulib.m4
m4/absolute-header.m4
m4/alloca.m4
m4/arpa_inet_h.m4
m4/c-strtod.m4
m4/dirname.m4
m4/double-slash-root.m4
m4/eealloc.m4
m4/errno_h.m4
m4/error.m4
m4/exponentd.m4
m4/extensions.m4
m4/extern-inline.m4
m4/fcntl_h.m4
m4/fcntl-o.m4
m4/float_h.m4
m4/getdelim.m4
m4/gethostname.m4
m4/getline.m4
m4/getprogname.m4
m4/gettimeofday.m4
m4/gnulib-cache.m4
m4/gnulib-common.m4
m4/gnulib-comp.m4
m4/gnulib-tool.m4
m4/iconv.m4
m4/include_next.m4
m4/inet_ntop.m4
m4/intmax_t.m4
m4/inttypes_h.m4
m4/largefile.m4
m4/lib-ld.m4
m4/lib-link.m4
m4/lib-prefix.m4
m4/libtool.m4
m4/limits-h.m4
m4/locale_h.m4
m4/localeconv.m4
m4/localtime-buffer.m4
m4/longlong.m4
m4/lstat.m4
m4/lt~obsolete.m4
m4/ltargz.m4
m4/ltdl.m4
m4/ltoptions.m4
m4/ltsugar.m4
m4/ltversion.m4
m4/malloc.m4
m4/malloca.m4
m4/manywarnings.m4
m4/memchr.m4
m4/mmap-anon.m4
m4/msvc-inval.m4
m4/msvc-nothrow.m4
m4/multiarch.m4
m4/netinet_in_h.m4
m4/off_t.m4
m4/pathmax.m4
m4/printf.m4
m4/secure_getenv.m4
m4/size_max.m4
m4/socketlib.m4
m4/sockets.m4
m4/socklen.m4
m4/sockpfaf.m4
m4/ssize_t.m4
m4/stat.m4
m4/stdalign.m4
m4/stdarg.m4
m4/stdbool.m4
m4/stddef_h.m4
m4/stdint.m4
m4/stdint_h.m4
m4/stdio_h.m4
m4/stdlib_h.m4
m4/strcase.m4
m4/strdup.m4
m4/strerror.m4
m4/string_h.m4
m4/strings_h.m4
m4/strndup.m4
m4/strnlen.m4
m4/strtok_r.m4
m4/sys_socket_h.m4
m4/sys_stat_h.m4
m4/sys_time_h.m4
m4/sys_types_h.m4
m4/sys_uio_h.m4
m4/tempname.m4
m4/time_h.m4
m4/tmpdir.m4
m4/tmpfile.m4
m4/unistd_h.m4
m4/vasnprintf.m4
m4/vasprintf.m4
m4/warnings.m4
m4/warn-on-use.m4
m4/wchar_h.m4
m4/wchar_t.m4
m4/wint_t.m4
m4/xalloc.m4
m4/xsize.m4
m4/xvasprintf.m4
mackeys/Makefile
mackeys/Makefile.in
nodejs/Makefile
nodejs/Makefile.in
osx/Makefile
osx/Makefile.in
plugins/Makefile
plugins/Makefile.in
po/Makefile
po/Makefile.in
pycontrib/Makefile
pycontrib/Makefile.in
pyhook/Makefile
pyhook/Makefile.in
share/Makefile
share/Makefile.in
tests/atconfig
tests/atlocal
tests/Makefile
tests/Makefile.in
Unicode/Makefile
Unicode/Makefile.in
uthash/doc
uthash/include
uthash/LICENSE
uthash/package.json
uthash/README.md
uthash/src
uthash/tests
```

That all looks quite sane to me, unless you want to be running `./bootstrap` and regenerating your makefiles again.

**Comment by HinTak** [comment]
Please stop referring to git.

Let's say somebody wants to contribute, one-off. He downloads a particular version of fontforge's release tar ball, make some changes to it, verify that the changes (including adding some new files, perhaps) does what it is meant to do; then
he does

make whatever-clean

then he unpacks the release tar ball elsewhere again, and compare the old tree and the modified tree thus:

`diff -ruN old_tree new_tree` , to try to generate a diff to be sent to be attached to one of these issue reports. 

At the moment, such a diff is full of rubbish.

Please stop referring to git - not everybody is interested in getting hold of the whole repo and all its history, etc, just to send a diff, one-off . And please stop asking people to take a long-term interests in your project. Most people don't, and don't want to.

**Comment by JoesCat** [comment]
Hi @HinTak,
I understand what you're looking at. Fact is, FontForge is a fairly large codebase, which also went through a very large conversion of the make system post-20120731, plus has/had a lot of contributions done too. From our point of view, there is always a struggle between trying to get something accomplished, putting out immediate fires, improving code where recognizable, and trying to make code self-test (ie coverity, travis, and other test-as-we-patch checkers). This means, there is going to be a trade-off in time attending to various issues, and some things just have to be seen as long-term with no expectation of immediate results - if you want an example of long term, look at the history for AUTHORS, it is worth recognizing developers and contributors, and despite the time put into that one file, you could see it only put a small dent in what has yet to be looked at. The Make system could be viewed the same way, it would be good to make it perfect, but for now, it sort of goes okay and allows us to move along.

My suggestion for the problem you point-out would be to not do your work in the master copy, this is more effort, but allows your master to be equal to what you see in github:
git clone https://github.com/HinTak/fontforge.git ~/myfontforgemaster
modify ./git/configure with whatever customizations you want (for myself, I've added other forks, to make it easier to import other user's code contributions).
next:
cp -pR ~/myfontforgemaster ~/myfontforgeworkingcopyA
cp -pR ~/myfontforgemaster ~/myfontforgeworkingcopyB
cp -pR ~/myfontforgemaster ~/myfontforgeworkingcopy....
Do your mods and testing in ~/myfontforgeworkingcopyA...
If you're satisfied with your work, then create a branch in ~/myfontforgemaster and copy your patch in so that you can upstream it to main fontforge.

If you are interested in making clean do as it should, some directories have already gotten a closer look, others have not, and then there's also the fact that you need to maintain too, so even though some directories did get attention in the past, they probably could use some review again. From memory, I believe gutils, inc and currently Unicode directories are reasonably okay if you try, while there are other directories that have gotten no attention yet.
If you are interested in cleaning, this is what I have done:
rm -fR ~/myfontforgeworkingcopyA
cp -pR ~/myfontforgemaster ~/myfontforgeworkingcopyA
cd ~/myfontforgeworkingcopyA
rm -fR .git
./bootstrap
./configure (plus options)
make dist
tar -xzf tarfile to a directory
diff -r directory ~/myfontforgemaster

from here, see what needs fixing and improving to make "directory" same as ~/myfontforgemaster
...after that, advance to next step and do similar by going a step further and improving that, such as make clean, etc.

make your patches easy to understand and easy to merge into mainline.

We can talk, or we can do. Do is better.
Looking forward to seeing your patches :-)
Cheers
Joe

**Comment by jtanx** [comment]
@HinTak

> Please stop referring to git.

The only reference I made was to show what files were ignored, which you consider 'junk'.

> `diff -ruN old_tree new_tree` , to try to generate a diff to be sent to be attached to one of these issue reports. At the moment, such a diff is full of rubbish.

You appear to have a fundamental misunderstanding of how autotools based projects work. When you run `./configure`, you're generating the makefiles. Are you telling me that running `make clean` should remove the makefiles? Please show me a project that does this. 

If you desire a clean source tree, then do an out of source build. Granted, autotools isn't very good at that, from what I recall, so your mileage may vary.

No one is forcing you to use git, but if you choose not to, and want to send in a patch then that's your prerogative.

**Comment by mskala** [comment]
Normally, in any autotools-based build, "make distclean" will remove the Makefiles.  Examples are, literally, almost any autotools-based builds; if FontForge is an exception, it shouldn't be, and that would probably be the result of bootstrap leaving cruft behind.  See also https://www.gnu.org/prep/standards/html_node/Standard-Targets.html .

**Comment by jtanx** [comment]
Huh, neat, I didn't realise that. Using the 20161004 dist tarball, I can see:

```
$diff -ruBw fontforge-2.0.20161004/ pristine
Only in pristine/inc: fontforge-config.h
Only in pristine/osx/FontForge.app/Contents: Info.plist
Only in pristine/tests: testsuite
```

Which actually suggests that distclean is removing more than it should be.

In any case, I've just done an out of source build, which works fine. So my suggestion is still to do that, if you really don't want to use git.
