### ISSUE TITLE
sort the content of fontforge/python.c (and perhaps also fontgorge/scripting.c) in some kind of order

### ISSUE THREAD

**Issue by HinTak** [fontforge/fontforge#3113]
At the moment, the content of  fontforge/python.c (an perhaps fontforge/scripting.c also) is rather a mess. Much of it is in alphabetical order, but some of it - copy/paste? - is grouped by functionality, and yet some other part is simply historical - i.e. newer stuff gets added to the end of a section.

And static funcions should either be all at the beginning, or just before they are first used; not sure that's true.

I'd suggest organize it a bit in whatever way, to make it easier to navigate, and also to have one particular obvious place to add any specific new functionality.

I am not volunteering, and I'd prefer not to engage in any extended discussion. This is a wierd community spending more time making excuses... it is not a difficult change and really requires no discussion, just somebody who is agreeable to most, to make the change, in whatever direction.

**Comment by Anonrate** [comment]
In something as big as FontForge, reordering and moving one function can break the whole application.   This should be closed for stupidity.

**Comment by HinTak** [comment]
That would be a justification to not work on any sufficiently large projects ( linux kernel, gnome, cairo, etc) then , of afraid of breaking them. LOL 

--------------------------------------------
On Sun, 1/10/17, Anonrate <notifications@github.com> wrote:

 Subject: Re: [fontforge/fontforge] sort the content of fontforge/python.c (and perhaps also fontgorge/scripting.c) in some kind of order (#3113)
 To: "fontforge/fontforge" <fontforge@noreply.github.com>
 Cc: "HinTak" <htl10@users.sourceforge.net>, "Author" <author@noreply.github.com>
 Date: Sunday, 1 October, 2017, 9:51
 
 In something as big as FontForge,
 reordering and moving one function can break the whole
 application.   This should be closed for stupidity.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ctrlcctrlv** [comment]
@Anonrate Your response to this issue was rude and uncalled for.

The code does need reorganization; almost every file does. Some of the larger (1000+ line) functions need it the most. `python.c` is as good a place as any to start - the problem is finding volunteers.

**Comment by Anonrate** [comment]
@ctrlcctrlv I do apologize but the way the issue was worded, was repugnant.  I do however agree that a lot of the code needs to organized and made to properly follow conventions as it is hard to read.  I was actually thinking about doing so myself, but I honestly didn't think that it would be made of use.  I rather enjoy formatting code.

**Comment by frank-trampe** [comment]
Most of FontForge is a tangled mess. With the codebase as big as it is and my time as limited as it is, a lot of FontForge is still jungle, and the commit history is a valuable navigation aid. Large-scale reformats and restructures deprive us of that tool, which is why I tend to discourage them.

@HinTak, I know that some of our design and management decisions are baffling, but there are generally good reasons behind them. It's a rare project of this size and complexity that survives without its original author and without funding. We have a tremendous number of constituencies to please, and, overall, I think that we do a very good job of balancing their needs and delivering monotonic improvements subject to our resources.

It's difficult to convey lightness in written form, so it's important to choose words carefully. @HinTak, I hope that you will accept @Anonrate's apology.
