### ISSUE TITLE
FontForge Error

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3118]
@frank-trampe @davelab6 @jtanx 
![unbenannt](https://user-images.githubusercontent.com/18243844/28454991-9216ff1c-6dfd-11e7-873e-e798bab6d7ab.PNG)
![unbenannt1](https://user-images.githubusercontent.com/18243844/28454992-9307d658-6dfd-11e7-9839-a894bccebfe3.PNG)

This needs to be corrected. In the Kerning table more than 100,000 Kernening Pare should fit.

**Comment by jtanx** [comment]
A quick search suggests: https://forum.glyphsapp.com/t/too-many-kerning-pairs/2037

> Technical background: Each pair in the "kern" table takes 6 bytes, there is a 14-byte header, and the maximum size of a subtable is 64K bytes, so (65536-14)/6 gives you 10920. Most font engines only support a "kern" table with one subtable, so there's the limit.

So it's not fixable, sorry.

**Comment by typedesigner** [comment]
@jtanx Thanks, clear.

**Comment by khaledhosny** [comment]
Any particular reason are you generating old-style kern table instead of kerning in GPOS table (which does not have this llimit, among others)?

**Comment by typedesigner** [comment]
@khaledhosny @jtanx old-style kern ? Please tell me how I can use new style kern in FontForge? Is there an introduction?

**Comment by davelab6** [comment]
New style keen is gpos kern

On Jul 23, 2017 10:31 AM, "typedesigner" <notifications@github.com> wrote:

@khaledhosny <https://github.com/khaledhosny> @jtanx
<https://github.com/jtanx> old-style kern ? Please tell me how I can use
new style kern in FontForge? Is there an introduction?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fontforge/fontforge/issues/3118#issuecomment-317257076>,
or mute the thread
