### ISSUE TITLE
can't open font that has parentheses in its name

### ISSUE THREAD

**Issue by Yay295** [fontforge/fontforge#3133]
In Python

    font = fontforge.open(file_name + '(' + font_name + ')')

where `file_name == 'Automatica -BRK-xy.ttf'` and `font_name == 'Automatica (BRK)xy'` throws `EnvironmentError: Open failed`. `fontforge.open(file_name)` works fine, and this is the only font I have that has parentheses in its name which is why I think the parentheses are the problem.

[Automatica -BRK-xy.zip](https://github.com/fontforge/fontforge/files/1216914/Automatica.-BRK-xy.zip)

**Comment by skef** [comment]
Can you say a bit more about this problem and the behavior you expect?

The string corresponding to `file_name + '(' + font_name + ')'`, given those settings, is `Automatica -BRK-xy.ttf(Automatica (BRK)xy)`. The file in the zip is named `Automatica -BRK-xy.ttf`. So one simple explanation for why the open fails is that there is no file that name, but I take it that's too simple and you're trying to open a file with some name that actually has parentheses in its name. 

If I rename your file `Automatica -BRK-xy.ttf(Automatica (BRK)xy)` it indeed doesn't open, but that's because FontForge is currently picky about file extensions and since '.ttf' isn't at the end of the name it doesn't recognize the type. If instead I rename it `Automatica -BRK-xy(Automatica (BRK)xy).ttf` then FontForge does successfully open it, at least on Linux where I am testing.

**Comment by Yay295** [comment]
Since font files can have more than one font in them (TTC files at least), FontForge needs to allow you to open the individual fonts. It does this by adding a special case for parentheses after the extension. `fontforge.open('Automatica -BRK-xy.ttf(Automatica (BRK)xy)')` does not mean to open the file named 'Automatica -BRK-xy.ttf(Automatica (BRK)xy)', but to open the font named 'Automatica (BRK)xy' that is within the file named 'Automatica -BRK-xy.ttf'. Now obviously a TTF file wouldn't have more than one font in it, but this method does work on every other font file I have (it's easier to do it this way for all of them than to have a special case for when there actually is more than one font in the file). It's also possible to open fonts this way by index (`fontforge.open('Automatica -BRK-xy.ttf(0)')`), so that's what I'm doing to get around this bug. It seems to me that there's just some parsing issue due to the extra parentheses, which shouldn't be hard to fix. I don't know where in FontForge's code this is handled though.

**Comment by skef** [comment]
Ah good -- I thought something of this sort might be at issue but there's nothing documented at the python level. (It is documented at http://fontforge.github.io/en-US/documentation/interface/filemenu/#open where I didn't think to check.)

I'm taking a look at this.

**Comment by skef** [comment]
Congratulations! Here are lines 2292-4 of fontforge/splinefont.c:
```
    /* Someone gave me a font "Nafees Nastaleeq(Updated).ttf" and complained */
    /*  that ff wouldn't open it */
    /* Now someone will complain about "Nafees(Updated).ttc(fo(ob)ar)" */
```
It's probably not a big deal to pair some parentheses here ...

**Comment by Yay295** [comment]
Nice. Looks like that code was added by George Williams. In 2007...

**Comment by skef** [comment]
And in a ... number of places. 

The TTF paths are fairly easy to fix up with an added parameter to _SFReadTTF and a NULL in the other places it's called. However, the macbinary paths are a mess. I'm leaning towards doing the more proper thing for the former and just living with copied code in the latter.
