### ISSUE TITLE
Setting macStyle via python script not working

### ISSUE THREAD

**Issue by ffpyguy** [fontforge/fontforge#3174]
I don't understand why this isn't working using python. Here is my code:

```
import os, sys, fontforge

filename = sys.argv[1]
font = fontforge.open(filename)

print font.macstyle # outputs -1
font.macstyle = 2  # is Italic
print font.macstyle # outputs 2, but in final output font the macStyle hasn't changed, why?

font.generate('output.otf')
font.close()
```

I've tried several different input fonts but same results, macStyle doesn't change..

**Comment by jtanx** [comment]
Since a9c48a6314b93cdded1b2bfa1312c2bb150b240c / #2145, you must ensure that the 'style map' parameter also matches (a subset of the OS2 fsSelection bits), e.g.:

```py
...
font.macstyle = 2  # is Italic
font.os2_stylemap = 1 # Italic - https://www.microsoft.com/typography/otspec/os2.htm#fss
...
```

That's enough such that you will have correctly overridden the style bit in the output. However, when you read the file back, it will still show as `-1`. I think this is by design;  normally the macstyle is inferred from the font subfamily name, so `-1` essentially indicates that it will be inferred on generation. (For future reference, `SFFillFromTTF` doesn't set `sf->macstyle` from `info->macstyle`, and leaves it at the default value of `-1`).

**Comment by ffpyguy** [comment]
Thanks this worked! How come there is no mention of this **.os2_stylemap** property in the documentation? Perhaps it should be added and mentioned how to set the macstyle correctly.
