### ISSUE TITLE
Exporting SVG clips bottom of the glyph

### ISSUE THREAD

**Issue by iyoossaev** [fontforge/fontforge#3271]
While exporting a single glyph (in my case it's uni4E1C and all others from CJK ideographs from the SimSun TTF font) to SVG, the glyph seems to be wronly placed/centered/clipped. This issue only manifests when exporting to SVG; exporting the same glyph to PDF or PNG works fine. Examples in the attached archive.

Issues experienced with the latest FontForge version (31-Jul-2017) on a machine running Windows 10.

To reproduce this behavior, open the easily available SimSun font, double-click on a glyph and use File → Export (as SVG)
[FontForge problems.zip](https://github.com/fontforge/fontforge/files/1821810/FontForge.problems.zip)

**Comment by shivekkhurana** [comment]
Hi @MrVocabulary 

Was this issue resolved for you? I'm facing the same problem. 

```
$ fontforge -v
Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 12:50 UTC 14-Nov-2019-D.
fontforge 20190801
build date: 12:50 UTC 14-Nov-2019
```

**Comment by MrVocabulary** [comment]
Hi @shivekkhurana,

unfortunately not :(

**Comment by skef** [comment]
The vertical metrics for the viewBox are determined by the ascender and decender metrics of the font and changing that (at least as a default) would screw up a lot of workflows.

Now that we have flags for glyph-level export we could add one for this case but it would be good to know how and why it's important, given that:

1. The glyphs of most fonts fit into those metrics and
2. The problem is easily worked around using other tools. (For example, I just opened your example in Inkscape, went to File -> Document Properties ... and pressed the "Resize page to drawing or selection" button and got the desired result.

**Comment by shivekkhurana** [comment]
My use case needs me to generate svg version of a text in multiple fonts. 

To avoid embedding fon/css in svg, my plan is to convert all font characters to svg and then combine multiple characters together to form the text again.

I need to convert 100s of fonts to svgs for this purpose. Doing it manually isn't very efficient. 

Re 1: I have tried multiple fonts and the letters "g", "y" etc are getting clipped at the bottom
Re 2: It'll not be efficient to export each glyph in a font manually using Inkscape for my particular use case

I understand that what I'm trying to do is probably not aligned with the purpose of this project. If you can guide me to some docs or code or let me know how to go about implementing a fix, I'll be happy to code and raise a PR (if need be).

**Comment by skef** [comment]
Sent this as an email first by mistake: 

If we were to have a special flag to avoid viewBox clipping, the vertical metrics on (at least) those characters would be different. If you're converting 100s of fonts to SVGs I'm guessing it wouldn't be very fun to hand-align those characters anyway.

I'm a bit busy right now so I can't experiment but I would think the thing to do is to temporarily change the ascender and decender metrics in the font so that all characters "fit" vertically, then generate the SVGs. The trick is to avoid scaling the font when doing so. I believe that's possible I just don't immediately recall the details.

**Comment by shivekkhurana** [comment]
Vertically aligning the glyphs will make it hard to render the fonts back. The end goal is to be able to compose text and export it as svg. 

Is it possible to add bottom padding to each glyph to avoid clipping? I don't mind a little extra white space at all.

**Comment by skef** [comment]
@shivekkhurana I'm not sure we're disagreeing. (As I recall) the current implementation places the top of the viewbox at the ascender line and the bottom at the descender line. That way you can align the top and bottom of the individual exported SVG files and each character will be properly aligned to the baseline. If we were to add padding to the individual glyphs that don't fit within those metrics then they would not be aligned in the same way and would need awkward hand-processing. 

There could be a flag to choose the top and bottom positions when exporting all glyphs but if that's what is desired why not just change the ascender and descender temporarily (or in a copy) which has the same result?

**Comment by shivekkhurana** [comment]
Sorry. I missed this important detail, "The trick is to avoid scaling the font when doing so", and assumed that changing the descender and ascender metrics will change the scale of some glyphs. 

I'll try it using the UI and then write a script to do that on scale. Will update here if I'm able to get it working or if I get stuck. 

Thanks for the prompt replies and help @skef 

🌮

**Comment by skef** [comment]
To be clear: just changing those metrics might have that effect. However, I'm reasonably confident that *some* combination of adjustments can change the metrics without scaling the font -- I just don't recall what they are right now. The fontforge-users list might be of help if your experimentation doesn't turn up anything.
