### ISSUE TITLE
Glyph name is sometimes not in the font, though the glyph was just created

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3278]
After creating a glyph using Python, the glyph’s name is sometimes not `in` the font. I would expect it to always be `in` the font.

When I run this script:
```python
#!/usr/bin/env python
import fontforge
font = fontforge.font()
for cp in range(0x00, 0xFF + 1):
    name = hex(cp)
    glyph = font.createChar(cp, name)
    glyph.width = 0
    assert name in font, name
font.generate('out.ttf')
```
I get this error:
```pytb
Traceback (most recent call last):
  File "./build.py", line 8, in <module>
    assert name in font, name
AssertionError: 0x1
```

That means it failed on the second iteration of the loop, meaning there is no glyph named “0x1”, though there is a glyph named “0x0”. However, when I comment out the assertion and inspect the resulting font, all 256 glyphs have their expected names.

I am running OS X El Capitan and I am using these versions of Python and FontForge:
```console
$ python --version
Python 2.7.13
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:30 UTC 21-Mar-2018-D.
 Based on source from git with hash: 
fontforge 09:30 UTC 21-Mar-2018
libfontforge 20180321
```

**Comment by skef** [comment]
Make a glyph with an encoding and you wind up in this code in `PyFFFont_CreateUnicodeChar()`:
```
    if ( enc!=-1 ) {
        sc = SFMakeChar(fv->sf,fv->map,enc);
        if ( name!=NULL ) {
            free(sc->name);
            sc->name = copy(name);
        }
    } else {
```

`SFMakeChar()` winds up creating the glyph with a dummy name, which this code replaces. But it doesn't do anything with the `glyphnames` hash. 

On my admittedly quick reading there seem to be three options for fixing or working around this problem:

1. Just call `SFHashGlyph()`. This would get the name entry in, but leave the entry for the dummy name hanging there until the next time the table is rebuilt.
2. Rewire `SFMakeChar()` to take a name argument that overrides that provided by `SCBuildDummy()`. 
3. Just call `GlyphHashFree()` to start over. 

My sense is that option 3 is probably the right call for this case. Rebuilding a hashtable isn't a huge deal, and it's built on demand rather than immediately. @jtanx what do you think? 

This raises a separate question about what happens with these python calls when mixed with a GUI environment, which I am leaving as separate.

**Comment by jtanx** [comment]
tbh I'm not sure, I haven't really touched that code before. Although looking at what the old scripting stuff does is a good reference, I see it calls `SCSetMetaData` as part of the `SetGylphName` function

**Comment by skef** [comment]
Intercapping "Metadata": truly a sign of a disordered mind!

SCSetMetaData calls `SFGlyphRenameFixup()` and then `GlyphHashFree()`, but the former deals with references by name and there shouldn't be any of those just after creation. So basically option 3. 

I'm hoping to fix the `addPosSub` problem soon so I'll add this in.
