### ISSUE TITLE
Unicode 11.0 support

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge#3304]
Is Unicode 11.0 supported in FontForge?

- http://blog.unicode.org/2018/06/announcing-unicode-standard-version-110.html
- http://www.unicode.org/versions/Unicode11.0.0/

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem

**Comment by JoesCat** [comment]
Hi @Symbian9,
Thanks for the FYI.
At the moment, FontForge internal tables are still (mostly) coded to Unicode 9.0
To update FontForge to 11.0, some of the updating is automated (which is good/easy Unicode/makeutype, Unicode/makebuildtables, Unicode/charset/generate.sh, Unicode/makebuildtables), but some of the updating is manual (time consuming and/or did not find a possible program that used to do it at some point in time - The manual part has to do with tables sprinkled around various file locations and also superseded with some patching that fixes something but also broke existing automation, example last 3 programs listed, plus Unicode/dump, plus....).
I was looking into some ideas to deal with the hard/manual part, plus fix some bugs along the way ([mish/mash](https://github.com/JoesCat/fontforge/blob/makeudiff/Unicode/g_makeudiff.c)) but timewise, those other ideas will need more thought.
FontForge Unicode 11.0 will hopefully have it ready this month (other labour-saving ideas will have to wait).
libuninameslist 11.0 is waiting on two issues involving how to handle a python wrapper, otherwise planned for July1.
