### ISSUE TITLE
Add custom glyphs

### ISSUE THREAD

**Issue by AspiredWriter** [fontforge/fontforge#3318]
Hello,
this might be ridiculously rudimentary and obvious but I just can't get how to make this work.
I'm building a conlang font which doesn't "belong" to any language set. I've tried adding new glyphs that are not represented by the abc but when I try to use the glyph (using unicode to insert it in my document) It does nothing. just empty. I've tried to place it onto other characters (for instance chinese characters) but then it puts in the built in unicode char rather than the glyph.

I'm using reference copying ('cause I have special accents) but even when I tried just copy-pasting it still does the same thing.

Help please.
![screenshot cropped](https://user-images.githubusercontent.com/16743635/42722756-675988a4-875a-11e8-8037-2936b1464765.jpg)

I'm using windows 10 FontForge version (in screencap)
![ff version](https://user-images.githubusercontent.com/16743635/42722783-fcdae4d6-875a-11e8-9dcf-5c00e8cdc466.jpg)

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x ] Screenshot
- [x ] The FontForge version and the operating system you're using
- [x ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
I think you're fundamentally misunderstanding what is supposed to happen.

The primary purpose of FontForge is not so you can make fonts for languages existing outside of Unicode. FontForge can be used to do so, but you have to understand how computers encode characters to be successful at this.

That label is just showing you how your operating system, with its installed fonts and mechanism for fallback, will display that character. The label has nothing to do with how your character looks. The only way you could get the label to show your 9̊̄ thing for a certain character is to install a font which has that glyph at that character and configure fontconfig to display the character using that font when that character is requested.

Instead of using Chinese characters, it probably makes more sense in your situation to use a [Unicode Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas); there are many codepoints available to you in the BMP. You can also name characters based on whatever system you're using.

When your font is done, I suppose you can export it, install it, and configure fontconfig to display it, but that is not the purpose of the label. It's expected that you're actually trying to draw that character, so that label is only a visual cue to help you remember what that character should look like if you can't tell.

**Comment by AspiredWriter** [comment]
> The label has nothing to do with how your character looks.
I think you have misunderstood my problem. I appologize, I should have been clearer.

My problem is not the label. The problem is that once I generate my font and try to use it in my document (for instance in Microsoft Office) and try to use my glyph (which you can't access with regular keys on the keyboard and so I use the Alt+numpad number to access it via unicode) what I get is the character on the label rather than the glyph I've created. I am guessing FontForge can't find the glyph for some reason and the font reverts to a default glyph. What am I doing wrong?

**Comment by ctrlcctrlv** [comment]
@AspiredWriter OK, now we're getting somewhere. I'm almost certain MS Office is the problem. In order to show Chinese properly, it's very strict about fallback fonts.

Try it in GIMP, which uses freetype2/fontconfig(?) on all OS. I think that should work fine?

In order to fix it in Office, you definitely should stop using Chinese Unicode block, use the PUA.

**Comment by AspiredWriter** [comment]
@ctrlcctrlv , I don't have gimp so I used photoshop. Not sure if it's the same thing but it didn't work in that either. I tried renaming my font to AGL with PUA but it seemed to do nothing and have no effect

**Comment by ctrlcctrlv** [comment]
I said to use GIMP specifically because it uses freetype2. Download it.

**Comment by ctrlcctrlv** [comment]
You can also upload the font and I can see if I can figure out the problem :)

**Comment by ctrlcctrlv** [comment]
Yes, I'm sorry to insist on you using GIMP but it's one of the only programs that I know uses the Freetype2 renderer on all platforms. If it works in Freetype2 we can begin debugging other platforms. I want to start with Freetype2 because that's what I know best.

Downloading your font now and reviewing it.

**Comment by ctrlcctrlv** [comment]
OK so you're definitely doing stuff I would not recommend at all, but I seem to be able to see all the glyphs in this extremely weird font as you intend them in KCharSelect which is using fontconfig/freetype on KDE in Linux.

![kcharselect1](https://user-images.githubusercontent.com/838783/43314755-7dcc32c8-91c6-11e8-8264-a8f536cecbc2.png)

Really, on Windows it's no wonder you're running into trouble with the font fallback system on that OS. You need to move all these glyphs *into the Private Use Area* to be even remotely Unicode compliant. They are not the symbols you're putting them under. 

I see you've got a half range, which might be why Windows is rejecting this font. Windows will always choose to display Cyrillic in a font that supports the entire Unicode range, to my knowledge. That could be the pattern you're talking about.

![half range](https://user-images.githubusercontent.com/838783/43314929-09775dac-91c7-11e8-9806-bcbd3a61fca5.png)

**Comment by ctrlcctrlv** [comment]
@AspiredWriter Yes, that is what I mean by Private Use Area. It should be safe to use any codepoint in the range U+E000 – U+F8FF. :)

**Comment by ctrlcctrlv** [comment]
By half range I mean that your glyphs only take up half of the Cyrillic codepoint range (U+0400 - U+04FF), which could be one reason Windows prefers other fonts over yours for displaying those characters.

**Comment by AspiredWriter** [comment]
@ctrlcctrlv 
oddly, it seems that ranges 57344-61471 (E000 - F01F) and 61696-63743 (F100 - F8FF) work fine whilst 61472-61695 (F020 - F0FF) work fine in the excel sheet but not the userform. Truly baffling but I can use the first range so it seems the problem is solved. Thanks a lot for all of the help and getting me to a solution even though I'm not sure I understand it.

**Comment by AspiredWriter** [comment]
@ctrlcctrlv 
Hello. I thought this issue was resolved as I made a font with a copy of a character all over the private use area glyph unicode range and all of which worked well. However, when I tried to make a font with my actual characters in this range in the same manner I've found that some characters, again, reverted to the defaults and many more don't show at all. It is even worse than it was previously and I can't understand why it is happening.

I'm adding both fonts here. the MyFontSpaceToUse is the one that works well. The MyFont4 is the one I need to make work but is having trouble.

[Fonts.zip](https://github.com/fontforge/fontforge/files/2259338/Fonts.zip)
