### ISSUE TITLE
Italic and Regular version of Font overwriting each other on Windows

### ISSUE THREAD

**Issue by cy0x** [fontforge/fontforge#3345]
Hi there, I have recently created my first font in FontForge. Ive made a Regular and an Italic variant, but after trying to install them (as OTF, on my windows PC) ive run into a problem. If I try to use the font in any application, it only shows me the Italic variant of the Font.

![1](https://user-images.githubusercontent.com/43956826/46607467-641f9f80-cb01-11e8-8190-7f130eb8e038.jpg)

I am unable to select the Regular variant of the font, even though it is installed. 
![2](https://user-images.githubusercontent.com/43956826/46607492-7e597d80-cb01-11e8-9d47-b168f8413b4f.jpg)

Now to my suprise, after testing it on a MAC it suddenly worked just fine. I really have no idea what the cause of this problem could be, so i'd appreciate your help.

Cheers
![3](https://user-images.githubusercontent.com/43956826/46607618-ec05a980-cb01-11e8-8d1d-55132d759807.jpg)

**Comment by abnog** [comment]
Hi!
I don't know if you eventually resolved this issue, but I recently came with a similar problem. It turned out that I didn't set up properly the "Style Map" setting on the "OS/2" section ("Misc." tab).
Once I did the fonts installed on windows without any problem

Hope this can help somebody.

Cheers.

**Comment by ctrlcctrlv** [comment]
Thanks @cy0x, yes you are right, Windows relies heavily on the `OS/2` table, and that is the issue here.
