### ISSUE TITLE
solution for Issue #2361 not working for me

### ISSUE THREAD

**Issue by RobertoZedinho** [fontforge/fontforge#3359]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by JoesCat** [comment]
> I've tried to make that simple change on the fontforge.bat file but when I try and save changes an "access denied" message pops up.

I am guessing that the file was created as read-only. To edit the file, you also need to enable write permission. If you are using File Explorer, right-mouse-click the file to give you a menu, and choose properties. Look for permission to write, turn it on. This will allow you to edit the file.

> I've also tried to change it through MS-DOS by typing "edit fontforge.bat" on the right folder but, as I've just discovered, edit command no longer works for 64.bit systems.

Notepad is a good text-editor replacement for "edit", and comes installed with windows.
Use Notepad instead.
If you cannot save to fontforge.bat, just save it as fontforge1.bat, and run that instead.
As a word of caution, Notepad likes to save with the extension .txt, so you might end up saving it as fontforge1.bat.txt
To disable this behaviour, you need to go to control panel, and find file/folder settings, then look at view permissions, and turn off this behaviour so that you see the extensions like .bat, .txt, .exe, etc.
https://www.google.com/search?q=windows+control+panel+folder+view+extensions+off

> As I've checked out that my PC allows me to delete and paste files in that folder, could you please send me that changed fontforge.bat file to try it out?

I suspect the file is currently read-only, and needs to have permission set to also include write permission too. Use notepad to edit the file. For me to send a file would have no effect as it can't be overwritten or edited as long as it has write permission off.
https://www.google.com/search?q=windows+write+permission

**Comment by RobertoZedinho** [comment]
I could finally save both double quote changes but sadly for me fontforge window title remains the same. Anyway, thank you for your help...
    En lunes, 12 de noviembre de 2018 22:12:48 GMT-3, Joe <notifications@github.com> escribió:  
 
 

I've tried to make that simple change on the fontforge.bat file but when I try and save changes an "access denied" message pops up.


I am guessing that the file was created as read-only. To edit the file, you also need to enable write permission. If you are using File Explorer, right-mouse-click the file to give you a menu, and choose properties. Look for permission to write, turn it on. This will allow you to edit the file.


I've also tried to change it through MS-DOS by typing "edit fontforge.bat" on the right folder but, as I've just discovered, edit command no longer works for 64.bit systems.


Notepad is a good text-editor replacement for "edit", and comes installed with windows.
Use Notepad instead.
If you cannot save to fontforge.bat, just save it as fontforge1.bat, and run that instead.
As a word of caution, Notepad likes to save with the extension .txt, so you might end up saving it as fontforge1.bat.txt
To disable this behaviour, you need to go to control panel, and find file/folder settings, then look at view permissions, and turn off this behaviour so that you see the extensions like .bat, .txt, .exe, etc.
https://www.google.com/search?q=windows+control+panel+folder+view+extensions+off


As I've checked out that my PC allows me to delete and paste files in that folder, could you please send me that changed fontforge.bat file to try it out?


I suspect the file is currently read-only, and needs to have permission set to also include write permission too. Use notepad to edit the file. For me to send a file would have no effect as it can't be overwritten or edited as long as it has write permission off.
https://www.google.com/search?q=windows+write+permission

**Comment by jtanx** [comment]
should be fixed.
