### ISSUE TITLE
font windows not visible on Windows 10

### ISSUE THREAD

**Issue by uswd64** [fontforge/fontforge#3383]
Hi,

I've installed the latest Windows version on Windows 10 Pro 64-bit version 1803. Running on an AMD Ryzen Threadripper 1950X and NVidia Quadro P2000 graphics card.
After launching Fontforge and opening a font the font windows disappears on the upper right side. No chance to grab the window and reposition it. Tried to specify exact resolution in the ".Xdefaults" but didn't help.

Any help appreciated.

Best regards,
Ulrich

**Comment by jtanx** [comment]
What's your screen setup like?

Perhaps a gdk build would work https://ci.appveyor.com/project/fontforge/fontforge/builds/21129916/artifacts

**Comment by uswd64** [comment]
I have two monitors, one with 2560×1440 and one with 1920×1080 ppi and 32 bpp.
And I've tried the gdk build which seems to work. Does this unofficial build have the same features?
Thank you for your help.

**Comment by jtanx** [comment]
Yeah the issue is probably because of the multi-monitor setup, which breaks vcxsrv / the X11 backend.

The prod build would probably work if you disconnected one of the monitors.

Feature-wise, the CI GDK build is near the same as standard prod releases. The only thing missing from CI builds is unicode path support for files.
