### ISSUE TITLE
Resset / change unicode char in private area /PUA to default (glyphs character) in font info

### ISSUE THREAD

**Issue by javapep** [fontforge/fontforge#3406]
**Resset / change unicode char in private area /PUA to default (glyphs character) in font info**

Hi, folks, I have the problem with Unicode char in pua for alternate glyphs, I don't know how to fix it. How to reset to default Unicode char in glyph info. I'm placing the glyph in private area for OpenType features, coz if I generate the font this Unicode chart change to forming my own glyph and can't to back default again. Than if i open new page this Unicode chart still all ready not back to default. i attached the problem.

1.This my own glyphs...and all Unicode char forming like my own glyphs.
2.This unicode char that change like my own glyphs.
3.This default unicode char.... The problem is all unicode char can't to setting to default again

Thanks you in advance

![deepinscreenshot_select-area_20190108104647](https://user-images.githubusercontent.com/37425641/51005070-f35ca900-156f-11e9-83c8-1952b1accd18.png)
![deepinscreenshot_select-area_20190108213530](https://user-images.githubusercontent.com/37425641/51005371-176cba00-1571-11e9-9da9-6aa9241e4d3a.png)
![deepinscreenshot_select-area_20190108213614](https://user-images.githubusercontent.com/37425641/51005373-18055080-1571-11e9-85a9-d285b539e162.png)

**Comment by skef** [comment]
Having read through your description, I am not quite sure what problem you face, and whether it is more of a bug in the software or a question about normal practice. So I'll make a few suggestions from both perspectives. 

The most common practice for alternate glyphs, at least in FontForge, is to give them unique names but assign all of them "-1" as a unicode value. This is equivalent to each not having any associated unicode slot. Only the standard or "default" glyphs should have their associated unicode values in the font. Alternates are then substituted by name, not unicode value, in GSUB lookup tables, which can be accessed in FontForge from the `Lookups` section of the `Element->Font Info` dialog, or the "Substitutions`, `Mult Subs`, and `Ligatures` section of the dialog in your screenshots. You can read more about OpenType and FontForge substitutions here: http://fontforge.github.io/en-US/documentation/interface/lookups/

If this does not solve your problem, it would be helpful if you could update this issue with a description of a specific sequence of steps that reproduce your problem in FontForge. Whether your issue is related to a software bug or a misunderstanding of how FontForge is intended to work, that more detailed description would likely clarify your problem.

**Comment by sidanandibaue-gif** [comment]
PUA no Unicode significa "Private Use Area" (Área de Uso Privado) .
 
- Definição: É um intervalo de pontos de código que, por definição, não terão caracteres atribuídos pelo padrão Unicode .
- Finalidade: As PUAs são intencionalmente deixadas indefinidas para que terceiros possam atribuir seus próprios caracteres sem entrar em conflito com as atribuições do Consórcio Unicode .
- Utilização:
- Permitem que indivíduos e organizações definam caracteres personalizados, como fabricantes de equipamentos, grupos de usuários, órgãos governamentais ou editores de fontes .
- Possibilitam a criação de nomes e outras palavras usando caracteres que não estão disponíveis em fontes de tela e impressora padrão .
- Intervalos: Existem três áreas de uso privado definidas no Unicode: 
- BMP (Plano Multilíngue Básico): U+E000–U+F8FF
- Plano 15: U+F0000–U+FFFFD e U+100000–U+10FFFD
- Plano 16: U+F0000–U+FFFFD e U+100000–U+10FFFD
- Acordos Privados: O uso compartilhado da PUA deve ser definido por "acordo privado", pois diferentes indivíduos ou organizações podem definir os mesmos pontos de código. Os usuários de caracteres implementados na PUA devem ter um entendimento comum dos caracteres e seus pontos de código .
- Fontes: Para exibir corretamente os caracteres PUA, é necessário ter a fonte apropriada instalada .
