### ISSUE TITLE
When I try to move a point or a control point it keeps moving plenty of others!

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3419]
This issue makes it near impossible to make "a" character!

Video: https://www.dropbox.com/s/2gzpynctmq6kfcs/2019_01_20_18_08_34_1364x768.avi?dl=0

**Comment by skef** [comment]
FontForge includes tools for directly drawing quadratic Bezier curves, but it is not normally used that way. In fact it is used that way rarely enough that I cannot find a handy tutorial on the quadratic mode in the documentation. 

In your video you are using FontForge in Quadratic mode (note the "Q"s in the layer box on the lower-left). Some of the behavior you are seeing is inherent to Quadratic curves and the constraints you have chosen, and some has to do with FontForge's choices about which points to leave selected when. (A selected point is shown as a yellow outline circle.) 

Before getting into those details, though, is there a specific reason you are drawing quadratic curves directly, or is this just where you "wound up" in trying to use FontForge? Because if there is not a specific reason it would be better to first work out what you are trying to accomplish and how to use FontForge to accomplish that.

**Comment by PiotrGrochowski** [comment]
If I were to make the font cubic it would be distorted after conversion to truetype, which is naturally because of the limited resolution.

**Comment by yg8ijvjvjv** [comment]
I am a TrueType font designer so I exclusively work in quadratic outlines.

**Comment by yg8ijvjvjv** [comment]
"Which other control (off-curve) points move when you drag one depends on:

    How the control points are "constrained" (tied to one another), and
    Which control points are selected.
"

I don't think that should be the case, I believe that in TrueType, each point (including off-curve points, excluding interpolated points) should be able to select and move independently. See the [proof of concept](https://github.com/fontforge/fontforge/pull/4457#issuecomment-772424288) to see how such independence would work.
