### ISSUE TITLE
SVG icon causes FontForge to crash NaN value in spline creation

### ISSUE THREAD

**Issue by robmadole** [fontforge/fontforge#3425]
FontForge version: `fontforge 12:31 UTC  3-Oct-2018, libfontforge 20181003`

### To reproduce:

1. Open FontForge
1. Open the "A" glyph by double-clicking
1. Choose "File" "Import"
1. Choose the `hand-middle-finger.svg` [attached here and yes, we see the irony too](https://github.com/fontforge/fontforge/files/2798081/hand-middle-finger.svg.zip)

### Result:

FontForge crashes (segfault I believe)

We also see this in our Python-based script:

```
Internal Error: NaN value in spline creation
Internal Error: No Solution
```

This SVG file has gone through some cleaning procedures as we prepare it for our build step as part of creating a new release of Font Awesome. We know it has to be something related to that but the root cause is hard for us to determine.

We can get around this issue by using the un-altered / un-cleaned up version. FontForge has no problem with that one.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
The problem occurs in `svg.c:SVGTraceArc()` in this code:
```
        factor = rx*rx*ry*ry - rx*rx*y1p*y1p - ry*ry*x1p*x1p;
        if ( RealNear(factor,0))
            factor = 0;         /* Avoid rounding errors that lead to small negative values */
        else
            factor = sqrt(factor/(rx*rx*y1p*y1p+ry*ry*x1p*x1p));
        if ( large_arc==sweep )
            factor = -factor;
```
`rx*rx*ry*ry - rx*rx*y1p*y1p - ry*ry*x1p*x1p` winds up being -1.4901161193847656e-08. When compiled with `USE_DOUBLE` the `RealNear(a,0)` test is `return( a>-1e-8 && a<1e-8 );`, which is therefore false. That leaves factor as a small negative value after all, and `factor/(rx*rx*y1p*y1p+ry*ry*x1p*x1p)` as -3.6379650510233617e-16. The square root of that is NAN, which then propagates through various calculations and ends up (for complicated reasons) here:
```
0x00007ffff74fc605 in AddEdge (es=0x7fffffffac70, sp=0x5555558a18b0, tmin=0, tmax=1) at splinefill.c:254
254         if ( es->edges[mpos]==NULL || e->o_cur<es->edges[mpos]->o_cur ||
```
with `mpos` as -2147483648. 

Balancing cutoffs like `RealNear()` is tricky, domain-specific, and beyond my current experience level. The code in question is very old, all dating from 2001-2003. (@frank-trampe adds a higher cutoff for `float` in 2014, but that isn't at issue with the default compilation flags.)

This particular problem could be fixed by dividing factor by ten before calling `RealNear()`, or by adjusting the cutoff in that function. I'll leave it to more experienced hands to decide on a general solution.

**Comment by skef** [comment]
A comment in `SVGTraceARC()` indicates it is an implementation of section [F.6.5](https://www.w3.org/TR/SVG11/implnote.html#ArcConversionEndpointToCenter) of the SVG 1.1 spec. That corresponds to section [B.2.4](https://www.w3.org/TR/SVG2/implnote.html#ArcConversionEndpointToCenter) of the SVG 2 spec, but from a quick skim I don't see any substantial differences. 

There is a healthy amount of advice in these appendices, though, and they aren't very long. I'll take a look later and see if one offers a principled answer to the cutoff problem.
