### ISSUE TITLE
Web server in collab mode?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3431]
Since we're discussing removing possibly deprecated elements (#3399), I'd like to ask about this feature.

What does it do? Has it ever worked? Who came up with this? Does anyone actually use it? 

For me it doesn't work: (Arch Linux, x64)

```
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/share/fontforge/nodejs/collabwebview/server.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
```

Even if it did I'm dubious about its utility or applicability to the current code base. Most probably it should be removed.

**Comment by ctrlcctrlv** [comment]
@skef Thank you, I was having trouble finding that. 

I think it should be removed from the default installation, but it could be a cool plugin. It doesn't seem to be maintained and is currently broken (for me, most probably for you too).

**Comment by skef** [comment]
It's a little tricky because the code isn't limited to added files. There is a compilation flag and a bunch of hooks in the main code. I've been leaning towards:

1. Ensuring that the contrib and nodejs directories don't install unless the support is compiled in (if this isn't already true) and
2. Warning that it has not been updated and maintained and may not work on many systems. 

Longer term it would be best if more of the implementation were pushed one level out. Currently the transport and addressing and such intrude into the code. It would be better if there were python hooks for sending and receiving "collaboration messages" as changes occur with the transport logic living on the python side. That way:

1. There would be no compilation flags or added libraries for the executable itself.
2. Interested parties (if any) could experiment with different collaboration arrangements without being tied to a single messaging system. 

One could also potentially "collaborate" with a script, opening up new potentially interesting scripting possibilities, such as help functions that demo operations for you. 

However, this would be a bit of work.

**Comment by skef** [comment]
This was removed.
