### ISSUE TITLE
overlap-removal fails for this shape

### ISSUE THREAD

**Issue by daT4v1s** [fontforge/fontforge#3454]
### When reporting a bug/issue:
- [x] Screenshot
- [ x] The FontForge version and the operating system you're using
2019-01jan-15 build ubuntu 18.04LTS
- [ ] The behavior you expect to see, and the actual behavior

![screenshot from 2019-02-07 06-56-55](https://user-images.githubusercontent.com/47403824/52410500-853fcf00-2aa6-11e9-8e43-2eec18133b62.png)
![screenshot from 2019-02-07 06-56-26](https://user-images.githubusercontent.com/47403824/52410505-8a048300-2aa6-11e9-912d-1fe5606edc1c.png)

[overlap.zip](https://github.com/fontforge/fontforge/files/2840675/overlap.zip)

**Comment by skef** [comment]
The marker for the first point in the lower contour indicates it is clockwise. This is the expected behavior for overlapping shapes of differing directions. Please read https://fontforge.github.io/editexample2.html#Creating-o , and please familiarize yourself with the tool a more before filing issues at a high rate.

**Comment by daT4v1s** [comment]
one of the reasons also for the surge in the number of issues was that i was testing a profiled PGO build of fontforge on linux and wondered it it would make the programs faster, in the process of doing that was trying a lot features and the program ended spitting out a lot of quirks and spammy dialogs in the process..
