### ISSUE TITLE
What are those extra settings in "Simplify More"?

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3486]
"Allow curve smoothing
<small>if tan less than 0.2</small>"

"Snap to horizontal/vertical"

"Flatten bumps on lines
<small>if smaller than 20.5 em-units</small>"

All of those settings are blocked no matter what else I select in Simplify More. Are those just dummy settings to make people think there's more to this tool?

**Comment by daT4v1s** [comment]
It you are editing in quadratic instead of cubic, less options are available

**Comment by ctrlcctrlv** [comment]
To expand on @daT4v1s's astute observation, FontForge layers have two possible modes in regards to nodes, cubic and quadratic, marked in the GUI as "Q" or "C".

As far as I know, in the wider typography world and in the latest OpenType standards, "Q" style curves, which are actually TTF curves, are deprecated in favor of CFF curves, OpenType curves. More info about this is available [from Linotype](https://www.linotype.com/8120/the-difference-between-cff-and-ttf.html) [and Typekit](https://blog.typekit.com/2010/12/02/the-benefits-of-opentypecff-over-truetype/).

Luckily the two formats can be converted between easily. In FontForge, just right click on any quadratic layer and click "Make Cubic" to get all the options back.

Also, FontForge will automatically create quadratic splines when you export to TTF, so as far as I know, there's no reason to use quadratic layers at all (unless you prefer to edit them, but few graphic designers these days would since they've fallen out of fashion in gfx software).

**Comment by skef** [comment]
He's on record as having none of that:

> If I were to make the font cubic it would be distorted after conversion to truetype, which is naturally because of the limited resolution.

_Originally posted by @PiotrGrochowski in https://github.com/fontforge/fontforge/issues/3419#issuecomment-455893652_

*\*sigh\** Remember when this project was pre-Peak Piotr?

**Comment by jtanx** [comment]
Never mind, I already banned him a while back.

**Comment by yg8ijvjvjv** [comment]
Do you have any respect of TrueType font designers?
