### ISSUE TITLE
Shift JIS and CP932 have incorrect encodings.

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3496]
Examples:

Microsoft Windows:
0x8160 → U+FF5E FULLWIDTH TILDE
0x817C → U+FF0D FULLWIDTH HYPHEN-MINUS

FontForge:
0x8160 → U+301C WAVE DASH
0x817C → U+2212 MINUS SIGN

This is heavily detrimental to the compatibility.

I wonder where did you take those conversions. Did you convert each character manually to Unicode, or did you take Unicode values from some random buggy Linux implementation? Microsoft-932 should match exactly what Microsoft Windows gives for this codepage, obviously.

**Comment by ctrlcctrlv** [comment]
>Did you convert each character manually to Unicode, or did you take Unicode values from some random buggy Linux implementation?

Instead of assuming malice and/or incompetence, how about actually looking at the code&hellip;

Most of the Unicode conversions are determined by the official files posted for this purpose by the Unicode consortium, to wit:

https://github.com/fontforge/fontforge/tree/master/Unicode

Some conversions, such as the one you're talking about, are decided by iconv:

https://github.com/bnoordhuis/libiconv/blob/5124dedfeb6c6f138c2d08d1d3abdc2eda240e0e/lib/cp932.h

Since the iconv developers have been at this much longer than me, I'm going to assume their conversions are correct and you're trolling as usual.

**Comment by skef** [comment]
FontForge's current behavior matches the Unicode 932 spec:

http://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT

The  general issue seems to be a matter of (mild) controversy:

https://lists.gnu.org/archive/html/bug-gnu-libiconv/2016-12/msg00010.html 

But shifting the developers here away from Unicode's documentation toward some other standard would likely require extraordinary evidence.

**Comment by PiotrGrochowski** [comment]
> you're trolling as usual.

WAIT FOR A MOD TO BAN YOU FOR PROFANITY!!!!! :(

**Comment by PiotrGrochowski** [comment]
> FontForge's current behavior matches the Unicode 932 spec:
> 
> http://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT

I've read that text file and the two characters mentioned at the top post seem to match Microsoft Windows's behavior, not FontForge's behavior.

**Comment by skef** [comment]
Oh, sure enough. That would be one point in favor of changing then. 

This would be a picky change given that it's apparently a supporting library, rather than FontForge code, that does the mapping at present. I myself wouldn't start down the road to making the change without more evidence of this being a real problem for people, and not just something reported for the sake of reporting it.

**Comment by PiotrGrochowski** [comment]
It does make it more difficult to create actual fonts that include all the characters of ShiftJIS/CP932/CP942, because FontForge's built-in ShiftJIS and CP932 encodings have many characters tentatively incorrect.

**Comment by skef** [comment]
The discussion in ashtuchkin/iconv-lite#145, if I'm reading it right, suggests that FontForge's current practice matches a Japanese standard and the alternative is something 90's Microsoft decided to do.

**Comment by skef** [comment]
The situation is ambiguous at best, and FontForge's practice follows at least one of the relevant standards.
