### ISSUE TITLE
Consider making GDK the default backend

### ISSUE THREAD

**Issue by khaledhosny** [fontforge/fontforge#3541]
After the release GDK (3?) should be made the default backend and probably consider deprecating and eventually removing the raw X backend. GDK should work anywhere X is supported, so there should be no loss of functionally, and we have two major OSs where GDK is preferable to X.

**Comment by frank-trampe** [comment]
We certainly ought to do this on Windows and Macintosh, as it will offer immediate and almost unqualified improvements. I'm inclined to wait on Linux, as X11 works very well there and even a slight miss would represent a regression. Thoughts from @jtanx?

**Comment by jtanx** [comment]
Yeah, sounds reasonable to me to leave it for a bit while more people actually use it, then reevaluate at that point.

**Comment by skef** [comment]
I read @khaledhosny as suggesting this for the subsequent release ("After the release..."). So one cycle could be used to collect and fix GDK bugs on Mac and Windows and then Linux would be switched over.

**Comment by frank-trampe** [comment]
I would like to implement this suggestion sooner than the next release for Macintosh and Windows and later than the next release for Linux. We added UFO support to FontForge many years ago, and we're still fixing bugs. The graphical interface is no simpler than the UFO mechanisms.

**Comment by skef** [comment]
Oh, I think the decision to send out Mac and Windows with GDK by default has been in place in the build infrastructure for a while. 

There are approaches to fixes and improvements that can be taken with GDK that would be difficult or untenable with GXDraw. The longer the latter is a requirement the less that can be done in those areas. I think that's the concern.

**Comment by frank-trampe** [comment]
Yes on the Macintosh and Windows thing. But we're doing so only because the status quo is so bad. I'm willing to pull the trigger on Linux whenever we meet a reasonable non-regression standard across the whole product. I just think that it's important to be realistic about the time required to mature such a complicated feature in such a complicated product.

**Comment by ctrlcctrlv** [comment]
Just my 2&cent;, the FontForge I compile to make my fonts on Arch Linux is with the GDK backend...the X11 backend has a good reason to be deprecated on Linux, and that is because it doesn't detect DPI settings as well as GDK - everything is too small.

Why use GDK on two platforms and X11 on another? It makes Linux inferior and requires us to do needless debugging of every issue ("Does this happen in GDK/X11?")

**Comment by khaledhosny** [comment]
GDK also supports Wayland, and Wayland is the default for Gnome for a while now, so there is a portion of Linux users that would immediately benefit from from a default GDK backend.

**Comment by jtanx** [comment]
The last time I checked, wayland support is super broken, because the gnome compositor doesn't provide window decorations, so it's near on impossible to use as-is.

**Comment by khaledhosny** [comment]
I see.

**Comment by frank-trampe** [comment]
@ctrlcctrlv, now that you're using GDK FontForge on Linux, we might have enough test data after a month or two to make the switch. Please keep us apprised.

**Comment by ctrlcctrlv** [comment]
Why was this closed? Please reopen it.

**Comment by skef** [comment]
In practice this plan is complicated by the noises @jtanx has been making about moving onto GTK. If that happens it would probably call for another extended try-out cycle.

**Comment by ctrlcctrlv** [comment]
Even if it's going to be delayed this should remain open. There's no reason to remove it from the agenda entirely, is there?
