### ISSUE TITLE
Script tag bugs in tottfgpos.c

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3559]
The array `scripts` in tottfgpos.c is outdated. It is missing recently encoded scripts like Chakma and Javanese. It is also missing recently encoded code points for older scripts, like U+18B0 CANADIAN SYLLABICS OY.

It conflates blocks with scripts. For example, U+03E2 COPTIC CAPITAL LETTER SHEI is in the block Greek and Coptic, but it is Coptic, not Greek.

It conflates ISO 15924 codes with OpenType script tags. For example, although Cirth has an ISO 15924 code, it has no OpenType script tag, so 'cirt' does not belong in the table.

'aram' for Imperial Aramaic should be 'armi'

The function `ScriptFromUnicode` can convert old Indic tags to new Indic tags, but it omits 'mymr' → 'mym2'.

The function `ScriptIsRightToLeft` is missing newly encoded scripts. [Here are all the RTL scripts in Unicode.](https://www.unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B%3ABidi_Class%3DAL%3A%5D%5B%3ABidi_Class%3DR%3A%5D-%5B%3AZyyy%3A%5D-%5B%3AZzzz%3A%5D&abb=on&g=sc) Note that directionality is not entirely determined by script, so if anything uses this function to determine the directionality of a specific code point, that is wrong.

**Comment by JoesCat** [comment]
It's not outdated, it is just that https://github.com/fontforge/fontforge/blob/master/Unicode/makeutype.c :65 was limited to only work with characters 0...65535 (BMP) range of characters.
```code
define MAXC	65536
```
FontForge was created at a time when most computer users had limited RAM compared to today's computers. At the moment, we left it at 65536 (0..0xffff) since there are a couple of comments about makeutype.c that suggest we need to look at this a bit more carefully for the higher values.
is_Ligatures_data.h is one of the first subsets that extend the full unicode range, and we'll need to investigate the makeutype.c code a bit further before extending this the full range.
...it's a work in progress ATM.

**Comment by dscorbett** [comment]
None of that is related to this bug report. Most of the examples I gave apply to the BMP, and tottfgpos.c already supports non-BMP code points anyway.

**Comment by skef** [comment]
@dscorbett I know some of FontForge's infrastructure is designed to pull Unicode information from other libraries or to be easily reconfigured from Unicode Consortium sources. This stuff looks more hardcoded at present. Is FontForge's split typical, so it makes the most sense to just go in and make the data current? Or do other projects handle this particular data differently/better?

**Comment by dscorbett** [comment]
I wouldn’t know what is typical, but it makes sense to hard-code as little as possible. HarfBuzz, for example, generates some of its tables with Python scripts using files from Unicode and the OpenType spec as inputs. The OpenType data tends to not to be machine-readable, unfortunately, so most of that data probably needs to be hard-coded.

**Comment by skef** [comment]
OK. Unfortunately I may not know enough to pick out all the relevant info, but I'll see if it can at least be moved into its own header file, and try to make it current.

**Comment by skef** [comment]
On the ISO 15924 stuff: Let's grant it doesn't really belong where it is -- what are the chances that removing it would cause people problems? Who knows enough about this stuff to balance the standards against the real world, and judge what is a mistake and what is embedded knowledge? (That person is very much not me.)

**Comment by dscorbett** [comment]
I think the chance of a problem is low. Nothing should be relying on the existence of tags like 'cirt': real-world shapers don’t interpret them, so fonts probably don’t use them.

**Comment by skef** [comment]
Good!

**Comment by skef** [comment]
@dscorbett I've taken a look and we should confer a bit more. I may have more questions about the properties like right-to-left later, but this is about the script array. 

Conceptually, the intent of that array seems to be to represent the contents of http://www.unicode.org/Public/12.0.0/ucd/Scripts.txt , but indexed through the four character string from the `sc` entries in https://www.unicode.org/Public/12.0.0/ucd/PropertyValueAliases.txt (except lower case). 

However, there are way, way more ranges in Scripts.txt -- probably too many to use like this. So instead we might think of a table similar to the one in Scripts, except whenever a range for a given script is separated by a "Common" range all three are collapsed into a range for that script. That might be tractable and probably comes close to the block structure. Maybe some key ranges could then be removed to improve (for example) the lower-seven-bit situation. 

I haven't written anything to do this but it should be easy. However, there's also this list and the note: https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags . There's (unsurprisingly) no "Tamil v.2" in Unicode. So:

1. Does the basic Scripts.txt strategy sound at least roughly correct?
2. It's probably the OpenType rather than Unicode script strings that are relevant here, right? And if so does that call the first strategy into question? If there's one Unicode Tamil, how does one decide between `taml` and `tml2`?

**Comment by skef** [comment]
There's also this https://github.com/twardoch/feaLab/blob/master/Lib/feaLab/hb_scripts3.py https://github.com/fonttools/fonttools/issues/1112

**Comment by skef** [comment]
And this: https://github.com/fonttools/fonttools/pull/1150

I guess I can just grab the current map and combine it with the unicode file automation and that would be 90% of the problem.

**Comment by dscorbett** [comment]
1. What all is `scripts` for? That basic Scripts.txt strategy is not correct; depending on how FontForge uses `scripts`, this may or may not matter. Unicode [recommends](https://www.unicode.org/versions/Unicode12.0.0/ch05.pdf#G7642) using multistage tables to store character properties efficiently.
2. Since the first element in each element of `scripts` is an OpenType script tag, I agree that they are more relevant than Unicode script values. For cases like 'taml' and 'tml2' I recommend doing what tottfgpos.c currently does: store one of them in the table and write a function that optionally converts to the other based on a flag.

The OpenType script tags 'byzm', 'math', and 'musc' correspond to Unicode blocks, not Unicode scripts, and will require special handling when automating this.

**Comment by skef** [comment]
> That basic Scripts.txt strategy is not correct; depending on how FontForge uses scripts, this may or may not matter. 

I guess this is the question. If you look at the current `latn` entry it doesn't even come close to covering all the Latin Unicode script ranges. 

If the goal is to really know the script that corresponds to every Unicode character in a time and space efficient way it might be best to extend `libuninameslist` with a function to report it and do the "work" there. Then the existing table to could be remain for users who aren't able or willing to compile that library. *Is* that the goal?

**Comment by skef** [comment]
@JoesCat Suppose FontForge needed a few more bits of info on this or that unicode character. Is it viable to add a few functions to `libuninameslist` for such purposes? Assuming someone is willing to do the work, of course, including coding up the extraction from the Unicode Consortium files. Would that raise questions about what is intended to be a "minimal" interface or something?

**Comment by skef** [comment]
I'm afraid that doing this right would require doing things rather differently, and I have no way of establishing a design in advance that I can be confident will end up accepted. So I'm not going to look at this further for the time being.

**Comment by JoesCat** [comment]
One of the unix philosophies is to break things down into small tasks, and in this case libuninameslist has basically one task, and does it well. I think leaving it alone to do this one task is best, otherwise we end up taping and strapping on all sorts of oddities and widgets like we have happening in FontForge.
We should avoid turning libuninameslist into another complicated FontForge mishmash.

I would also avoid putting user functions in python or other languages to access from FontForge.
One of the complaints I often read is "can you make it go faster?" ...and that won't happen that way.
If you are looking at scripts to build FontForge *.c, that is fine, that is a one-time run during upgrading.

What you can take away from looking at and learning about libuninameslist is the breakdown of tables into pages as a quick form of compression, because if you look at the unicode chart, there is a "lot" of empty space. Another form of compression I like, I found in *.fzx, and you can see bits of this sort of method added into is_Ligatures data and also in some of the makeutypes.c reference tables.
For best compression, I think the way to go is a cross between libuninameslist pages, and *.fzx tables, so that we can use variable sized tabling to merge in the unialt tables this way, but this is a very big project to do, because the utype.c tables are referenced everywhere.

Looking at the Unicode directory, there are something like 5 programs of interest, and probably some stuff that got lost, deleted, or never was included in the past, and this is the hard part that leaves you thinking, we really got to automate this because doing it by hand is a big chore, plus very prone to errors doing stuff manually.

The programs of interest are 1=makeutype.c, 2=makebuildtables.c, 3+4+5=charset/generate.sh, charset/gen-charset.pl, dump.c. I clump 3+4+5 together because there were advantages created with 3+4, and stuff lost from 2+5.
The way I attack this problem, first build 1=makeutype.c and resulting code. Then deal with 2,3,4,5 as a bit of group effort so that collectively for optimum results. tagpoint 20120731 is your reference goto guide before things started changing a lot. I would also suggest looking at patches for Unicode 8, 9, 11 to help catch additional points you might miss.
In terms of hitting the hardcoded stuff, you will probably want to grep a couple of key words that you would likely find in the BMP area. Since greek has a lot of customization, I start with that, then you can also grep johab or hangul to get more. This where you'll start finding all sorts of hard coded tables in various directories.
Sounds like a lot? It is.
Thoughts?
Yes.
Build the various tables using the 5 programs mentioned, then splice in your tables afterwards.
Probably a nice example might be to look at Unicode/makebuildtables.c to build gdrawbuildchars.c
Before Unicode9, this was a chore to make, but then for unicode11, I automated this file, and building this file is fairly easy and quick now.
https://github.com/fontforge/fontforge/commits/master/gdraw/gdrawbuildchars.c

My suggestion is look at the 5 programs in Unicode directory and see which is best adaptable to "automate" building the table you are interested in.

Warning: makeutype.c is not fully debugged and has warnings about making anything higher than BMP, so you'll notice ligatures is done before entering the other part that stops at MAXC
I've also run into problems with the way numbers are filtered/stripped, and believe this makeutype.c needs to be fixed. I found this problem while looking at trying to improve mirror(). This may be a good spot to learn more about makeutype.c if you're interested in mirror() further (like ligatures).

**Comment by skef** [comment]
Alright, but this is 

1. A whole lot of very specific advice, 
2. From one project member
3. Who project members might not wind up agreeing with, and
4. Who isn't offering to do the work him or herself. 

So even if I followed it close to the letter that's no guarantee it would be accepted at the end. So I'm not going to look at this further.
