### ISSUE TITLE
Losing focus when typing in glyph editor input field

### ISSUE THREAD

**Issue by tisimst** [fontforge/fontforge#3598]
One spectacular feature is being able to see glyphs next to the one you're editing in the Outline Glyph Editor window, which I've been able to easily type into in the latest public release. Such a good feature!

However, in a recent dev build (which I'll show specifically below), after I mouse-click into the input field above the glyph outline editor pane, it immediately loses focus and I can't type anything at all. The only thing I've gotten to work is by pressing + holding the mouse button and typing. However, this only allows me to input one character at a time. Arduous, but still (kind of) usable. The problem always occurs, regardless of the glyph & font being edited.

OS: Windows 8 & 10.

Here's the input field I'm talking about:
![glyph-outline-editor-input-field-problem](https://user-images.githubusercontent.com/2730119/55184214-3681ed80-5157-11e9-98a4-52cc27f68d57.png)

Here's the good version of FF:
![ff-good-version](https://user-images.githubusercontent.com/2730119/55184246-4a2d5400-5157-11e9-8f94-27a57fea5f77.png)

Here's the bad version of FF that doesn't allow typing:
![ff-bad-version](https://user-images.githubusercontent.com/2730119/55184251-4d284480-5157-11e9-8f01-7b9eb87bcd32.png)

**Comment by skef** [comment]
I can reproduce this. 

There's probably an easy GGDKDraw fix, but I think it's worth mentioning here that this feature has a number of other interface problems, with the one currently documented best described in #3192. When I looked into fixing that there wasn't any obvious way to.

My conclusion was that it it would be preferable for a number of reasons to put two separate text fields before and after the glyph name below the menu, and let users type the text of what should appear before and after the glyph into those. Then I would lean towards making the glyph name itself just a label rather than a field, and have users navigate between glyphs in the normal way. The current system just doesn't have clear semantics in cases like a name change. 

Separate fields wouldn't be a burden and would make the implementation much more straightforward. If there was agreement on this approach I would be willing to give implementing it a shot.

**Comment by tisimst** [comment]
I *could* live with separate fields, but having the ability to toggle between the displayed glyphs in the outline editor is exceedingly helpful. In other words, I use it for more than simply seeing how the current glyph looks around others, but rather toggling between them and editing any of them at-will. Would having separate fields disallow this functionality?

**Comment by skef** [comment]
>  Would having separate fields disallow this functionality?

Not if there are three of them, but that *would* be klunkier.

**Comment by skef** [comment]
An alternative would be to have the brackets function as actual delineators, which based on my experimentation before they just don't. For that to work you would need there to be exactly one of each, in the right order, at all times, and to be able to type before, between, and after them. (Probably be good to embolden them as well.)

Getting text fields to behave in ways like that is tricky, with a lot of corner cases. (Which is probably why the interface looks like it's supposed to work that way, but doesn't.)

**Comment by ctrlcctrlv** [comment]
I have this problem too. I have a solution too, although a hacky one. Hold down your left mouse button, then type your letter. You can also make a string outside of FontForge, e.g. in a terminal or some text editor, then put this string in your X clipboard (`xsel -b` perhaps), then paste it in while holding down the left mouse button.

A pain indeed, but I thought I was alone in it.

**Comment by ctrlcctrlv** [comment]
Hello friends:

I feel my workaround was poorly described in text, so I made a video to try to help. The keystrokes are displayed on screen by a program I wrote called [QKOS](https://github.com/ctrlcctrlv/QKeysOnScreen/).

[CharView String Demo.zip](https://github.com/fontforge/fontforge/files/3021839/CharView.String.Demo.zip)

I hope this clarifies not only the bug, but indeed also the workaround! If you understood me the first time, feel free to ignore this.

**Comment by jtanx** [comment]
I'm so glad I added the logging into ggdkdraw.

Turning up logging (`GGDKDRAW_LOGLEVEL=all`), it was suspicious that windows were being destroyed and created each time that field was focused. Turned out it was because of #3398.

Adding a check to not recreate the windows if the charview hasn't changed seems sufficient to fix this.

**Comment by tisimst** [comment]
Thank you!!!!!!!!!!!!!!!! Works just as expected!
