### ISSUE TITLE
COMBINING CEDILLA (U+0327) not considered by "Build Accented Glyph"

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3615]
Arch Linux, https://github.com/fontforge/fontforge/commit/3e641ec84d141d291aa75bd84897aee04bfe5428

FontForge prioritizes `comma` (,) over what I affectionately term `cedillacomb`, that is, COMBINING CEDILLA (U+0327), ◌̧ .

In fact, `cedillacomb` seemingly isn't considered at all.

Not sure how to fix this, but will look into it.

Edit: Seems like there are some data files used by `SFIsSomethingBuildable` and `SCBuildComposit` I have to edit.

**Comment by ctrlcctrlv** [comment]
OK I found the problem. It's this bizarre function, SFGetAlternate. Including comments like:

https://github.com/fontforge/fontforge/blob/3e641ec84d141d291aa75bd84897aee04bfe5428/fontforge/fvcomposite.c#L1198

Is this really valid? To use George Williams' interpretation of the appearance of glyphs in a font over what the standard defines? I think most of this function should be gutted, but welcome comments from other esteemed contributors as always.

**Comment by JoesCat** [comment]
Might have been true for unicode 2 or 3. Charts get refined with time. Old errors out, new ones in.
I had to override an error in unicode 11.0 - Unicode/makeutype.c:798 - capital ß, and this is in 2018

It may be a case that some stuff got corrected and refined with time, so some code may indeed be removed and allow the unicode chart values to be the ones coming through instead.
You may want to gut this in small chunks instead of one big sweeping removal. The smaller chunks are easier to see, validate.

**Comment by ctrlcctrlv** [comment]
With the benefit of a good night's sleep, I think what I'll attempt is to write a PR which will add an option, "UnicodeSupremacy", to optionally bypass SFGetAlternate at first and perhaps other functions in the future.
