### ISSUE TITLE
⟦Spiro⟧ Glyphs with spiros are saved as cubic splines even in quadratic layers

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3670]
Arch Linux, 71cde27

This may be related to #3667 but I'm not sure. 

I made some files to prove this. Please download and peruse [SavingBug.zip](https://github.com/fontforge/fontforge/files/3099881/SavingBug.zip), else I fear this report will make no sense.

I drew two Spiro circles in two different files, using the &ldquo;Get Info&rdquo; dialog to make them exactly the same. All that's different is whether or not I drew them on a &ldquo;Q&rdquo; Quadratic layer or a &ldquo;C&rdquo; Cubic layer&mdash;`Quadratic.sfd` &amp; `Cubic.sfd`.

I then did the same, I drew two circles made of B&eacute;zier splines, only differing in their respective layer types&mdash;`QuadraticB.sfd` &amp; `CubicB.sfd`.

I then made two diffs&mdash;`SpiroDiff.diff` & `BézierDiff.diff`.

I really think the results speak for themselves. Drawing Spiros on quadratic layers is fundamentally broken, it saves in the cubic format. I think this is the root cause of #3667.

### SpiroDiff.diff
This is essentially a noop. _That's bad!_

```diff
diff --git a/Quadratic.sfd b/Cubic.sfd
index 8f70a41..d79a061 100644
--- a/Quadratic.sfd
+++ b/Cubic.sfd
@@ -14,13 +14,13 @@ Descent: 200
 InvalidEm: 0
 LayerCount: 2
 Layer: 0 0 "Back" 1
-Layer: 1 1 "Fore" 1
+Layer: 1 0 "Fore" 0
 XUID: [1021 575 -1819899406 628701]
 OS2Version: 0
 OS2_WeightWidthSlopeOnly: 0
 OS2_UseTypoMetrics: 1
 CreationTime: 1555747562
-ModificationTime: 1555747779
+ModificationTime: 1555747871
 OS2TypoAscent: 0
 OS2TypoAOffset: 1
 OS2TypoDescent: 0
@@ -50,6 +50,7 @@ Encoding: 79 79 0
 Width: 1000
 VWidth: 0
 InSpiro: 1
+Flags: HO
 LayerCount: 2
 Fore
 SplineSet
```

### BézierDiff.diff

They're actually saved in different formats depending on  their type. _That's good!_

```diff
diff --git a/QuadraticB.sfd b/CubicB.sfd
index e0ee6b8..6050776 100644
--- a/QuadraticB.sfd
+++ b/CubicB.sfd
@@ -14,13 +14,13 @@ Descent: 200
 InvalidEm: 0
 LayerCount: 2
 Layer: 0 0 "Back" 1
-Layer: 1 1 "Fore" 0
+Layer: 1 0 "Fore" 0
 XUID: [1021 575 -1819899406 9896654]
 OS2Version: 0
 OS2_WeightWidthSlopeOnly: 0
 OS2_UseTypoMetrics: 1
 CreationTime: 1555747893
-ModificationTime: 1555748292
+ModificationTime: 1555748270
 OS2TypoAscent: 0
 OS2TypoAOffset: 1
 OS2TypoDescent: 0
@@ -49,18 +49,15 @@ StartChar: Q
 Encoding: 81 81 0
 Width: 1000
 VWidth: 0
+Flags: HO
 LayerCount: 2
 Fore
 SplineSet
-400 700 m 128,-1,1
- 288 700 288 700 194 606 c 128,-1,2
- 100 512 100 512 100 400 c 128,-1,3
- 100 288 100 288 194 194 c 128,-1,4
- 288 100 288 100 400 100 c 128,-1,5
- 512 100 512 100 606 194 c 128,-1,6
- 700 288 700 288 700 400 c 128,-1,7
- 700 512 700 512 606 606 c 128,-1,0
- 512 700 512 700 400 700 c 128,-1,1
+400 700 m 0
+ 250 700 100 550 100 400 c 4
+ 100 250 250 100 400 100 c 0
+ 550 100 700 250 700 400 c 0
+ 700 550 550 700 400 700 c 0
 EndSplineSet
 EndChar
 EndChars
```

cc: @skef

**Comment by skef** [comment]
I think the most useful thing to note here is that things seem to work OK when switching between Spiro and Bezier splines in a CharView, whether in Cubic or Quadratic mode. So how does that work?

From `fontforgeexe/cvpalettes.c`:
```
static void SCCheckForSSToOptimize(SplineChar *sc, SplineSet *ss,int order2) {

    for ( ; ss!=NULL ; ss = ss->next ) {
        if ( ss->beziers_need_optimizer ) {
            SplineSetAddExtrema(sc,ss,ae_only_good,sc->parent->ascent+sc->parent->descent);
            ss->beziers_need_optimizer = false;
        }
        if ( order2 && ss->first->next!=NULL && !ss->first->next->order2 ) {
            SplineSet *temp = SSttfApprox(ss), foo;
            foo = *ss;
            ss->first = temp->first; ss->last = temp->last;
            temp->first = foo.first; temp->last = foo.last;
            SplinePointListFree(temp);
        }
    }
}

static void CVChangeSpiroMode(CharView *cv) {
    if ( hasspiro() ) {
        cv->b.sc->inspiro = !cv->b.sc->inspiro;
        cv->showing_tool = cvt_none;
        CVClearSel(cv);
        if ( !cv->b.sc->inspiro )
            SCCheckForSSToOptimize(cv->b.sc,cv->b.layerheads[cv->b.drawmode]->splines,
                    cv->b.layerheads[cv->b.drawmode]->order2);
        GDrawRequestExpose(cvtools,NULL,false);
        SCUpdateAll(cv->b.sc);
    } else
#ifdef _NO_LIBSPIRO
        ff_post_error(_("You may not use spiros"),_("This version of fontforge was not linked with the spiro library, so you may not use them."));
#else
        ff_post_error(_("You may not use spiros"),_("FontForge was unable to load libspiro, spiros are not available for use."));
#endif
}
```

`fontforge/spiro.c:SplineSet2SpriroCP()` works differently for cubic and quadratic input splines, as it should. `SpiroCP2SplineSet()` and `SSRegenerateFromSpiros()` don't. The former calls the latter right before returning; both are non-static and called from elsewhere in the code. So it seems to me that *approximately* what needs to happen is that the second bit of `SCCheckForSSToOptimize()` above needs to move into `SSRegenerateFromSpiros()`. That may or may not kill the performance -- it's hard to tell just from inspection. 

If it's too much of a performance problem, or if the optimizer stuff in `SSRegenerateFromSpiros()` really does need to happen first (quite possible!), then this is a more difficult problem, because the fix would involve detecting stray, unconverted cubic splines and converting them with something like `SSRegenerateFromSpiros()` when they *need* to be quadratic, which is basically when saving or exporting them in some sense. 

(From what I can tell, what the current code does is make and associate a cubic spline after every spiro edit (using `SSRegenerateFromSpiros()`) for the purpose of drawing the path itself. It doesn't need to be quadratic for just that purpose. But the saving code isn't smart enough to replace that temporary spline with a quadratic one.)
