### ISSUE TITLE
Wrong character positions in OTB font

### ISSUE THREAD

**Issue by joshuakraemer** [fontforge/fontforge#3692]
When I convert a BDF to an OTB font, the glyphs are wrongly positioned in the resulting OTB file. All glyphs seem to be shifted by 2 characters, e.g. glyph "A" is placed on character "C".

Fontforge version: 2019-04-15
Operating system: Void Linux

The attached zip file includes a sample BDF font and the OTB font generated from it:
[fonts.zip](https://github.com/fontforge/fontforge/files/3144517/fonts.zip)

**Comment by ctrlcctrlv** [comment]
I can confirm this on the latest commit https://github.com/fontforge/fontforge/commit/e99cc504beb6b7765d72d9f4698ae1b727031aaa on Arch&mdash;even FontForge doesn't understand the file it has generated correctly.

![Screenshot_20190505_154459](https://user-images.githubusercontent.com/838783/57190484-3abadb00-6f4d-11e9-996d-1adc5f336be8.png)
![Screenshot_20190505_155050](https://user-images.githubusercontent.com/838783/57190511-76ee3b80-6f4d-11e9-8171-bcc03eb2ee0e.png)

It seems to insert two extra space characters, which as @joshuakraemer wrote shifts everything by two (selected below).
![2otb](https://user-images.githubusercontent.com/838783/57190549-f1b75680-6f4d-11e9-9152-96535dc065ca.png)

Space (0x20) becomes a zero width space, exclamation mark (0x21) becomes a five pixel wide space, as does quotedbl, ", (0x22).

I was able to figure out the reason for you @joshuakraemer, but I agree that this is a bug. Your BDF font includes two characters, that, as far as I know, only have meaning in OpenType&hellip;perhaps because this BDF was itself converted from an OpenType, that's why they are there:

```bdf
STARTCHAR .null
ENCODING 0
SWIDTH 0 0
DWIDTH 0 0
BBX 1 1 0 0
BITMAP
00
ENDCHAR
STARTCHAR nonmarkingreturn
ENCODING 13
SWIDTH 333 0
DWIDTH 5 0
BBX 1 1 0 0
BITMAP
00
ENDCHAR
```

If I decrement `CHARS` by two to make 255, and delete `.null` and `nonmarkingreturn`, I get a correct OTB&mdash;[DVS2.otb.zip](https://github.com/fontforge/fontforge/files/3145263/DVS2.otb.zip): 

![corr](https://user-images.githubusercontent.com/838783/57190654-545d2200-6f4f-11e9-8586-28659b488dd2.png)

FontForge should be changed to handle this more gracefully, but I hope this helps for now.

**Comment by ctrlcctrlv** [comment]
My suspicion is that FontForge can't understand how to export an OTB font if it has glyphs &leq; 0x1F, so if there are any glyphs like that, it forces the minimum glyph encoding index to be 0x20. For now, you should delete glyphs with encodings inside the _C0 and C1 control codes_ block before exporting.

**Comment by joshuakraemer** [comment]
Thank you very much, this workaround (removing glyphs ≤ 0x1F) works.

It seems that FontForge has also problems with glyphs without a code point. The attached font (DejaVu.sfd) contains a glyph named "nonmarkingreturn" with code -1. If an OTB is generated from that file, it contains no glyphs at all. In another font (which I cannot attach because it is proprietary), the same glyph (name "nonmarkingreturn", code -1) is present. Here, the generated OTB font cannot even be opened with FontForge, it crashes with SIGSEGV.
[DejaVuSans.sfd.zip](https://github.com/fontforge/fontforge/files/3170300/DejaVuSans.sfd.zip)

**Comment by jtanx** [comment]
@joshuakraemer are you able to check if #3711 also fixes the segfault you experienced?

**Comment by joshuakraemer** [comment]
@jtanx, it works indeed, no segfault occurs any more. Thank you very much for your work!

**Comment by jtanx** [comment]
Nice, thanks for testing!
