### ISSUE TITLE
Blank window and no window border on archlinux

### ISSUE THREAD

**Issue by jilen** [fontforge/fontforge#3714]
Fontforge shows  blank area with no window border

![Screenshot from 2019-05-29 16-43-50](https://user-images.githubusercontent.com/546573/58543209-9c5f2400-8231-11e9-9928-769ced51fd05.png)

OS: Archlinux latest
Fontforge: fontforge 02:37 UTC 27-Apr-2019

**Comment by jtanx** [comment]
It looks like FF is build with the GDK backend by default, and you're likely using Wayland.

does this work?

```
export GDK_BACKEND=X11
fontforge
```

**Comment by jilen** [comment]
That's it! Thanks @jtanx

**Comment by ctrlcctrlv** [comment]
Is it possible to fix GDK on Wayland?

**Comment by jtanx** [comment]
I've mentioned this elsewhere, but not really, no, which is why I wanted to move the backend to be on top of GTK instead.

The reason being, how gnome have implemented mutter, it doesn't provide any server side decorations (SSDs) - the window title and border etc. You have to implement that client side (CSDs), which we're not doing (and won't be doing).

**Comment by liZe** [comment]
It's been discussed in [#2782](https://github.com/fontforge/fontforge/pull/2782#issuecomment-392513486).
