### ISSUE TITLE
Towards a replacement to the «Expand Stroke…» function

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3718]
I, and others, have reported many Expand Stroke bugs, which no one seems to know how to fix. (For example, #3694, #3264, #3242, #3240, etc.)

Expand Stroke bugs are rarely ever fixed. I hope @skef doesn't hope me quoting him in some private correspondence to help make my point:

> I'm wary of [Expand Stroke]. It seems like GW approached a lot of the tricker spline code by tinkering **rather than drawing on theory or established algorithms.** I stared at #3432 for a while (for example) after finding that non-termination condition and still don't have much of an idea of how the algorithm is supposed to work

@skef is much better at B&eacute;zier spline math than I am, so if he doesn't understand how GW's algorithms work, I stand no chance of doing so.

The function is also aging, and to think that we could extend it is dubious at best. For example, we might want to make it so that you could vary the width of points along the spline as is possible with the width tool in e.g. Illustrator or via multiple plugins (Letterink, etc) to Glyphs.app or in Inkscape via &laquo;[Power Stroke](https://graphicdesign.stackexchange.com/questions/117822/stroke-width-tool-equivalent-in-inkscape)&raquo;.

My questions are:
* What &ldquo;established algorithms&rdquo; would help the situation?
  * Perhaps [InkScape's](https://gitlab.com/inkscape/inkscape/blob/master/src/livarot/PathStroke.cpp), which seems very Robust? Perhaps [Noodler's](https://github.com/mekkablue/Noodler/blob/master/Noodler.glyphsFilter/Contents/Resources/plugin.py), used by Glyphs.app? Something else I'm not aware of?
* Is it even possible to replace the «Expand Stroke…» dialog wholesale? 
  * Obviously at first we'd want to have them side-by-side until we replicated all the functionality.

**Comment by skef** [comment]
Ideally a "stroke" would be a sequence of potentially joining Bezier segments, which may be lines or curves. The "y" in #3264 shows how it's not always that simple.  Anyway, the way this stuff works in general is that you take each segment and deal with it separately and then merge the results. The artifacts the common FontForge error refers to as "fragments" are, I believe, per-segment lines/curves entities (either segments or multi-segment paths -- I'm not sure). 

The general idea is to produce an [offset](https://pomax.github.io/bezierinfo/#offsetting) of each side of the stroke. It's provably impossible to produce the exact curves in the general case, but you pick a non-perfect degree of approximation to fall within. The most widely discussed and cited offsetting algorithm seems to be [Tiller-Hanson](https://ieeexplore.ieee.org/document/4055919) but [many other approaches](http://3map.snu.ac.kr/mskim/ftp/comparing.pdf) have also been developed.

Of course, the theory of offsetting on its own doesn't tell you how to implement a Calligraphic (rectangular) pen. I've glanced at GW's code enough to know that it's based on curve approximation rather than direct calculation. If I were asked this question in an interview, I would offer an algorithm like:

1. Iterate through points on the segment at some interval
2. For each point `x` calculate the normal angle `a` at that point.
3. Call `d = dist(a)` to get a configurable distance away from the point based on the angle. (This is where Circular/Calligraphic/Polygon come in. The angle at the point gives the distance away.) 
4. Use `a` and `d` to calculate an offset point `nx`
5. Pick a Bezier order and do a least-squares-fit for a curve of that order on the calculated points.
6. Reduce the higher-order Bezier curve to multiple Cubic/Quadratic segments with one of the standard algorithms for that purpose. 

And there you have your custom offset-curve for one side of a segment. 

Now, however, you have to join all of these individual segments together, with caps and joins of the selected types. Seems like there would be lots of ugly special cases!

**Comment by skef** [comment]
And ... think about "y" in #3264. It has lines that overlap but that end at different places. How does/should that interact with "join style"? Maybe there should be a pre-processing step to eliminate those. But what if they don't overlap exactly, but are very close?

Ugh.

**Comment by ctrlcctrlv** [comment]
Just speaking as someone who makes fonts in FontForge, the "y" case is a really natural thing to draw, and the fact that I can't stroke paths like that is regularly annoying and requires me to do workarounds like split up my paths

**Comment by ctrlcctrlv** [comment]
InkScape has no trouble with it. Perhaps we should think of this as two issues, the regular path stroking and the calligraphic path stroking, which I seldom use due to how buggy it is.

**Comment by skef** [comment]
Hmm, I've presumably already failed my interview. The line relevant line swept by the polygon often won't be at the normal angle. So you have to consider the shape and angle together and produce a distance *and* angle based on the "nib" shape. I think what you want is to "move" an imaginary line at the parallel angle (not the normal angle) towards the nib until they intersect, and then that intersection point gives you the distance and new angle for `nx`.

**Comment by ctrlcctrlv** [comment]
PS: It seems like what we want to achieve is called in mathematics a Minkowski sum, but doing Minkowski sums of curves seems non-trivial.

**Comment by ctrlcctrlv** [comment]
(Or impossible.)

**Comment by ctrlcctrlv** [comment]
cc: @mekkablue

**Comment by frank-trampe** [comment]
@ctrlcctrlv, I made a fairly big set of changes to `splineoverlap.c` a year or two ago to add relational geometry and to eliminate a lot of failure cases. That is likely familiar and accessible territory. The stuff in `splinestroke.c` has mostly gone unmaintained since George disappeared. We can certainly look at it in depth, but let me give some background.

Overlap removal was once a total disaster. We considered using lib2geom from Inkscape, but there were several deal-breakers. One of them was that certain values or entities required conversion, such that there was some chance that removing overlap with no overlap present would still change the splineset. Accordingly, I put a bit of work to get the overlap removal routines to work most of the time. Much of the effort involved adding relational geometry (using pre-removal adjacency in post-processing, essentially). Apparently, those efforts were not perfect, but the code is now familiar enough to me and clean enough that I can probably solve the problems that originate in `splineoverlap.c` (#3694, for example).

`splinestroke.c`, though, is a different matter. It is a bit more broken and a bit less familiar to me. The fact that so few things actually work correctly, combined with the fact that there is no null case in which it is not expected to produce changes, makes it easier both to make substantive changes and to use a "non-native" tool for the stroking. Even with that, the complexity of mapping back and forth between vastly different data structures might be a deal-breaker. We probably need to figure out how much is broken. In particular, there is some chance that a small restructuring would let us delegate more of the stroking process to the more fixable overlap removal routines.

I will look at both of these things in depth next week.

**Comment by ctrlcctrlv** [comment]
@frank-trampe :

First of all, thanks for taking a look at #3694. I wrongly categorized it was an expand stroke bug when it's really an overlap bug, as the error message says.

I might be willing to add lib2geom support to FontForge&hellip;but I wouldn't go so far as to ask that my lib2geom support phase out the legacy FontForge stroker, considering there are many reasons people might want to use it.

I'm not promising to do this (although I'll certainly give it a try), but I'm just asking if I, or I and @skef working together, did do it, whether or not you'd accept it:

# &#x261E; Proposal
* Add a new element to the Expand Stroke dialog, &ldquo;Method&rdquo;&mdash;&laquo;Legacy&raquo; or &laquo;2Geom&raquo;.
* Add a new compile time option, disabled by default, `--with-lib2geom`.
* Add to the documentation that if you have trouble with &ldquo;Expand Stroke&rdquo;, try compiling with 2Geom.
* Make new files `2geom.c` and `2geom.h` to handle the new Expand Stroke functionality.
* Perhaps, in 2Geom mode, add UI elements related to dashed lines, which is something I need for another project. But at the very least we'd want to replicate everything as it is in 2Geom mode, at least for the circular brush!

**Comment by ilyaza** [comment]
I want to say something **extremely** simple about rectangular pens (or, more generally, Minkowsky sums with polygons).  However, I do not think this is:

*  Given a shape, take 4 suitable parallel translations of the shape.
*  Remove overlaps.

Then this gives “about 99%” of the Minkowsky sum.  What is missing are “the joiners” corresponding to the parts of the initial contour going approximately in the direction of the sides of the rectangle.

Moreover, I have a conjecture (I did not wake up yet, so cannot check it):

To construct these joiners, it is enough to have code which calculates the Minkowsky sum with a side of the polygon (if the polygon is convex???).

If the conjecture is false, then **still** having a code to add a segment is enough in the case of a parallelogram: a parallelogram is a Minkowsky sum of its two sides, and addition is associative: so just add one side, then another.

**Comment by ilyaza** [comment]
Right: for Minkowsky sum A⊕B of B and C, the points b,c on boundaries of B and C **do not** contribute to the the boundary of A⊕B unless there are tangent lines at b and at c which are parallel. (Here there are many tangents at a corner — as usual.)

So if C is a polygon with corners cᵢ, then this would construct the sum:

* Take translations of B by cᵢ⸣s.
* Mark points bⱼ which are corners of B and points on the boundary of B with tangent lines in the direction of sides of C.
* Take translations of C by bⱼ⸣s.
* Remove overlaps between all these translations.

**Comment by ilyaza** [comment]
Oups, I left out one case: B may have whole pieces of the boundary which go in the direction of a side of C.  So there should be another bullet point above (trivial to implement if C is a rectangle; simple if C is convex).

**Comment by ilyaza** [comment]
No, what is said above is not 100% correct: it finds all the pieces of boundary correctly, but it may have some “junk” inside.  For example, consider a Minkowsky sum of two straight perpendicular segments…

**Comment by skef** [comment]
Incidentally, this past day I've been looking at lib2geom and its integration with Inkscape. Unfortunately they've made some design decisions that go against typical FontForge conventions.

Mainly there is no provision for any kind of "payload", hard-coded or not, in the `Geom::` Bezier points, and more generally no reliable notion of point identity. One effect of this is that round trips through 2Geom operations reset Inkscape node types. In FontForge you'd also lose generalized types, some other stuff like point names. 

It's an interesting question how much work it would be to improve round trips through lib2geom, and whether any of those folks would be interested/amenable. But there's no easy fix.

**Comment by ctrlcctrlv** [comment]
I'd be okay in some cases with losing that information and am still pursuing it. I'm not saying we should remove the legacy stroker

**Comment by skef** [comment]
After some off-line communication, I should clarify: Some algorithms, like expand stroke, fully replace the "source material". For those there's no issue with lib2geom as oppose to other algorithms. The problem, to the extent there is one, is that lib2geom is a questionable choice as a *general* geometry library.

The cost in terms of compilation and packaging of an library dependency may therefore be a factor. (I believe Inkscape currently builds lib2geom "internally", so not in a way that supports library dependencies. And currently few other projects use it.)

**Comment by ctrlcctrlv** [comment]
I need this really badly so I hired someone to help me integrate it. Either you guys accept it or you don't. I see no reason not to accept it due to its benefits and the fact that it's optional. Even if I only fix the bugs preventing my project from progressing it's worth it, but I hope to extend FontForge's path stroking abilities to cover dashed/dotted lines, calligraphic paths, and paths along paths. Maybe we can vendorize it as Inkscape has done. Inkscape is very robust which is why I have chosen lib2geom. Few other projects use it, so what? Somebody has to be the first.

Once again, it's optional, and I'm already working on it.

**Comment by frank-trampe** [comment]
I think that adding lib2geom support is great. Adding user interface support for the advanced stroking, though, seems like the sort of thing that would require a lot of helpful planning to do right, but, as long as it's initially optional, we can repay that technical debt later. Do you anticipate any extensions to SFD?

**Comment by ctrlcctrlv** [comment]
@frank-trampe Not initially, but eventually I'm going to want to save the Expand Stroke dialog state into SFD so you don't have to reset it every time you open your font. (This is useful even _sans_ lib2geom.) I agree that there are UI challenges for some of the more advanced stuff I want to do, especially path-along-path. However, for constant calligraphic strokes and circular strokes the UI already exists, and adding similar dash/dotted line stuff as Inkscape has, only minor changes to the Expand Stroke dialog need to be made UI wise.

**Comment by frank-trampe** [comment]
Great. This seems like the sort of thing that will make a lot of people happy and upset nobody.

**Comment by skef** [comment]
I've been thinking about this and may have something to show for it soonish. 

# Circular

I suspect the Minkowsky Sum route is a red herring. If the goal is a representation of the shape of the curve, it's easy enough to just calculate and then fit individual points. The difficulty comes from deciding where to break the curving line of points into splines, so that you don't have too many (on the one hand) or a poor fit (on the other). But once you solve that difficulty one way or another the fitting problem in the circular brush case isn't all that interesting. The positions of the endpoints of the offset curve are easy to calculate in closed form. The tangent angle at those endpoints should remain the tangent angles on the curve being stroked (because the offset is normal). So the only fitting variable is the length of each line from on-curve point to control point. That's a very restrained question that requires at most a few extra points to reason about.

After looking at a few options I think the [splitting approach from the famous primer](https://pomax.github.io/bezierinfo/#offsetting) is probably the best among them. 

# Polygonal

I'm pretty sure that polygonal brushes don't pose the same geometric challenges that circular brushes pose. A circular brush changes the shape because the "inking edge" of the brush moved around a curve is swept faster on one side and slower on the other. In contrast one edge of a polygonal brush is always being "drawn" by one corner, determined by the slope of the curve. The corner is just, in effect, a vector offset: the edge has (or should have) *exactly the same shape* as the spline stroked. (Right? Connect two pens with a rigid rod and keep that rod at the same angle. If you write with one the other will faithfully reproduce what you write. You could sit at an angle to a [polygraph](https://www.monticello.org/site/research-and-collections/polygraph) and it would still work. Affine transformation and all that.) 

This means that *ignoring overlap issues* the stroked edge in the polygonal brush case can be made by cutting the original curve into pieces, translating those pieces based on the corner vector relevant to that portion, and (because the derivative is continuous so you only transition from one corner to an adjacent one at a given point) connecting the "adjacent" curves with lines. Where the pieces need to be cut is determined by the slopes on the curve matching those of the brush lines. (Some connecting lines may cross the line already constructed, or will cross what will be constructed. But as long as the whole mess winds up clockwise when closed up that can be `splineoverlap.c`'s problem.) 

One of the early results in spline math is that it's very easy to convert some interval of a spline of any order into another spline of that interval -- you're just remapping `t`. There's already high-quality code in `splineoverlap.c` to do it (currently called `MonoFigure()` -- a misleading name because nothing in the function relies on the spline argument being a Monotonic).  So the mathematical difficulty boils down to answering the question "At what values of *t* does the tangent angle to the curve being stroked equal *θ*?" (which tells you where to slice). After banging my head against iterative numerical solutions to this problem I realized there's a nice clean closed-form for it, which may be obvious to those better with spline math than I. 

So the convex polygonal case seems to just be a matter of implementing a couple pieces and putting them together correctly and then working out some visual simplifications (basically deciding at what scale to stop slicing and what to do instead). Floating point rounding aside the result should be exact -- there's no "fitting". And all the "square" brushes are, of course, just particular convex polygonal brushes.

# The existing code 

The way `splinestroke.c` currently works is more or less:

1. Record points at small (relative to em) intervals for each edge being stroked, recording the spline and `t` value that generated the point.
2. Spend a great deal of effort "hiding" points within the boundaries determined by other points. 
3. Go back and reconstruct the "fragments" of splines determined by non-hidden points: 
    1. look for sequences of non-hidden points associated with the same spline and grab the first and last `t` values.
    2. Regenerate an appropriate (say 10) number of offset points on the relevant edge.
    3. Fit those offset points to a spline while keeping the tangent angle at either end consistent with the original spline (see above).
4. Attempt to put all the fragments back together.

This entire algorithmic approach is centered on an attempt to solve the overlap problem prior to spline generation rather than after. One would guess that's because the overlap code was not reliable at the time. @frank-trampe's improvement of that code can now be leaned in whatever replaces `splinestroke.c`. Indeed, it would be ludicrous not to go that direction.

**Comment by skef** [comment]
Note that the second section of the above is a different, longer-winded way of getting at @ilyaza's June 6 comments. 

Joining strokes two with a discontinuous derivative is pretty easy. You have the end tangent angle (slope) of the previous stroke and that of the current one. Figure out whether, on the edge that you're drawing, if there will be a "gap" or if you're on the edge that will overlap. If the latter, just join the two points with a line and let `splineoverlap.c` sort things out. Otherwise go through your polygonal brush and compute offsets to the points corresponding to the intermediate slopes, and join with lines. 

In isolation it would be easier to just generate the left and right edge of each control spline, connect them with lines at either end, and then duplicate the brush shape at each endpoint. That would handle both endpoints and joins. The problem is the `remove_inner` and `remove_outer` parameters for closed splines, which are important to the "Change Weight" implementation. To support those the way they are supported now it's best to be able to trace the edges independently. (It's possible that you could just make the shape, remove the overlap, and then choose from the resulting splines based on whether they are clockwise or counter-clockwise. That would work in most cases but I think there are some where it wouldn't. That problem nukes a lot of "just offset shapes on top of one another and remove overlap" approaches.

**Comment by ctrlcctrlv** [comment]
Hey guys:

@repu1sion is getting pretty close to done with this, we should have a PR next week. We're not targeting this for the next release for several reasons:

* Only circular brush replaced with lib2geom
* It only fixes bugs, it doesn't add anything new yet

Once we have both path-along-path and dashed/dotted lines it's worth putting it into a release, let's say the spring 2020 release.

**Comment by ctrlcctrlv** [comment]
(It is worth putting it in master whenever it's done though, but most likely we're not going to be able to merge it before August 1 anyway due to the review involved.)

**Comment by skef** [comment]
> Only circular brush replaced with lib2geom

Does this mean that only the circular brush is done or that the caligraphic and/or polygonal brush code doesn't use lib2geom?

**Comment by ctrlcctrlv** [comment]
I want to replace all the brushes. I know it's possible to at least add a lib2geom calligraphic brush. It might not be possible to add a polygonal one. With lib2geom compiled in, our first PR will only use it for the circular brush though, retaining the other 2 legacy brushes.

**Comment by skef** [comment]
Assuming the polygonal brush were replaced and the caligraphic brush were made a special case of it, would there still be interest in a non-lib2geom circular brush? And if so what would the role of the lib2geom option be?

**Comment by ctrlcctrlv** [comment]
Requiring lib2geom makes it harder to build as most distros aren't packaging it yet, but then again no one's packaging it because few projects are using it. So, I don't know. I certainly never plan to use the legacy circular brush once I can use the lib2geom circular brush. I will be so happy to be rid of FontForge's buggy circular brush...
