### ISSUE TITLE
Little help with centralizing the view

### ISSUE THREAD

**Issue by gabanzin** [fontforge/fontforge#3749]
Hello, since now apologize for posting here, I'am afraid this is the wrong section for this, but all I want from this software is to put the accents in some letters, and the "i" is messing up with my mind, he doesnt centralizes on the square... 
https://imgur.com/IjcJPeX

All I need is some spaces after the "í" because when a write is seem something like that: **s a íd a**
Appreciate for your help.
Daniel

**Comment by skef** [comment]
I'm not sure of all of what you are asking here, but as far as the illustrated i-acute is concerned:

1. The algorithms FontForge uses to automate accent placement often have problems and need hand-adjustment after running them. 
2. However, this particular i-acute looks about right. There are two conventions you may not be aware of:
    1. The conventional "center point" of an acute accent is its bottom tip, rather than half way through the "body" of the shape.
    2. Accents over italic characters are usually shifted over to match the italic angle, just as the dot on the normal "i" is shifted over.

In this case the bottom of the acute accent is more or less centered between the lines extending from the sides of the "i", which would be considered a good position by those conventions.

**Comment by gabanzin** [comment]
Unterstood
this is what I'm trying to do: move accent of the " í " to the right:
Before modification: https://imgur.com/isgCUqU
After modification: https://imgur.com/kv1AlWO
when accent moved, the center of view automatic go to the right, letter move to the left... hope you understand

**Comment by ctrlcctrlv** [comment]
No, I at least don't understand. What's the actual problem? Why can't you just move the accent or use anchors?

**Comment by gabanzin** [comment]
If move this Anchor-16 it will centralize? I dont know how work the sorftware, all what I want is move the accent for right, because the font came with accent the out of align. But when I do this, the " i " move to the left, and decentralize the view

**Comment by skef** [comment]
Oh, I think I may understand the issue now.

@gabanzin: The position of the character relative to other characters (and ignoring kerning) is determined by the 0 line and the width line, the latter of which is 447 in your two diagrams. These have related slanted lines because it's an italic font. None of those lines have changed when you move the accent character.

What I take it you are noticing is that when you move the accent the whole character moves *in the display box in the FontView window* (the one pictured in the left of your images). **Ignore this**. That window just centers the glyph shape and isn't meant to depict positioning. To view the positioning or "spacing" relative to other characters you can use a Metrics window.

**Comment by gabanzin** [comment]
@skef Really appreciate for your help, and all you guys. I got it. Have a good week for all of you.
