### ISSUE TITLE
Annoying warnings popping up: «Asked for cubic when had quadratic.»

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3775]
I think this is a regression caused by a bug I fixed; at least the warning is something I introduced (on the advice of @skef)&mdash;#3679.

Just removing the warning works for me, but what causes it? I can't seem to figure it out, I think it's auto save related but would like help tracking it down.

To see the regression:

* Open a new font.
* Open any glyph.
* Enable Spiro.
* Put a G4 curve (circle shaped) point anywhere.

**Comment by skef** [comment]
I've been seeing this message to, but (maybe?) only when playing around with your `y.sfd` test file. 

It's worth noting that if this turns out to be a case where FontForge actually should convert the quadratic to a cubic it's actually pretty easy to add that code. So once we know we can either fix the calling code or add that capability to the function.

**Comment by ctrlcctrlv** [comment]
Yes it doesn't happen in B&eacute;zier mode. If you don't use Spiro in your daily work you won't notice it, but I probably had Spiro enabled when I made `y.sfd`, even though that only has corners; since I use Spiro to make all my fonts, including the one I'm working on now (all below letters made with Spiro)

![2019-07-11-145258_3486x327_scrot](https://user-images.githubusercontent.com/838783/61028695-e1a77180-a3eb-11e9-82ba-e1f350d70f3e.png)

**Comment by khaledhosny** [comment]
I get this message why I try to save Amiri SFDIR files, any idea how do I find which glyph is causing this? I don't recall using Spiro in Amiri.

**Comment by ctrlcctrlv** [comment]
Can we see the SFD(IR)?

**Comment by ctrlcctrlv** [comment]
Even without seeing it, I think all you have to do is add a `printf` at sfd:c1653 and write out sc->unicodeenc or sc->glif_name

**Comment by skef** [comment]
When style has substance:
```
    if (order2 && !want_order2) IError("Asked for cubic when had quadratic");
```
The simplest way to track these things down is by adding a gdb breakpoint corresponding the error. And the simplest way of doing that is to add one for the line number in the file that corresponds to the error. Which is one reason why these mashed-up-on-one-line control statements aren't the best idea; line numbers are a UI component.

**Comment by skef** [comment]
Ah, this problem is actually pretty simple. From `SFDDumpSplineSet`:

```
int order2 = spl->first->next==NULL || spl->first->next->order2;
```
This is the code that attempts to derive the existing "order" (cubic or quadratic) from the splineset. The info is in the `spline` structure. If there is only a single point there is no such structure so the `NULL` check prevents a segfault. Unfortunately it's also de-facto treating single point splines as Cubic. 

Since a single point spline is equally fine to treat as cubic or quadratic, this line would be better put as:
```
int order2 = spl->first->next!=NULL ? spl->first->next->order2 : want_order2;
```

**Comment by khaledhosny** [comment]
Thanks, the change above made the warning go away for me.

I don't think I have any single point splines, the errors comes always after saving the last glyph.

**Comment by khaledhosny** [comment]
May be it happens when saving the grid.

**Comment by skef** [comment]
> May be it happens when saving the grid.

I guess I should say that my explanation accounts for the test case specifically and there could be other code that causes the warning in different ways. But (assuming the fix is correct) if this makes the immediate problems go away I think it's reasonable to merge it, close the issue, and start again if there are additional reports.

**Comment by frank-trampe** [comment]
That seems like the right approach, but I cannot find the pull request.

**Comment by skef** [comment]
Making it now.
