### ISSUE TITLE
FontForge should use SF Pro as its UI font on macOS, instead of Helvetica

### ISSUE THREAD

**Issue by fitojb** [fontforge/fontforge#3844]
The Helvetica version included in macOS has wrong metrics, which have caused issue #3835. But SF, and not Helvetica, is the main font used across macOS for its UI. FontForge should match that.

**Comment by skef** [comment]
Can we nail down specifically what metric is wrong? Do other mac applications have this problem with the system Helvetica? Is there something in the AAT tables or elsewhere that FontForge should be attending to?

**Comment by fitojb** [comment]
No other applications “use system Helvetica”, and back when macOS used Helvetica as a system font, it wasn’t the one currently used by FontForge, but a hidden version with different metrics (`HelveticaNeueDeskInterface`).

**Comment by skef** [comment]
So after looking at this briefly, here's what seems to be the current issue: Any given release of Mac OS X has a system font. This font is not meant to be "public", in that it's not meant to appear in selection drop-downs. FontForge is not a native application, and is designed so that it retrieves the font for its widgets the same way it retrieves any other font. It uses an old X11-y convention of asking for "Sans" and using whatever the OS suggests as the best sans-serif font.

Hard-coding San Francisco (assuming that's possible) is likely to work poorly on older systems and may work poorly on future systems. FontForge can special-case Mac OS X font selection, but needs a good heuristic. It's not obvious what that heuristic would be.

**Comment by jtanx** [comment]
> and using whatever the OS suggests as the best sans-serif font.

Nah, that's Pango hard coding it to Helvetica as per [this link](https://github.com/GNOME/pango/blob/dd3fc1b1976890bde122c87813f03da6c26129b9/pango/pangocoretext-fontmap.c#L156-L157)

**Comment by skef** [comment]
Ah, so I was wrong about the source of the mapping but our library already exposes a string for it's heuristic. Good!

**Comment by milotype** [comment]
I've tried "San Francisco", "system-ui", "System Font", "Font sustava" (the Croatian name) in the "resources" file, but nothing works, I can't see any changes. 
Maybe the above mentioned by @jtanx works only when an app uses the "standard" menu bar? BTW (probably you guys know that) San Francisco is a "system font" only, it cannot be used in any app through font menues.

I'm attaching some picts of "SFNSText-Regular.otf" just for info:
PS names
![PS names](https://user-images.githubusercontent.com/43657314/62254733-9e448f80-b3fa-11e9-93f4-6248d30db1d9.png)
General info
![general](https://user-images.githubusercontent.com/43657314/62254760-b4eae680-b3fa-11e9-8eb7-d063986e58a0.png)
TTF names
![ttf names](https://user-images.githubusercontent.com/43657314/62254763-bc11f480-b3fa-11e9-841e-a23b261868aa.png)
OS2 names
![OS2 metrics](https://user-images.githubusercontent.com/43657314/62254775-c7652000-b3fa-11e9-8a61-4203c37cda2e.png)

**Comment by milotype** [comment]
… also, my San Francisco fonts are in my folder: /System/Library/Fonts
Maybe I'm overdoing with infos, but I'm no programmer, sorry if it's too much …

**Comment by milotype** [comment]
One more, just to try to convince everybody of the "cramped" line-hight. Just tested vietnamese (see pict). So, if localization is to be taken seriously, I do feel strongly about the need for improving the line-height issue.

![vietnamese](https://user-images.githubusercontent.com/43657314/62255729-c1713e00-b3fe-11e9-9ba3-21cc3841fd80.png)

**Comment by ctrlcctrlv** [comment]
Can we see the Metrics of Helvetica

**Comment by skef** [comment]
Hmm ... "system-ui" may not be a meta-name but the first-level name of a font family being designed and distributed for that purpose: https://flaviocopes.com/css-system-fonts/#a-note-on-system-ui

**Comment by ctrlcctrlv** [comment]
What does the CSS standard have to do with this? I highly doubt our font strings are CSS conformant, especially with such a recent innovation as `system-ui`

**Comment by skef** [comment]
The CSS standard is probably irrelevant, and at most slightly relevant. The interesting thing is that Pango link above from @jtanx that includes "system-ui" as an input option.

**Comment by ctrlcctrlv** [comment]
OK. If we for some reason need another heuristic on OS X, web research shows me that there's a function called "systemFontOfSize" which returns a UIFont; I think that should work. See https://github.com/facebook/react-native/pull/1635 and [this added line](https://github.com/facebook/react-native/pull/1635/files#diff-7ae444980481763df6e0f68df04d5b59R44).

**Comment by skef** [comment]
Hmm. So it appears that gdk already thinks the system font will be used: https://github.com/GNOME/gtk/blob/5d10100fc03918c21586eb2256a7b88d55642598/gdk/quartz/gdkevents-quartz.c#L1724

Is it possible that the way we're using Pango is causing it to pick a new font when we might be able to get it to use GDK's "preference"?

**Comment by khaledhosny** [comment]
The `system-ui` font alias name is not working in Pango’r CoreText backend, it gets eventually mapped to Sans because there is no font named ”San Fransisco” on macOS.

**Comment by khaledhosny** [comment]
https://gitlab.gnome.org/GNOME/pango/merge_requests/112

**Comment by skef** [comment]
That's the *best* kind of fix for this sort of thing (user delay aside).

**Comment by jtanx** [comment]
@khaledhosny nice!

**Comment by ctrlcctrlv** [comment]
Nice, so this should probably be closed as "bug in upstream software"?

**Comment by milotype** [comment]
Is there any way I could test this on my mac?
What would I need to do?

**Comment by jtanx** [comment]
Not at the moment, no, and given that we'll be building only the Python 3 bundles into the future, you probably won't be able to test it when that Pango does get released, unless you either compile FontForge yourself or manage to upgrade your OS.

**Comment by ctrlcctrlv** [comment]
To add onto what @jtanx said, you should look into at least dual-booting GNU/Linux if you want to keep up with FontForge development going forwards @milotype. I know you can't upgrade your OS but you should at least be able to do that

**Comment by milotype** [comment]
;-(( ... but thank you for the suggestion with dual-booting! I'll have to research on how to do that ...
Also thanks to everyone for all your patience with this issue.

**Comment by skef** [comment]
I would suggest VirtualBox as an easier alternative but unfortunately it's also no longer supported with your host OS  ...

**Comment by khaledhosny** [comment]
> Is there any way I could test this on my mac?
> What would I need to do?

Try to manually set FontForge UI font to `.AppleSystemUIFont` (with the leading `.`) and see if it helps.

**Comment by milotype** [comment]
Thanks, I've tried that already, as well as other diverse constelations. But i've come to the conclusion, that the shorthand isn't working on (at least my) mac 10.11.6. Also using Apples UI font in the non-apple-native FontForge will probably not succeed. As I mentioned in https://github.com/fontforge/fontforge/issues/3835#issuecomment-517036574 and https://github.com/fontforge/fontforge/issues/3835#issuecomment-517036769. (Don't forget, I'm no programmer, so that's just a thought.)

No matter what I add to "Font:"-family-name-property, there is no change. For instance:
`xxx.xxx.Font: 400 10pt sans` to `xxx.xxx.Font: 400 10pt noto sans,sans`
"Noto sans" doesn't take precedence.

But when I completely replace the definition, like
`xxx.xxx.Font: 400 10pt sans` to `xxx.xxx.Font: 400 10pt noto sans`
the line-heights look better (other metrics) – **but still not identical across submenues** (because of the icons, as discussed before).

This is true for all  `Font:`, `FontFamily:`, `SansFamily:`, etc. definitions in the "resources" file.
So I have changed all of the above definitions with just one family name, namely "noto sans".
For instance
`fontforge.FontView.SansFamily: dejavu sans,helvetica,caliban,sans,clearlyu,unifont`
to
`fontforge.FontView.SansFamily: noto sans`

I've also changed
`MonoFamily: dejavu sans mono,courier,monospace,clearlyu,unifont` to
`MonoFamily: courier`
and all "Inconsolata" to "courier".

This way most of the UI works as specified. (**BUT**, I've noticed, that the "Lookups" tab for GSUB and GPOS in "FontInfo" doesn't get changed.) 

So obviously what I'm doing is a hack. And it doesn't solve my "initial complaint", that all line-heights should be (proportionaly) identical across FontForge's UI.

I hope some of my information is still usefull for all of you.

**Comment by ctrlcctrlv** [comment]
GPOS/GSUB also look different on Linux. I assume a different font string is used for them, perhaps even hard coded.

Using commas is only valid in certain fields.

**Comment by jtanx** [comment]
Just confirming, that system-ui change in pango does work:
![image](https://user-images.githubusercontent.com/5137410/62661821-974aed80-b9b5-11e9-8d15-7949163aa04e.png)

Although that requires changing this: https://github.com/fontforge/fontforge/blob/master/fontforge/fontforgeui.h#L181

Not entirely sure why some are hardcoded but others configurable in resources.

**Comment by khaledhosny** [comment]
Since we use Pango, I suggest (until the code is fixed to not har-code these fomts) changing it to something like the following and let Pango pick the defaults of each system:
```C
#define SERIF_UI_FAMILIES	"serif"
#define SANS_UI_FAMILIES	"system-ui,sans" /* system-ui is not supported by old Pango */
#define MONO_UI_FAMILIES	"monospace"
#define FIXED_UI_FAMILIES	"monospace"
```

**Comment by jtanx** [comment]
Alright, so it wasn't hard-coded as much as it's not in the default resources file. You can probably override it with [something like](https://github.com/fontforge/fontforge/blob/master/fontforgeexe/metricsview.c#L5255):

```
fontforge.MetricsView.Font: ...
```

Although I guess it would be nice to be able to just override the default once
