### ISSUE TITLE
FontForge generating very weird OS/2 usWinAscent / usWinDescent

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3850]
I received an email regarding my latest font, Quaerite Regnum Dei:

>The Rendering problems on Windows is due to the disproportionate font metrics. You need to adjust the usWinAscent value which is
>
>* ascent (usWinAscent): 10618
>* descent (usWinDescent): 1630
>* BTBD (Windows): 12347
>
>A normal value is close to the UPEM, which in your font is 1100.
>
>Thanks, Joseph 

Indeed, he's right. But I didn't do this on purpose, I didn't intentionally set any OS/2 values outside of the family in the "Misc." table. I certainly didn't mess with the OS/2 metrics.

OS/2 Metrics of OTF as reported by FontForge:
![2019-08-02-093132_1584x1181_scrot](https://user-images.githubusercontent.com/838783/62337673-354b3d80-b508-11e9-893c-9100d7ff725d.png)

OS/2 Metrics of SFD:
![2019-08-02-093222_1584x1181_scrot](https://user-images.githubusercontent.com/838783/62337701-4f851b80-b508-11e9-92f1-b6408fe7e43d.png)

What am I doing wrong? I think this is a bug.

**Comment by ctrlcctrlv** [comment]
Ugh, so sorry guys. I hate opening issues and then figuring out the problem&dagger; later. I really need to just get a [rubber ducky](https://en.wikipedia.org/wiki/Rubber_duck_debugging) or something.

&dagger; I had some glyphs in the PUA which I forgot to clean up before creating my OTF, they were originally manuscript pages with multiple glyphs traced, some way out of range +10,000. Sigh&hellip;

**Comment by frank-trampe** [comment]
The best fix to any problem is it not being one.

**Comment by khaledhosny** [comment]
I suggest you always set Typo and HHea metrics manually, since these control the line height and you don’t want this to change depending on what glyphs you added/removed from the font.

The win metrics should be only used for clipping, so keeping “Is Offset” checke for them is OK, except that some legacy Windows APIs/applications still use them for line spacing (I personally don’t care about such buggy applications, but for Latin fonts you might be able to keep them happy without sacrificing much, your call).

**Comment by yg8ijvjvjv** [comment]
That's why you don't use Is Offset for the font height boundaries. In fact, each time you want to change the font height boundaries you should redesign the entire font for it to be optically correct with the font height boundaries.
