### ISSUE TITLE
SFD version is increased even if no new features are used.

### ISSUE THREAD

**Issue by khaledhosny** [fontforge/fontforge#3856]
Saving a file with latest FonntForge will increase the SFD version even if no new features are used, which breaks building such files with older versions of FontForge.

See https://travis-ci.org/alif-type/libertinus/builds/567619530#L543.

I suggest reverting the version change, since there are many more deeper changes that were added to SFD format over the years (like saved undo stuff), without increment the version number. The worst that can happen is old version discarding the saved image data (which I believe is what triggered the version increase), which is no worse than losing undo history.

**Comment by ctrlcctrlv** [comment]
If you don't intend to use the new feature, you can disable `WritePNGinSFD` (maybe not exact name of setting, but something like that) as a work-around for now.

We did notice at the time that even if no features were used it'd still increment, but it was still merged. See https://github.com/fontforge/fontforge/issues/3800#issuecomment-513508891

**Comment by khaledhosny** [comment]
OK

**Comment by frank-trampe** [comment]
This was all intentional. The option is `WritePNGInSFD`. We had considered turning it off by default, but then it would never get adopted. Those who want stability can still set the preference to 0.

**Comment by khaledhosny** [comment]
I can’t ask everyone sending me a patch to change some obscure, global FontForge option hidden somewhere. Anyway, I have a simpler way to handle this.

**Comment by frank-trampe** [comment]
What is the simpler way (in case somebody else has this problem)?

**Comment by khaledhosny** [comment]
I have a normalizer script that removes all the superfluous stuff FontForge saves in SFD files, I’ll just make it fix the SFD version as well, there are never any background images in my files.

**Comment by frank-trampe** [comment]
Ah, okay.

**Comment by ctrlcctrlv** [comment]
Your normalizer is awesome, I also use it in my projects :-)

That's a good solution, and we should probably document it.

**Comment by skef** [comment]
> We did notice at the time that even if no features were used it'd still increment, but it was still merged. [See #3800 (comment)](https://github.com/fontforge/fontforge/issues/3800#issuecomment-513508891)

I try to maintain a generally submission-friendly attittude when reviewing on open source projects. A corollary of that attitude is that when I note a potential problem with a change without objecting to a merge, that's not "absolution" -- particularly in the face of further user feedback. I raised the issue because of the potential for issues like this one, not as an argument against filing them.

I was going to say "However, it's a tricky problem to solve ...", but I'm not sure that's right. FontForge makes extensive use of random file access while reading; is there one for writing? Rather than having to add a second loop, could the version just be changed by tracking its location and editing it before closing? Or will would that not be viable on some of our platforms?

**Comment by frank-trampe** [comment]
@skef, sorry I didn't respond to that at the time. I still think that this is the right approach. It would be even more confusing if the file format version number did vary based on the content and would worsen the tangled mess of version determination logic. Eventually, we will need to rewrite with a single version number variable that then triggers the various features, and it seems prudent to minimize the number of steps that we take away from that path.

**Comment by skef** [comment]
> It would be even more confusing if the file format version number did vary based on the content and would worsen the tangled mess of version determination logic.

There's "good confusing" and "bad confusing". I think hearing that you have a cross-version sharing issue because person X is using a new feature your version doesn't understand is better than hearing that you have a cross-sharing issue issue because person X could have used a new feature your version doesn't understand. First of all, the first case should happen much less frequently than the second. Second of all (and perhaps more importantly) it's easier to explain some obscure image-related preferences flag to a collaborator *who actually uses images*.

**Comment by frank-trampe** [comment]
I would agree with you on those two cases, but there is an even simpler way to message it. Just saying that there's a version mismatch without needing to elaborate is about as simple as it gets, and, perhaps for that reason, most software handles it that way.
