### ISSUE TITLE
Inability to type some characters in Metrics Window

### ISSUE THREAD

**Issue by aimnadze** [fontforge/fontforge#3982]
Hi,

It is impossible to type the following characters in Metrics Window: `#`, `[`, `]`

Steps to reproduce:
* Open FontForge
* Open any font
* Open Metrics Window
* Type `#`, `[` or `]` the the field above

Expected result:
* The glyph of the character to be displayed

Actual result:
* Nothing is displayed
* Subsequent characters are also hidden

System details:
OS: Linux Debian
Version: origin/master
Built with: cmake

**Comment by aminabedi68** [comment]
you should use valid names:

![2019-10-20_23-32-35](https://user-images.githubusercontent.com/25493297/67165480-4cc0f680-f392-11e9-9528-189ec0545b9a.png)

**Comment by skef** [comment]
The number sign in the metrics window has been discussed in #3357. I believe the brackets are "reserved" because the metrics facility shares code with the character bar at the top of the Char View. 

Generally speaking the metrics window is often able to interpret unicode characters but some are reserved or may not work for other reasons. The glyph name is a good fallback.

**Comment by aimnadze** [comment]
Yeah, I already got it. But let it behave always the same way. Consider the following scenario:
* Open FontForge
* Open a font
* Select `#` symbol
* Click "Metrics" > "New Metrics Window"
The window opens and there is `#` written in the text field above.
It should probably show `/numbersign` instead.

This causes the confusion.

**Comment by ctrlcctrlv** [comment]
Thank you @aimnadze for the bug report. The problem seems similar to #4070. I will patch it today.
