### ISSUE TITLE
Move slots that are referenced without breaking references

### ISSUE THREAD

**Issue by svenper** [fontforge/fontforge#4040]
Is there a way to move slots that are referenced (e.g. /a) without breaking references (/aacute)?

It can currently be worked around afterwards by cutting and pasting the destination slots into themselves but this can be tricky if such slots are spread out all over the place (like the various accented "a" characters, /aacute, /uni1EA1, etc.).

Could the program remember the names of a Cut operation's source slots and replace the references after they have been pasted elsewhere?

```text
fontforge 20190801
build date: 18:07 UTC  2-Aug-2019
```

**Comment by ctrlcctrlv** [comment]
Why not just change the glyph encodings (Element&rarr;Glyph Info&hellip;) and reencode (Encoding&rarr;Reencode&rarr;Unicode, BMP)?

**Comment by svenper** [comment]
I like to keep character variants next to their originals, which gets broken up if I re-encode.

**Comment by skef** [comment]
@svenper - Is that the ultimate goal of this question -- to have control over the order in which glyphs appear in FontForge -- or is there some other issue?

**Comment by svenper** [comment]
Yes, as long as they can appear next to each other, and it would be easy to add another variant to a new slot next to them if the need should arise, I don't really care about the underlying encoding.

**Comment by skef** [comment]
In that case my advice is:

1. As far as I'm aware FontForge has no easy way of cutting and pasting while retaining references. You would have to do some post-repair. 
2. If all of your variants are Unicode-encoded, and there aren't too many of them, you could solve your problem with a custom encoding.
3. Otherwise you might want to read [this](https://github.com/skef/fontforge_coverage_tools/blob/master/doc/ff_sfd_pseudoenc.md#how-this-works-and-why-it-is-safe) and fiddle around with a test file modifying the first Encoding number. (Just try swapping two, for example). That will demonstrate what ultimately governs the display order and gives you the option of writting a little external tool to do the job. My tool (the one that documentation is for) won't work for you because it's only for unencoded glyphs but the basic idea would be the same.

**Comment by ctrlcctrlv** [comment]
You should use a custom encoding, yes.

**Comment by skef** [comment]
There are various encoding improvement and workaround needs, especially some means of organizing unencoded glyphs. However, doing development on copy and paste just to support ordering isn't a good approach.
