### ISSUE TITLE
Expand Stroke Remove Overlap removing countour it shouldn't

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4050]
# Instructions

Run &laquo;Expand Stroke&raquo; with a radius of 10 on.

# File

[ij.sfd](https://github.com/fontforge/fontforge/files/3939279/ij.sfd.zip)

# Results

## Remove Overlap &rarr; None (Debug) :heavy_check_mark: 
![2019-12-09-185454_2560x1461_scrot](https://user-images.githubusercontent.com/838783/70430222-41966700-1ab5-11ea-8081-49a16b7d461d.png)

## Remove Overlap &rarr; By Layer or By Contour :x: 
![2019-12-09-185554_2560x1461_scrot](https://user-images.githubusercontent.com/838783/70430289-6ab6f780-1ab5-11ea-8d57-4286529a7b43.png)

**Comment by skef** [comment]
This one is part of a problem I don't really understand and that it's good to have a simple test case for. 

If you deselect all points and then select one point on a closed contour, the direction section of the Element menu is supposed to indicate whether the contour is clockwise or counter-clockwise. If I add a circle contour to this one that works as expected. 

With the dots, in contrast, the indicative menu items are disabled. So for some reason FontForge doesn't seem to know the direction of those dots. 

The stroke code is supposed to be agnostic about source contour winding direction except when applying Remove External and Remove Internal. But in order to be agnostic it has to be able to detect what the direction is in the first place. I believe that's the source of the problem here.

**Comment by skef** [comment]
What I thought was a solution to this problem in #4060 turns out not to be. Unfortunately I don't have a current plan to fix this problem.

**Comment by ctrlcctrlv** [comment]
So if someone else were to try they'd basically need to replace `SplinePointListIsClockwise`?

**Comment by skef** [comment]
I think the question is: Is it more work to try to implement someone else's algorithm or to read through the existing one until you understand it so you can fix it? It's hard to answer that except in relation to a specific alternate algorithm. 

Since I don't have one chosen, I'm punting for now because digging into `autotrace.c` seems like a lot of work. I may have burned out a bit fixing the Cubic -> Quadratic problem.

**Comment by ctrlcctrlv** [comment]
Sorry about that. Enjoy your holidays. This layer stuff has me shaking my head too; George tacked it on in a hurry and it really shows.
