### ISSUE TITLE
Stroking a certain ‹S› results in degenerate spline

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4059]
Arch Linux, 82579d3b0c329288e522fde35d7d8c82ee786cc3

Another Spiro-produced spline causing problems.

For some reason it's most apparent in the MetricsView:
![2019-12-12-114319_3554x1275_scrot](https://user-images.githubusercontent.com/838783/70680884-7b918400-1cd4-11ea-9e77-50487e657379.png)

However once you know where to look, it becomes obvious also in the CharView:
![2019-12-12-114353_2560x2101_scrot](https://user-images.githubusercontent.com/838783/70680924-982dbc00-1cd4-11ea-8ace-fd6098767510.png)

# Required settings
* Major 45, Minor 45
* Angle **must** be 45
* **None (Debug)** must be selected
* Line Cap can be either Round or Nib

# File
[S.sfd](https://github.com/fontforge/fontforge/files/3953724/S.zip)

**Comment by frank-trampe** [comment]
This bug report has a rare personal touch to it.

**Comment by skef** [comment]
Looking at this

**Comment by ctrlcctrlv** [comment]
Sorry I missed you on IRC earlier @skef. Next time write my name in the chat ("copypaste") to ring the bell. :) I am "in".

**Comment by skef** [comment]
So the preliminary answer is that the problem happens somewhere in the simplify code after the contour is converted to quadratic (which happens because the layer in the file is quadratic). 

I have a test case with a much smaller number of points, but obviously it's tricky to nail things down in the simplify code.

**Comment by skef** [comment]
1. Open the S glyph in this file: 
[Snew.sfd.txt](https://github.com/fontforge/fontforge/files/3959381/Snew.sfd.txt)
2. Change the foreground layer from quadratic to cubic
3. Stroke the contour with Circular(45,45,45), Cap=Butt, Join=Nib, RemoveOverlap=None, Simplify=No, Add Extrema=Yes

The result looks like:

![s1](https://user-images.githubusercontent.com/6175836/70776365-b37ae480-1d31-11ea-8e2a-7cca781dd289.png)

The two points close together on the longer curved edge are well formed with reasonable control points. 

Now switch the foreground layer back to quadratic:

![s2](https://user-images.githubusercontent.com/6175836/70776499-10769a80-1d32-11ea-8709-1347e36acfda.png)

Note that one side of those two curved points has become (what appears to be) a line. The control point to the upper left of that line has this info:

![s3](https://user-images.githubusercontent.com/6175836/70776582-4d429180-1d32-11ea-918d-f560c496fa27.png)

Although the next cp is not depicted it is positioned at 0,0. It is not depicted because the previous cp of the next point has *offset* 0,0 rather than *position* 0,0, as it should for a line. Which of the redundant control points FontForge uses when interpreting quadratic splines depends on various factors.

In any case it is this 0,0 control point that eventually comes into use in the simplify process. Therefore my initial diagnosis was wrong -- the problem isn't with Simplify but with this earlier corruption. 

There are therefore really two issues with this cubic to quadratic conversion:

1. The corruption of the control point value
2. The seeming distortion of what was a curved segment into a line.
