### ISSUE TITLE
Way too many people have push access

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4081]
And this is a security risk. I doubt too many people installing e.g. `fontforge-git` from the AUR think about how many people can push.

And remember, since none of us active developers are in the habit of signing our commits, anyone with push access can push in one of our names.

Just because nothing has happened yet doesn't mean nothing will happen.

56 people can push to the head of the repository. That's 56 random people we're trusting to all have great security, and not to troll the repository, and not to sell their account to someone who would troll the repository.

In the new year, we should cut down severely on those who have push access. If this results in me myself losing access that's the a cost I'm willing to bear if it means that only a select few can merge PRs. (Though I would argue on my behalf that given how active I am and that I develop all my fonts on master, I should have access so I can quickly revert bad changes, as I've done in the past.)

I'm not saying any of the 56 are bad people. I'm just saying that this is wildly insecure.

To edify, let's see how little had to be contributed to get access.

* @cicku authored a single merge commit, 714747a1d4b465c9962d0a6200308674b6bd819f, which updated a translation. He now has seemingly lifelong push access.
* @monkeyiq was an employee and makes a point of ignoring requests for comment. He definitely should lose access.
* I love @behdad but he doesn't even seem to have made any commits at all to the project!

Some contributed a lot, like @blipvert. The problem is, they last contributed in 2014. Ditto for @mskala, who can do even more destruction as they are an Owner; they last contributed in 2016.

We need to come up with criteria for having push access. Like being a Wikipedia admin, I'd say the two most important criteria are:

* needing the extra power it grants you over normal members, and
* actually using that power to some degree in the present.

The ["Core" team](https://github.com/orgs/fontforge/teams/core) is a good start for who should have push access. I'd add myself to that (duh :joy:), @skef, Joe, and maybe one or two others that aren't coming to mind right now. (Very tired, this is my last e-mail of the night.)

**Comment by tshinnic** [comment]
I believe I am one of those mentioned. I have not contributed since a
rather severe snit over a situation I found in GWW's TTF code. Even back
when, I relied on more experienced, more familiar, people to review my PRs.

It was to encourage people to contribute that liberality was employed.
Given that people are now more familiar with how opensource projects work,
how they work together, push access is not a needed encouragement.

I will rely on the project's more experienced people to know what to do in
this, and in the future.

**Comment by skef** [comment]
I hope you don't mean to imply that I am not random; it's a core part of my identity.

**Comment by behdad** [comment]
Yeah I have no idea why I'm there to being with. :)

**Comment by mskala** [comment]
On Sun, 29 Dec 2019, Fredrick Brennan wrote:
> And this is a security risk. I doubt too many people installing e.g.
> fontforge-git from the AUR think about how many people can push.

I'm not sure December 29 was a good day to initiate this discussion.  I,
for one, am currently on vacation without easy access to my Github account
or even to email, and I think it's predictable that many others for whom
it's relevant will be similarly unavailable for a serious discussion in
the last week of December.

That said, in my own case, it's fine to remove me from the list.  I think
I was originally added in the hope I'd contribute more - I didn't seek it.
In the years since then, the company running Github has embraced values
abhorrent to me, and I've narrowly limited my participation in
Github-hosted projects.

**Comment by frank-trampe** [comment]
Per @mskala's point, we can certainly let the discussion run a bit. I suppose that we also need to discuss signing.

**Comment by ctrlcctrlv** [comment]
Given that this state has endured for years, and how long the list is, I didn't expect we could resolve it quickly. :-)

**Comment by mskala** [comment]
Okay, I'm back from vacation, and have another thought.  Bearing in mind that I'm not a really active participant here and probably won't be in the future, maybe my opinion shouldn't bear a lot of weight on how the people who _are_ running the project should do so; nonetheless, maybe it'll be of interest.

There are good reasons why the committer list should be limited, but the "security" issue for end users who may be using the Git repository as a distribution channel, is not a good reason.  As [I've written before](https://ansuz.sooke.bc.ca/entry/230), development version control systems are lousy substitutes for proper software releases targeting end users.  If AUR or other packagers are encouraging end users to get the software straight from the Git head, or building systems around the assumption of end users getting the software that way, they're doing something we shouldn't encourage or enable, and we definitely shouldn't be designing and operating the version control system which has other important purposes around the assumption of trying to make it "safe" in this inappropriate and fundamentally unsafe use case.  Just like although we don't necessarily have a duty to _prevent_ people from doing "curl | bash," we shouldn't go out of our way to protect users from the consequences of that if they do it.

If many end users perceive a need to clone the Git repository in order to get "the latest" Fontforge, it may point to a need to make the more appropriate distribution channels for end users more visible and more up to date.

**Comment by skef** [comment]
> There are good reasons why the committer list should be limited, but the "security" issue for end users who may be using the Git repository as a distribution channel, is not a good reason.

I think the worry is mostly about susceptibility to and (lack of) awareness of non-PR pushes into the master branch. If a large number of people have access to make subtle changes then they can leak into the official releases.

**Comment by ahyangyi** [comment]
I used to have push access and I (ab)used it to push two crash fixes many years ago. I think that was part of the history how our community formed -- contributors were rare, anyone who is engaged in discussion was invited and entrusted with push power. In other words, we gave everyone in sight push power.

And... then at some day I lost that push access. The “remove push access” thing had definitely happened before and there is nothing inherently wrong to do it again.

Personally, I am happy that I no longer have that push access and I would have to make a proper MR to get something to be merged in. It, in some sense, feels _too_ good: I still have the right to submit MRs, but I do not have the burden of having to review people's MR. Sounds awesome doesn't it?

The worry on the other side of the equation is that if we don’t have enough people with push power, things might get stale, MRs not getting reviewed in time, etc. Especially when we hit the more International holiday times (meaning: Christmas and New Year). Thus I prefer having a slightly more inclusive group of entrusted people.

**Comment by ctrlcctrlv** [comment]
I agree that it should not be hard to get push access; and if we take away someone's access, they should be able to ask for it back after contributing again for a time. Let's say someone contributes ten patches in 2015, then none for over a year. They should lose access. But then let's say they come back and contribute two patches. That should be enough to give it back.

**Comment by cicku** [comment]
I feel like being insulted to be mentioned in your initial message.

**Comment by ctrlcctrlv** [comment]
I'm insulted that you feel insulted 🙄

**Comment by JoesCat** [comment]
@ctrlcctrlv - FYI - https://github.com/fontforge/libuninameslist/issues/4

**Comment by JoesCat** [comment]
Before this discussion devolves into a flame war, I suggest, [write, but don't press "send" right away](https://www.inc.com/magazine/19981101/1026.html), because you'll find that what you want to say now, can be improved further, or probably was not something worth pressing "send" in the first place.

Getting back to the original posting - I notice lately versus a few years back, that there are a lot of "force-push" in the PRs, which is something that I saw few times in the past. It's just an example of differences between today's active developers, and that of developers from a few years ago - different developers have different habits.

...however...

@skef mentioned,
> I think the worry is mostly about susceptibility to and (lack of) awareness of non-PR pushes into the master branch. If a large number of people have access to make subtle changes then they can leak into the official releases.

The only subtle changes to occur are likely at or near HEAD, git history will be out of sync if you try to slip something lower than HEAD. There may be one, two, three developers currently at or near HEAD that might notice a git history out of sync, others below that point won't know.
The deeper down someone attempts to slip something in, the more likely to get caught, because there are likely more developers likely to have a local copy or fork at lower levels that would complain of git history out of sync.

Some years ago, I believe ownership was culled down to 3 people, and push access too.
I recall times when I couldn't merge PRs too. ...then it opened up again.... The point is, limiting access to 2 or 3 people puts a huge load on those very few people.
FontForge isn't just github. There is also [the mailing lists and older sourceforge repos](https://sourceforge.net/p/fontforge/_members/), a number of websites and more.
I'm not surprised to see the list of developers with power to merge (or push) grow from 3.

Limitation to just two or three, is a huge task for volunteering.
A dozen is more manageable if everyone is/was active, but we aren't all active at the same time, some of us are dormant, or get busy on other things, while others have plenty of free time at the moment. 56 allows someone in the group to chip in if some merges appear stagnant, or could use an assist.

If there is a concern, then, dropping a private email between the 56 and CCing the core 3 would be better than making public examples of some contributors. Some will agree to let go, others will request to continue their status. FontForge isn't like the kernel, maintained by a plethora of thousands of developers (volunteer, as well as paid-for organizations, etc). FontForge is a complex piece of software that catches the attention of a few developers, and more often than not, they became contributors with push/merge status based on what they did, or what they can do to help.

**Comment by ctrlcctrlv** [comment]
Even a dozen people is not 56 and represents a substantial improvement

**Comment by JoesCat** [comment]
Don't forget churn is a lot lower. :-)

**Comment by skef** [comment]
I should clarify that I'm fine with whatever policy the FontForge org (whatever that may be) adopts. I was added informally (I didn't ask) and it seems fair to remove my access on the same basis. I'm just as fine with making no changes. 

I will say that, on a practical level, if the (or "a") goal is to have all PRs reviewed it makes sense to give push access to active (and "trusted"?) reviewers and somewhat less sense to give other users access. However, I suppose that in a world of constrained resources the problem of who is an "active" reviewer and how do deal with a dearth of reviewers is not very different from that of who is an "active" contributor and how to deal with a dearth of contributors. 

On this specifically:

> The only subtle changes to occur are likely at or near HEAD, git history will be out of sync if you try to slip something lower than HEAD. There may be one, two, three developers currently at or near HEAD that might notice a git history out of sync, others below that point won't know.

If I haven't noticed any commits going in via PR I'm personally unlikely to sync. If I have noticed commits I'm likely to sync but unlikely to check the contents in any detail. Therefore if everyone were like me a sneaky change might not be caught. That said I have noticed a direct commit or two, but each was fine and justifiable (in my opinion). (A build file fix here, a travis tweak there...)

**Comment by blipvert** [comment]
I'm fine with limiting access to a core group.  Even when I was very active in the project, I rarely ever pushed my own commits.

**Comment by frank-trampe** [comment]
I know that Github keeps adding management features. Is there a way we could just block pushing to master?

**Comment by JoesCat** [comment]
Looking at my "settings" for my fontforge-fork, it doesn't appear to differentiate much between push or merge.

I do see that in "branches" the default is "off" for {Allow force pushes - Permit force pushes for all users with push access.} This I think is good for preventing pushing something lower than HEAD into master branch.
There is the option of merging into a non-master branch (call it a secondary master if you want), then an admin would have to merge it to the true master, but that will put a heavy load on the core maintainers. This can work ok in a commercial/work environment, but it's not good for a small crew of volunteers... plus it puts a lot of brakes on developers that really want the satisfaction of seeing their contributions merged into master (quickly). I'd recommend against choosing this here.

**Comment by ctrlcctrlv** [comment]
Even if they can only push to HEAD, and not lower than HEAD, they can write contributions with our names, which until recently would not even be differentiated, but now (since GitHub added squash merges to the interface) are differentiated as e.g. "@JoesCat authored and @ctrlcctrlv committed", even if I authored the patch and just put your name on it.

**Comment by ctrlcctrlv** [comment]
By the way, I will try to come up with a list of names to be removed, with the understanding that just having a small core of around 5 people has been rejected. I will attempt to get us to around 20 names instead.

**Comment by JoesCat** [comment]
That's a good point. Looking through the settings, I also saw in branches -> {Require signed commits, Commits pushed to matching branches must have verified signatures.} which is default off.

This limits merges and pushes to either using the web interface, or if someone knows how to enable signing their own pushes, this as well. Do note that someone that can sign their own commits on a git push can also enable their git to do autosigning too so don't use this as a way of saying "the code is verified and signed".
The main CON, I think is, you probably cannot give someone credit as easily for their efforts. Translators are the first that come to mind - lots of work and effort, but git is not something they use easily. to a lesser degree - other contributors who've added something useful but haven't mastered git.

**Comment by JoesCat** [comment]
I agree - 5 would be brutal. A bump-up in activity, cut in spare time, vacations, travel, sick, disagreement, or changes in direction. One or two people move on, and suddenly you've only got 80%, 60%, 40% ability to function effectively.

@skef,
> If I haven't noticed any commits going in via PR I'm personally unlikely to sync

I didn't use a good choice of words saying sync, but I do recall working with someone and finding my git history not matching the repo ... evidently, it turned out that the entire repo was getting force-pushed when they committed new patches. Argh! Based on this experience, I very much recommend ensuring force-push is "off"

**Comment by ctrlcctrlv** [comment]
I recommend @frank-trampe divest the following of access:

1. @cicku&mdash;Some commits in libuninameslist in 2013 do nothing to change my opinion. Easily insulted. Class C.
2. @ahyangyi&mdash;one PR in 2013, hasn't contributed since. Class C.
3. @Alatius&mdash;long time contributor for many years, even helping George Williams. I actually used his detective work from 2010 to open a PR in 2019. Sadly, seems to have moved on. Class A.
4. @anoxic&mdash;Only ever contributed to website, certainly if they start that again they don't need to be able to push to the main repository. Class C.
5. @aoifemooney&mdash;no commits I can find. Class C.
6. @bevan7&mdash;same rationale as @anoxic. Class C.
7. @&zwj;blipvert&mdash;Long-time contributor, agrees with me, so not mentioned. Class B.
8. @&zwj;behdad&mdash;he agreed with me above, so has not been mentioned. Class A as he's a recognized expert.
9. @coolwanglu&mdash;long-time contributor, last contributed in 2014. Class B.
10. @dmeranda&mdash;last contributed in 2012. Class C.
11. @dolsup&mdash;contributed a Korean translation in 2015. Class T.
12. @erinmclaughlin&mdash;same rationale as @anoxic. Class C.
13. @garyritchie&mdash;same rationale as @anoxic. Class C.
14. @georgd&mdash;has seemingly never contributed to the main repository. Class A as he made EB Garamond.
15. @JeremieD&mdash;no commits I can find. Class C.
16. @jhps&mdash;last contributed in 2013. Class B.
17. @JohnWong&mdash;contributed a Chinese translation in 2014. Class T.
18. @jrbastien&mdash;contributed a French translation in 2017. Class T.
19. @kartikm&mdash;contributed primarily documentation, last in 2014. Class C.
20. @keevee09&mdash;same rationale as @anoxic. Class C.
21. @kelvin13&mdash;same rationale as @anoxic. Class C.
22. @Kemie&mdash;updated some icons in 2012. Class C.
23. @larsenwork&mdash;lots of commits, unfortunately last in 2015. Class A.
24. @lemzwerg&mdash;I think we've corresponded before, but no commits I can find in the main repo. Class C.
25. @lpsandaruwan&mdash;no commits I can find. Class C.
26. @mhosken&mdash;works at SIL, unfortunately last contributed 2014. Class B.
27. @michal-n&mdash;has contributed many translations. Class T.
28. @MichinariNukazawa&mdash;found a bug in 2014; fixed `.gitignore` in 2016. Class C.
29. @monkeyiq&mdash;did it for pay, ignores all requests for comment about the work he did. Class D.
30. @mozbugbox&mdash;last contributed in 2014. Class B.
31. @mpetroff&mdash;last contributed in 2014. Class B.
32. @n8willis&mdash;same rationale as @anoxic. Class C.
33. @nikhilindia&mdash;no contributions I can find. Class C.
34. @pathumego&mdash;no contributions I can find. Class C.
35. @raphlinus&mdash;contributed my favorite component, Spiro. However, that was in 2007. It doesn't seem fair to *not* add him. Class A.
36. @routters&mdash;same rationale as @anoxic. Class C.
37. @rrthomas&mdash;last contributed in 2014. Class B.
38. @summerstyle&mdash;same rationale as @anoxic. Class C.
39. @tomlechner&mdash;made some substantial contributions in 2012. Class B.
40. @tshinnic&mdash;last contributed in 2014. Class B.
41. @vernnobile&mdash;fixed some icons in 2013. Made some cool fonts in FontForge. Class C.
42. @vitalyvolkov&mdash;same rationale as @anoxic. Class C.
43. @xen&mdash;no contributions I can find. Class C.
44. @yesyayen&mdash;changed one word in 2013. Class C.
45. @zerng07&mdash;no contributions I can find. Class C.

If all my recommendations are followed, **eleven** will have push access. 

I recommend the following be moved from the core "Owner" team and into the regular "Member" class:

1. @mskala&mdash;major long-term contributor, last in 2016. Class A (as regards this "demotion").
2. @adrientetar&mdash;major long-term contributor, last in 2014. Class A.

I divided them into classes, which are not hard rules (obviously), just my preferred guidelines:

Class A&mdash;Can receive access again just by asking, if accompanied with a PR.
Class B&mdash;Can receive access again after 1 approved PR.
Class C&mdash;Can receive access again at discretion of Owners.
Class T&mdash;I don't think translators should have access because as @JoesCat notes, Git is complicated. That's not to say translators can't _also_ contribute code, so this is class is for translators who only contributed translations.

If you see this in your mailbox and get insulted because I missed your contributions, relax, and just let me know the email/name you contribute with in the Git log, which was what I primarily consulted. If I didn't miss any contribution of note, and you're insulted for the sake of being insulted, be insulted then. Especially if you have an "Anonymous" business suit as your icon and miss the irony of using a 4chan symbol while being easily offended.

**Comment by dolsup** [comment]
I partially agree with @ctrlcctrlv as a person in Class T. 
I think the people translate fontforge itself don't need to have push access because It seems to the project now uses [crowdin](https://crowdin.com/project/fontforge) for translation contribution.

But, In case of the [website team](https://github.com/orgs/fontforge/teams/website/members), they have access to only 2 repos ([fontforge/designwithfontforge.com](https://github.com/fontforge/designwithfontforge.com), [fontforge/fontforge.github.io](https://github.com/fontforge/fontforge.github.io)) and there is no external solution to translate these websites yet. They need to directly modify text in code files.
But of course, even if without direct push access, there is a way that translation contributors can still make their jobs, by making a fork and do somthing and make PRs to main repo.

Sorry for my long-term absence. I'll take a look asap.

**Comment by tshinnic** [comment]
The simplest criterion that got most agreement at Wikipedia regarding
admins ageing out of privileges was date of last contribution *as an admin*.
The rationale that worked to justify this was - if you haven't contributed
your attention *at an admin level recently* then you probably aren't
current enough with rules/problems/directions/organization to not be
dangerous.

So after a year of admin inactivity, that bit is held in abeyance, with the
right to ask for the privilege to be restored at any point for renewed
admin activity, and assuming review of recent doings at WP. Please note
that this change at WP was made necessary when a couple admin accounts were
not being watched and got cracked.

So while the above list was sorted alphabetically, it could also be sorted
by date of latest contribution, or more particularly by date of last
admin-like contribution. That might make things clearer.

In my case it would point out that I never trusted myself enough (humble
and lovable I am) to push anything, but relied on others to review PRs.

As for urgency for all this, who knows?  As for need, absolutely definitely
needed to have only a core group have the core privileges.

In August 2018 one person threw his toys out of the pram all over Github
projects, including unilaterally changing the license for the Lerna
project, affecting as many projects as he had reach into. It was very ugly
to watch the ensuing mayhem and recovery.

It proved that only people who can put the good of the project at the heart
of their actions should have the core privileges. A sustaining number of
people, to be sure. But in a healthy project, promotion should be due to
project's needs.

--
I'm a pessimist about probabilities; I'm an optimist about possibilities.
    Lewis Mumford  (1895-1990)

**Comment by lemzwerg** [comment]
Well, my last commit was 8caf77b in March 2019...  Unfortunately I don't have enough time to invest more time into fontforge.  There are parts that would deserve much more love, for example, the TrueType debugger...

**Comment by ctrlcctrlv** [comment]
@lemzwerg I'm so sorry, I didn't realize that you're Werner Lemberg, FreeType developer, has `gnu.org` email, etc. Please disregard, I will take you off the list. We have indeed communicated before, through multiple channels.

**Comment by xen** [comment]
I'm ok if you remove my access. I think number of people with admin access should be limited and all who want to participate should send pull requests.

**Comment by cicku** [comment]
I'm OK as well.

**Comment by ahyangyi** [comment]
@ctrlcctrlv 
I had one PR and one even earlier non-PR commit which you missed. (And, a private fork, but it is out of question here...*).

Anyway, I'm OK with removing write access. I would want people to review my PRs even if I somehow retained my write access anyways, so that's very fine.

But leave my membership. I love that badge.

* funny fact about my private fork: it adds some extra safeguard code in places that were known to crash, but since it's just hiding the bugs rather than fixing them, I never considered PR'ing it to the master branch. Funnily, my patches had absolutely no merge conflict in the past 6 years, meaning that while I didn't really fix the bugs, probably nobody else did either... If the parts of code I touched were so pristine over the course of 6 years, maybe @tshinnic's argument that one year's inactivity means you are not current enough is... weaker than it looks.

**Comment by ctrlcctrlv** [comment]
(I only considered accepted PRs)

**Comment by frank-trampe** [comment]
Since there seemed to be widespread consensus, I have started implementing this and have pared the "Owners" group down to me, @davelab6, and @jtanx. It seems to me that the easiest way to implement the team changes is to make a new smaller "Developers Active" group. @ctrlcctrlv, do you have a positive list in your notes?

@ahyangyi, members shall remain members, by the way.

**Comment by frank-trampe** [comment]
There is a way to disable force pushes to master. I just did that for this repository. If it does not cause problems, we can roll it out elsewhere.

**Comment by davelab6** [comment]
I'm OK with not being in the Owners group. I nominate @ctrlccrlv to take my
place :)

**Comment by frank-trampe** [comment]
@davelab6, too late for that. I already blocked your escape route with a flaming tanker truck.

**Comment by ctrlcctrlv** [comment]
This has gotten really awkward for me.

**Comment by ctrlcctrlv** [comment]
I consider the issue now solved, and security around the master branch much improved. Thanks all.
