### ISSUE TITLE
Generate character map python png

### ISSUE THREAD

**Issue by Krulvis** [fontforge/fontforge#4093]
I would like to create PNG previews of fonts that display a collection of various glyphs.
Is it possible to generate a character/glyph map that displays selected glyphs into one PNG with equal spacing between each glyph?

I looked through the documentations and saw that you can generate a PNG from a single glyph:
```
font = fontforge.open("droids.ttf")
font["A"].export('a.png')
```
But it seems redundant to create a PNG for every glyph and then paste them together in a new file, is there any other way that this can be done through that I am missing?

**Comment by skef** [comment]
No, I don't believe there is any such system. 

There is of course the metrics view, which can be screenshot. However, that will display the glyphs with spacing and kerning applied rather than evenly spaced. One could of course copy the font, delete any kerning, and reset the spacing however one wanted with a simple python script. That would make the metrics view "behave" as you want.

**Comment by ctrlcctrlv** [comment]
Actually, @skef is wrong. There is such a system. I only know because I have dug very deep into FontForge's UI code. (See #3659.) The &laquo;Print&raquo; dialog implements a &ldquo;SplineFontTextArea&rdquo; (`SFTextArea`, sftextfield.c), which can be exported as a PNG.

Write something in the print dialog, right click, &laquo;Save as Image&raquo;.

This is probably also accessible via the scripting interface, and if not, it should be. Check out `printSetup`, `printSample`.

Closing as invalid for now.

**Comment by skef** [comment]
@ctrlcctrlv That does avoid the screencap step but doesn't address the spacing issue.

**Comment by ctrlcctrlv** [comment]
If you want equal spacing, rasterize one of the outputs of the print function.

**Comment by jtanx** [comment]
note #2171
