### ISSUE TITLE
Expand stroke - only outside of path?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4107]
Since we are still discussing improvements to Expand Stroke, this is another Illustrator feature that I wonder about the feasibility of implementing.

![image](https://user-images.githubusercontent.com/838783/73148291-8a05f480-40f6-11ea-91b0-3adc9822ff5a.png)

[Another example](https://community.adobe.com/t5/illustrator/stroke-text-outside/m-p/4528154#M14389)

I forgot to ask @skef this last we talked. It is useful for making fonts and as far as I know not possible in Inkscape without hacks

**Comment by skef** [comment]
This is one of those cases where implementing the feature probably wouldn't be that much work but the existing functionality gets you close enough that it's questionable whether the work and interface would be worth it. 

I'm not sure whether this request is about producing the above all at once, or producing separate glyphs with those outlines so that in a multi-layer font they overlap when shaped. Only the latter strikes me as a font-specific use. Either way, however, you get quite close to that just by selecting "External Only".

The main missing bit is that you'll have to manually remove the smaller contours corresponding to the counter-clockwise contours. So we could add a control "Both/CW Only/CCW Only" control and be 90% of the way there. 

The other missing bit is that depending on the shape of the letter and the size of the expansion you might get little holes. I just did a test that included Libertinus's captial F and diameter 200 and got a little hole in the upper part. To remove those you would have to algorithmically search them out after the Remove Overlap pass.

However, how hard is it to delete those contours manually? Maybe 10 seconds per layer per glyph (assuming External Only is checked)? 

There might be other uses for CW/CCW only and it's easy enough to do, so that could be worth thinking about. On the other hand @ctrlcctrlv has elsewhere already expressed worries about the complexity of the dialog. (Sadly, a UI generally includes all the features that interest a given user and also those that don't.)

**Comment by skef** [comment]
BTW an Arcs join is exactly what you want for automating this effect ...

**Comment by skef** [comment]
I don't think you could create an SVG font with multiple outlines like in your link because SVG doesn't have layers, just opacity and ordering. The shaper would therefore have no way of sorting out what to show and omit among the overlapping boundaries. I really don't know anything about COLR except that it is layer-based, but that at least means that a COLR font would have the needed information.

**Comment by ctrlcctrlv** [comment]
I think that showing multiple glyphs has caused confusion. Please consider "GDSE" to all be one glyph, (let's say, similar to ㎓) and the output to be expected if it's one glyph being stroked.

**Comment by skef** [comment]
Everything I said applies the same way.

**Comment by ctrlcctrlv** [comment]
OK, so your answer would be, assuming you want to apply a stroke of width 40 to the outside of a glyph, instead apply a stroke of width 40*2+(distance between center of closed shape to its outside), and use arc joins. Right?

**Comment by skef** [comment]
Sort of -- I'm not sure what the "distance between the center of ..." part is about. We use a diameter to specify a circular nib but it basically draws an offset at r=d/2 on the left of the contour and one at r=d/2 to the right. The offsetting process traces a contour, not the center of a shape. 

If you're wondering how to do this with a glyph this itself generated via Expand Stroke you would just do it in two stages: First generate the glyph and then offset it again to make the "outline".

Here I just pasted three Libertinus glyphs into a new char and stroked at d=200 (and therefore r=100) with Arcs and "External Only":

![foo](https://user-images.githubusercontent.com/6175836/73158608-2e594e00-4099-11ea-8791-4dbbbab69fd0.png)
 
You can see the little hole in the F and the "counter-external" holes in the Os. But it takes a couple seconds to delete those.

**Comment by ctrlcctrlv** [comment]
Got it, thank you. I think you're right that no new function is necessary. After playing with it for a while I definitely see the benefit of arc joins now, too! Really helps with these large stroke widths.

**Comment by skef** [comment]
Yeah -- at large radii miters (the usual approach) become pretty obvious.
