### ISSUE TITLE
Build as a static library for use in lambda

### ISSUE THREAD

**Issue by sis-dk** [fontforge/fontforge#4161]
I followed the steps in the INSTALL.MD file to build fontforge from source. But it doesn't allow me to build with shared libs switched off and python extensions enabled. I would like to run fontforge inside a python code on AWS lambda. Could someone please guide me on how to go about a setup that would allow me to run this on lambda?

**Comment by skef** [comment]
I'm assuming you're building from a recent master with CMake rather than an older version with autotools. 

You probably want `-DENABLE_GUI=off` 

Beyond that, it won't work to build *no* shared libraries because even if the python modules were mostly or entirely statically linked they themselves need to be shared libraries. 

The folks here can't solve every problem for every distribution or environment (and are pretty selective about working on such problems), but I'm willing to go down this road a bit. What is the problem with shared libraries and lambda; why do you want to avoid them?

**Comment by jtanx** [comment]
It makes no sense for a python *extension* to be statically linked to the python libs, as then your extension could be linked to a different version of python to what it runs under (plus even if it were the same, it's now carrying around its own copy of the python interpreter inside of it?)

If you instead mean you want to run a fontforge python script (i.e. via `fontforge -lang=py -script blah.py`) then you should be able to staticaly link by setting `-DENABLE_PYTHON_EXTENSION=no`.

Also I hope you're aware that FontForge shouldn't be used on untrusted input, and/or that you have heavy sandboxing in place...

**Comment by skef** [comment]
Closing this as the deep issues are beyond the scope of our build process.
