### ISSUE TITLE
segfault in SFDDumpUTF7Str

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#4164]
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
fontforge-20190801-2.fc31.x86_64
Fedora 31

Found issue with this font https://fontlibrary.org/en/font/old-standard sfd files

- [x] The behavior you expect to see, and the actual behavior
I narrow down that issue to this commit
https://github.com/skef/fontforge/commit/8da6d56bf7af2d25f779e52edef61b2fd4557b3c?diff=split#diff-3e858c47b8dd6fd0be7e24df08d53e7dL7995

if this commit snippet that changes SFD_GetFontMetaData() is reverted then issue gets fixed.

So, I opened one of sfd file and found it does not have Em Size in power of 2. Its default value is 1000. I tried to change 1000 to 1024 and fontforge crashed.

fontforge should not crash and allow to change Em Size value.

- [x] Steps to reproduce the behavior 
Like explained above, open sfd file from upstream archive, try to change Em size, fontforge crashes as

> (gdb) bt
#0  SFDDumpUTF7Str (sfd=0x555556f7dd30, _str=0x6e61745320646c4f <error: Cannot access memory at address 0x6e61745320646c4f>) at sfd.c:211
#1  0x00007ffff7749a6c in SFD_DumpSplineFontMetadata (sfd=sfd@entry=0x555556f7dd30, sf=sf@entry=0x555555840bd0) at sfd.c:2355
#2  0x00007ffff7d24786 in DumpSplineFontMetadata (sf=sf@entry=0x555555840bd0) at fontinfo.c:4009
#3  0x00007ffff7d24834 in GFI_OK (g=<optimized out>, e=<optimized out>) at fontinfo.c:4026
#4  0x00007ffff79a84ac in GButtonInvoked (b=b@entry=0x5555570f77b0, ev=ev@entry=0x7fffffffcd20) at gbuttons.c:257
#5  0x00007ffff79a892e in gbutton_mouse (g=0x5555570f77b0, event=0x7fffffffcd20) at gbuttons.c:485
#6  0x00007ffff79b0ce8 in _GWidget_Container_eh (gw=gw@entry=0x5555570354c0, event=event@entry=0x7fffffffcd20) at gcontainer.c:304
#7  0x00007ffff79b143b in _GWidget_TopLevel_eh (event=0x7fffffffcd20, gw=0x5555570354c0) at gcontainer.c:747
#8  _GWidget_TopLevel_eh (gw=0x5555570354c0, event=0x7fffffffcd20) at gcontainer.c:618
#9  0x00007ffff79fb85a in dispatchEvent (gdisp=gdisp@entry=0x5555555fb5e0, event=<optimized out>, event@entry=0x7fffffffcee0) at gxdraw.c:3283
#10 0x00007ffff79fd95e in GXDrawEventLoop (gd=0x5555555fb5e0) at gxdraw.c:3391
#11 0x00007ffff7ddfefa in fontforge_main (argc=<optimized out>, argv=<optimized out>) at startui.c:1416
#12 0x00007ffff7a731a3 in __libc_start_main () at /lib64/libc.so.6
#13 0x00005555555550ae in _start ()

- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
I'm confused. How can you be using the 20190801 release, but your issue is also due to a commit from last month?

**Comment by pnemade** [comment]
Fedora security team always checks upstream for any CVE bugfixes. As per https://github.com/fontforge/fontforge/issues/4084#issuecomment-570705717 that fix is CVE fix and Fedora package maintainers need to patch the code to have Fedora packages free from any known security issues.

Downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1790041

**Comment by ctrlcctrlv** [comment]
Oh, well, how can we tell Fedora not to do that for our project? Because that's objectively the wrong thing to do for FontForge, as I mention in the issue.

We know that #4091 (PR to fix #4084) broke stuff, and #4100 went in immediately after to fix it. Honestly, I find it ridiculous that Fedora is cherry-picking our repository like that, especially because FontForge has so many possible ACE scenarios that all of us are in universal agreement (most recently https://github.com/fontforge/fontforge/issues/4161#issuecomment-586226722) it **shouldn't be expected to be secure** or used in a server without a sandbox.

Seriously, do not cherry pick this repository then ship that code to users. Wait for us to make releases. Security fixes are not urgent for this project.

If you could let them know our displeasure, we'd appreciate that. Guess we need to cut a new release sooner rather than later now, great. :roll_eyes:

**Comment by skef** [comment]
With respect to security Fedora is likely going to do what Fedora is going to do.

Anyway, it's appropriate for the project to close this as a duplicate of #4099, which is fixed in #4100. @pnemade if you have the means encourage Fedora to cherry-pick the fix in #4100, as it is no more or less a security issue as the other ones they've been cherry-picking.

**Comment by skef** [comment]
Come to think of it, @pnemade, given the policy you could likely force Fedora's hand by filing a CVE for #4099. That would put it on their list and make them pick up its fix.

**Comment by pnemade** [comment]
Thanks @ctrlcctrlv and @skef 

I have added comment to downstream CVE parent bug that fontforge upstream recommends not to cherry-pick upstream commits.

**Comment by ctrlcctrlv** [comment]
Thank you @pnemade. In my mind this makes cutting a release more urgent. We might need to think about putting off some priorities until the next release.

**Comment by skef** [comment]
The python extension work is going to take longer than I had hoped. (I need to do some UI work after all, ultimately for security reasons I won't go into here.) I see no obvious reason we can't cut a release with more or less what we have now. That would mean putting off the contrib discussion, but not necessarily for long if (for example) we do a maintenance release in a month or two. 

I'm currently most bothered by the lack of a fix for #3699 / #2556 . Unfortunately the problem is upstream of the symptom so I can't yet say much about the scope. If folks wanted I could shift my efforts to that problem and maybe we could do a release once I have it sorted or have given up.

**Comment by ctrlcctrlv** [comment]
Yes, please. We need to cut one pretty much ASAP. Like, I want to cut one by the 21st, my birthday. :cake: 

The Arch packagers on Twitter told me they do the same thing as Fedora. It's probably industry standard, I wouldn't be surprised if other distro security teams operate the same way.

It's true, we could file another CVE, but that seems like a hack and also dishonest.

**Comment by skef** [comment]
It's not at all dishonest. CVEs are intended to be tracked at the patch/PR level -- the database model is intended to support cherry-picking. If we or someone else filed a CVE for something that wasn't actually a crash *that* would be dishonest. But #4100 fixes a repeatable crash that some distros have introduced into their release of FontForge and haven't patched. 

If the dishonesty you're thinking of is "we don't want distros to cherrypick and this encourages that model" I would say it's actually model-neutral. Non-cherrypickers won't be called on to pick it up, cherrypickers will.

**Comment by ctrlcctrlv** [comment]
Oh, OK. I understand. If you consider crashing to be a security problem then I guess you can file a CVE. I thought it was dishonest because I don't understand how crashing affects security. But then again I don't work as a "pentester" or "computer security expert" or "defensive security consultant" or w/e.

**Comment by skef** [comment]
Ah, yeah. The premise of SegFault-as-security-problem is that it might be possible to cook up, say, a very particular sfd file and use the crash point to cause the program to start executing instructions supplied in the file. All crashes (especially those caused by buffer overflows, as the buffer is a natural place to introduce nefarious code) are seen as potential sites for such exploits.
