### ISSUE TITLE
Issues installing in macOS (Could NOT find GDK3)

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#4176]
macos 10.4.6
fontforge master (46704cc75744965c7d11a434332f8e4a81d42bfc)

I'm just installing via source code because homebrew project doesn't build python extension anymore.
after solving some dependencies (had to uninstall gstreamer) I'm stuck in this one
GDK3
```
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GDK3: Found unsuitable version "", but required is at least
  "3.10" (found )
```
how can I proceed with installation?
any way of installing via homebrew? I only need the python extension
Thank you

**Comment by skef** [comment]
I'm not the right person to answer this except that I'm reading it just after it's opened and *may* be able to help on short notice.

The issue here is that a somewhat recent version of GTK 3 needs to be installed in order to build with the UI. You could try building entirely without the UI with `-DENABLE_GUI=off` but not many people do that. So I would think it would be easier to try to pull down GDK 3 with Homebrew via GTK 3, most likely by way of something like this: https://formulae.brew.sh/formula/gtk+3

However, if you're really still running Tiger this may be a tricky installation. Some of our dependencies may not go back that far.

**Comment by skef** [comment]
In any case the project's CMake guide is here: https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge

**Comment by jtanx** [comment]
Yep, you need to `brew install gtk+3` (or whatever the gtk3 package is).

If it's still not working, try this:

```
pkg-config --cflags gdk-3.0
```

If it reports any errors, paste them here. I know there used to be one with libffi which required manual fixing of the PKG_CONFIG_PATH, but on catalina it seemed to work without that.

**Comment by skef** [comment]
The OP left some thumbs-up on this; I'm going to close for now and will reopen if requested.

**Comment by dimitre** [comment]
Question: I'm trying to compile and it is missing ```distutils``` 
I think it was removed in 3.12. should I downgrade to 3.11 to finish installing? any other way around?

**Comment by iorsh** [comment]
> Question: I'm trying to compile and it is missing `distutils` I think it was removed in 3.12. should I downgrade to 3.11 to finish installing? any other way around?

This branch should work: https://github.com/iorsh/fontforge/tree/py_sysconfig
