### ISSUE TITLE
Letter drawn but doesnt show up in window

### ISSUE THREAD

**Issue by FontforgeUser** [fontforge/fontforge#4178]
When I draw a character, the character doesn't show up in the corresponding window. (See Screenshot). I through that the characters woudl show up. I'm not sure whether there is anything that I need to select? Could you please advise. I am using version 01st August 2019 on Windows 7 64bit version

![Screen Shot 02-21-20 at 07 59 AM](https://user-images.githubusercontent.com/61307572/75015454-87da5000-5480-11ea-96ca-a12050357541.PNG)

**Comment by skef** [comment]
Only *closed* "paths" or "contours" are displayed in the FontView window, because these are the only ones that will be interpreted correctly by a font rasterizer. 

There are a number of ways to close a path. Given the approach you are taking I recommend running "Expand Stroke" on your numeral to turn the line into a shape. Either choose "Element -> Expand Stroke ..." from the menu or type Control-Shift-E. Then, as a start, just click "OK" or press the Enter key to use the default arguments. You should see a shape created from your line which will also appear in the FontView window. 

Alternatively, you might want to look at this page of the documentation: https://fontforge.org/editexample.html#CharCreate
