### ISSUE TITLE
Barely visible accents of Central European characters in overview

### ISSUE THREAD

**Issue by zslevi** [fontforge/fontforge#4234]
![latin2-Hun-FontForge](https://user-images.githubusercontent.com/62501513/77247162-b5a4e700-6c2e-11ea-8b9e-cb3ba88e334e.png)

The above characters are very hard to tell apart in overview mode. It's especially troublesome when the glyphs aren't added yet.

I'm using FontForge version 20200314 on Windows 7.

**Comment by skef** [comment]
Try installing DejaVu Sans on your system (or updating the bug if it is already present).

**Comment by zslevi** [comment]
I already have Dejavu Sans installed. I think the problem is the small cell height allotted for these characters.

**Comment by skef** [comment]
Ah -- turns out I *didn't* have DejaVu Sans on my system. 

The cell height is based on the ascender and descender heights in the font. Turns out DejaVu Sans is putting those accents way above the ascender (which you can verify by opening it in FontForge ...)

Try a different font. Google's Noto Sans worked well in my testing.

**Comment by zslevi** [comment]
I changed for Courier, it works now.

Note for other users: the settings can be found under 
File -> X resource Editor -> Font View

You also has to click "Save As" and give a path for the preferences file, clicking Ok won't save your settings.
