### ISSUE TITLE
Support better selection of FontInfo font

### ISSUE THREAD

**Issue by KamilLanda** [fontforge/fontforge#4238]
FontForge version: 20200314 (also in older versions), Win10Profx64

Please is it possible to set some distance in the list of the GSUB/GPOS lookup names? I tried all settings in the File/ X Resource Editor, but no success. 
![distance-idea](https://user-images.githubusercontent.com/61148366/77247804-c8bab580-6c34-11ea-8de4-943e1a9e5345.png)

**Comment by skef** [comment]
It's very common in the FontForge code to choose the height of an area based on font metrics. So adding a feature for this case would be excessive. 

This is what the list looks like on my system (Arch Linux, but that shouldn't matter):
![lookups](https://user-images.githubusercontent.com/6175836/77273301-75feef00-6c70-11ea-91e7-c0d8949ab907.png)

So the problem here is likely your font, which FontForge is choosing inelegantly by looking for `SANS_UI_FAMILIES` directly rather than defaulting to, say, `GGadget.Font`. That should be fixed (in `fontinfo.c`). 

In the mean time, however, you can change the font yourself by saving a resources file and adding a`fontforge.FontInfo.Font: ` line with a font specification like `400 12pt sans` (or whatever). Just pick a font that, unlike the one on your system, has reasonable metrics. This workaround isn't sufficient to close this issue, unfortunately, because a) there is no interface in the reference-setting dialog for this, and b) it will get deleted every time you save using that interface. 

Still, this is a reasonable work around for the time being. Give it a try.

**Comment by KamilLanda** [comment]
I add line to the preference file
`fontforge.FontInfo.Font: 400 11pt noto sans`
and it is super, font "Noto Sans" is very good readable for me, thanks a lot :-). 
 ![distances-OK](https://user-images.githubusercontent.com/61148366/77306071-64145f00-6cf7-11ea-964e-90917e1617cb.png)

**Comment by skef** [comment]
This would benefit from *some* kind of fix. We could at least make the default font chosen be the GGadget font rather than picking it "fresh" in `fontinfo.c`.
