### ISSUE TITLE
data missing from exported UFO font

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4286]
hi
I don't know what kind of data could save on a UFO font format but the following data are missing from exported UFO fonts:
-ZWSP , ZWNJ , ZWJ ... and glyphs like them probably
-Grid Fitting data (gasp)

and in the lastest version, fontforge can't parsing the feature file of exported UFO (when sb trying to open it with fontforge)

![fontforge_2020-04-18_23-05-56](https://user-images.githubusercontent.com/25493297/79661659-9b2c4200-81c9-11ea-9050-8c22052ebe68.png)

**Comment by skef** [comment]
Ideally feature files would round-trip without functionality loss (as opposed to names and table formats), but in general UFO is currently an export format for FontForge rather than a "save" format.

**Comment by aminabedi68** [comment]
you should consider that UFO is a cross-application format and must not be affected by the host programs(fontforge I mean) because other font softwares can't parsing the font, sb tells me the structure of fontforge is one step closer than UFO to implement opentype (maybe this is a clue(?))

**Comment by aminabedi68** [comment]
sorry, i love fontforge and i know you are working on sevral complicated things that l can't understand, but a large number of users need UFO format working more efficient beacuse many times when we design a font we may need to move that into other softwares or working on that with some handmade or mini tools developed for UFO format. please fix it once forever. thank you.

**Comment by skef** [comment]
I don't see any documentation on grid fitting parameters or hinting more generally in the UFO 3 spec.

We've had a number of issues filed asking FontForge to duplicate the beyond-spec convention of this or that other font editor (often Glyphs.app). As one contributor I don't have any objection to following such conventions; it seems like a productive way to move forward. However, I'm not personally going to chase down that info. If folks want FontForge to do that sort of thing they would be well advised to describe in detail what the desired behavior is, down to specific files and tags.

As far as feature files are concerned, that area could use a significant overhaul but some of the issues are wrapped up in the UI dialogs, which makes it a bit of a mess. (It might also be more or less thankless work in practice.)

**Comment by ctrlcctrlv** [comment]
UFO is not, and never will be, FontForge's source format. It is an output format.

At most, we will add currently discarded data to that output format from SFD, either using our own extensions to UFO or parts of the UFO spec. An option not to mangle the `features.fea` file when saving to UFO is possible too. (Essentially, an option not to write any `features.fea` at all.) But your expectations need to be realigned with our project's actual goals.

Closing per misalignment. Please open one issue for each type of data you'd like saved into UFO. So one issue for `gasp`, one issue alleged ZWSP failure (I assume due to `IsWorthOutputting` being wrong), one issue for Spiro (I know this is also missing and was planning to open an issue eventually), et cetera.
