### ISSUE TITLE
Crash in SplineSetStroke in version 20200314

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4315]
The following script crashes FontForge 20200314. This is a regression from version 20190801. I am using macOS 10.14.6.
```python3
import fontforge
font = fontforge.font()
glyph = font.createChar(0x30)
pen = glyph.glyphPen()
pen.moveTo((0, 0))
pen.lineTo((1, 0))
pen.lineTo((0, 0))
pen.endPath()
glyph.stroke('circular', 1, 'round')
```
[Here is a crash report.](https://github.com/fontforge/fontforge/files/4568596/fontforge_2020-05-02-150223.txt)

**Comment by skef** [comment]
I'm looking at this with ASAN ...

**Comment by skef** [comment]
This crash ultimately stems from stroking an open contour that has the geometry of a closed contour. 

It's easy enough to detect an open contour that starts and ends in exactly the same place and treat it like a closed contour. But given that contours can also end close to where they begin that isn't a great fix for this. 

I made a build that skipped the post-processing steps (described below) and reproduced the stroke to generate this output:

![o_together](https://user-images.githubusercontent.com/6175836/80892905-9adc7e00-8c82-11ea-935d-246ae78d3ce0.png)

Moved apart from each other the two contours look like this:

![o_apart](https://user-images.githubusercontent.com/6175836/80892939-e727be00-8c82-11ea-90ba-8e4e3d948c99.png)

You can think of the top contour as analogous to the outside of an "o" and the bottom contour as analogous to the inside. As sometimes happens the latter is clockwise and entirely contained in the former, which is analogous to the case of a closed contour that, when stroked, has no internal space (the stroke radius overwhelms the interior dimensions). When the source contour is closed these redundant contours are typically removed by RemoveOverlap(). 

When a contour is open the code first produces a left side and a right side. Then it puts a cap on the end of the left, merges the new end of the left with the start of the right, then puts a cap on the end of that output and closes the result. It uses `SplineSetJoin()` for both the merging and the closing. It's this sequence of steps that results in the crash. 

Given that the input is strange and could/should have been a closed contour, I think the fix can focus on avoiding the crash and need not return an ideal result. So I have to think more about:

1. How to alter `SplineSetJoin()` not to produce bad output when given this sort of input.
2. How to change the code that calls `SplineSetJoin()` in this case to reflect the first changes. 

I haven't looked in depth but `SplineSetJoin()` seems to be closing the first contour and then somehow merging it with the second. I think that's because the inner loop isn't checking whether `spl2` is already closed but that's just based on a glance. 

@dscorbett I assume this isn't blocking your work -- it's just something you ran into but can work around?

**Comment by dscorbett** [comment]
Right: this isn’t a blocker. I found it while trying to make a minimal case showing that version 20200314 prints far more error messages for stroking than the previous version.

**Comment by skef** [comment]
@dscorbett Most of those errors are from Remove Overlap, correct? We're currently tracking that problem in #4184 (after closing the less specific #4122).

**Comment by dscorbett** [comment]
Yes, that’s right. Thanks for the pointer.
