### ISSUE TITLE
Removing the character builder

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#4334]
I'm looking into cleaning up the Unicode library, specifically currently into dropping the [charset conversion tables](https://github.com/fontforge/fontforge/tree/master/Unicode/charset), which are unused 99% of the time because iconv is used instead (and iconv is a hard dependency).

One of the remaining uses of the hand-rolled charset conversion tables is the existence of a character composer and insertion dialog, which is [documented here](https://fontforge.org/docs/ui/mainviews/metricsview.html#entering-non-ascii-characters), and looks like this:

![image](https://user-images.githubusercontent.com/5137410/82040330-cc753080-96e9-11ea-9966-424fcdfff841.png)

I was contemplating switching it to use iconv if possible, but looking further, it turns out this functionality has been broken (read: unusable) since late 2012 (bisected to f5fbd93b1e8b653c515faacfdc48886fe950b8d9, with the introduction of the new hotkey system).

So considering:
* It hasn't been usuable for 8 years and no one has complained
* The GDK backend doesn't actually implement support to make it work anyway
* If moving to GTK/Qt this likely would not be ported over
* There exist other, dedicated tools to do something similar (charmap, gucharmap etc., alt codes etc.)

My preference is to remove it, rather than try to fix it up. Thoughts?

**Comment by frank-trampe** [comment]
I had no idea that this feature existed and probably would not have used it anyway since my adventures outside of keyboard characters are sufficiently limited to allow use of the character map. But lack of complaint isn't in itself proof that something is unproblematic. I know how long the bugfix queues at most projects are and generally don't complain about things that aren't either terrible or easy to fix.

It may be better to contemplate this as a low-urgency new feature. If somebody were working in FontForge on a special-character-intensive project, being able to enter special characters faster than allowed by copying and pasting from the character map is an upside. The Control + Shift + U entry does not work in FontForge on Ubuntu. For this use case (with which I personally lack first-hand experience), this is a useful feature.

How broken is it?

**Comment by ctrlcctrlv** [comment]
I knew about this feature, actually!

I thought you guys removed it in 2012. I've survive without it this long, don't particularly care if it comes back, especially not if it makes more important priorities harder.

**Comment by jtanx** [comment]
> How broken is it?

It's unusable.

* If you are still using the old X11 backend, then the moment you press F12, the window closes due to something in f5fbd93
* If you are using the newer GDK backend, it won't do anything because I didn't know of this at the time, and it doesn't implement the parts necessary to make it work

So the thing I'm getting at is to perform some cleanup I was originally intending, I would have to spend a decent amount of effort to make it work, for a very questionable benefit.

**Comment by ctrlcctrlv** [comment]
Yes, I thought it had been removed as I use the GDK backend and F12 no longer does anything, and hasn't for a very long time.

**Comment by skef** [comment]
Given the backend issues I also favor removing it.
