### ISSUE TITLE
Extract outline of the glyph using python script.

### ISSUE THREAD

**Issue by chunchet-ng** [fontforge/fontforge#4398]
Hi there,

Does anyone know how to extract the outline of a given character/glyph in contours using fontforge's python module?

I am new to the font creation field and would like to extract the contours for research purposes (on text detection/recognition).

Suggestions are very much appreciated!

**Comment by skef** [comment]
One option is to just export the glyph or a layer of a glyph as an SVG or glif file. The former will contain SVG "paths" of quadratic or cubic bezier curves (depending on the source font) and the latter will be in the [glif XML format](http://unifiedfontobject.org/versions/ufo3/glyphs/glif/).

Another option is to just deal with the points directly. This (pointless demonstration) script prints each point of capital S in a font:

```
#!/usr/bin/env python

import fontforge
import sys

font = fontforge.open(sys.argv[1])

glyph = font['S']
layer = glyph.foreground

for contour in layer:
    for point in contour:
        if point.on_curve and point.selected:
            print(point)
```

Point objects are described [here](https://fontforge.org/docs/scripting/python/fontforge.html#point), contours [here](https://fontforge.org/docs/scripting/python/fontforge.html#contour), and glyphs [here](https://fontforge.org/docs/scripting/python/fontforge.html#glyph). The relevant data include whether the point is on or off curve and whether the contour is quadratic (`is_quadratic` is True) or cubic (`is_quadratic` is False).

**Comment by chunchet-ng** [comment]
I followed your "pointless demonstration" and found out that points are not printed for some characters in the font. 
Ideally, I want to get all the points along the character's outline, and possibly extract their skeletons. 

Is this the most direct way of getting the points? Also, after getting the points, do i have to reconstrcut the character's outline using the bezier/quadratic curve points?

**Comment by skef** [comment]
If a glyph has printed content (as opposed to a space character) but not points it probably consists only of references. Those glyphs will be partial or complete duplicates of other glyphs. If you don't care about the duplication you can call `unlinkRef` on the glyph object first. (In the above that would be `glyph.unlinkRef()`).

As far as what you do "after getting the points", I can't say because I don't know what you're doing. If what you need is a raster image of the outline then none of this process is likely to help and you may be better off taking a different approach.

I don't know what you mean by "skeleton".

**Comment by chunchet-ng** [comment]
What do you mean by printed content? So the point.x and point.y do not represent the outline structure of the character and why would the character's glyph a partial/duplicate of another's?

Sorry for the confusion, i think we have some misunderstanding on certain terms.

1) By character outline I meant this:
![image](https://user-images.githubusercontent.com/16194241/87121746-13307280-c2b6-11ea-846e-2835c214a57a.png)

2) And for the skeleton, I meant this, or as defined in [wikipedia:](https://en.wikipedia.org/wiki/Topological_skeleton)
![image](https://upload.wikimedia.org/wikipedia/commons/9/93/Skel.png)

I hope to get the points of the outline (1) and export them in vertices. So that i can use them to calculate and draw the skeleton.

**Comment by skef** [comment]
If you just want an image of the glyph you can do this on the glyph object:

```
glyph.export('S.png', pixelsize=300)
```

**Comment by chunchet-ng** [comment]
Alright, is there a way for me to get the outline in the format of vertices (x,y coordinates), so that i can plot them out (like what i have shown in the previous character image with just the outline).

**Comment by skef** [comment]
A spline-encoded character doesn't have "an outline" in pixels, although there are numerous ways to generate something like that. Probably the most basic way is to use de Casteljau's algorithm, as in https://incolumitas.com/2013/10/06/plotting-bezier-curves/

This discussion has drifted from "how do I X with FontForge?" to something closer to "help me with my homework", and this isn't an appropriate forum for general image processing questions.

**Comment by chunchet-ng** [comment]
Ah I see, sorry for making you think of it this way. I guess you really do misunderstand my intention.

I never intend to ask an exact solution from you. I dont have any prior knowledge on font creation and the FontForge's doc is especially confusing for a beginner like me, where i dont know how can i extract the information i need out of it, hence i show you some images of my ideal results. I thought that the outline vertices will be encoded but apparently it is not. They have to be calculated based on the bezier/quadratic curve (correct me if im wrong).

**Comment by skef** [comment]
If you want the simplest solution you can just:

1. Export the image with an appropriate pixelsize and `bitdepth=1` (to turn off anti-aliasing
2. Find some python library like Pillow (https://pillow.readthedocs.io/en/stable/reference/Image.html) to open the image with
3. Read the pixels in nested loops for x and y (in Pillow with https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getpixel)
4. Whenever there is a transition from white to black or black to white, record those coordinates.

This is what I mean by "basic image processing questions". I've explained how to get at either vector or raster representations of a glyph, the rest is just image processing. Almost no program is going to provide an interface to a list of x,y coordinates of an outline because that's a strange way to store and manipulate image data.

Please do not ask Pillow questions here -- I just picked that as an example.

**Comment by chunchet-ng** [comment]
Alright, very cool. Thank you for your help until this stage, have a good day.
