### ISSUE TITLE
Export all glyphs as individual SVGs to a specific location

### ISSUE THREAD

**Issue by zcraber** [fontforge/fontforge#4455]
Is there any way to export all glyphs from a font as individual SVGs to a specific location in Windows 10?

**Comment by ctrlcctrlv** [comment]
I'm not positive but I'm pretty sure you need a python script for this

**Comment by zcraber** [comment]
> I'm not positive but I'm pretty sure you need a python script for this

I found this from [Stack Overflow](https://stackoverflow.com/a/50127893/7563803): `SelectWorthOutputting(); foreach Export("svg"); endloop;`
But SVGs are getting saved to a default location. Also, some glyphs are not getting saved. For e.g., small letters are not getting saved. I don't have experience in coding. So, any help would be appreciated. Thanks in advance.

**Comment by KamilLanda** [comment]
1) Do some copy of your SFD file, because for correct output you need unlink references in the glyphs. 

2) Do some subdirectory in the directory where you have SFD file
-for example your SFD file is in d:\myfonts\myfont.sfd, so do subdirectory d:\myfonts\svg for script output, this subdirectory you will need put to the script

3) Open your SFD file - you have two choices, better is first
a) by doubleclick from some File manager or Windows Explorer
b) From FontForge menu: File/ Open

4) Use File/ Execute script, check radiobox FF, and put there:

SelectAll()
UnlinkReference()
Export("svg/%n-%e.svg")
![font-forge-script](https://user-images.githubusercontent.com/61148366/94851401-b235b800-0428-11eb-95b4-cbd37689a2eb.png)


This FontForge script select all glyphs, then unlink references in glyphs, and then export glyphs to the SVG subdirectory. %n means the file name will be the glyph name, and %e adds glyph encoding to the file name -> it is important, if you don't use %e then glyphs with the same names differs only with lowercase/uppercase will be rewrites only to one file. For example if you have glyphs "a" and "A", then Export only with %n do only one file -> "a.svg". Export with %n-%e will do correctly two files, for example something like "a-12.svg" and "A-38.svg".

If you opened your SFD file from File menu, you must add path to the Export command like: Export("d:/myfonts/svg/%n-%e.svg") else you will see message "Save failed". 

When i tried this script, FontForge exported some glyphs with limited viewbox, there is examples for arabic letter Ha'. 
![Ha](https://user-images.githubusercontent.com/61148366/94851491-d09bb380-0428-11eb-89da-df36cbc49199.png)


It is possible to correct viewbox for example in InkScape, but batch process is better. I use program Find and Replace http://findandreplace.io for batch replacing by regular expressions in the files. I had viebow in exported files 2048px high
![poznblok](https://user-images.githubusercontent.com/61148366/94851586-f0cb7280-0428-11eb-9b5f-97ba59768328.png)


so I changed it with Find and Replace to the 2500px:
![fnr](https://user-images.githubusercontent.com/61148366/94851618-fd4fcb00-0428-11eb-81f6-b718cce58ba9.png)

**Comment by zcraber** [comment]
@KamilLanda It worked! Thanks a lot for this detailed explanation. Learned a lot today. Thanks again.

**Comment by schroef** [comment]
Tried this code saving to an usb drive and call keeps failing. i added svg folder next the sfd file but no luck?

**Comment by Rezmason** [comment]
Holy moly guacamole cannoli, this is a _superpower_. 😳

**Comment by lancejpollard** [comment]
```
fontforge -lang=ff -c 'Open($1); SelectAll(); UnlinkReference(); Export("svg/%n-%e.svg");' font.ttf
```

**Comment by lancejpollard** [comment]
[Doesn't export my full glyph](https://stackoverflow.com/questions/74160332/how-to-export-full-glyph-as-svg-from-font) :/.

**Comment by ctrlcctrlv** [comment]
https://stackoverflow.com/a/74161522/1901658
> The tail is not cut off. The tail is still there in the file, if you view it in Inkscape you will see this. The reason this is done is so you can edit the SVG and then re-import and FontForge will get the metrics right, it can't be done another way and roundtrip.
>
> If you want to force the viewbox to be larger, just lower the font's descent in Font Info (be careful not to scale the font, lower the descent only).

**Comment by fmotion1** [comment]
>` fontforge -lang=ff -c 'Open($1); SelectAll(); UnlinkReference(); Export("svg/%n-%e.svg");' font.ttf`

Does anyone here know how to specify a dynamically named folder to the Export function? When I invoke via powershell and pass a variable to the initial `svg/` element, the script breaks and errors out.

**Comment by ekuester** [comment]
Fantastic! Under Fedora Linux I had to give the full path to the storage folder. Here only the characters worth outputting are exported:
```
SelectWorthOutputting()
UnlinkReference()
Export("/home/your_username/Dokumente/Thesis/font_work/valentine/SVGS/%n-%e.svg")
```
Works! Thanks!
