### ISSUE TITLE
FontForge was maded with Trojan.Win32.LeChuck which breaks and crashes the system

### ISSUE THREAD

**Issue by yg8ijvjvjv** [fontforge/fontforge#4551]
title

**Comment by ctrlcctrlv** [comment]
This is a serious accusation against Jeremy's Windows build. I've audited the Windows build and see no reason to believe it's true. "title" is not enough of a description. Prove there's a trojan in the Windows build without relying on proprietary software to bring this further.

**Comment by JoesCat** [comment]
Checking the internet, the LeChuck is a pretty old trojan. One of the hits says "adware".
Basically some adware may redirect infected computers to secondary sites.
@yg8ijvjvjv - it might be worth your the time to have your PC checked for viruses as you might probably be getting re-directed.

To be fair - there was a problem with a prior release, but it was flagged within a day, while the latest release is almost two months old, so someone would have certainly mentioned something within a week, if not days, or hours from the release on November 7, 2020.
If someone else confirms/triages the same problem, it may be worth a follow-up, but for now, the current assumption is you might have an infected PC, or the download was supplied from someone else and did not come from https://fontforge.org or https://github.com/fontforge/fontforge/releases

**Comment by JoesCat** [comment]
Another thing that could be easily overlooked is the router (if you have one).

**Comment by ctrlcctrlv** [comment]
@JoesCat Problem with a prior release? I don't think we've ever distributed malware.

**Comment by frank-trampe** [comment]
@yg8ijvjvjv, would you point us to the specific file?

**Comment by jtanx** [comment]
The build comes [straight from CI](https://ci.appveyor.com/project/fontforge/fontforge/builds/36190062/job/5pn5ndygkbp3pqtj/artifacts) so 🤷. It's probably from `run_fontforge.exe`, have had problems with false positive detection on that in the past. Could probably be simplified now that it no longer needs to spawn an X11 server before starting fontforge.

**Comment by ctrlcctrlv** [comment]
The chances the problem is on our side are _extremely_ remote, which is why I closed this since I thought it off-putting to tech unsavvy users who might see an open issue and "not want to risk it". 

And like Jeremy says it's from CI... No way this is on our side. There's a less remote (but still very remote) possibility that it's a problem with a compromised third party provider, but if that's so there's not nearly enough here to track down anything.

**Comment by JoesCat** [comment]
On January 1, 2021 04:24:43 AM Fredrick Brennan wrote:
> @JoesCat Problem with a prior release?
> I don't think we've ever distributed malware.

Long time ago, approximately 2012...2015. If I was to look it up, I think 
it's mentioned in the sourceforge user or developer mailing list, but it 
was caught pretty soon after release. It was a false-positive.

**Comment by yg8ijvjvjv** [comment]
> The build comes [straight from CI](https://ci.appveyor.com/project/fontforge/fontforge/builds/36190062/job/5pn5ndygkbp3pqtj/artifacts) so .

Why did you make the build from copyright infringement?

**Comment by ctrlcctrlv** [comment]
Continuous integration.

**Comment by JoesCat** [comment]
@yg8ijvjvjv - I was a little curious about where the binaries came from too, but doing some searching I first found this [Push built Artifact *.exe to Github "Release" (opensource, public repos, dev account)](https://help.appveyor.com/discussions/problems/23134-push-built-file-to-opensource-public-github-release) which then lead to this [Publishing artifacts to GitHub Releases](https://www.appveyor.com/docs/deployment/github/#provider-settings).
I don't think appveyor would host this info if the binaries are a problem.
Do you have info/URL we can read?

**Comment by yg8ijvjvjv** [comment]
FontForge can initiate a crash by Autotracing or opening multiple large fonts or operations because it consumes memory. Having a certain memory limit before crashing is linked to  .

**Comment by yg8ijvjvjv** [comment]
Trojan.Win32.LeChuck is mainly caused by memory consumption which makes it seem like the program is glitchy. If you're unable to remove Trojan.Win32.LeChuck from the compiler, try coding the cap in code to initiate memory errors in FontForge.

**Comment by yg8ijvjvjv** [comment]
I don't think Trojan.Win32.LeChuck will ever be fixed because FontForge has a 32-bit edition and any memory allocator system will fail similarly to Trojan.Win32.LeChuck. So the only way to fix it is to make a software memory cap in FontForge to error.

**Comment by ctrlcctrlv** [comment]
We're not instituting a memory cap because your Windows antivirus is buggy and throws false positives.

**Comment by yg8ijvjvjv** [comment]
Don't assume things you don't know about, I don't use an anti-virus, a trusted user made me post "FontForge was maded with Trojan.Win32.LeChuck which breaks and crashes the system". It was determined entirely by observations of FontForge behavior. A memory cap where FontForge halts the operation with error instead of using the failed allocation is necessary because 32-bit is limited to 4GB of memory and reaching that will inevitably cause crashes because it eventually becomes impossible to allocate.

**Comment by ctrlcctrlv** [comment]
Again, we're not instituting a memory cap to satisfy buggy proprietary security software. I'd oppose a patch to do so. Some of my fonts like TT2020 require many GB of memory to compile correctly. We cannot tell the difference between legitimate use of memory or not.

**Comment by yg8ijvjvjv** [comment]
Since when is the fundamental limit of 32-bit memory a buggy proprietary security software? Do you really think memory allocation was made with buggy proprietary security software before 64-bit processors came out? I'm not talking about the particular compiler you use which is probably 64-bit. I'm talking about 32-bit FontForge and 32-bit has a fundamental memory limit.

**Comment by jtanx** [comment]
... which has nothing to do with a virus false positive?

If you want a 64 bit build then see here: https://sourceforge.net/projects/fontforgebuilds/files/x86_64/ or here https://github.com/fontforge/fontforge/runs/1634107440

**Comment by ctrlcctrlv** [comment]
I'm not the one claiming there's a trojan in FontForge.

**Comment by yg8ijvjvjv** [comment]
32-bit memory only goes up to 2^32 bytes which is 4GB. It is a fundamental, not buggy proprietary security software.

**Comment by ctrlcctrlv** [comment]
And the operating system seems to be correctly handling it by terminating FontForge. Not a bug. If you need more memory use 64 bit.

**Comment by jtanx** [comment]
Ok we're done here.

**Comment by ctrlcctrlv** [comment]
Thank God 😊

**Comment by JoesCat** [comment]
> trusted user made me post "FontForge was maded

It was hard to understand where this was going, but I think the above phrase more-or-less explains it.
Basically @yg8ijvjvjv doesn't seem to understand programming, but was attempting to say that FontForge suffers from buffer overflows and lack of memory checks, and was attributing all this to a trojan that takes advantage of this sort of problem.

Unfortunately, a lot of programs suffer from this problem - it is not unique to just FontForge. For example AutoTrace, which would be another application used by FontForge would be yet another vector. Approximately, around year 2000 when FontForge was initially created Operating system file partitions were at most 2GB in size, and many programs ran as 16bit. Very few people envisioned the probability of programs being large enough to take-up an entire partition (imagine one program taking-up all of C:\ drive? seemed unimaginable). Nobody expected font files to reach 2GB in size - impossible.

With 32bits it was possible to do sloppy programming with little regard to memory checks, because nobody had personal computers with 2GB of RAM back then.

As time progressed, more memory was available, programs grew bigger, data files grew in size, and yes - the 31bit+sign=2GB was getting approached as a problem - and the sloppy programming habits of 16bit which were relieved by going to 32bit are now approaching and even causing headaches now. Not just FontForge, but all programs that don't pay attention to memory.

....so....short and simple answer....just for yourself....migrate to 64bit, and the problems avoided (when going 16bit to 32bit) will be pushed away for a while, maybe another 20years ;-)
longer answer....as code is improved, you should be seeing these numbers slowly progress to zero https://scan.coverity.com/projects/792 - but this would be for FontForge, the same can't be claimed for other programs.
The LeChuck Trojan is only one of many viruses and trojans out there taking advantage of buffer overflows - every developer worth their salt know of these problems.

**Comment by ctrlcctrlv** [comment]
It is absolutely absurd that some security software see the buffer overflow and makes such a severe accusation. 

How dare they?

"Because we detected the program contains bugs we terminated it."

Much better. No need to bring the word trojan into anything. That's rude. Par for the course in the security industry though, have to keep people scared. If the software never identified any Trojans maybe people would stop buying it after all.

**Comment by ctrlcctrlv** [comment]
Also I still don't think that it's necessarily a bug for us to allow the operating system to kill us if we're out of memory and try to allocate more. 

Testing every call to the allocator makes the code much larger and harder to follow. Just my opinion.
