### ISSUE TITLE
software crushes and nothing in it works :(

### ISSUE THREAD

**Issue by ShefOriDr** [fontforge/fontforge#4562]
I downloaded the software today (11/07/2020 version). I know how to work with it but it keeps earasing glyphs while I work on it and keep crushing. Seems like a bug - is there an option to download a previous version?

**Comment by yg8ijvjvjv** [comment]
No

**Comment by frank-trampe** [comment]
@ShefOriDr, could you supply screenshots, tell us which platform you're using, and tell us which typeface you're using? Once you tell us which platform, we can point you towards an older installer, but we would obviously like to fix the problem if possible.

**Comment by frank-trampe** [comment]
@yg8ijvjvjv, there's no need to provide false information on the issue tracker.

**Comment by yg8ijvjvjv** [comment]
There is only an option towards an older installer if the system is Vista or similar (XP and 2000 are similar), because someone used an incompatible function in code. In case of glitching the only option is to wait for bugfix. Example: Regression made it so only one bdf could be exported per FontForge. It has been fixed.

**Comment by ctrlcctrlv** [comment]
Who said anything about Vista? No one cares about such old systems outside of archivist societies.

**Comment by frank-trampe** [comment]
@yg8ijvjvjv, I think that the original poster is asking about an installer for an older version of FontForge, not for an older operating system. We can easily accommodate the former with the right information.

**Comment by frank-trampe** [comment]
It may not be relevant to the original inquiry, but I guess the old platform issue is worth mentioning. There are two sub-issues: the reasons to support the platform and the feasibility of doing so.

Vista isn't interesting since it was so terrible that it never achieved widespread adoption, but Windows 7 is interesting. Given that Windows 8 was bad and Windows 10 is unpopular due to breaking auto-updates, I still use Windows 7 on several machines (to run old scanners), and I imagine that many others do too for various reasons. I also have a few IRIX machines, and I like using them when I can. I would love to see FontForge continue to ship for Windows 7 and IRIX 6.5.30 (or 6.5.22).

The main issue isn't that we aren't interested in supporting certain older operating systems but that the build and packaging infrastructure and the upstream libraries do not support them. I even run into trouble building some packages on Ubuntu 18.04. People who want a recent FontForge release thus must generally have a recent operating system too.

**Comment by yg8ijvjvjv** [comment]
Try modifying the libraries until it works

**Comment by yg8ijvjvjv** [comment]
Even then, because this issue is not about Vista, XP or 2000, there is not an option towards an older installer and that was my point.

**Comment by skef** [comment]
This doesn't seem like it's going anywhere more specific -- submitter can update/refile if and when they like.
