### ISSUE TITLE
DF Kai SB from Microsoft is corrupted in the ideographs

### ISSUE THREAD

**Issue by yg8ijvjvjv** [fontforge/fontforge#4570]
![](https://cdn.discordapp.com/attachments/791394009841926195/797901380533747730/Screenshot_2021-01-10_154729.png)

Why this happens?

Here in charmap glyph0391 is longer and unlinked and works.

**Comment by yg8ijvjvjv** [comment]
why  Fontforge  crashes despite being in an extremely healthy state

**Comment by yg8ijvjvjv** [comment]
however in the GB 2312 font FangSong it works because it has no glyph

**Comment by yg8ijvjvjv** [comment]
HughLaurie1959/bedriczwaleta (a trusted user) said the crash is because it's Trojan.Win32.LeChuck in the source code (not in the compiler). This is related to the 32-bit memory limit and the only way to fix it is to use x64 FontForge but the pagefile must not be too small or else it will again crash.

**Comment by HinTak** [comment]
Some DynaLab fonts (that's what the "DF" short for - DynaLab in Taiwan made Kai and MingLiU for Microsoft) have the interesting way of using hinting instructions to moving and positioning sub-glyphs by large distances, so requires the hinting instructions on to be viewed in the intended way; otherwise they appear garbage. You need to switch on the hinting instruction interpretation.

This applies to not just Kai and MingLiU shipped in Microsoft Windows, but other DynaLab fonts too.

**Comment by yg8ijvjvjv** [comment]
The only thing that is impossible to remove from Fontforge is Trojan.Win32.LeChuck the only way to fix it is by reverting and crashing it with Process Hacker and using Windows XP

I recommend hinting instruction interpretation in v35 mode

**Comment by skef** [comment]
Sure enough -- if you make largish bitmap strikes those glyph look more like the Windows character map. 

Closing
