### ISSUE TITLE
Adding curve line between two points

### ISSUE THREAD

**Issue by WarBeer101** [fontforge/fontforge#4583]
How do I add a curve between two established points? I'm trying to remove some serifs that are on a curved surface of a character. Everything I use to connect them just creates a straight line without any handles.

**Comment by yg8ijvjvjv** [comment]
Are you a TrueType or a PostScript type designer? The quadratic and cubic curves are quite different in their functionality.

**Comment by yg8ijvjvjv** [comment]
In TrueType, this would normally be achieved by inserting an off-curve point between two on-curve points. However, FontForge for some reason does not manipulate off-curve points quite as well as on-curve points. Instead, the user is forced to awkwardly go to the point info and set the off-curve points in a distinctly non-TrueType way.

**Comment by skef** [comment]
If you've got "dangling handles" from deleting the previous curves my answer at https://github.com/fontforge/fontforge/discussions/4537#discussioncomment-301577 might help. Otherwise I'm not sure there's a way to get a clean curve without "designing" it, perhaps because of a lack of heuristic for deciding what it should be. (I suppose the obvious thing to do is match the angles and curvatures at each end but I'm not sure there's handy code to do that.)

**Comment by skef** [comment]
Coming back to this: I've seen this question in a few contexts and I don't think it's an interesting or important one *if* you know the following: Curves in FontForge are draggable. When you:

1. Deselect all points (by clicking in the background
2. Press the mouse down on the middle of the line you just added, and
3. Drag the mouse away from the line

it will become a curve and handles will "pop out" accordingly. (Step 1 is important though, otherwise you'll just drag the points.)

This may not answer the question but I think it sufficiently addresses it. Closing.

**Comment by WarBeer101** [comment]
Thank you!
    On Tuesday, February 2, 2021, 04:57:16 PM EST, skef ***@***.***> wrote:  
 
 


If you've got "dangling handles" from deleting the previous curves my answer at #4537 (comment) might help. Otherwise I'm not sure there's a way to get a clean curve without "designing" it, perhaps because of a lack of heuristic for deciding what it should be. (I suppose the obvious thing to do is match the angles and curvatures at each end but I'm not sure there's handy code to do that.)
