### ISSUE TITLE
Glyph's bottom edge placed at -200em in back layer

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4591]
in FF, any copied letter ( vector/image ) to the back layer, placed it at around -200em as bottom edge. 
Questions:
1. Can I instruct FF to place the letter's bottom edge at 0 em? So the glyph's bottom edge aligned to 0em?
2. Or is there any method I can do the adjustment to all the glyphs to place at 0em or -200em?
3. Or any setting I need to set? I tried vertical metric setting enable and it does not do what I wanted to do.

Please help. Thanks

**Comment by skef** [comment]
First a clarification: FontForge's import rule is to place the top of the image at the ascent line. It's placing the bottom of the image at the descent line because you're importing with "Scale to fit" set to true (the default).

If you turn that off then SVG images will be sized so that one em-unit corresponds to one svg-unit (based on the viewbox). (I believe raster images work the same way with em-units and pixels but I haven't verified this.) So if you want your image to import at a given place you need to size the viewbox/raster height relative to the ascent line and then place the glyph within that size appropriately. Then import with "Scale to fit" turned off. 

(Of course, you can also size every image to be ascent+descent in height and not worry about whether scale-to-fit is on or off. Then just place the glyph at the appropriate place within its width and height.) 

As far as moving them after the fact is concerned:
 
I believe that any *vector* import just winds up as contours, which can be translated as you like with a `.transform()` method. Since you're interested in the background layer you could do something like this in python to move the background layer of the letter "a" vertically:

```
import fontforge
import psMat

f = fontforge.open('filename.sfd')
g = f['a']
b = g.background
m = psMat.translate(0,200)
b.transform(m)
g.background = b
```

Unfortunately there is not currently a scripting interface for moving or sizing raster images (See some discussion [here](https://github.com/fontforge/fontforge/pull/3915#issuecomment-559670867).) So you're better off using the conventions I described above.

**Comment by waykyi** [comment]
Thank you very much skef. I did overlooked Transform features right in the FF. There is Transform/move with ( X,Y ) which does exactly as I wanted. Either one or the whole glyphs in the font can be moved to the sides or up/down to co-ordinates number you specified in ( X, Y ). Thanks a lot, it solve the problem I have.
