### ISSUE TITLE
Elementary Mono 1.4 O glitches in width in Windows 8 onwards

### ISSUE THREAD

**Issue by yg8ijvjvjv** [fontforge/fontforge#4594]
After [Kissinger](https://typedesign.netlify.app/kissinger.html) was glitchy in Windows Vista/7 and failed except for Upper in 10 ( issue https://github.com/fontforge/fontforge/issues/4558 ) I encountered a glitching in [Elementary Mono 1.4 O](https://typedesign.netlify.app/elementary.html). This was made with FontForge as well and what happens is that whereas Windows 7 works, in Windows 8/8.1/10 some characters in the 1.4 O are incorrectly fullwidth despite being halfwidth in the font.

**Comment by yg8ijvjvjv** [comment]
https://imgur.com/a/nFygNyB is a screenshot of the glitching.

**Comment by skef** [comment]
"I made font X with FontForge and it doesn't work in context Y but I have no more specific information about FontForge's potential contribution to that problem" is not an appropriate topic for this forum. And the fact that the issue happens on some versions of Windows and not others points away from FontForge rather than towards it.

You can refile if and when you get a more specific diagnosis.
