### ISSUE TITLE
Fontforge not working.

### ISSUE THREAD

**Issue by RAtwood90** [fontforge/fontforge#4640]
Hello i'am getting no Error Messages but i get a Issue may i do something wrong.

If i open two Fonts i can't copy the "€" to the another Font as example.

Or if i edit the Spacing between Fonts and reduce the Space between "k and e" in Fontforge all is fine but if i export it to ttf or otf and using it nothing changed the Font is still the same.

May Fontforge is not working correctly on my W10 64bit OS installed the latest Version from your Site.

May you can give me some Tips or something to get a Resolution for this.

Regards Atwood

**Comment by skef** [comment]
Copy/Paste is only reliable within a single running instance of FontForge. So rather than clicking on two SFDs (or other font files) in the OS file browser, you need to click on one and then use "Open" in the "File" menu to open the other one. Then it should work.

We would need more information to help with the spacing problem, such as what steps you are taking and generation parameters you're using, and a test file if possible.

**Comment by RAtwood90** [comment]
@skef https://www.youtube.com/watch?v=UUUeogQAjv0 doing this Steps until Minute 3. Then saving as ttf Font with Create Font.

I deleted the Font today cause it didn't worked.

**Comment by skef** [comment]
Fonts are complicated, particularly when it comes to kerning, so this is a complicated subject.

In some cases the "Windows-compatible 'kern'" generate option will help. If you're building kerning tables in the normal way it may be better to stick with OpenType rather than generating as TrueType. With OpenType there are a number of things that can go wrong having to do with what languages and scripts you list in your Lookups.

Depending on what you're doing this could also be a "caching" problem, where the you think the OS is using the font you just made but it's actually using an older version.

**Comment by ctrlcctrlv** [comment]
Not a FontForge bug.
