### ISSUE TITLE
FontForge on Mac OS Big Sur 11.2.2 what went wrong? Please Help me ...

### ISSUE THREAD

**Issue by piiccaa** [fontforge/fontforge#4651]
Since Big Sur on my iMac Pro FontForge looks like that. How can I fix this an use FontForge correct again ... pleas help ...
<img width="848" alt="Bildschirmfoto 2021-03-05 um 11 01 12" src="https://user-images.githubusercontent.com/42291454/110100208-71a8e480-7da2-11eb-8044-801e08f7f646.png">

**Comment by GoatFaced** [comment]
I am also having this issue

**Comment by GoatFaced** [comment]
I have managed to sort this out. Not sure what the issue was, but after reading other threads and discussions I decided to take the following steps.

First I uninstalled Fontforge, disabled Helvetica and downloaded and installed the font Deja vu and then downloaded and installed the latest version of Quartz. I then downloaded and installed a fresh Fontforge and now everything is back to normal.

Hope this helps someone else!

**Comment by ultrasquid** [comment]
This can happen when the active X Resource Editor settings (that's the menu item second from the bottom in @piiccaa 's image, between preferences and quit) Font Family does not contain an installed font name. It is possible the X resource file became corrupted or was edited accidentally to a non-installed font name to cause this problem. dejavu sans is one of the default settings so installing DejaVu fonts and reinstalling Fontforge as @GoatFaced did should resolve this.
