### ISSUE TITLE
How to start fontforge with Haiku?

### ISSUE THREAD

**Issue by Brunobasta** [fontforge/fontforge#4652]
I tried to start fontforge version 1.0 (git version 20190501 git-3) with Haiku 64bit Beta2 nightly (hrev 54972)

After starting fontforge in Terminal no GUI will show up!?
http://0x0.st/-Per.png
How to start fontforge with the Terminal CLI (bash)?
nothing happens...
Install fontforge and start it within Terminal with: fontforge
http://0x0.st/-PeE.png
Or do we have only the  fontforge - FontForge font manipulation module?

**Comment by skef** [comment]
This old message says that the HaikiPorts version of FontForge is not compiled with the UI: https://discuss.haiku-os.org/t/creating-fonts-for-haiku/4077 . Looking at https://github.com/haikuports/haikuports/tree/master/media-gfx/fontforge there don't seem to be any dependencies on graphics libraries, so that's probably the reason (`./`configure` isn't finding what it needs to compile the UI source files and is skipping them). 

We don't have control over how distributions or other OSes compile FontForge, so I'm afraid you'll have to work with them to resolve this issue, assuming it can be resolved (you'd need either a working X11 stack or GTK3).

**Comment by Brunobasta** [comment]
Ah ok that makes sense. I will contact the HaikuPorts devs and inform them to remove the app from HaikuDepot...
Thank you for your help. Whished to have this app working.
