### ISSUE TITLE
Letters crash into mnemonic underlines under CJK locales

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4661]
52e84327b429f557c1b73f3c8bc214082dcde485, Arch Linux

```
LANGUAGE=ja fontforge -new
```

![image](https://user-images.githubusercontent.com/838783/110902101-5292e100-82d3-11eb-9c14-320720bb102a.png)

```
LANGUAGE=ko fontforge -new
```

![image](https://user-images.githubusercontent.com/838783/110902306-ad2c3d00-82d3-11eb-83af-4e59092d26b3.png)

```
fontforge -new
```

![image](https://user-images.githubusercontent.com/838783/110902185-735b3680-82d3-11eb-8bc9-23d429386c45.png)

cc: @skef

Also I ran all the existing locales, and the parenthesis-based mnemonic method I'd consider sane seems to only exist in Chinese, Japanese, and Korean. Others seem to haphazardly assign _visible_ mnemonics based on the native string, not exactly good because it's not like the `mnemonic` field of `GGadget` pays that any mind, so they conflict.

**Comment by skef** [comment]
> not exactly good because it's not like the mnemonic field of GGadget pays that any mind, so they conflict.

In most contexts we pick up the mnemonic from the string itself (via the `text_in_resource` flag and `utf82u_mncopy()`). So there shouldn't be a problem with entries that don't match the original. 

The main problem is how you wind up with unique mnemonics if the translators don't know the total contents of a menu or dialog. I don't know enough at this moment to say whether there's a solution to that of one kind or another. (Maybe conflicts are OK if there's an easy way to advance to the next one?)

**Comment by skef** [comment]
My guess is whoever did the Latin character-based menu translations were working from the program rather than isolated strings so they could assign mnemonics sensibly.

This new evidence pushes me back to my earlier position: The menu and dialog APIs should stay out of the localization business. We should have an API for a language-neutral token where needed (for future menu-configuration or regathering dialog parameters) but not specify it needs to be identical to the (default) English localization.

**Comment by skef** [comment]
I just did the ja test also in Arch, and didn't have this problem. (I don't even have a Korean font installed, I just get hex-4 boxes.)

The issue is presumably how well the point size of the fallback CJK font matches the configured point size. In the images above the characters are large enough to make the whole text line too high, cutting off the bottoms. So I'm tempted to call this a font configuration problem. I'm not sure we need to do anything, and if we do I doubt its more than tinkering with the default font selection list.

**Comment by ctrlcctrlv** [comment]
Well, it's Noto CJK and Cantarell, not really any fancy non-default fonts in use here

**Comment by skef** [comment]
I suspect the problems are most likely in an environment where the Latin and CJK are being pulled from mismatched families. Not something we can prevent with a string alone but we could do something like pick the most likely candidates and always list the Latin and CJK names sequentially ...

**Comment by skef** [comment]
There is something else weird going on with these mixed characters. In #4682 the mnemonic is sometimes displayed at normal size and sometimes smaller. There must be code somewhere causing this but I have no idea where.

**Comment by skef** [comment]
@ctrlcctrlv Seems like the recent menu work and @jtanx's fixes resolved this problem, at least on my machine. Can you confirm?

**Comment by ctrlcctrlv** [comment]
Yup!
