### ISSUE TITLE
Fontforge windows version display UI font doesn't have all unicode characters.

### ISSUE THREAD

**Issue by darkhog** [fontforge/fontforge#4804]
This means that it's extremely hard to make a font that offers full unicode coverage as you simply don't know how each glyph looks like, instead being greeted with this mess: https://i.imgur.com/miN3T2X.png Yes, you can google how each glyph is supposed to look like, but it makes making a full unicode font more of a hassle than it has to be.

Solution: Change the UI font to one with full unicode coverage or allow us to change the UI font to any otf/ttf font we like.

**Comment by skef** [comment]
The glyph label font is (currently) set by the "FontView -> Font Family" field in "File -> X Resource Editor ..." dialog, so it can certainly be customized. Installing [Unifont](http://unifoundry.com/unifont/index.html) (in some form compatible with your OS) and putting that towards the end of the list is one way to get close-to-full coverage. 

Once it is integrated #4704 will change this answer slightly. It will also make it easy to customize the default font family chain by broad OS (e.g. Mac, Windows, Other) so that FontForge has more coverage without customization. 

#4704 also notes the need for better default choices so this bug could be considered a duplicate but I'll let someone else close it on that basis if they like.
