### ISSUE TITLE
Request: offer to show only glyphs that are available on the current font

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [fontforge/fontforge#4825]
As the title says.
I suggest to add this checkbox in the "view" menu.

**Comment by skef** [comment]
This isn't exactly equivalent but the solution to this problem in FontForge is to select "Compact" in the encoding menu.

**Comment by skef** [comment]
(It's not exactly equivalent because under some circumstances you may need to deselect "Compact" before running an operation to get the same result. But those circumstances are relatively rare.)

**Comment by AndroidDeveloperLB** [comment]
@skef It's actually very nice. I just didn't know it should be there. Doesn't it make more sense to see it in "view", because I want to view only what's defined?

Also, why not have this as the default one? Doesn't it make sense to view only what's on the font, and not what isn't?

**Comment by skef** [comment]
It's not under "view" because the implementation is in terms of, and wrapped up with, encoding. 

As for the default it depends on whether one primarily wants to edit features of glyphs in an existing font or is creating a new one or adding glyphs to an existing one. In the addition case it's useful to have the empty slots.

**Comment by AndroidDeveloperLB** [comment]
I see. 
What did you mean by "This isn't exactly equivalent "  ? It seems to do exactly as I wrote, no?
What's the difference?

**Comment by waykyi** [comment]
Is this equal to Select/Show worth out putting?

**Comment by skef** [comment]
@AndroidDeveloperLB There are unusual cases where a glyph can have multiple unicode values and the *same* glyph will be listed multiple times (which is different from two glyphs that have exactly the same content, or one glyph that includes another glyph as a reference).

**Comment by ctrlcctrlv** [comment]
@skef I thought glyphs with widths > 0 were also "worth outputting".

**Comment by skef** [comment]
Could easily have been wrong about that ...

My qualifiers to all my answers have more to do with the fact that everything in FontForge seems to have exception cases than with particular exceptions. "Compact" normally does what one would expect.

**Comment by AndroidDeveloperLB** [comment]
@skef I see. Is there a way to make it skip those that are empty, though?

**Comment by skef** [comment]
No, if there is data associated with a glyph it will be in the compacted list.

**Comment by AndroidDeveloperLB** [comment]
@skef Can you please add this option for this feature?

**Comment by skef** [comment]
Probably not? Most users aren't going to be troubled by a few blank slots (which is all they'll have) and among the almost 900 open issues that's not likely to be a priority ...

**Comment by AndroidDeveloperLB** [comment]
@skef It lets me easily select only those that have content, to be able to export them, this way...

**Comment by skef** [comment]
Identifying the glyphs isn't an issue, it's first a UI question and secondly and more importantly a difficulty with how Compact is wrapped up with encoding. Adding multiple compact-substates would make an already huge mess even messier.

**Comment by AndroidDeveloperLB** [comment]
@skef Well you could have a setting of multiple checkboxes to define what "compact" means. 
Do you at least understand what was my use case?

**Comment by skef** [comment]
Your use case for wanting to suppress display of contourless glyphs in Compact mode? No.

**Comment by AndroidDeveloperLB** [comment]
@skef Suppose I want to export all of those that have content in them.
One that is just spacebar isn't useful in this case, but even the one with a simple tiny circle (like a dot: ".") is still visible and thus I would want to export it.

**Comment by skef** [comment]
Oh, I misunderstood that comment.

That's not what display is for, that's what *selection* is for. Those options are under Edit -> Select, e.g. "Glyphs worth outputting". 

Getting what you want specifically is a little tricky because there's no "glyphs with content" option. So what you would do is:

1. Clear the selection (by tapping somewhere in the FontView)
2. Edit -> Select -> Glyphs with only references
3. Edit -> Select -> Glyphs with only splines *while holding the shift key*
4. Edit -> Select -> Glyphs with both *while holding the shift key*
5. Do whatever you need to do based on the current selection. 

Holding the shift key while performing a selection operation does a union.

**Comment by skef** [comment]
> Holding the shift key while performing a selection operation does a union.

Well, sometimes ...

**Comment by AndroidDeveloperLB** [comment]
@skef Can you please add this option, then?

**Comment by skef** [comment]
No. Select multiple menu options or, if you feel like it, add your own option to the tools menu. Adding a custom option to the main UI for every use case isn't viable.

**Comment by AndroidDeveloperLB** [comment]
@skef Too bad

**Comment by cesss** [comment]
FWIW, I was looking for an open source TTF+OTF viewer+debugger so that I could check the internals of fonts, their metrics, their defined glyphs, and everything which is in a font. So my first interest is inspecting font contents, rather than editing/creating them (although in the future I might need to do some editing as well). After some searching, I found that fontforge was a usual recommendation for looking inside fonts. And, when I first ran it, the first thing I was looking for is a toggle to display only available glyphs, so that I could check all and every defined glyphs (because many fonts have only a small percentage of slots defined). I'm not saying that you really must implement this feature, just my 2 cents that it can be expected by a number of users (as I said, it was the first feature I looked for).

**Comment by skef** [comment]
@cesss, as implied above, if you're just interested in viewing the glyphs with content you can just pick "compact" from the encoding menu. Yes, this is unintuitive (although the language was recently changed to make it a bit more intuitive). Yes, this not exactly the same as just displaying the defined glyphs (because it's a bit wrapped up in encoding). But it is similar enough to work in 99% of the cases.
