### ISSUE TITLE
Quite strange degenerate output from a simple oval

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4884]
I seem to have somehow drawn an oval FontForge cannot tolerate. Twice, actually, first in `a` and then `d`.

![image](https://user-images.githubusercontent.com/838783/149443537-d133f8d7-dd77-4577-ac0d-2c67f31001bc.png)

No tricks here of any sort, of that I promise you—this is the glyph:

![image](https://user-images.githubusercontent.com/838783/149443635-43e987ff-7d61-4d07-a5de-a59050ecadfe.png)

[strokebug20220113.zip](https://github.com/fontforge/fontforge/files/7867454/strokebug20220113.zip)

Bug triggered thus:

![image](https://user-images.githubusercontent.com/838783/149444421-9774601e-2d7a-4604-90d4-fb9d6c250315.png)

Original glif file:

![image](https://user-images.githubusercontent.com/838783/149444491-5e03035d-db0b-48f2-9089-b1f45b458515.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="a" format="2">
  <advance width="461"/>
  <unicode hex="61"/>
  <outline>
    <contour>
      <point x="372" y="392" type="move"/>
      <point x="372" y="392"/>
      <point x="372" y="388.43213"/>
      <point x="372" y="382" type="curve"/>
      <point x="372" y="25" type="line"/>
    </contour>
    <contour>
      <point x="371" y="212" type="move"/>
      <point x="371" y="116"/>
      <point x="319" y="26.000015"/>
      <point x="228" y="26" type="curve"/>
      <point x="137" y="26.000008"/>
      <point x="81" y="116"/>
      <point x="81" y="212" type="curve"/>
      <point x="81" y="308"/>
      <point x="137" y="392"/>
      <point x="228" y="392" type="curve"/>
      <point x="319" y="392"/>
      <point x="371" y="308"/>
      <point x="371" y="212" type="curve"/>
    </contour>
  </outline>
</glyph>

```

Not sure if @skef still cares. Really, not sure why I do—except holding out hope or a nib-based libskef which seems to be more and more extinguished as of late. Reported all the same.

**Comment by skef** [comment]
I will likely take a look at this soon.

**Comment by skef** [comment]
Note: I still care about the code quality of my contributions, and I also still care about the PRs that continue to languish in the queue due to the absentee landlords of this repository. A fork may be the only way forward for this code base.

**Comment by ctrlcctrlv** [comment]
Wow, "absentee landlord" would be a benign insult coming from me given the things I've written onto bug trackers in the past (just today I described an implementation of a path type as "[contrary to common sense](https://github.com/linebender/kurbo/issues/211)" and then wrote a _third_ [attempt](https://github.com/MFEK/glifparser.rlib/commit/9b06a9422b796d25ab2b270abfd51500c6e5857b) at converting it), but you rarely make public statements that incendiary.

I'm writing this to say, I think a fork led by you is generally in my interests and I'd probably support it. There are many hurdles to overcome to avoid ending up like Runebender, TruFont, Sorts Mill, etc. I would very much be open to discussing a way forwards.

**Comment by skef** [comment]
At this point even the stop-gap things that are supposed to partially make up for the other things not happening ... don't happen.

Sometimes people who have led projects to genuinely better places are prone to compare alternatives to their own _counterfactual_ work, as opposed to what they actually do, even when the latter starts to border on _little or nothing for years_. I've worked the back channels on this. Multiple times. Nothing changes.

Ideally the repo owners would step aside for other people, however inferior they seem on paper, so that non-trivial things could happen again. If that can't happen a fork is the clear alternative.

**Comment by skef** [comment]
Interesting -- the distortion shows up (and the error message is outputted) when using the MetricsView but not in the FontView preview.

**Comment by skef** [comment]
I've looked at this a little. Note:

```
GlifName: a
Width: 461
VWidth: 0
Flags: WO
LayerCount: 2
Fore
SplineSet
372 392 m 257
 372 392 372 388.43213 372 382 c 257
 372 25 l 1281
228 26 m 257
 137 26.000008 81 116 81 212 c 257
 81 308 137 392 228 392 c 257
 319 392 371 308 371 212 c 257
 371 116 319 26.000015 228 26 c 257
EndSplineSet
EndChar
```

While this is not an excuse, cp/p/cp arrangements like 26.000008 26 26.000015 are asking for it floating-point-wise. And rounding does indeed make the problem go away. 

What's happening is that the wrong offset is being used, I think because of a bad fp fallback calculation, but I need to look at it more to nail things down.

**Comment by ctrlcctrlv** [comment]
Thanks for fixing this. I couldn't tell you exactly what caused the strange offset here—26.000015. I certainly didn't do it on purpose, I was not purposely fuzzing or testing or anything.

**Comment by ctrlcctrlv** [comment]
Thinking more—it could be a consequence of my polar coordinate calculations. If I set the handle based on polar→Cartesian, then it may have just barely missed the integer boundary.

**Comment by skef** [comment]
As always, the more you verify changes to the expand stroke code with your collection, the less likely some unforeseen problem slips through.

**Comment by ctrlcctrlv** [comment]
Yes, indeed :-) It's possible this could happen to a pure FontForge user, although far less likely as George seems to be more aggressively rounding polar→Cartesian results (from Point Info dialog). Perhaps I should be doing the same—but then again, I'm not breaking any spec by not, so…

**Comment by skef** [comment]
It may be worth a reminder that fixing this has no effect on your font beyond happening to make FontForge work if someone happens to preview it in the metrics window. Since it's a stroked font you'll still be "asking for it" if it gets released this way, in that there are many renderers and one or more might be tripped up by those close-but-not-quite floating point values.
