### ISSUE TITLE
LBearing & RBearing in zero-width glyph

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5023]
Why the measurements of LBearing & RBearing in zero-width glyph are different??
LB have negative number while RB has positive number in measurements.
![Left   Right Bearings](https://user-images.githubusercontent.com/73824794/169789403-c7565529-de23-4dcd-9892-7d64e7ed56c7.jpg)

Both points ( left & right most ) are in negative territory of horizontal baseline.
Can someone explain me why and how to measure? Thanks

**Comment by ctrlcctrlv** [comment]
You are stuck in a wrong pattern of thinking. Let's see if I can fix it.

I believe it's partly due to what FontForge calls these. I suggest at least [LR]**S**Bearing, addition of **S** for side, but really space is not so constrained—we can write out the true typographic terms, _left side bearing_, _right side bearing_.

A picture from Microsoft:

![image](https://user-images.githubusercontent.com/838783/170032267-7fdeeb84-5bd3-463e-984a-f7ec10a11d69.png)


With that said, let's remember that traditional typography has many things which due to either ⓐ the trivial means of their calculation, or ⓑ the lack of need to calculate them on the screen, they are not officially part of the font format, but appear in certain programs meant to help traditional type designers acclimate. In truth, there is no "left side bearing", just an origin at (nil, nil) and a width which is a single number, not a line.

When you "set the left side bearing" you actually do no such thing, you rather move all points relative to the origin such that it is made to appear such to the user, with the origin always appearing exactly where she expects the LSB to be. Cf https://github.com/MFEK/glif/blob/0a27adec3b0894860bb929167a292244fabe83b2/src/tool_behaviors/move_glyph.rs#L43 (forgive me, I have not the faintest idea where the code for this is in FontForge and gave up looking through cvfreehand.c)

Given that there is no format truth to these bearings there is considerable interpretation going on in cases like yours. So what are you seeing?

The RSB is normally ahead of the glyph, yes? So if the glyph is placed into backwards territory and RSB=LSB=0, and for that matter origin=width=0, then the RSB is logically positive, as logically as it would be were the glyph beyond the origin and the width were say ≈1200.

But the LSB is normally to the left (to the left, everything you own…). Because it is now to the right, it's logically negative.

No bug.
