### ISSUE TITLE
fontforge seems doesn't rewrite component matrix in copy back to fore via script

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#5122]
Hi
fontforge seems doesn't rewrite component matrix in copy back to fore via script. i mean copy C:back to C:fore working correctly via GUI, but with `glyph.setLayer(glyph.layers['Back'], 'Fore')`, component matrix(scale and position) doesn't be affected.

i created a test file:
[test.zip](https://github.com/fontforge/fontforge/files/9737629/test.zip)
square on A:fore, scaled to 50% on A:back
circle on B:fore, scaled to 50% on B:back
component of A`[1 0 0 1 0 0]` and B`[1 0 0 1 0 200]` on C:fore, component of A`[1 0 0 1 0 0]` and B`[0.5 0 0 0.5 50 200]`  on C:back

![test](https://user-images.githubusercontent.com/25493297/194663910-d3b7f636-0e1b-47ef-bfc9-2ade807bb31d.png)

(i didn't check for `use_my_metrics` flag, it would be very helpful if this flag will rewritable too)

**Comment by aminabedi68** [comment]
cc: @skef
please take a look. thanks.

**Comment by ctrlcctrlv** [comment]
@aminabedi68 If you wish, please humor me and try a workaround.

- Please set global FontForge option `OnlyCopyDisplayed` to 0.
- Please make any temporary buffer glyphs you need.
- Please use `font.copy` and `font.pasteInto` instead and report back.

I believe it will work because `PasteIntoFV` considers `Ref`'s.

**Comment by aminabedi68** [comment]
Hi @ctrlcctrlv 
i don't know how to set `OnlyCopyDisplayed` to 0, and what you meant about _make any temporary buffer glyphs you need_, but i change the peace of script for this test from:


``` python
...
for glyph in font.glyphs() :
 glyph.setLayer(glyph.layers['Back'], 'Fore')
...
```

to:

``` python
...
font.selection.select(("ranges",None),"A","C")
font.activeLayer = 0
font.copy()
font.activeLayer = 1
...
```
and it's working now, thank you :) 👍
so, the `setLayer` function has this issue.

**Comment by ctrlcctrlv** [comment]
This is still a valid bug :) but I'm glad my idea worked.

You can change preferences inside Python scripts. cf. `fontforge.getPrefs`, `fontforge.setPrefs`

**Comment by skef** [comment]
This isn't really a bug, at least as reported. The unexpected result has to do with confusion about the state of `test.sfd` (or whatever came before it). 

The FontForge `layer` object in the Python interface contains a set of contours specific to that glyph. The corresponding object for references is `layerrefs`. If you want to copy contours and references you need to copy both the layer object and the layerrefs reference tuples. (Which still isn't everything, but if we're talking about stuff relevant to the background (and therefore not anchors or the char width, it's close).

So, what's going on with "C"? Well, the problem is that C *already has* references to the foregrounds of A and B, each with a default matrix. Of course, before A or B has any foreground content there's minimal evidence of this. (FontForge actually does show the names of empty references a bit above the origin.) It's putting content in those foregrounds that is causing the content to show up. The `setLayer()` for C has no effect.

**Comment by ctrlcctrlv** [comment]
I see.

“C”? ;-)
