### ISSUE TITLE
About source contour mode

### ISSUE THREAD

**Issue by Photonico** [fontforge/fontforge#5132]
Hi,

The `source contour mode` is much more efficient than `output contour mode`:

![img](https://fontforge.org/docs/_images/typical.svg)

In my font file, the `Fore` layer is in `output contour mode`, only `Guide` layer is in `source contour mode`.

![img](https://raw.githubusercontent.com/Photonico/Problems/master/2022/Screenshot_20221022_042610.png)

However, I find it possible to set the `Fore` layer in `source contour mode`. In another font file, the `Fore` layer is in `source contour mode`.

![img](https://raw.githubusercontent.com/Photonico/Problems/master/2022/Screenshot_20221022_042533.png)

I want to know how to set `Fore` layer in `source contour mode`. It is very efficient.

Sincerely,
Lu

**Comment by ctrlcctrlv** [comment]
I don't understand your meaning. Font files don't necessarily contain unstroked paths. This is a mode of Expand Stroke, not fonts in general.

**Comment by Photonico** [comment]
> I don't understand your meaning. Font files don't necessarily contain unstroked paths. This is a mode of Expand Stroke, not fonts in general.

Thanks for your reply. How to let `Fore` layer contains unstroked paths?

**Comment by Tynach** [comment]
@Photonico Wait, given your last few statements and the last screenshot, do you actually mean *cubic* outline mode, rather than *quadratic* outline mode? Like, in that last screenshot, you show a font in (presumably) the OpenType format, which has *cubic* outlines, along with things like `FamilyBlues` and `OtherBlues` values to define regions of the font where it's more likely to find strokes to hint.

To use cubic splines, go to 'Element'→'Font Info...'→'Layers', and then either click on 'Mixed' or 'Always Cubic'. If you want Mixed, you can choose which layers of the font are in which format.

In general, OpenType and Type1 fonts use Cubic splines and define hints as horizontal or vertical spans within the font that contain stems.. And by contrast, TrueType fonts use Quadratic splines, defining hints via bytecocde instructions.

As for one being more 'efficient' than the other... That's subjective. The curves are formed using different math, so to get exactly the same curve in both means making one less efficient than the other.

If you have a curve exactly how you like it in quadratic form, and convert it to be a cubic curve, it has to have a lot more control points on the cubic curve to 'simulate' the quadratic curve. And vice-versa, if you convert a cubic curve into a quadratic curve, the quadratic curve needs to have more control points to 'simulate' the cubic curve.

**Comment by Photonico** [comment]
> @Photonico Wait, given your last few statements and the last screenshot, do you actually mean _cubic_ outline mode, rather than _quadratic_ outline mode? Like, in that last screenshot, you show a font in (presumably) the OpenType format, which has _cubic_ outlines, along with things like `FamilyBlues` and `OtherBlues` values to define regions of the font where it's more likely to find strokes to hint.
> 
> To use cubic splines, go to 'Element'→'Font Info...'→'Layers', and then either click on 'Mixed' or 'Always Cubic'. If you want Mixed, you can choose which layers of the font are in which format.
> 
> In general, OpenType and Type1 fonts use Cubic splines and define hints as horizontal or vertical spans within the font that contain stems.. And by contrast, TrueType fonts use Quadratic splines, defining hints via bytecocde instructions.
> 
> As for one being more 'efficient' than the other... That's subjective. The curves are formed using different math, so to get exactly the same curve in both means making one less efficient than the other.
> 
> If you have a curve exactly how you like it in quadratic form, and convert it to be a cubic curve, it has to have a lot more control points on the cubic curve to 'simulate' the quadratic curve. And vice-versa, if you convert a cubic curve into a quadratic curve, the quadratic curve needs to have more control points to 'simulate' the cubic curve.

You solved my question. Thank you very much!
