### ISSUE TITLE
SnapDistance not decreasing on zoom as expected

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#852]
The new code to make points display larger seems to have effected point movement with snapping, so it is now a little too harsh; I think the SnapDistance pref's function maybe effected by the point size increase?

http://youtu.be/EvJ5qWHsgKM

**Comment by ctrlcctrlv** [comment]
**Seven years later&hellip;**

Sorry Dave, I actually like this feature. We are however discussing a similar problem right now at https://github.com/fontforge/fontforge/issues/4369#issuecomment-640163264. I think that when zooming out, still having the same snap is useful, and I often quickly zoom out to snap faster, then zoom back in.

It never occurred to me this was a bug, and now that I've gotten so used to it, I'm sorry to say, it's all grown up and has graduated to being a feature.

Therefore, and especially since it seems no one is going to reply for another seven years, I'm closing this in favor of #4369.
